### ISSUE TITLE
remember gadget shotgun state fix

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#10]
The current fix doesn't fix due to auto lasers and rainbow lasers

**Comment by Kamikaze94** [comment]
Huh, why have edited and closed this suddenly?
I'm in trhe beta for a few days now, and as far as I can tell, you are right, the laser colors aren't working there atm.
Thanks btw for your script on how to fix it. I took the part out, that is just for akimbo lasers, as we have no akimbo shotguns (yet...?), but it seems to work fine.

**Comment by Kamikaze94** [comment]
Updated the repos now, included some small code cleanup, ^^
