### ISSUE TITLE
NPC Heisters Appear Like Jokers In Client Safe House

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#100]
So I joined my friends safe house, and all the NPC Heisters have names and health bars above their heads. They also appeared in the left hand side of HUD List as if they were Jokers.
![20161025160639_1](https://cloud.githubusercontent.com/assets/12417397/19705756/e0a4628a-9ad3-11e6-9203-cb5335231849.jpg)

**Comment by Kamikaze94** [comment]
Confimed, Overkill seems to just syncs the NPCs as converted cops to clients.....  :/

**Comment by Kamikaze94** [comment]
Alright should be fixed with todays commit.

**Comment by NerdVenom** [comment]
Nice, thanks Kamikaze94.
