### ISSUE TITLE
Bug Fix( Lobby Assets bug + bow weapon Acc (+) 0% ) Please!

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#101]
Bug Fix( Lobby Assets bug + bow weapon Acc (+) 0% ) Please!

Lobby Assets bug
![bug assets](https://cloud.githubusercontent.com/assets/21234977/19796591/7a8bbbde-9d20-11e6-9dde-818564c6d8fd.jpg)

bow ( Payday 2 chivary pack ) weapon Acc (+) 0%
![bug acc](https://cloud.githubusercontent.com/assets/21234977/19796607/9507570c-9d20-11e6-94d1-62e567b0ad32.jpg)

fix please!

**Comment by Kamikaze94** [comment]
Uhm, did you do anything special, to get the assets to not show up?
Strange, never had this issue, nor heard about it...

The bow accuracy is know, friend told me a few day ago.
He said, the accuracy is also 0% in the end screen, so it looks like a problem in the base game to me...?
Some changes were made how different projectiles get handled during housewarming party might be a result of that.)

**Comment by Malidictus** [comment]
The new Buy All Assets option is a little inconsistent. I've never seen outright missing assets, but it's inconsistent in when it will "fill in" and when it won't. Sometimes there are assets I can't buy (Expert Driver) say but clicking Buy All Assets will still fill in the envelope. Other times I can buy everything but Buy All Assets won't fill in. I'll have to pay more careful attention as to which heists it happens on, but I believe Undercover causes issues frequently.

The Buy All Assets asset itself works just fine, but its visuals behave oddly.

**Comment by hud8614** [comment]
![20161029051722_1](https://cloud.githubusercontent.com/assets/21234977/19828007/94309ec6-9df5-11e6-80e4-424bd830d630.jpg)

![20161023012734_1](https://cloud.githubusercontent.com/assets/21234977/19828010/9792eef2-9df5-11e6-9420-fb7d78d22c24.jpg)

**Comment by Malidictus** [comment]
Election Day Warehouse did not spawn a Buy All Assets asset whatsoever just now.

**Comment by Kamikaze94** [comment]
Every asset besides "Buy All" seems to disappear, if you change your Profile as client.
Anyone can confirm this, or knows this is not happening with the base game?

@Malidictus As Client or Host? 
From my experience this happens sometimes as Host.
Not sure why. If you restart for example it can show up again, so it can show up again + is happening randomly on multiple (probably all) heists....

**Comment by Malidictus** [comment]
Host. It seems like if other players are present in the lobby, the "Buy All Assets" asset doesn't fill in, either when used directly or when other people buy the assets one by one. It's seemed pretty consistent so far. I've only seen it outright missing once, and I believe it was Big Oil Day 2 with extra Assets from Day 1.

It's not a BIG deal because the asset still works, but I figured it might help you track down other issues with it.

**Comment by Malidictus** [comment]
The "Buy All Assets" seems to fill in properly when I'm the only player in the lobby. When other players are in the lobby - specifically other players running WolfHUD - it doesn't fill in but the assets are still purchased.
