### ISSUE TITLE
Suggestion: adding pager text to push to interact

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#104]

**Comment by Kamikaze94** [comment]
Not sure, what exactly you mean with this?
Something like a different text for the locked interaction for pagers, like HoxHUD did?

If yes, problem is, that the unit you interact with is not formwarded up to the point where I would need it. The base game just passes the already localized text over. So in the interaction display class there is pretty much no way to tell, with which object you are interacting. Would need some rewriting in my Interaction hooks as well as a more intrusive access into the base game functions. 
Never felt like it is worth it. Normally people know (at least after they tried once) that canceled pagers trigger the alarm...^^
