### ISSUE TITLE
Crash log, not sure what sparked it.

### ISSUE THREAD

**Issue by Skyfry428** [Kamikaze94/WolfHUD#106]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
               _process_kill()  @mods/WolfHUD/lua/KillCounter.lua:99                
                                @mods/WolfHUD/lua/KillCounter.lua:115               
                            ()  =(tail                                              
                      call):-1  ()                                                  
                        =(tail                                                      
                      call):-1  _on_damage_received()                               
                                @mods/Keepers/lua/copdamage.lua:3                   
lib/units/enemies/cop/copdamage.lua:1655  ()                                                  
                        =(tail                                                      
                      call):-1  _do_melee_damage_original()                         
                                lib/units/beings/player/states/playerstandard.lua:2533  
@mods/WolfHUD/lua/GameInfoManager.lua:2922  ()                                                  
                        =(tail                                                      
                      call):-1  _update_melee_timers_original()                     
                                lib/units/beings/player/states/playerstandard.lua:2624  
        _update_melee_timers()                                                      
@mods/WolfHUD/lua/Interaction.lua:126  _update_check_actions()                             
                                lib/units/beings/player/states/playerstandard.lua:731  
             update_original()                                                      
lib/units/beings/player/states/playerstandard.lua:343  update_original()                                   
                                @mods/Sliding/sliding.lua:51                        
                    original()                                                      
@mods/WolfHUD/lua/BurstFire.lua:197  update()                                            
                                @mods/base/req/hooks.lua:258                        
lib/units/beings/player/playermovement.lua:265  ()                                                  
                        =(tail                                                      
                      call):-1  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

System information:
	Application version : 1.57.1
	CPU : Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 730 / C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_848dea456d3c865e\nvd3dum.dll[21.21.13.7570]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8142MB 468KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (High Definition Audio Device))

**Comment by Kamikaze94** [comment]
Hmm, not sure either...
Sometimes the game is not really helpful when saying "Access violation"....^^

Added some additional checks to the mentioned line at the top of your Callstack though, so hopefully it doesn't happen again....

**Comment by Malidictus** [comment]
I was just coming to post the same crash from a friend of mine, which happened just now (we're using the latest auto-update version). The circumstances might help with that. This was First World Bank, I just deployed the last of the C4 on the wall which opens up the toilet to the new section. He, meanwhile, was meleeing a shield and had deployed a Molotov on the ground. We had two bots and two Jokers.
