### ISSUE TITLE
How can I change the color of the enemy health bar to white?

### ISSUE THREAD

**Issue by gabriel25gomes** [Kamikaze94/WolfHUD#107]
I know I have to change "self._health_text_rect = { X , X , X , X }" but I don't know the white color code line...

**Comment by Kamikaze94** [comment]
The texture has no white health bar.
If you extract Payday 2, take a look at "guis/textures/pd2/healthshield.texture".
It contains the Health bar outline, a green healthbar and a blue healthbar.

If you want a white one, setup a mod_override for that texture and edit it to be white, is the way to go.

_edit: Attached healthshield image in png format._
![healthshield](https://cloud.githubusercontent.com/assets/3707261/20154077/0c78f2ba-a6c6-11e6-916f-f2b6d79779fb.png)

**Comment by gabriel25gomes** [comment]
Thanks for the help.
