### ISSUE TITLE
Suggestion: Have an option to use Alpha HUD Circles which replaces the stock HUD circles.

### ISSUE THREAD

**Issue by dribbleondo** [Kamikaze94/WolfHUD#108]
More of a personal preference thing, but I've always hated how skinny the timer circle is on the default HUD. Hoping this could be added in the same vein as Federal Inventory and DrivingHUD (Mod_overrides for Windows, .pdmod for Linux) as it does look rather nice.

https://steamcommunity.com/app/218620/discussions/15/558755530510283940/ for the entire "Alpha HUD" page.

**Comment by Kamikaze94** [comment]
Isn't this exactly what Restoration HUD does?

Also, if you take Restoration's mod_override part, it should work with WolfHUD, unless they changed the texture sizes, in which case you'd need simply to resize them...
