### ISSUE TITLE
Suggestion: Show teammates/friendly AI damage as well onto enemies.

### ISSUE THREAD

**Issue by DevilzAvacado** [Kamikaze94/WolfHUD#109]
Kinda like what pocohud does.

**Comment by Kamikaze94** [comment]
Well, thought about that when I made the script for player damage popups, but never rally bothered to go back and actually do it...^^

Anyways, implemented that feature now, should arrive in the release version with the next update.
Thanks for the suggestion, that actually mae me do something about it :P
