### ISSUE TITLE
WolfHud not doing anything.

### ISSUE THREAD

**Issue by Corncats** [Kamikaze94/WolfHUD#110]
I completed the installation instructions and yet when I start the game BLT is there but WolfHud isn't and it isn't doing anything.

How to fix??

**Comment by Kamikaze94** [comment]
Hmm, maybe check the BLT log, located at "Payday 2/mods/logs/" and see if it gives any clue about whats going wrong?

Also, just to make sure, the folders you put in place look like "Payday 2/mods/WolfHUD/", and inside that are files like "mod.txt", "Core.lua" and folders called "loc", "lua" and "menu"?

**Comment by Kamikaze94** [comment]
Assuming its resolved.
