### ISSUE TITLE
Wolf Hud  Certain NO SOUND/AUDIO

### ISSUE THREAD

**Issue by lascivious1** [Kamikaze94/WolfHUD#116]
Mostly everything seems fine with Wolf Hud,  however I am having an issue with certain audio.  Examples are not hearing guard pagers, not hearing audio when player calls out a special enemy as well as no audio when dropping deployable.  I know there are more than that, just can't remember them.

**Comment by lascivious1** [comment]
now throwables arent working . even checked the keybind.  love wolf hud. but going soon, if this continues.

**Comment by Kamikaze94** [comment]
Alright, how much RAM do you have? And how much of this os normally free/occupied by Payday when this happens?
The Sound Engine Payday uses has those missing sound artifacts, when its running out of RAM, or the game has a memory leak somewhere (last seen when Cook-off was added, I think.)
Juast for example, mods that allow you to spawn vehicles in any levenl and having to load a lot more packages could possibly result in cutting out sound too.

WolfHUD isn't modifying the sounds that get played by the mission, so I'm not sure, why there are sounds missing for you.

Regarding the throwables, was the mission still in stealth by any chance? WolfHUD has an option to suppress throwable explosives in stealth. 
You can still throw grenades, but only by pressing the throw key (default 3) two times quickly. This is meant to prevent accidentally throwing nades and breaking stealth. 
You can disable it in "WolfHUD Settings > Interaction Options", the second from bottom.
