### ISSUE TITLE
Lobby player Ping. fix please.

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#118]
fix please.
![20161121225446_1](https://cloud.githubusercontent.com/assets/21234977/20488217/8b74e84e-b049-11e6-924b-e4a6ac1dd6f3.jpg)

![20161121224615_1](https://cloud.githubusercontent.com/assets/21234977/20484893/b54739b8-b03c-11e6-9188-78100ac36a91.jpg)

**Comment by Kamikaze94** [comment]
Done.
Plus adding a little offset, in case LPI played hours gets dispalyed, to get rid of the overlap there...
