### ISSUE TITLE
Crash with Dragon's Breath + damage popup

### ISSUE THREAD

**Issue by Cyberbeni** [Kamikaze94/WolfHUD#119]
When using Dragon's Breath, the game crashes after a while, crashlog says this:

Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Link to full crash log: https://drive.google.com/open?id=0B4uy9sQmjUmOZjN5STVLbHdZLUk

**Comment by Cyberbeni** [comment]
Oh, same bug as #102

**Comment by Kamikaze94** [comment]
Are you using the latest dev version (e.g. downlaoded from here, not paydaymods/lastbullet)?
It should be fixed in the dev build but isn't updated in the release version currently.

**Comment by Cyberbeni** [comment]
I'm using the release version.

Fire shotguns still suck, so doesn't really matter.
