### ISSUE TITLE
Bug with loot bags

### ISSUE THREAD

**Issue by Portalception** [Kamikaze94/WolfHUD#12]
When in Bank heist, picking up the drill does not trigger the next objective, infact the drill stays where it is and i obtain a duplicate drill, which i can drop and proceed to pickup another thermal drill, over and over again. This also happens to other bags such as the warheads from meltdown. The main problem is the fact that picking up any loot items causes the item to be added to my inventory but the loot itself will stay there, effectively breaking all heists.

**Comment by Kamikaze94** [comment]
Hmm, never happened to me, or anyone who told me...
Are you on the vanilla or Beta version of the game?
Which version of WolfHUD are you running? master/beta branch from here or the version from paydaymods.com?
Does your BLT log mention any errors? Which mods are you running besides this? Is it possible, that its a bug of those mods/ an interference between WolfHUD and another mod?

EDIT:
 Just tried, Bank Heist picking up drill + drilling vault, etc. works just fine...
Were you hosting the Bank job you mentioned? A friend of mine had a weird problem where some  other player caused some strange appearing of his interaction circle and stuff. 
Wouldn't surprise me, if tehre are troll mods like that in the mean time, too...

**Comment by Portalception** [comment]
Im running the vanilla version of the game and im running my fair share of mods as well. but uninstalling wolfhud fixes it completely, im not sure if a mod conflict causes it or anything but im using the latest wolfhud thats updated from the blt menu in game. I downloaded the one at last bullet at first and came here to report bugs, i downloaded both the master and beta and both had the problem (without updating from blt menu)

**Comment by Portalception** [comment]
About a hundred lines of 
10:39:28 AM FATAL ERROR: mods/PocoHud3/poco/../poco/Hud3.lua:829: attempt to index local 'defaultLbl' (a nil value)
Followed by
10:39:29 AM Log: CURL CLOSED
10:40:07 AM Log: CURL INITD
10:40:15 AM Log: Initiating Hook
10:40:23 AM Log: Initiating Hook
10:40:23 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
10:40:23 AM Lua: [Mods] Loading mods for state (table: 00300440)
10:40:23 AM Lua: [Mods] Loading mod: Armour Correct Sorting...
10:40:23 AM Lua: [Mods] Loading mod: AutoFireSoundFix...
10:40:23 AM Lua: [Mods] Loading mod: base...
10:40:23 AM Lua: [Mods] Loading mod: Better Bots...
10:40:23 AM Lua: [Mods] Loading mod: CreateEmptyLobby...
10:40:23 AM Lua: [Mods] Loading mod: Detailed Carry Info...
10:40:23 AM Lua: [Mods] Loading mod: Driver's Neck Brace Removed...
10:40:23 AM Lua: [Mods] Loading mod: Enemy Health and Info...
10:40:23 AM Lua: [Mods] Loading mod: Extra attachments complation...
10:40:23 AM Lua: [Mods] Loading mod: GoonMod...
10:40:23 AM Lua: [Mods] Loading mod: LDDG Reborn...
10:40:23 AM Lua: [Mods] Loading mod: Lobby Player Info...
10:40:23 AM Lua: [Mods] Loading mod: Meth Helper (Not spammy)...
10:40:23 AM Lua: [Mods] Loading mod: No Confirm Dialogs...
10:40:23 AM Lua: [Mods] Loading mod: PocoHud3...
10:40:23 AM Lua: [Mods] Loading mod: Poser...
10:40:23 AM Lua: [Mods] Loading mod: pp...
10:40:23 AM Lua: [Mods] Loading mod: Real Weapon Mod Names...
10:40:23 AM Lua: [Mods] Loading mod: Real Weapon Names...
10:40:23 AM Lua: [Mods] Loading mod: Steelsights...
10:40:23 AM Lua: [Mods] Loading mod: Weapon attachments customizer...
10:40:23 AM Lua: [Mods] Loading mod: WolfHUD...
10:40:23 AM Lua: [Error] Could not load revision file for Federal Inventory!
10:40:23 AM Lua: [Mods] Mod 'mods/LDDG Reborn/' is disabled!
10:40:23 AM Log: Initiating Hook
10:40:23 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
10:40:23 AM Lua: [Mods] Loading mods for state (table: 00300480)
10:40:23 AM Lua: [Mods] Loading mod: Armour Correct Sorting...
10:40:23 AM Lua: [Mods] Loading mod: AutoFireSoundFix...
10:40:23 AM Lua: [Mods] Loading mod: base...
10:40:23 AM Lua: [Mods] Loading mod: Better Bots...
10:40:23 AM Lua: [Mods] Loading mod: CreateEmptyLobby...
10:40:23 AM Lua: [Mods] Loading mod: Detailed Carry Info...
10:40:23 AM Lua: [Mods] Loading mod: Driver's Neck Brace Removed...
10:40:23 AM Lua: [Mods] Loading mod: Enemy Health and Info...
10:40:23 AM Lua: [Mods] Loading mod: Extra attachments complation...
10:40:23 AM Lua: [Mods] Loading mod: GoonMod...
10:40:23 AM Lua: [Mods] Loading mod: LDDG Reborn...
10:40:23 AM Lua: [Mods] Loading mod: Lobby Player Info...
10:40:23 AM Lua: [Mods] Loading mod: Meth Helper (Not spammy)...
10:40:23 AM Lua: [Mods] Loading mod: No Confirm Dialogs...
10:40:23 AM Lua: [Mods] Loading mod: PocoHud3...
10:40:23 AM Lua: [Mods] Loading mod: Poser...
10:40:23 AM Lua: [Mods] Loading mod: pp...
10:40:23 AM Lua: [Mods] Loading mod: Real Weapon Mod Names...
10:40:23 AM Lua: [Mods] Loading mod: Real Weapon Names...
10:40:23 AM Lua: [Mods] Loading mod: Steelsights...
10:40:23 AM Lua: [Mods] Loading mod: Weapon attachments customizer...
10:40:23 AM Lua: [Mods] Loading mod: WolfHUD...
10:40:23 AM Lua: [Error] Could not load revision file for Federal Inventory!
10:40:23 AM Lua: [Mods] Mod 'mods/LDDG Reborn/' is disabled!
10:40:24 AM FATAL ERROR: mods/Steelsights/Firemode.lua
10:40:24 AM FATAL ERROR: attempt to call a string value
10:40:25 AM Log: Initiating Hook
10:40:25 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
10:40:25 AM Lua: [Mods] Loading mods for state (table: 1F1F0AE0)
10:40:25 AM Lua: [Mods] Loading mod: Armour Correct Sorting...
10:40:25 AM Lua: [Mods] Loading mod: AutoFireSoundFix...
10:40:25 AM Lua: [Mods] Loading mod: base...
10:40:25 AM Lua: [Mods] Loading mod: Better Bots...
10:40:25 AM Lua: [Mods] Loading mod: CreateEmptyLobby...
10:40:25 AM Lua: [Mods] Loading mod: Detailed Carry Info...
10:40:25 AM Lua: [Mods] Loading mod: Driver's Neck Brace Removed...
10:40:25 AM Lua: [Mods] Loading mod: Enemy Health and Info...
10:40:25 AM Lua: [Mods] Loading mod: Extra attachments complation...
10:40:25 AM Lua: [Mods] Loading mod: GoonMod...
10:40:25 AM Lua: [Mods] Loading mod: LDDG Reborn...
10:40:25 AM Lua: [Mods] Loading mod: Lobby Player Info...
10:40:25 AM Lua: [Mods] Loading mod: Meth Helper (Not spammy)...
10:40:25 AM Lua: [Mods] Loading mod: No Confirm Dialogs...
10:40:25 AM Lua: [Mods] Loading mod: PocoHud3...
10:40:25 AM Lua: [Mods] Loading mod: Poser...
10:40:25 AM Lua: [Mods] Loading mod: pp...
10:40:25 AM Lua: [Mods] Loading mod: Real Weapon Mod Names...
10:40:25 AM Lua: [Mods] Loading mod: Real Weapon Names...
10:40:25 AM Lua: [Mods] Loading mod: Steelsights...
10:40:25 AM Lua: [Mods] Loading mod: Weapon attachments customizer...
10:40:25 AM Lua: [Mods] Loading mod: WolfHUD...
10:40:25 AM Lua: [Error] Could not load revision file for Federal Inventory!
10:40:25 AM Lua: [Mods] Mod 'mods/LDDG Reborn/' is disabled!

**Comment by Kamikaze94** [comment]
Okay, so it's probably WolfHUD and something else interfering...
maybe you should try disabling other mods, seeing if that works? Preferably ones that change something about bags? Does this happen with all bags or just Thermal drills?

Btw, some annotations: Enemy Health and Info is included in WolfHUD. So is most of No confirm Dialogs (Don't know anymore, I think I readded one or two, which seemed to be easily accidentally confirmable).
Real Weapon Names is also included. So no need for those, just increases the chances of Problems,  :)

I can confirm, WolfHUD working well with Better Bots, CreateEmptyLobby, Lobby Player Info, Meth Helper and PocoHUD 3 (but your version of PocoHUD seems to have some errors too, as seen at the start of your log...)
For the rest, I have never used it, nor can I say how well its written, or how likely it is to break stuff...
Probably trial and error time...  :/

EDIT: Just saw the error caused by Steelsights, in 'Firemodes.lua' . Maybe that one doesn't quite like the BurstFire script, coming with WolfHUD? You might want to disable BurstFire in the WolfHUD Options in that case...

OFFTOPIC:
Btw, is "pp" the tool I think of, when hearing that?
Plus are you by any chance running on Linux? Beacuse of the missing revision File for Federal Inventory, the mod should create it on Windows at startup...

**Comment by Portalception** [comment]
I found the mod conflicting with yours, the detailed carry info was causing the problem, I guess since your hud did not have a box for the carry info to be shown the mod broke down. All other mods are working fine together now. Yes pp is *that* tool. I mostly use it for trying out new guns to see if i would buy the dlc, also very handy for video making. I am running on windows 7 x64, and it dosent create it. dosent really matter because im thinking about installing it since i will be seeing my weapon icon in games now. Thanks a bunch and thanks for this great mod!
