### ISSUE TITLE
Driving Hud

### ISSUE THREAD

**Issue by Remobit** [Kamikaze94/WolfHUD#121]
With Custom Hud disabled and Info Hud enabled the car info appears offscreen, so only the bottom of its box is visible.

**Comment by Kamikaze94** [comment]
Are you using the lastbullet/paydaymods release version, or the latest version here from GitHUB?

I took care of the positioning of DrivingHUD a few commits ago, but its not in the release version currently.
If you are on the dev build I might have to revisit some coding I did, and check where this behavior originates from.

Thanks for the report :)

**Comment by Remobit** [comment]
Ah, okay. No, I'm using the build from paydaymods.
