### ISSUE TITLE
Random Crashing 

### ISSUE THREAD

**Issue by Arcaxio** [Kamikaze94/WolfHUD#122]
I don't know why, but my game crashed all of a sudden. Here's a crash log, what do you think caused it?  I'm using the latest WolfHud dev version.
----------------------------------------------------------------------

Mon Dec 12 18:57:15 2016

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                   _set_text()  @mods/WolfHUD-master/lua/HUDList.lua:4580           
               _update_value()  @mods/WolfHUD-master/lua/HUDList.lua:4941           
                                @mods/WolfHUD-master/lua/HUDList.lua:4915           
                            ()  =(tail                                              
                      call):-1  call()                                              
lib/utils/eventlistenerholder.lua:33  _call_listeners()                                   
lib/units/beings/player/playerinventory.lua:461  equip_selection()                                   
lib/units/beings/player/playerinventory.lua:318  _start_action_equip_weapon()                        
lib/units/beings/player/states/playerstandard.lua:4761  _update_equip_weapon_timers_original()              
lib/units/beings/player/states/playerstandard.lua:3000  _update_equip_weapon_timers()                       
@mods/WolfHUD-master/lua/GameInfoManager.lua:3088  _update_check_actions()                             
lib/units/beings/player/states/playercarry.lua:146  update()                                            
lib/units/beings/player/states/playerstandard.lua:392  update()                                            
lib/units/beings/player/states/playercarry.lua:86                                                      
lib/units/beings/player/playermovement.lua:266  ()                                                  
                        =(tail  call):-1                                            
                            ()  =(tail                                              
                                call):-1                                            

-------------------------------
Just in case if you asked, I'm using the dev version because the stable release will crash the game because of Dragon Breath Rounds. So... When are you going to release a new stable version? I know dev versions are more unstable, but it's the only way to use DBR without always crashing my game. But apparently something else crashed my game, and I don't know whats causing it.

**Comment by Kamikaze94** [comment]
Strage, hear of this crash only once before.
Added a check for the text label, in case thats what is causing problems here.
Guess that's all I can do for now :)

**Comment by Kamikaze94** [comment]
As you havn't said anything regarding this again, I assume its solved. :)
