### ISSUE TITLE
Lock n' Load buff no longer accurate

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#124]
A couple of patches back, Overkill changed the way Lock n' Load's damage buff is calculated. It's now based on magazine size rather than ammo in the magazine, meaning it's a fixed number depending on your gun. However, HudList's buff tracker still shows an increasing buff as the ammo in my weapon's magazine drops. From looking at the actual reload speed, I'm pretty sure that's not the case.

**Comment by Malidictus** [comment]
Since creating this, I've installed the current development version of WolfHUD where this issue appears to be resolved. Seems like this was solved before I even noticed it. Lock n' Load works as it should now. Feel free to close this.

**Comment by Kamikaze94** [comment]
Ah, I thought yu were using the latest dev build already....^^
Yeah, there was an update from Seven, after Overkill changed it.

Anyways, thanks for the update :)
