### ISSUE TITLE
Payday keeps crashing when i do this

### ISSUE THREAD

**Issue by Payday2KeepsCrashing** [Kamikaze94/WolfHUD#126]
Any heist where i am using dragons breath/Flame Bullets i crash around 2 mins into the heist, not sure if this is just me. Here is the crash notes:

Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.60.1
	CPU : Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[10.18.13.6881]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8153MB 612KB
	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Kamikaze94** [comment]
Same as issue #119 
Known bug in the release version, fixed in dev branch.
