### ISSUE TITLE
Other player crashed when they are trying to join the preplaning phase(Loading phase)

### ISSUE THREAD

**Issue by PJzuza** [Kamikaze94/WolfHUD#127]
I was hosting some heists to help my friend doing some achievements but he always got crashed and here is his crash log.

Thu Dec 22 11:31:40 2016

Application has crashed: C++ exception
[string "lib/managers/missionassetsmanager.lua"]:544: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   

-------------------------------

Current thread: Main

-------------------------------

System information:
Application version : 1.60.1
CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
DirectX : 12.0 
GPU : NVIDIA GeForce GTX 960M / nvd3dum.dll[21.21.13.7595]
Language : @ID69065f31945c7d82@
Memory :     8097MB 760KB
OS : 6.2.9200 () 0x300-0x1 (64 bits)
Physics : threaded
Renderer : DX9 threaded
Sound : Microsoft (Динамики (2- USB Advanced Audio Device))

And more info: he has been using only VELOSync and I've been using other mods but after I've deleted WolfHud the problem's gone so any clue about this problem? Thank you

**Comment by Kamikaze94** [comment]
Definetly related to the BuyAllAssets script.
Are you using the currently released version of WolfHUD (from paydaymods/lastbullet) or the development build?

**Comment by PJzuza** [comment]
Hi I am using the development build in the GitHub and I've found a solution to fix it. The problem came from another mod called Buy All Assets V3 which I'd installed it a long time ago. When I deleted it and reinstalled the wolfhud again. Now the game is working fine so I am sorry for making some confused issue thread here and thank you for you help Kamikaze94.
