### ISSUE TITLE
[Suggestion] Limiting light intensity with Akimbo flashlights

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#130]
Currently, using flashlights with Akimbo weapons is very problematic because the flashlights on both weapons turn on simultaneously. This makes the flashlights far too bright to be useful. WolfHUD does have the option of reducing flashlight intensity, but that also affects all single weapons, making their single flashlight too dim to be useful. I believe a special-case exception for akimbo weapons is in order, and would suggest one of the following approaches:

1. Cut the intensity of Akimbo flashlights by half of the value I've chose from the Flashlight Extender mod for all other weapons.

2. Force-disable the flashlight on one of the two guns - preferably the left one.

3. Institute a separate Flashlight Intensity option specific to Akimbo weapons only.

**Comment by Kamikaze94** [comment]
Latest commit (ae29b05fa818d619eaff8c271071cc641014f2bd) cuts akimbo flashlight brightness in half now.

**Comment by Malidictus** [comment]
I just checked and YUP! It works as advertised. Akimbo pistols are perfectly usable with flashlights now :) Thank you kindly. I think you can go ahead and close this - it's done.
