### ISSUE TITLE
Suggestion: Auto Skip Result Screen should also speed up tallying of the experience, etc.

### ISSUE THREAD

**Issue by FlamingFox911** [Kamikaze94/WolfHUD#135]
As it currently stands, you have to hold down Space in order to speed through the Result Screen, even if you have Auto Skip Experience Screen turned on. Preferably, when this option is on, it should speed through without having me to use spacebar.

**Comment by Kamikaze94** [comment]
Added options for Stat Screen auto speedup and instant restart in latest commit (ae29b05fa818d619eaff8c271071cc641014f2bd), disabled as default though.
