### ISSUE TITLE
Taser freeze?

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#136]
I'm posted this on the official forums and it may be a vanilla bug, but I run WolfHUD and it happens a lot in my lobbies. Plus I'm stuck for ideas and I'm trying all of my options :)

Rarely but consistently, a player will freeze  when a tasing event happens in the game. It's usually a "third person," that is to say not the host and not the one getting tased. This freeze is permanent, but the game doesn't seem to be stuck in an infinite loop. The game's process will sit at 0% CPU and unchanging Memory. It will never crash (and thus never produce a crash log), and it will display the last image the frozen player saw.

The freeze occurs almost immediately after a tasing event and may or may not be related to the Shockproof skill in some way. I have very little information on the matter.

**Comment by NerdVenom** [comment]
I just had this happen as well, but I got the "payday 2 has stopped responding" dialog window. Seems to be random if the game will crash or not.

**Comment by Malidictus** [comment]
Right, but it's not a crash in the executable in either case. It's the executable becoming non-responsive and having the be shut down via Windows. That doesn't generate a crash report, is the problem. If you have an idea of how to cause this freeze in a repeatable fashion, please let me know. I've been struggling with it for a long time.
