### ISSUE TITLE
Dont Work with Kingpin

### ISSUE THREAD

**Issue by DarkSide1305** [Kamikaze94/WolfHUD#137]
I cant use Kingpin when i have Wolfhud Enabled.

**Comment by NerdVenom** [comment]
Have you tried playing with just WolfHUD enabled? I've had no problems using Kingpin.

**Comment by DarkSide1305** [comment]
Im just using a Newer Version of Wolf-Hud now. And it works now.

**Comment by OhhLoz** [comment]
How did you fix it? Mine doesnt work either.

**Comment by NerdVenom** [comment]
OhhLoz, are you using the latest dev version?

**Comment by OhhLoz** [comment]
Yea I just downloaded it, thought the one on paydaymods & ingame update would be ok, it seems to work however I dont know how to migrate my settings over without overwriting the differences.

**Comment by NerdVenom** [comment]
you might want to try going here : https://github.com/Kamikaze94/WolfHUD and clicking the green "Clone or download" button then click download zip in the bottom right corner of the popup. Delete your current version then Make a folder named "WolfHUD" and put the contents of the "WolfHUD-master" folder into it.

**Comment by OhhLoz** [comment]
I've done that and it works, but I dont know how to carry my settings over from the faulty version.

**Comment by NerdVenom** [comment]
If you look in Payday 2/mods/saves/ do you see "wolfhud.json", "wolfhud.txt" or "wolfhud_colors.txt"? As far as I know, this is the only folder where your options should be saved.

**Comment by OhhLoz** [comment]
Well when I switch between the master version and my old version the huds change so the settings must be somewhere in that folder, or the master version is saving under a different name/directory.

**Comment by NerdVenom** [comment]
Depending on how old your previous version was, it might be best to just start fresh. A pain in the ass I know but it can avoid any issues with importing old settings.

**Comment by OhhLoz** [comment]
I was only on the previous version as I downloaded it around 1-2 weeks ago.

**Comment by NerdVenom** [comment]
Ah, well I'm at the end of the support I can provide you. I have no idea how you would import the old settings. Sorry but at least you have Kingpin working now.

**Comment by OhhLoz** [comment]
Ah! I fixed it, I think the new master file creates/relies on a .json, whereas the old version uses WolfHUD.txt, copying WolfHUD.txt to the json got all my old settings back. I havent checked the menus to see if they have changed to accomodate this, but its good enough for me.
Thanks again.

**Comment by Kamikaze94** [comment]
Closing, as it seems already solved... :)
