### ISSUE TITLE
CRASH!!!

### ISSUE THREAD

**Issue by TOXICxSTRIKE** [Kamikaze94/WolfHUD#138]
When going loud the game crashs halfway through the assault wave. i lookd at the crash and it said Acces Violation and for the BLT Log it said [WolfHUD] Trying to update unknown laser theme: custom_laser please respond

**Comment by Kamikaze94** [comment]
Maybe you are running a mod that adds additional themes or something?

Anyways, closing this, as the Laser Script got entirely replaced with a newer one.
Feel free to open another issue, if you experience problems with the new script as well :)
