### ISSUE TITLE
messiah charge not showing in the down counter on the beta

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#14]
as title

also noticed a missing a comma on the following line of the mod.txt
{ "hook_id" : "lib/units/weapons/newraycastweaponbase" "script_path" : "Core.lua"},

**Comment by Kamikaze94** [comment]
Forgot that is_olay is no longer parameter of the constructor. thanks for the info.
And upps, missing comma was an accident, ^^

**Comment by Hulkfog** [comment]
Nine lives shows OK
Might be best to remove it for now
