### ISSUE TITLE
Laser Gadget Auto-On Issue

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#140]
When you start a heist, your Secondary weapon won't auto turn on the laser gadget. If you turn it on yourself, it will be the color of your teammates lasers. This is only fixed by switching to your Primary then back to your Secondary weapon.

**Comment by OhhLoz** [comment]
I also encountered this, but not sure if its down to the update since I dont remember it happening before.

**Comment by NerdVenom** [comment]
I played before the update today, no issue. So something they did in Update 130 has cause this.

**Comment by Malidictus** [comment]
Gadget state will also be lost when entering a vehicle now, as well.

**Comment by NerdVenom** [comment]
This issue has been fixed by the latest dev version. Only issue is the auto on when leaving a vehicle.
