### ISSUE TITLE
[Payday2 Update 130] I got crashed before the assault begin at Hotline Miami heist

### ISSUE THREAD

**Issue by PJzuza** [Kamikaze94/WolfHUD#141]
After the Payday 2 game has been updated (the update 130) it made a wolfhud unstable and get some crashings before the assault begins so is it possible to fix the problem? oh and I'll have this problem if I am a client but when I am a host I don't get any problems
and here is my crash log

Wed Feb 01 22:42:59 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/AdvAssault.lua:146: attempt to index field '_wave_text' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.62.0
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : Intel(R) HD Graphics 530 / nvumdshim.dll[21.21.13.7633]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8097MB 760KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

Thank you.

**Comment by Malidictus** [comment]
This was already reported here:

https://github.com/Kamikaze94/WolfHUD/issues/139

Apparently, it's an issue with the Assault Wave ticker, specifically with how it handles the current wave number for the Safehouse.

**Comment by PJzuza** [comment]
Thank you for your answer and yes I just saw the thread when you've mention it. My bad that I double posted the problem. I'll close this thread and check the thread you've mention instead
