### ISSUE TITLE
Game crash issue report

### ISSUE THREAD

**Issue by pine0922** [Kamikaze94/WolfHUD#142]
Here is the crash.txt info.
what is that _wave_text?

----------------------------------------------------------------------------------------------------------
Application has crashed: C++ exception
mods/WolfHUD/lua/AdvAssault.lua:146: attempt to index field '_wave_text' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                    KERNELBASE  (???)     VirtualQueryEx                                      

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.62.0
	CPU : Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0 
	GPU : NVIDIA GeForce GTX 760 / nvd3dum.dll[21.21.13.7849]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16273MB 160KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (扬声器 (Realtek High Definition Audio))

**Comment by pine0922** [comment]
Problem solved

Thank you >TheRealElysium<


TheRealElysium commented a day ago • edited
This happens because set_assault_wave_number is now being called in sync_start_assault. WolfHUD has modified set_assault_wave_number to add a wave panel, but this data is only defined during a safehouse raid. set_assault_wave_number calls this data but it has not been set, so the game crashes. While I'm sure the above fix prevents a crash, it isn't really a solution to the problem. I've wrapped calls to _wave_text in a check for the safehouse raid, which should retain the intended functionality and prevent crashes. This may not be the cleanest solution but it is what I've come up with.

http://pastebin.com/HFyGX5dJ

https://www.diffchecker.com/2KQkV69h

**Comment by pine0922** [comment]
Application has crashed: C++ exception
mods/WolfHUD/lua/MenuTweaks.lua:605: attempt to index field 'peer_join_start_t' (a nil value)

new crash issues

**Comment by Kamikaze94** [comment]
Same as issue #139 , solved in latest commit.
