### ISSUE TITLE
Crash + federal inventory.

### ISSUE THREAD

**Issue by Nationwideis30guys** [Kamikaze94/WolfHUD#143]
I was playing with wolfhud on this website http://paydaymods.com/mods/298/wolfhud i believe its the same as this site. I was playing bomb something dockyard and i have BLT,better ai and wolfhud and i went loud one or two minutes in and it started to freeze and crash.( my payday has some other mods that i installed incorrectly) so being my dumb self, i uninstalled payday and now its still downloading.. just 4 gigabytes left.. and this was today, my first time playing with wolfhud and blt and better ai.

Also before i started playing i struggled with f.l (federal inventory). i opened payday 2 and it said if it wanted me to update f.l so i pressed yes and it exited out of it and didn't do anything. i kept trying and nothing happened. i eventually pressed no and it said it was disabled and if i wanted to download it so i pressed it and pressed yes and it did nothing it said in the corner box of the main menu i had to restart my game so i did and then it did the same things. its annoying though. and i do not know what it does i think it said something with textures or something.

-Nation wide is 30 guys.

**Comment by NerdVenom** [comment]
Federal Inventory replaces all the inventory icons with full color ones. As for your crash, check out this https://github.com/Kamikaze94/WolfHUD/issues/139

**Comment by Nationwideis30guys** [comment]
so there is not a way to fix it with the crashes?

**Comment by NerdVenom** [comment]
This link has a fix : http://pastebin.com/HFyGX5dJ

Click download, rename it Advassault.lua and put in your WolfHUD/lua folder. Overwrite if asked.
