### ISSUE TITLE
Game crashes when i use incendiary rounds for shotguns

### ISSUE THREAD

**Issue by Poloski** [Kamikaze94/WolfHUD#144]
I was playing on Slaughterhouse, boiling point, and safehouse raid, and as soon as i started to shoot the incendiary rounds of my raven shotgun and hit multiple cops the game crashes.

Sun Feb 05 12:07:44 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.62.0
	CPU : Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 610 / nvd3dum.dll[21.21.13.6909]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     3957MB 404KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Auriculares (Dispositivo de High Definition Audio))

**Comment by MadCircus** [comment]
I'm having the same Problem, 

Sat Feb 04 20:44:34 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.62.0
	CPU : Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvd3dum.dll[21.21.13.7849]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8144MB 172KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (SyncMaster-4 (NVIDIA High Definition Audio))

**Comment by Kamikaze94** [comment]
Same as issue #119
Known bug in the release version, fixed in dev branch.
