### ISSUE TITLE
wolfhud textures

### ISSUE THREAD

**Issue by Nationwideis30guys** [Kamikaze94/WolfHUD#145]
i just fixed my wolfhud and now no crashes. so it installed the textures correctly for wolfhud and i hate it. how can i remove it?

**Comment by TheRealElysium** [comment]
They should be located in /assets/mod_overrides somewhere.

**Comment by Kamikaze94** [comment]
"Payday 2/assets/mod_overrides/WolfHUD_Textures" is one file containing the vehicle images for drivingHUD mainly.
"Payday 2/assets/moid_overrides/Ferderal Inventory" are the colored Weapon/deployable/etc icons.

The first one is mandatory, or you might get wrong icons displayed, the second one is optional.
