### ISSUE TITLE
Payday2 crashes on loud heists.

### ISSUE THREAD

**Issue by syndencity** [Kamikaze94/WolfHUD#146]
Stealth works fine, but after about 6 minutes into loud (near the assault start) it crashes.
Log:
----------------------------------------------------------------------

Sun Feb 05 20:42:42 2017

Application has crashed: C++ exception
mods/WolfHUD-master/lua/AdvAssault.lua:146: attempt to index field '_wave_text' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

I'm no expert, but judging by the crash thingy it might have to do something with the advanced assault display? If so i guess disabling it will fix it?

**Comment by syndencity** [comment]
noticed #139 but i don't have the dev build, so there might be a different issue? not sure, gonna try the solution in that thread.

**Comment by NerdVenom** [comment]
This link has a fix : http://pastebin.com/HFyGX5dJ

Click download, rename it Advassault.lua and put in your WolfHUD/lua folder. Overwrite if asked.

**Comment by syndencity** [comment]
Thanks, gonna try it, will edit the post when i test it.

**Comment by syndencity** [comment]
Weird, didn't work, crashed the second the assault started. Crashlog says the same thing.
Maybe i did something wrong?

**Comment by syndencity** [comment]
Nevermind, putting the script in and disabling advanced assault banner works, thanks!

**Comment by NerdVenom** [comment]
If you have actually fixed it, you should be able to keep the advanced assault banner enabled. I'm running the dev version from this page and I get no crashes when using that fix.

**Comment by syndencity** [comment]
I'm off my pc atm, and I followed your instructions precisely twice and the issue was still there, the third time I disabled advanced assault banner and didn't crash, so I will turn it on again when I get back on my pc and check if it crashes. I'll post here when I do.

**Comment by Kamikaze94** [comment]
Fixed in latest commit, as @NerdVenom stated in the original issue #139 .
