### ISSUE TITLE
WolfHUD/lua/AdvAssault.lua:146: attempt to index field '_wave_text'

### ISSUE THREAD

**Issue by SomePlayer** [Kamikaze94/WolfHUD#148]
EDIT: This is the same issue as https://github.com/Kamikaze94/WolfHUD/issues/146

The game just updated with new John Wick heist. 
And the dev branch is now crashing for me. Even on the good old maps. 
While the old (stable) version works for a friend, but he does not have the new DLC. And we have not tried those missions with him as host.

crash.txt

Application has crashed: C++ exception
mods/WolfHUD/lua/AdvAssault.lua:146: attempt to index field '_wave_text' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlQueryPackageClaims                               
                         ntdll  (???)     NtQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.63.1
	CPU : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 760 / nvd3dum.dll[21.21.13.7633]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16244MB 840KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (Razer Kraken USB))

**Comment by Kamikaze94** [comment]
Fixed in latest commit.
