### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Jowy12** [Kamikaze94/WolfHUD#149]
Application has crashed: C++ exception
mods/WolfHUD-master/Core.lua:621: attempt to call field 'DirectoryExists' (a nil value)

**Comment by Jowy12** [comment]
The crash occurs when i leave public lobby. Just instant crash.

**Comment by Kamikaze94** [comment]
Looks like it couldn't find the DirectoryExists function.
That one is actually not part of WolfHUD, but coded into BLT.
If you havn't getten it fixed, I'd suggest trying to reinstall BLT :)

**Comment by Jowy12** [comment]
Actually it's fixed now after i downloaded the recently updated WolfHUD. Thank you for the answer (:
