### ISSUE TITLE
Crash when attempting to "set slider value"

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#150]
I just got the new Dev Build of WolfHUD from 14 hours ago (yay, the mod lives! :) ), and ran into a crash messing with the settings. I attempted to enter a slider value for the chat window's fade duration of 20 seconds. That's achieved by right-clicking a slider, which opens up a window to enter text into. I left the 20 which was already there and hit the Enter UI button. This produced the following crash:

Application has crashed: C++ exception
[string "lib/managers/menu/menunodegui.lua"]:1616: attempt to call method 'set_font_size' (a nil value)

**Comment by Kamikaze94** [comment]
Huh, which mod lets you enter a slider value with right click?
If I right-click my sliders ingame, just nothing happens...?

**Comment by Jowy12** [comment]
I can confirm this crash issue too :D
Got the same log too.

**Comment by DOUBLE2DEAGLE** [comment]
I think BeardLib does that right click thing

**Comment by Malidictus** [comment]
Huh... I thought it was Slider Values from WolfHUD? I do have BeardLib, so it might be that one. Could be it's not supplying a nil value to BLT when I attempt to use it. Sorry, I apparently misunderstood what Slider Values did.

**Comment by DOUBLE2DEAGLE** [comment]
Slider Values just shows the numerical value of sliders

**Comment by Malidictus** [comment]
Then this isn't a WolfHUD issue. My apologies. I think you can feel free to close it.
