### ISSUE TITLE
2 'Questions' about the latest version

### ISSUE THREAD

**Issue by OhhLoz** [Kamikaze94/WolfHUD#153]
Hello,
After downloading the latest branch, the inventory page names are gone, and I can no longer double click to rename them, was this feature intentionally removed?

Also, we used to be able to cancel an interaction with the same button we started it with (by default F), however in the latest version it has been remapped to G. I read that you added a note in brackets in the settings that we can still use F to cancel it but when I tried it didn't work. Is this intentional too?

Thanks,
OhhLoz

**Comment by Kamikaze94** [comment]
Alright, just did a quick test.
Renaming tabs is still there. You can rename them by double clicking in the inventory screen. You cannot change the name in mission briefing.

The default button to cancel locked interactions has always been your equipment key (default G), but there is an ingame option to change it to your interaction key (default F). could change that no problem in my test. please note that the changed setting updates with the start of the next interaction, not instantly.

**Comment by OhhLoz** [comment]
Ah yes, I thought that checkbox removes the ability to cancel the interaction altogether, however it did allow me to use F instead.

I still cant get the inventory pages working.

**Comment by OhhLoz** [comment]
Also, display weapon names for teammates/player doesn't seem to work either.

**Comment by Kamikaze94** [comment]
Weapon names seem to be working fine for me (at least player ones, havn't checked teammates)
Strange...

**Comment by OhhLoz** [comment]
Ah, its not worked for me in any version, on 'both' setting.

**Comment by OhhLoz** [comment]
Yea, neither player or teammate ones work for me, Where are they supposed to be? Even on the newest version.
