### ISSUE TITLE
wolfhud : RESOLITION change Crash!

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#154]
https://www.youtube.com/watch?v=HQ9kV9ujR6w&feature=youtu.be

PAYDAY 2 Crash log
Application has crashed: C++ exception
[string "lib/managers/menu/menunodegui.lua"]:1616: attempt to call method 'set_font_size' (a nil value)
SCRIPT STACK

Fix please! T^T

**Comment by hud8614** [comment]
Fix Please !!!!!T_T

**Comment by Kamikaze94** [comment]
Same crash as issue #150.
