### ISSUE TITLE
commit 422 controller bug 

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#155]
All non bag related interactions show $btn_interact 
![wolfhud btn_interact](https://cloud.githubusercontent.com/assets/17696438/22854554/fc0b0f3e-f068-11e6-8ee7-aedfd2ab7a7f.PNG)

**Comment by Kamikaze94** [comment]
Ah, completely forgot about that.
Same happened when I first added the bag value stuff...
Put the BTN_INTERACT macro line out of the if statement, should be working now.

Thanks for the report :)
