### ISSUE TITLE
Crash in loadout screen

### ISSUE THREAD

**Issue by Jowy12** [Kamikaze94/WolfHUD#157]
Application has crashed: C++ exception
[string "lib/managers/missionassetsmanager.lua"]:544: attempt to index field '?' (a nil value)

**Comment by XxLegoTadhgxX** [comment]
same

**Comment by Kamikaze94** [comment]
Are you using the latest dev version?
Because I don't see any way anymore, how this could be caused by this mod, since I rewrote the BuyAllAssets script to basically not modify any functions of the assetsmanager anymore...
