### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by pine0922** [Kamikaze94/WolfHUD#158]
it happend when i run the game.
Application has crashed: C++ exception
mods/WolfHUD/lua/WeaponGadgets.lua:152: attempt to perform arithmetic on field '_current_intensity' (a nil value)

**Comment by Kamikaze94** [comment]
Added a default value on missing intensity value to gadget.
This should prevent crashing if the update function is called before full setup of the gadget.

Btw, did the crash appear right at the start in blackscreen/spawn state?

**Comment by pine0922** [comment]
during spawn state, crash before character shows up.
currently I'm rolling back to stable version.
