### ISSUE TITLE
Crash on Shotgun kills with Dragon Breath Rounds

### ISSUE THREAD

**Issue by towipion** [Kamikaze94/WolfHUD#159]
Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.63.1
	CPU : Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX TITAN X / nvd3dum.dll[21.21.13.7849]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16279MB 364KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (M43-C1-4 (NVIDIA High Definition Audio))

The game crashes after 10-15 minutes of playing. Rather I'm with a group or alone it'll crash.

**Comment by towipion** [comment]
Ended up downloading the link from this site and it works now.

**Comment by Kamikaze94** [comment]
Same as issue #119
Known bug in the release version, fixed in dev branch.

**Comment by Fairs1973** [comment]
How do I change the mod to the dev branch? Is downloading it here from GitHub the only way, or is there a function in the options or so? And how about automatic updates after changing to the dev branch?

**Comment by Kamikaze94** [comment]
You can only manually download and install the dev version.
It won't update automatically until the release version gets updated.
In that casae, BLT will tell you about an update. If you choose to update, you are on the release version again.
