### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by KouRyuu2** [Kamikaze94/WolfHUD#161]
Crash as I got to loading screen of a heist. Jewlery Store Normal

Tue Feb 14 20:54:15 2017

Application has crashed: C++ exception
mods/WolfHUD/Core.lua:652: bad argument #1 to 'concat' (table expected, got string)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.63.1
	CPU : AMD A8-6410 APU with AMD Radeon R5 Graphics (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R5 Graphics / aticfx32.dll[21.19.407.0]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     7129MB 268KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Kamikaze94** [comment]
Looks like one of the getSetting calls passed a string rather that a table as first argument.
I ran a quick search through all of WolfHUD's files, and I didn't forget to change it anywhere...

Have you changed any file within WolfHUD? Or running any mod that might try to get a certain value from it (maybe for some compatability feature)?

Guess I'll have to add a check for that parameters type regardless....
