### ISSUE TITLE
Crashing when dieing after swan song

### ISSUE THREAD

**Issue by thepcnoob** [Kamikaze94/WolfHUD#167]
i keep crashing when i go down from swan song and get the error:

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

I've tried reinstalling everything but it is still occurring, i tried removing the GameInfoManager.lua file but then when i try to put down an ECM my game crashes with the error:

Application has crashed: C++ exception
mods/WolfHUD/lua/EquipmentTweaks.lua:48: attempt to index field 'gameinfo' (a nil value)

**Comment by DrSokolov** [comment]
1) First, go to mods/WolfHUD/lua/GameInfoManager.lua
2) Open it up with a text editor. I'm using Notepad++
3) Locate the 386th line  berserker_damage_multiplier = { "swan_song", "swan_song_aced" }, - Delete 
Do same thing for 3136 and 3137th lines.
melee_damage_health_ratio_multiplier = { category = "melee", buff_id = "berserker" }, -Delete 
damage_health_ratio_multiplier = { category = "damage", buff_id = "berserker_aced" }, - Delete
