### ISSUE TITLE
Crashing after swan song fades

### ISSUE THREAD

**Issue by firstnecron** [Kamikaze94/WolfHUD#173]
After swan song expires, I crash with the error: 

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

**Comment by renuschd** [comment]
this is fixed in the dev version so if you download it from here(github) and install it it'll fix

**Comment by Kamikaze94** [comment]
Duplicate of issue #163.
