### ISSUE TITLE
self._brush = Draw:brush(self._themes[self._theme_type].brush) is gone

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#176]
A long time ago, there was this thread: https://github.com/Kamikaze94/WolfHUD/issues/34. In it, we discussed a way to make laser sight beams solid by inserting the line in the title into the gadget Lua file. That was kept disabled and out of the options, but still stayed in the code as a commented-out line which I could re-enable manually.

With the redesign of the whole gadgets file, that line seems to have gone. I remember the issue that caused it to disappear initially was the bug with sniper lasers staying permanently for drop-in clients. That has recently been revealed to be a Vanilla bug, however. I was wondering if it's possible to reinsert that line, commented out if necessary, so I can use it again.

The truth of the matter is that even at maximum opacity, Lasers are still far to feint for me.

**Comment by Kamikaze94** [comment]
Added back in commit 318637d1ed94d989f21e6835f83a2d631080541d.
:)

**Comment by Malidictus** [comment]
Thank you kindly :) I'll have a look at it as soon as I'm back home. Did you push an Auto Update or is this still Developer-only?

**Comment by Malidictus** [comment]
So I forgot to actually check the other day, but I did check yesterday. Yup! That line is back, and it works just fine. You can feel free to close this, if it isn't already. Sorry for the delay.
