### ISSUE TITLE
comparing num with string crash

### ISSUE THREAD

**Issue by BadLucKWyvern** [Kamikaze94/WolfHUD#177]
here are 3 consecutive crashes. same error
cook off 2 and 4 players mayhem diff
Payday Crash Log reader

Sun Feb 19 16:06:02 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.64.1
	CPU : Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[9.18.13.4788]
	Language : @IDaadeda58d8e5a71d@
	Memory :     15832MB 432KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Haut-parleurs (Realtek High Definition Audio))

----------------------------------------------------------------------

Sun Feb 19 21:14:12 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.64.1
	CPU : Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[9.18.13.4788]
	Language : @IDaadeda58d8e5a71d@
	Memory :     15832MB 432KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Haut-parleurs (Realtek High Definition Audio))

----------------------------------------------------------------------

Sun Feb 19 21:20:58 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.64.1
	CPU : Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[9.18.13.4788]
	Language : @IDaadeda58d8e5a71d@
	Memory :     15832MB 432KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Haut-parleurs (Realtek High Definition Audio))

**Comment by OnclePhillipe** [comment]
I'm close to OP, and it seem that we solved this issue by adding a tonumber at line 12 in DamagePopup.lua
like this : 
`if tonumber(data.damage) > 0.09 and alive(data.attacker_unit) and alive(player) and (data.attacker_unit == player or data.attacker_unit:base()._thrower_unit == player) then`

**Comment by Kamikaze94** [comment]
Same as issue #119
Known bug in the release version, fixed in dev branch.
