### ISSUE TITLE
Crash when modifying weapons

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#18]
When trying to modify a weapon in the inventory, I get this crash. Using latest version of as now.

Application has crashed: C++ exception
mods/Wolf HUD/lua/MenuTweaks.lua:48: attempt to index field '?' (a nil value)

**Comment by Kamikaze94** [comment]
Yeah, didn't test that, sorry.
Hooked the code into a better suitable function now + added check to prevent non-weapon slots to mess with my code, :)
