### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jhkljh** [Kamikaze94/WolfHUD#182]
had a crash after host restarted or something on a failed srtealth day1 FF and didn't notice it under issues anywhere.
i just updated to the dev version to fix other issues.
used to have hoxhud, but manually removed everything from it.
otherwise the only other mod ive ever used is wolfhud.
hope this helps with any debugging

[string "lib/managers/mission/elementspecialobjectiv..."]:740: attempt to call method 'SO_access' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.64.1
	CPU : Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[21.21.13.7849]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16328MB 568KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (4- ASTRO Wireless Transmitter ))

**Comment by Kamikaze94** [comment]
WolfHUD doesn't mess with mission objective nodes,and since you don't use other mods,I'd bet my money on base game bug...
Thanks for the report, but I think there isn't anything I could do for you. :)
