### ISSUE TITLE
Federal Inventory notification issues

### ISSUE THREAD

**Issue by Dunant** [Kamikaze94/WolfHUD#183]
as when i started the game,the game ask me if i want to install FI,i clicked "Yes" and the notification dissapeared,but when i want to access anything in the main menu,it keeps popping up the same notification again and again.
is this a common issue or what?
Thanks

**Comment by Kamikaze94** [comment]
Not sure there, maybe it cannot create the necessary folders for some reason.
You can always choose to do the manual installation.
It's the last step in the installation instructions on paydaymods or modworkshop.

**Comment by Kamikaze94** [comment]
Found the problem, should fixed now.

Thanks for the report. 👍
