### ISSUE TITLE
damage indicator crash

### ISSUE THREAD

**Issue by syndencity** [Kamikaze94/WolfHUD#185]
happens randomly
----------------------------------------------------------------------

Sat Feb 25 17:19:22 2017

Application has crashed: C++ exception
[string "lib/units/enemies/cop/copdamage.lua"]:2430: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???

**Comment by OnclePhillipe** [comment]
Same happened to me, but it's unplayable now
