### ISSUE TITLE
Crashing when a player enters custody, while burning cops, possible relation with Pocohud.

### ISSUE THREAD

**Issue by Seamlink** [Kamikaze94/WolfHUD#186]
PAYDAY 2 Crash log
Application has crashed: access violation
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Current thread: Main
Script stack:
             _process_damage()  @mods/WolfHUD/lua/TabStats.lua:863                  
                                @mods/WolfHUD/lua/TabStats.lua:855                  
                            ()  =(tail                                              
                      call):-1                                                      
@mods/PocoHud3/poco/../poco/Hud3.lua:2072  ()                                                  
                        =(tail  call):-1                                            
                 damage_fire()  lib/units/enemies/cop/copdamage.lua:1035            
         detect_and_give_dmg()  lib/managers/firemanager.lua:461                    
                  _do_damage()  lib/units/environment/environmentfire.lua:266       
                                lib/units/environment/environmentfire.lua:215

**Comment by Kamikaze94** [comment]
Nah, problem was, the process damage on TabStats didn't check if the attacker (that player in this case) was an alive and valid unit, causing the crash.
Added the missing check in commit 318637d1ed94d989f21e6835f83a2d631080541d.
