### ISSUE TITLE
Reload Timer Doesn't Appear

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#187]
Doesn't matter if I have the option on or off, the reload timer doesn't show up like the timer for other interactions.  I have the interaction circle disabled and I'm using the Total option for locking.

Now I also have MUI enabled for notification styles and HoloUI for menu styling, rest is turned off. Not sure if that would affect it.

**Comment by Kamikaze94** [comment]
Hmm, not sure either.
All I can say is, reload timer is working fine for me (I'm not using HoloUI though).
