### ISSUE TITLE
"wolfhud_enemy_ceiling_turret" : "TURRET",

### ISSUE THREAD

**Issue by chromKa** [Kamikaze94/WolfHUD#189]
check this in game (in mission)

**Comment by NerdVenom** [comment]
Might want to mention which heist it's on.

**Comment by chromKa** [comment]
SCARFACE MANSION.

**Comment by chromKa** [comment]
![20170325120254_1](https://cloud.githubusercontent.com/assets/19959081/24321411/1cf29dd8-115d-11e7-93c0-db8caf0be422.jpg)

**Comment by Kamikaze94** [comment]
Yep, had that changes a little ago, uploaded the changes now. (commit 318637d1ed94d989f21e6835f83a2d631080541d)
The correct unit ID was "ceiling_turret_module_no_idle" btw...  :)
