### ISSUE TITLE
Crash when joining, arrowbase.lua causing it

### ISSUE THREAD

**Issue by Kroggy** [Kamikaze94/WolfHUD#191]
This is what i get from crash.txt when i try to join any server in payday 2.
Modified the GameInfoManager yesterday for the swan song crash, where 3 lines were deleted. Worked after, and now it doesn't.

> Application has crashed: C++ exception
[string "lib/units/weapons/projectiles/arrowbase.lua"]:632: attempt to index local 'parent_body' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.65.0
	CPU : Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[21.21.13.7866]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16288MB 232KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Højttalere (Realtek High Definition Audio))

--------------------------------

And the log from mods folder:

04:18:19 PM Log: CURL INITD
04:18:23 PM Log: Initiating Hook
04:18:27 PM Log: Initiating Hook
04:18:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:18:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:18:27 PM Lua: [Mods] Loading mods for state (table: 001D0480)
04:18:27 PM Lua: [Mods] Loading mod: base...
04:18:27 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:18:27 PM Lua: [Mods] Loading mod: HoloInfo...
04:18:27 PM Lua: [Mods] Loading mod: SilentAssassin...
04:18:27 PM Lua: [Mods] Loading mod: VELOSync...
04:18:27 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:18:27 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:18:27 PM Log: Initiating Hook
04:18:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:18:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:18:27 PM Lua: [Mods] Loading mods for state (table: 001D04C0)
04:18:27 PM Lua: [Mods] Loading mod: base...
04:18:27 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:18:27 PM Lua: [Mods] Loading mod: HoloInfo...
04:18:27 PM Lua: [Mods] Loading mod: SilentAssassin...
04:18:27 PM Lua: [Mods] Loading mod: VELOSync...
04:18:27 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:18:27 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:18:27 PM Lua: [WolfHUD] ERROR: Error while loading, settings file could not be opened (mods/saves/WolfHUD_v2.json)
04:18:28 PM Log: Initiating Hook
04:18:28 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:18:28 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:18:28 PM Lua: [Mods] Loading mods for state (table: 267014E0)
04:18:28 PM Lua: [Mods] Loading mod: base...
04:18:28 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:18:28 PM Lua: [Mods] Loading mod: HoloInfo...
04:18:28 PM Lua: [Mods] Loading mod: SilentAssassin...
04:18:28 PM Lua: [Mods] Loading mod: VELOSync...
04:18:28 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:18:28 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:18:34 PM Log: Incoming HTTP Request/Request
04:18:34 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=delayedcallsfix&mod[3]=silentassassin&mod[4]=wolfhud&mod[5]=wolfhud_textures&mod[6]=fed_inv
04:18:34 PM Log: 1256
04:18:34 PM Log: Launching Async HTTP Thread
04:18:34 PM Lua: [Updates] Attempting to remove temporary hook dll...
04:18:34 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
04:18:37 PM Lua: [Updates] Received update data for 'silentassassin', server revision: 2
04:18:37 PM Lua: [Updates] Received update data for 'wolfhud_textures', server revision: 8
04:18:37 PM Lua: [Updates] Received update data for 'delayedcallsfix', server revision: 2
04:18:37 PM Lua: [Updates] Received update data for 'fed_inv', server revision: 13
04:18:37 PM Lua: [Updates] Received update data for 'payday2blt', server revision: 12
04:18:37 PM Lua: [Updates] Received update data for 'wolfhud', server revision: 20
04:18:37 PM Lua: [Updates] Received update data for 'payday2bltdll', server revision: 5
04:19:39 PM Lua: [1] SYSTEM: Shadow_Striker is joining.
04:19:46 PM Log: Initiating Hook
04:19:46 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:19:46 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:19:46 PM Lua: [Mods] Loading mods for state (table: 22351680)
04:19:46 PM Lua: [Mods] Loading mod: base...
04:19:46 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:19:46 PM Lua: [Mods] Loading mod: HoloInfo...
04:19:46 PM Lua: [Mods] Loading mod: SilentAssassin...
04:19:46 PM Lua: [Mods] Loading mod: VELOSync...
04:19:46 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:19:46 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:19:46 PM Log: Initiating Hook
04:19:46 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:19:46 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:19:46 PM Lua: [Mods] Loading mods for state (table: 402706A0)
04:19:46 PM Lua: [Mods] Loading mod: base...
04:19:46 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:19:46 PM Lua: [Mods] Loading mod: HoloInfo...
04:19:46 PM Lua: [Mods] Loading mod: SilentAssassin...
04:19:46 PM Lua: [Mods] Loading mod: VELOSync...
04:19:46 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:19:46 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:19:46 PM Log: Initiating Hook
04:19:46 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:19:46 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:19:46 PM Lua: [Mods] Loading mods for state (table: 3E111600)
04:19:46 PM Lua: [Mods] Loading mod: base...
04:19:46 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:19:46 PM Lua: [Mods] Loading mod: HoloInfo...
04:19:46 PM Lua: [Mods] Loading mod: SilentAssassin...
04:19:46 PM Lua: [Mods] Loading mod: VELOSync...
04:19:46 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:19:46 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:19:46 PM Lua: [WolfHUD] ERROR: Error while loading, settings file could not be opened (mods/saves/WolfHUD_v2.json)
04:20:00 PM Log: Initiating Hook
04:20:00 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:20:00 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:20:00 PM Lua: [Mods] Loading mods for state (table: 2E712560)
04:20:00 PM Lua: [Mods] Loading mod: base...
04:20:00 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:20:00 PM Lua: [Mods] Loading mod: HoloInfo...
04:20:00 PM Lua: [Mods] Loading mod: SilentAssassin...
04:20:00 PM Lua: [Mods] Loading mod: VELOSync...
04:20:00 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:20:00 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:20:00 PM Log: Initiating Hook
04:20:00 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:20:00 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:20:00 PM Lua: [Mods] Loading mods for state (table: 21762F00)
04:20:00 PM Lua: [Mods] Loading mod: base...
04:20:00 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:20:00 PM Lua: [Mods] Loading mod: HoloInfo...
04:20:00 PM Lua: [Mods] Loading mod: SilentAssassin...
04:20:00 PM Lua: [Mods] Loading mod: VELOSync...
04:20:00 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:20:00 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:20:00 PM Log: Initiating Hook
04:20:00 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:20:00 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:20:00 PM Lua: [Mods] Loading mods for state (table: 1CEC3F80)
04:20:00 PM Lua: [Mods] Loading mod: base...
04:20:00 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:20:00 PM Lua: [Mods] Loading mod: HoloInfo...
04:20:00 PM Lua: [Mods] Loading mod: SilentAssassin...
04:20:00 PM Lua: [Mods] Loading mod: VELOSync...
04:20:00 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:20:00 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:20:00 PM Lua: [WolfHUD] ERROR: Error while loading, settings file could not be opened (mods/saves/WolfHUD_v2.json)
04:20:01 PM Log: Incoming HTTP Request/Request
04:20:01 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=delayedcallsfix&mod[3]=silentassassin&mod[4]=wolfhud&mod[5]=wolfhud_textures&mod[6]=fed_inv
04:20:01 PM Log: 2311
04:20:01 PM Log: Launching Async HTTP Thread
04:20:01 PM Lua: [Updates] Attempting to remove temporary hook dll...
04:20:01 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
04:20:02 PM Lua: [Updates] Received update data for 'silentassassin', server revision: 2
04:20:02 PM Lua: [Updates] Received update data for 'wolfhud_textures', server revision: 8
04:20:02 PM Lua: [Updates] Received update data for 'delayedcallsfix', server revision: 2
04:20:02 PM Lua: [Updates] Received update data for 'fed_inv', server revision: 13
04:20:02 PM Lua: [Updates] Received update data for 'payday2blt', server revision: 12
04:20:02 PM Lua: [Updates] Received update data for 'wolfhud', server revision: 20
04:20:02 PM Lua: [Updates] Received update data for 'payday2bltdll', server revision: 5
04:20:19 PM Lua: [1] SYSTEM: renren03 is joining.
04:20:27 PM Log: Initiating Hook
04:20:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:20:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:20:27 PM Lua: [Mods] Loading mods for state (table: 51592FE0)
04:20:27 PM Lua: [Mods] Loading mod: base...
04:20:27 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:20:27 PM Lua: [Mods] Loading mod: HoloInfo...
04:20:27 PM Lua: [Mods] Loading mod: SilentAssassin...
04:20:27 PM Lua: [Mods] Loading mod: VELOSync...
04:20:27 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:20:27 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:20:27 PM Log: Initiating Hook
04:20:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:20:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:20:27 PM Lua: [Mods] Loading mods for state (table: 371710A0)
04:20:27 PM Lua: [Mods] Loading mod: base...
04:20:27 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:20:27 PM Lua: [Mods] Loading mod: HoloInfo...
04:20:27 PM Lua: [Mods] Loading mod: SilentAssassin...
04:20:27 PM Lua: [Mods] Loading mod: VELOSync...
04:20:27 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:20:27 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:20:27 PM Log: Initiating Hook
04:20:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
04:20:27 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:20:27 PM Lua: [Mods] Loading mods for state (table: 256C2D40)
04:20:27 PM Lua: [Mods] Loading mod: base...
04:20:27 PM Lua: [Mods] Loading mod: DelayedCallsFix...
04:20:27 PM Lua: [Mods] Loading mod: HoloInfo...
04:20:27 PM Lua: [Mods] Loading mod: SilentAssassin...
04:20:27 PM Lua: [Mods] Loading mod: VELOSync...
04:20:27 PM Lua: [Mods] Loading mod: WolfHUD-master...
04:20:27 PM Lua: [Mods] Mod 'mods/HoloInfo/' is disabled!
04:20:27 PM Lua: [WolfHUD] ERROR: Error while loading, settings file could not be opened (mods/saves/WolfHUD_v2.json)
04:20:38 PM Lua: [1] SYSTEM: Avenger Star is joining.
04:20:38 PM Lua: [1] SYSTEM: 1Bullet2Kills is joining.
04:20:50 PM Log: CURL CLOSED

**Comment by Kroggy** [comment]
Checked the saves folder and didnt see the WolfHUD_v2.json file
Started payday 2, went to wolfhud options and reset skills, file appeared and could join again. Will update if error occurs.

**Comment by Kamikaze94** [comment]
Seems like you got it fixed, so I'll close this. 😃
