### ISSUE TITLE
Crash by GameInfoManager.lua

### ISSUE THREAD

**Issue by Str1ker878** [Kamikaze94/WolfHUD#194]
Game crashes at seemingly random moment. Is there anything can be done to fix that? Well, besides removing the WolfHUD, ofc.

Quoting the crashlog:
```
----------------------------------------------------------------------

Sun Mar 12 22:54:56 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.65.0
	CPU : Pentium(R) Dual-Core CPU E5300 @ 2.60GHz (1 core); SSE; SSE2; SSE3; SSSE3
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 650 / nvd3dum.dll[21.21.13.7849]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     7167MB 180KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
```

**Comment by FlamingFox911** [comment]
This might be related to the problem with the recent updates with Payday that has caused this mod to crash whenever you (or someone?) went into swan song. There are and were numerous issue reports appearing before.

Have you tried the latest dev version of WolfHud on GitHub [here](https://github.com/Kamikaze94/WolfHUD/archive/master.zip)? I use it and I no longer get this error. If it still doesn't work, there is a butchering method of fixing it [here](https://github.com/Kamikaze94/WolfHUD/issues/163#issuecomment-280882422).

**Comment by Str1ker878** [comment]
Apparently that solved it. Thanks.
