### ISSUE TITLE
Crash after changing resolution (everytime)

### ISSUE THREAD

**Issue by Seamlink** [Kamikaze94/WolfHUD#195]
Crash date: 3/16/2017 3:36:12 PM

PAYDAY 2 Crash log
Application has crashed: C++ exception
[string "lib/managers/menu/menunodegui.lua"]:1552: attempt to call method 'set_font_size' (a nil value)
SCRIPT STACK
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
-------------------------------
Current thread: Main

**Comment by Kamikaze94** [comment]
Same issue as #150 .
