### ISSUE TITLE
Crash on Hoxton Breakout Day 2 Tabstats with Pocohud

### ISSUE THREAD

**Issue by Seamlink** [Kamikaze94/WolfHUD#196]
Current thread: Main
Script stack:
             _process_damage()  @mods/WolfHUD/lua/TabStats.lua:863
                                @mods/WolfHUD/lua/TabStats.lua:855
                            ()  =(tail
                      call):-1
@mods/PocoHud3/poco/../poco/Hud3.lua:2072  ()
                        =(tail  call):-1
                 damage_fire()  lib/units/enemies/cop/copdamage.lua:1035
         detect_and_give_dmg()  lib/managers/firemanager.lua:461
                  _do_damage()  lib/units/environment/environmentfire.lua:266
                                lib/units/environment/environmentfire.lua:215

**Comment by Kamikaze94** [comment]
Possible relation to issue #186, so this is hopefully fixed as well.
