### ISSUE TITLE
Trip Mine Sensor Mode

### ISSUE THREAD

**Issue by frollay** [Kamikaze94/WolfHUD#197]
I have just reinstalled the game (and mod) and I found that the trip mine auto-sensor mode has disappeared from the options. A quick search shows that the description is still in the localisation files.

**Comment by Kamikaze94** [comment]
Auto Sensor Trip Mines are a feature of the base game now, thats why I removed it.
Didn't bother to remove the settings strings though...

**Comment by frollay** [comment]
Thanks for the heads up! I must have missed it in the patch notes somewhere.
