### ISSUE TITLE
WolfHUD Causing Crash Upon Start

### ISSUE THREAD

**Issue by HawksWill** [Kamikaze94/WolfHUD#206]
Hi, I only have two mods installed, your WolfHUD and Silent Assassin. Since the newest update it crashes upon start, not even reaching intro cut-scene. Tried a fresh install and removed Silent Assassin to check if it was a conflict. Still crashed. Not quite sure whats wrong. But it is definitely related to WolfHUD.

**Comment by HawksWill** [comment]
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap

**Comment by FlamingFox911** [comment]
That doesn't really help, that callstack. What does the error give?
