### ISSUE TITLE
Random Crash after last GAME update

### ISSUE THREAD

**Issue by Nyakuya** [Kamikaze94/WolfHUD#207]
So, it's that. I'm having random crashes in the middle of the matches. One second i'm shooting up and then one second later i'm watching my desktop with the game closed.

CTD (Crash To Desktop), that's what i'm having since the last game update, (The russian weapon pack DLC).

I verified the game cache with steam, and all seems to be normal. So i uninstalled the mod and now i'm not having any crash at all.

Seems like the mod isn't compatible with the lastest game update, i do not know why.

I love this mod, so if anyone can help with this, i will be grateful.

CRASH LOGS:
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/877598/crash.txt)
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/877599/crashlog.txt)

**Comment by Kamikaze94** [comment]
Looks like the crash related to fire ammo shotguns.
If thats the case, it's not in the dev version, which can be downloaded here, but still in the released version on paydaymods and modworkshop.

Could this have been the issue?

**Comment by Nyakuya** [comment]
I don't remember if i was using a shotgun with incendiary ammo, i don't think so. But i figured out to deselect "show damage done to enemies", and the crashes stopped.

Still, it is possible for you fix this error?, because i like seeing the damage stat popping in the screen.

**Comment by Kamikaze94** [comment]
Did you us ethe release version from paydaymods/modworkshop when the crash happened or the dev version here from GitHUB?
Like I said, it shouldn't appear in the dev build, but I know this bug is in the release version.

**Comment by Nyakuya** [comment]
I use the version from the main page, "https://paydaymods.com/mods/298/wolfhud".
I should use the version from git?

**Comment by FlamingFox911** [comment]
@Nyakuya I would recommend it. It is for the most part stable, albeit a dev version.
