### ISSUE TITLE
FPS Lag using any video settings using wolfhud

### ISSUE THREAD

**Issue by lafingman0** [Kamikaze94/WolfHUD#217]
Current specs:
http://imgur.com/eC8EJ0D

The game will massively lag at times for no reason and sometimes crash. 

latest crash log:
https://mega.nz/#!jcsWwBjS!Tsh5PFLgLPbZ-CV5cVQtGp0yLymm4fWTdQhAk5Ba9Rw

**Comment by Kamikaze94** [comment]
Never seen this crash reason before: __"Application has crashed: breakpoint"__ ....

Btw, your script stack says:
```
@mods/BeardLib/Classes/json_utils.lua:71            
@mods/BeardLib/Classes/json_utils.lua:79            
@mods/BeardLib/Classes/json_utils.lua:79            
@mods/BeardLib/Classes/json_utils.lua:79            
@mods/BeardLib/Classes/json_utils.lua:79            
@mods/GSI/Classes/GSICommunicator.lua:62            
@mods/GSI/Classes/GSICommunicator.lua:45            
@mods/GSI/GSICore.lua:131                           
@mods/base/req/hooks.lua:107  
@mods/base/lua/GameSetup.lua:6  
```
I have no clue what GSI even is, but this or BreadLib might have something to do with your crash?

**Comment by lafingman0** [comment]
Ah perhaps, I went scorched earth with my plugins and it worked fine. Reinstalled wolfhud and BLT tonight and it is now working perfectly. thanks for the clarification. not sure when beardlib got installed :o
