### ISSUE TITLE
Crash on opening deployables

### ISSUE THREAD

**Issue by MeenahPeixes** [Kamikaze94/WolfHUD#22]
```
Application has crashed: C++ exception
mods/WolfHUD/lua/MenuTweaks.lua:51: attempt to get length of local 'amounts' (a number value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

```

**Comment by Kamikaze94** [comment]
Oh, ....
In the briefing Equipment Inventory or Lobby/Main Inventory Equipment?
Can you tell me, which deployables you have unlocked, and how many of them? And which are locked?
Do you have any mod adding/modifying eqipment?
For some reason, the quantity in your tweakdata is a number, not a table as It should be....

EDIT: You could add "log(name_id)" in line 47 right at the beginning of MenuTweaks.lua, the last equipment ID in your BLT log is the one having the malformated quantity...

**Comment by MeenahPeixes** [comment]
Well I figured out the problem. The "Deployable shield" mod dicked me over on this one.
