### ISSUE TITLE
Game Crash by Death

### ISSUE THREAD

**Issue by asdanjer** [Kamikaze94/WolfHUD#225]
If you use the Skill to live 3-6 Seconds  on after you died, the game Crashes when you die.

**Comment by OhhLoz** [comment]
If you mean swan song, redownload the latest build.

**Comment by asdanjer** [comment]
I olready did that twice

**Comment by BangL** [comment]
you probably downloaded the wrong file. the zip under "releases" is out of date.
go to "code" -> "clone or download" -> "download zip"
or use this link: https://github.com/Kamikaze94/WolfHUD/archive/master.zip
that will give you the very latest dev-build

**Comment by asdanjer** [comment]
Ok Thank you and sorry for wasting your time.
