### ISSUE TITLE
Crash when placing a sentry gun

### ISSUE THREAD

**Issue by sweezog** [Kamikaze94/WolfHUD#229]
I'm assuming this is referencing AP round sentry guns, hence the 'switch fire mode' note.

Application has crashed: C++ exception
mods/WolfHUD/lua/EquipmentTweaks.lua:26: attempt to call method '_switch_fire_mode' (a nil value)

SCRIPT STACK

-------------------------------
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.199
	CPU : Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[22.21.13.8165]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16276MB 868KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : C-Media Electronics Inc. (Headphones (ASUS XONAR PHOEBUS Audio Device))

**Comment by Kamikaze94** [comment]
Overkill decided to change the Sentry ammo type sync routine in April Fools update.
Already fixed that one here at GitHUB.
