### ISSUE TITLE
Flame Round Crash Bug

### ISSUE THREAD

**Issue by TheAussieSlime** [Kamikaze94/WolfHUD#233]
When using Flame rounds on the raven shotgun I tend to crash. Its not always, but after about a week of swapping them in and out I have found that it NEVER happens unless i am bringing flame rounds. the shotgun I used was the raven shotgun.

**Comment by Arcaxio** [comment]
Your probably using the version downloaded from modsworkshop or paydaymods, try using the dev build found on GitHub. It's on the "Code" tab, and click on the "Clone or download" button, and then replace the existing wolfhud mod with the dev version of wolfhud

**Comment by Kamikaze94** [comment]
Same as issue #119
