### ISSUE TITLE
Access Violation Crash?

### ISSUE THREAD

**Issue by otobot1** [Kamikaze94/WolfHUD#235]
I keep crashing and getting an access violation crash. I do have pocohud as well, but I haven't been able to make the game crash with pocohud enabled and wolfhud disabled. It only crashes when wolfhud is enabled. The problem could potentially be with the BLT hook? But I don't know how to check that.

----------------------------------------------------------------------

Sun Apr 16 06:26:36 2017

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.209
	CPU : Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[22.21.13.8165]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16327MB 64KB
	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by FlamingFox911** [comment]
Access Violation is by far the worst error to encounter since it basically tells diddly-squat. I'd recommend updating your BLT as well as grabbing the latest dev version of WolfHud.
