### ISSUE TITLE
Sentry HP not Syncing to Client

### ISSUE THREAD

**Issue by Ava2201** [Kamikaze94/WolfHUD#238]
As the title says.

I can see any Sentry's actual hp in my HUD, but any Client in the Lobby Can't see the Sentry HP in the HUD or by Visual effects, he could only hear the cracking noise when it was destroyed.

If you need any more input let me know.

**Comment by Kamikaze94** [comment]
The clients don't know a sentries actual HP.
Only the ratio gets synced, not the actual total and current HP.
HUDList uses the ratio to dispaly the health bar, so its working as client.
EnemyHealthbar is using the raw values and therefore is disabled as client (for sentries).

**Comment by Ava2201** [comment]
Alright thanks for the update and keep up the good work :)
