### ISSUE TITLE
updated wolfhud not working

### ISSUE THREAD

**Issue by wolfy1992** [Kamikaze94/WolfHUD#239]
I updated the wolfhud but when I open the game it closes again ive got blt installed so where could the problem be

**Comment by Kamikaze94** [comment]
Are you using the latest dev version? 
Does it minimize the game or completely close/crash?
Does it generate a crash log? ('%localappdata%/Payday 2/crash.txt')
Do you have "WolfHUD_Textures" and/or "Federal Inventory" mod_overrides installed?

**Comment by wolfy1992** [comment]
no it just opens the game and straight away closes and yes kami sorry to bother you with this it doesn't do it on the old wolfhud just the updated one dev version

**Comment by Kamikaze94** [comment]
Does BLT work, without WolfHUD?
Can you check, if the BLT log tells you about any problems ('Payday 2/mods/logs/')?

So far I'd guess it's some problem related to creating the folders for the mod_overrides...
Maybe try to manually install them. 
WolfHUD_Textures: https://download.paydaymods.com/download/latest/wolfhud_textures
Federal Inventory: https://download.paydaymods.com/download/latest/fed_inv

**Comment by wolfy1992** [comment]
so do I place them folders into the mod or into the payday 2 folder because nothing seems to be happening or do I put them all into 1 folder

**Comment by Kamikaze94** [comment]
Those need to be extracted into "Payday 2/assets/mod_overrides/".
Each of them gets it's own folder inside there, so you end up with "Payday 2/assets/mod_overrides/WolfHUD_Textures/" and "Payday 2/assets/mod_overrides/Federal Inventory/". In each of those folders should be the file "revision.txt" and a folder called "guis".

**Comment by wolfy1992** [comment]
well ive just been on it and there in the assets mod over ride folder

**Comment by ALE854** [comment]
I've got the same problem. The log looks like this: 
06:56:49 PM Log: CURL INITD
06:56:55 PM Log: Initiating Hook
06:57:03 PM Log: CURL CLOSED

**Comment by Kamikaze94** [comment]
@wolfy1992 
In that case, let me repeat the previous questions:

> Does BLT work, without WolfHUD?
Can you check, if the BLT log tells you about any problems ('Payday 2/mods/logs/')?

@ALE854 
According to the log, seems to be a BLT issue. Does BLT work without WolfHUD? 
Did you install the "x86 2013 C++ Runtime", as stated in the installation instructions here: https://paydaymods.com/download/#Installation ?

**Comment by ALE854** [comment]
I'll check after work.

**Comment by wolfy1992** [comment]
yes it does ok i think its working now problem was i had something missing but all done now thanks kami i,ll this thread id like a deathwish mask mod if you can manage that lmaooooo

**Comment by ALE854** [comment]
My game is working too today😄

**Comment by ALE854** [comment]
Thanks for a great mod😄. Just love it.
