### ISSUE TITLE
Crash on down

### ISSUE THREAD

**Issue by brattycandy** [Kamikaze94/WolfHUD#24]
When ever i get downed the game just crashes and closes

**Comment by Kamikaze94** [comment]
Got it working?
I know, there are some problems when you disable No Slomotion Feature, as that setting is not properly coded. 
That will be fixed in the next release, so probably tomorrow when the biker dlcs come out.

**Comment by Kamikaze94** [comment]
As I suspect it was related to the No SloMo option, and you closed it, marking this as fixxed now.
