### ISSUE TITLE
Driving HUD vehicle health missing

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#241]
I don't know exactly when this happened, but the vehicle health display on Driving HUD shows 0/0 health for all vehicles. The vehicles themselves still have normal health which I can see through WolfHUDs own healthbar system, but it doesn't work once I'm inside the vehicle. From what I can tell, this is true among all the vehicles.

**Comment by Jowy12** [comment]
Works just fine for me. You sure you have the latest Dev Version of WolfHUD?

**Comment by Kamikaze94** [comment]
This issue got fixed in commit: 7e3329b8435060786cab89ff4f02b5b69918f24a

**Comment by Malidictus** [comment]
Yeah, I got a few friends of mine to grab the latest version of WolfHUD and it works for them. Must have an outdated version. Why did you stop doing BLT auto-updates?
