### ISSUE TITLE
Kingpin (Injector) Bug

### ISSUE THREAD

**Issue by Alizke** [Kamikaze94/WolfHUD#245]
hello there
when you use kingpin from scarface pack, the kingpin (injector) icon not shows and there just a count down:
![20170422214220_1](https://cloud.githubusercontent.com/assets/11285825/25306657/d5abce12-27a6-11e7-826c-ba4ee23c9d22.jpg)
also afer cooldown it shows only a 1 number and not icon:
![20170422214514_1](https://cloud.githubusercontent.com/assets/11285825/25306659/e5c4a2ba-27a6-11e7-8516-dea80ae8ed7a.jpg)
please fix it
without this mod, pay day means nothing for me!
thanks guys

**Comment by Jowy12** [comment]
Just tested and worked just fine.

Please download the Dev Version of WolfHUD from this site. Click Clone/Download.

**Comment by Kamikaze94** [comment]
Not exactly an issue with WoilfHUD, but with Federal inventory.
Currently waiting for the mega rust mask to get added to the FBI files, as I'm not happy with the edited ingame screenshot version I currently have....
Looks like Overkill will take their time with it, so maybe I'll have to try and get a better looking version. or release what I currently got and update at a later date....

**Comment by Alizke** [comment]
Hey Jowy and thanks for your answer
but i have the dev version and its not working
Kamikaze by the way as i said pay day without wolf hud is nothing
but it can be awsome if you fix this too
because im a scarface fan and i always use it

**Comment by Kampfhoernchen** [comment]
To understand you right...you can´t play without the icon? And WolfHud is useless without this little picture? xD

**Comment by TripleSixLP** [comment]
Just to say, if you think that WolfHUD is useless without ONE fucking Icon....
Then why aren't you developing your own HUD? Just be thankful for the time Kamikaze is spending on this HUD. He is doing it because he wants to, not because he is making Money out of it.

**Comment by Alizke** [comment]
whats wrong with you 2 worthless spamers?
are you blind?
i said about 4 times: PAY DAY WITHOUT WOLFHUD IS NOTHING
better to put on your glasses

**Comment by TripleSixLP** [comment]
Dude first off:
Read the Names in the Description, before you spam your answers and insults.

Stop Insulting People.

**Comment by Kampfhoernchen** [comment]
That´s why i answered, you sound like you can´t use WolfHud without it, nothing more and nothing less. Pictures last a bit, like Kami said.

**Comment by Kampfhoernchen** [comment]
To bring something usefull ito this discussion, made a (like I think) nice Mega Rust Mask icon.

@Kamikaze94

**Comment by Alizke** [comment]
look like they updated the mod
thanks for everyone, spammer or someone who helped
