### ISSUE TITLE
Crashing with sentry auto AP

### ISSUE THREAD

**Issue by Skippady** [Kamikaze94/WolfHUD#247]
I just recently got the wolfhud updated and added all the mods needed for it when testing it out everything works perfectly fine, apart from when it comes using the sentries.

Tested on several maps and even offline mode when you go to place down a sentry with the auto ap round option on, the game freezes and then crashes and closes, but when you turn the auto ap round option off and place one down everything works perfectly fine.

not sure if there is any other info you need (kind of new to this bug reporting stuff xD)

**Comment by Skippady** [comment]
Any chance this issue is getting looked into or getting fixed because as of right now i have to change the sentry ammo to ap manually when i would very much like it to auto change to ap

**Comment by Jowy12** [comment]
Just did a test and it worked perfectly. Are you sure you have the latest Dev Version of WolfHUD? If not try to download it from this site. Just hit Clone/Download.
