### ISSUE TITLE
Mark and highlights error

### ISSUE THREAD

**Issue by shadowninjah641** [Kamikaze94/WolfHUD#249]
I can mark special units, guards, & cameras but can't see the highlight. Same goes for teammates, conversions, etc. I can only fix it by going into custody and out, but it's temporary since it happens every heist.

**Comment by FlamingFox911** [comment]
This might be a DirectX issue. I know for a fact that outlines have an issue appear in other games when you are running an older DirectX (say around 8 or 9).

**Comment by shadowninjah641** [comment]
I have DirectX 12. As for the options, they both are on mod and vanilla. sorry about the delay
