### ISSUE TITLE
Constantly crashing on heist startup

### ISSUE THREAD

**Issue by MeenahPeixes** [Kamikaze94/WolfHUD#25]
```
Application has crashed: C++ exception
[string "lib/units/weapons/newraycastweaponbase.lua"]:484: attempt to get length of field '?' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     SbSelectProcedure        
```

**Comment by Kamikaze94** [comment]
Are you sure, that is related to WolfHUD?
Only scripts hooked into newraycastweaponbase are burst fire and Weapon lasers, and I don't think I modify any part data in there, just read them. 
(Could also be an interference between it and another mod again...)

**Comment by MeenahPeixes** [comment]
I've looked through my lua mods and the only things hooked to newraycastweaponbase are Bot Weapons and WolfHUD. I've disabled Bot Weapons but it didn't change anything.

**Comment by MeenahPeixes** [comment]
Well guess what. It never crossed my mind that override format mods will fuck me over on something like this. It was a mod that replaces an NPC weapon model.
