### ISSUE TITLE
crash when i start a new heist 

### ISSUE THREAD

**Issue by mcproprot** [Kamikaze94/WolfHUD#252]
Application has crashed: C++ exception
mods/WolfHUD/lua/HUDChat.lua:222: bad argument #2 to 'min' (number expected, got nil)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.216
	CPU : Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD Radeon R9 200 / HD 7900 Series / aticfx32.dll[22.19.157.3]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     24503MB 956KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Lautsprecher (Realtek High Definition Audio))

**Comment by Jowy12** [comment]
Please download the Dev Version of WolfHUD from this site. Click Clone/Download.

**Comment by mcproprot** [comment]
Mon May 01 02:21:52 2017


Application has crashed: C++ exception
mods/WolfHUD-master/lua/AdvAssault.lua:208: attempt to index local 'timer_msg' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   


-------------------------------

Current thread: Main

**Comment by Jowy12** [comment]
Make sure you are using the Dev Version of WolfHUD. I've been using it without crash issues. Just click Clone/Download from this site.

**Comment by mcproprot** [comment]
this bug report is from the dev version

**Comment by mcproprot** [comment]
i get still the same crash log when i start a new heist    btw you´re german?

**Comment by FlamingFox911** [comment]
Are you using any other mods? I have not encountered this error before.
Also, perhaps something in the settings under Advanced Assault is triggering this?
