### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by Viilipurkki** [Kamikaze94/WolfHUD#254]
Setting changed from the ingame WolfHUD mod options menu are reset after a loading screen. This issue has appeared for me using both the stable realease from paydaymods and the newest master pulled from the repository.

**Comment by Viilipurkki** [comment]
I decided to run a test and found out that the settings are saved as long as you are running steam as an Administrator.

**Comment by Kamikaze94** [comment]
I guess Payday is installed in "C:\Program Files\" for you then?
It's less my intention and more of Microsofts decision to restrict write access in that folder to processes with admin privileges.
Not really anything I could change about that. 
You could try changing write permissions of the BLT  saves folder to Everyone, if you don't want to run the game with admin privileges all the time :)

**Comment by Viilipurkki** [comment]
My entire Steam is split between 2 drives with designations D:\ and M:\ and the strange part was that giving permissions didn't seem to work. Steam seemed to reset everything to read only whenever I tried to make then read/write. I'll try some things and see if it will work or not. The current work around with running Steam as admin is working and isn't causing any trouble so far.

**Comment by BangL** [comment]
I had similar issues on my steamlibrary on D:   the reason was a parent
folder that didnt have full write perms. So maybe check each and every
parent folder as well.

Am 05.05.2017 00:23 schrieb "Leevi Virtanen" <notifications@github.com>:

**Comment by Viilipurkki** [comment]
Well, the problem was on my end. UAC and Registry settings for Steam were messed up. Reinstalling the client fixed everything.
