### ISSUE TITLE
(General help - not a bug) Updating, and a missing icon

### ISSUE THREAD

**Issue by bepri** [Kamikaze94/WolfHUD#255]
How can I easily update this HUD? If I do a clear re-install it loses my settings.

Also, last time I re-installed and lost my settings (a couple weeks before the crime spree update tbh) the counter in the top-right for cameras stopped working. It's definitely turned on, but it just... doesn't show up. I used that way more than I realized. Any way to get that back?

**Comment by Jowy12** [comment]
Kami made a huge tweak at a point where you should resetting the options. Everything is working just fine now, you just need to download the Dev Version of WolfHUD from this site. Just click Clone/Download. The counter you mentioned is under HudList option > Right hudlist.

**Comment by Kamikaze94** [comment]
Yeah, I reworked the settings table some time ago, which required dropping the previous settings.

The camera counter was broken on alder heists as host and everywhere for clients some commits ago.
(Older heists have some weid camera handling sometimes, like Ukrainian job never sets the cams enabled, only active/inactive, depending on the operating guards position. The cam loop interaction on that heist also never gets enabled again, after the guard once left the console.)
As a client, it will still show unbroken inaktive cameras, as I havn't found a way to tell which guard operates the cameras as client (This stuff gats only registered for the host, as he is the only one handling detection anyways...)
Oh, and as @Jowy12 said, there is a setting for that one, but it should be enabled by default, unless you changed it :)
