### ISSUE TITLE
Crash on lobby

### ISSUE THREAD

**Issue by Autistidore** [Kamikaze94/WolfHUD#256]
I am using the most recent version available from github. When I either start a lobby or return to a lobby from a game I joined midway it crashes. On a whim I removed the EnhancedCrewLoadout.lua which fixed it but...ya know, no enhanced crew loadout now.

**Comment by BangL** [comment]
crash log?

**Comment by Autistidore** [comment]
Felt like I forgot something, sorry


Tue May 02 15:07:07 2017


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                     steam_api  (???)     SteamAPI_ISteamVideo_IsBroadcasting                 
                     steam_api  (???)     SteamAPI_ISteamVideo_IsBroadcasting                 
                     steam_api  (???)     SteamAPI_ISteamVideo_IsBroadcasting                 
                     steam_api  (???)     SteamAPI_RunCallbacks                               
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                      update()  lib/network/matchmaking/networkmatchmakingsteam.lua:225  
                      update()  lib/network/base/networkmanager.lua:302             
                      update()  lib/setups/menusetup.lua:293                        
                      update()  @mods/base/lua/MenuSetup.lua:6                      
                                core/lib/setups/coresetup.lua:537                   
                            ()  =(tail                                              
                      call):-1  
-------------------------------

System information:
	Application version : 1.68.216
	CPU : Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980 / nvldumd.dll[22.21.13.8189]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16327MB 948KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Corsair (Headset Earphone (2- Corsair VOID RGB Wireless Gaming Headset))

**Comment by Autistidore** [comment]
I saw the files got updated and it's all gucci now.
