### ISSUE TITLE
latest commit crash

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#265]
Seven fixed the first crash with the Sicario perk
mods/WolfHUD-master/lua/GameInfoManager.lua:3048: attempt to index a number value
mods/WolfHUD-master/lua/HUDList.lua:1149: attempt to index global 'data' (a nil value)

**Comment by Kamikaze94** [comment]
Both fixed in commit fbb53602ee553e4d1739c864fc3b615c00f5745a yesterday.

But thanks for the report, almost missed the thread about it on Steam 👍
