### ISSUE TITLE
Crash when i downed

### ISSUE THREAD

**Issue by TheLokestraps** [Kamikaze94/WolfHUD#267]
When the Swan Song skill is over, the game crashes instantly

log: 
Wed May 10 14:31:24 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.69.220
	CPU : Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 620 / nvd3dum.dll[21.21.13.7653]
	Language : @ID4176958b9b2622ce@
	Memory :     4054MB 644KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoces (Realtek High Definition Audio))

i know, my pc is shit

**Comment by FlamingFox911** [comment]
Please refer to #261. This <sub>unfortunately</sub> wasn't the first, nor will it be the last issue related to this.
