### ISSUE TITLE
damage pop up crash

### ISSUE THREAD

**Issue by Link4ever42** [Kamikaze94/WolfHUD#268]
When damage pop up is on hitting a shield with a melee weapon with shock and awe ace crashes the game having damage pop up off this dose not happen not sure if hitting a shield without the skill still makes the crash happen edit:just try it with out skill and pop up on no crash seems to happen with hitting the shield with skill aced

**Comment by BangL** [comment]
#261

**Comment by Kamikaze94** [comment]
Meleed a lot of shileds now, but cannot make it crash.... simply not happening, ^^

maybe your Crashlog of crash.txt should shine some light here...
Please add one, if you can. 😄

**Comment by Link4ever42** [comment]
Wed May 10 17:50:19 2017


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
       _process_popup_damage()  @mods/WolfHUD/lua/DamagePopup.lua:64                
                                @mods/WolfHUD/lua/DamagePopup.lua:8                 
                            ()  =(tail                                              
                      call):-1  _on_damage_received()                               
@mods/Keepers/lua/copdamage.lua:3  damage_melee()                                      
lib/units/enemies/cop/copdamage.lua:1696  _do_melee_damage_original()                         
lib/units/beings/player/states/playerstandard.lua:2734                                                      
@mods/WolfHUD/lua/GameInfoManager.lua:3280  ()                                                  
                        =(tail  call):-1                                            
_update_melee_timers_original()  lib/units/beings/player/states/playerstandard.lua:2840  
        _update_melee_timers()  @mods/WolfHUD/lua/Interaction.lua:131               
       _update_check_actions()  lib/units/beings/player/states/playerstandard.lua:804  
                    original()  lib/units/beings/player/states/playerstandard.lua:404  
                      update()  @mods/base/req/hooks.lua:258                        
                                lib/units/beings/player/playermovement.lua:275      
                            ()  =(tail                                              
                      call):-1  ()                                                  
                        =(tail                                                      
                      call):-1  
looking at it might be from keepers making this happen so that might be whats up
