### ISSUE TITLE
Experiencing game crash any time an ECM Jammer is used. 

### ISSUE THREAD

**Issue by HaylingZar** [Kamikaze94/WolfHUD#27]
The most recent attempt, I tested this by using an ECM jammer on a trustee bank. It has also caused crash on car shop and shadow raid. I have not found a way for the game not to crash when using ECM jammer.

Below is the log from the most recent crash:

> Application has crashed: C++ exception
> mods/WolfHUD/lua/HUDList.lua:3160: attempt to perform arithmetic on field '?' (a boolean value)
> 
> 
> 
> SCRIPT STACK
> 
> 
> 
> -------------------------------
> 
> Callstack:
> 
>          payday2_win32_release  (???)     ???                                                 
>          payday2_win32_release  (???)     ???                                                 
>          payday2_win32_release  (???)     ???                                                 
> 
> 
> -------------------------------
> 
> Current thread: Main
> 
> -------------------------------
> 
> System information:
> 	Application version : 1.54.4
> 	CPU : Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
> 	DirectX : 10.0 
> 	GPU : AMD Radeon (TM) R9 380 Series / aticfx32.dll[8.17.10.1452]
> 	Language : @ID94cca2fdaccfc2cd@
> 	Memory :     48131    0MB
> 	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
> 	Physics : threaded
> 	Renderer : DX9 threaded
> 	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Kamikaze94** [comment]
Yeah, has to do with the changes Overkill made to fix ECM duration sync.
Seven already push an hotfix. I pushed that a few minutes ago as an Update.

**Comment by HaylingZar** [comment]
Thanks a lot!
