### ISSUE TITLE
Crashing after place a sentry gun

### ISSUE THREAD

**Issue by SplaTTo** [Kamikaze94/WolfHUD#271]
After the 1.1 Gb update today, my Payday 2 crashes every time when i place a sentry gun. I updated WolfHUD to the latest version from here.
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/994583/crashlog.txt)
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/994589/crash.txt)

**Comment by Kamikaze94** [comment]
Problem with the base game.
https://steamcommunity.com/games/218620/announcements/detail/1958348777658408651
