### ISSUE TITLE
Crashing after Picking up Ammo with Bulletstorm

### ISSUE THREAD

**Issue by WingsZX** [Kamikaze94/WolfHUD#272]
After update 145.

**Comment by Sflashy** [comment]
ye i got the same problem and here crashlog
`----------------------------------------------------------------------

Fri May 12 19:03:51 2017
Application has crashed: C++ exception
mods/WolfHUD/Core.lua:577: bad argument #2 to 'format' (string expected, got no value)

SCRIPT STACK
-------------------------------
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                           ???  (???)     ???                                                 
-------------------------------

Current thread: Main

-------------------------------
`
