### ISSUE TITLE
Do I dare install Wolfhud again?

### ISSUE THREAD

**Issue by ALE854** [Kamikaze94/WolfHUD#275]
Payday with Wolfhud installed worked perfectly during Spring Break. The problems started after it was over. Couldn't get the game to launch. Now I have formatted my HD:s and reinstalled win 10 again and no mods. My question is, do I dare to install Wolfhud again or would I get the same problems again?

Crashlog:

Sun May 07 16:01:37 2017

Application has crashed: access violation

-------------------------------

Callstack:

payday2_win32_release (???) ??? 
payday2_win32_release (???) ??? 
payday2_win32_release (???) ??? 
payday2_win32_release (???) ??? 
KERNELBASE (???) WaitForSingleObjectEx 
kernel32 (???) WaitForSingleObjectEx 
KERNELBASE (???) ResetEvent 

-------------------------------

Current thread: Renderer

-------------------------------

System information:
Application version : 1.69.220
CPU : AMD FX(tm)-9590 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
DirectX : 10.0 
GPU : Radeon (TM) RX 480 Graphics / aticfx32.dll[22.19.162.4]
Language : @ID94cca2fdaccfc2cd@
Memory : 32664MB 912KB
OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
Physics : threaded
Renderer : DX9 threaded
Sound : Realtek Semiconductor Corp. (Realtek Digital Output(Optical) (Realtek High Definition Audio))

**Comment by ALE854** [comment]
I did. Just Love the hud😄👍

**Comment by FlamingFox911** [comment]
As long as its the dev version. Grab the latest from GitHub (Not the release, the raw files), and you should be good to go.

**Comment by ALE854** [comment]
I installed the same I used before. Not the dev version. I'm not good at understanding this modding so I don't understand what you mean by not using the release but the raw files?

**Comment by Jowy12** [comment]
You can find the Dev Version on this site. Just click Clone/Download.

**Comment by FlamingFox911** [comment]
To follow up Jowy12's [Comment](https://github.com/Kamikaze94/WolfHUD/issues/275#issuecomment-301302320)
![image](https://cloud.githubusercontent.com/assets/11638944/26035744/251bce58-389f-11e7-8eb3-118dfe79af91.png)

**Comment by ALE854** [comment]
Do I have to uninstall the version of Wolfhud I have installed first then?

**Comment by FlamingFox911** [comment]
It's recommended that you do. Simply delete the WolfHud Folder from the "Payday 2/mods" directory, then extract WolfHud to that directory. Personally, I like to extract the files, rename the folder "Wolfhud-master" to "WolfHud", then cut/copy it into the "Payday 2/mods" folder.

**Comment by ALE854** [comment]
Ok thanks. I'll try that.
