### ISSUE TITLE
Crash with Pistol Messiah

### ISSUE THREAD

**Issue by Heaiser** [Kamikaze94/WolfHUD#276]
My game crashes as the pistol messiah cooldown wears off.  Here is the crash log:

----------------------------------------------------------------------

Sat May 13 20:07:20 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.70.234
	CPU : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980 / nvd3dum.dll[21.21.13.7866]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     32711MB 948KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by FlamingFox911** [comment]
This is a duplicate issue, and was fixed in the development version of WolfHud
https://github.com/Kamikaze94/WolfHUD/issues/234#issuecomment-294362219

Please download the latest version of WolfHud [here](https://github.com/Kamikaze94/WolfHUD/archive/master.zip).
https://github.com/Kamikaze94/WolfHUD/issues/275#issuecomment-301322959

**Comment by Heaiser** [comment]
This worked, sorry about not noticing it was previously fixed!  Thank you!
