### ISSUE TITLE
[Possible WolfHud mod related] Crashed while I was trying to join the Crime Spree lobby if the host has WolfHud mod installed

### ISSUE THREAD

**Issue by PJzuza** [Kamikaze94/WolfHUD#279]
Hi. I don't have a WolfHud anymore but I've noticed that while I was trying to join the Crime Spree lobby when the host has the WolfHud installed (Dev version from GitHub and it's the newest one) I'll get crashed all the time and I always get the same crash log like this;

Application has crashed: C++ exception
[string "lib/managers/missionassetsmanager.lua"]:551: attempt to index field '?' (a nil value)

SCRIPT STACK

Callstack:

     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
Current thread: Main

System information:
Application version : 1.70.234
CPU : AMD Phenom(tm) II X2 555 Processor (1 core); SSE; SSE2; SSE3
DirectX : 10.0
GPU : AMD Radeon HD 5500 Series / aticfx32.dll[8.17.10.1404]
Language : @id94cca2fdaccfc2cd@
Memory : 8189MB 248KB
OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
Physics : threaded
Renderer : DX9 threaded
Sound : Microsoft (Speakers (JBL Pebbles))

So maybe this crashed (that's related about the feature Buy All Assets that's in the WolfHud mod) may come from WolfHud mod but I am not sure tho but if so then if it's possible can you add this feature in the option to check/uncheck it?(as optional to use this feature so it can prevent the problem)
PS. I don't have buy all assets mod and I'm using the Hud Mod called HudList.

**Comment by FlamingFox911** [comment]
After some digging around the web, I have confirmed that this is an issue that is related to Buy All Assets and the new Crime Spree update.

https://github.com/SydneyMOD/SydneyHUD/issues/14
http://steamcommunity.com/groups/SydneyMOD/discussions/4/133262738419706698/
https://steamcommunity.com/app/218620/discussions/14/135513549097936864/
https://steamcommunity.com/app/218620/discussions/8/1327844097125151914/

Although, judging from the time stamps and lack of additional feedback, it should be fixed, unless a recent update broke it again.

**Comment by katabamia** [comment]
The bug in SydneyHUD resolved by [SydneyHUD/commit/331e731](https://github.com/SydneyMOD/SydneyHUD/commit/331e731fe6bef301af2dcf3ccb90b2c70598a9aa)

Sorry for tagged issue to WolfHUD. Anybody please close this.
