### ISSUE TITLE
Crash on pressing TAB

### ISSUE THREAD

**Issue by Predii** [Kamikaze94/WolfHUD#281]
Downloaded the latest version and ran into a crashing issue whenever I pressed tab during a heist.
Played around with mod settings and determined it was the 'Crew Loadout Options/Show on Tabscreen' option that causes the crash.

Tried several loadouts to see if it was something I had equipped, but it appears to crash with anything if you have that option enabled.

**Comment by Kamikaze94** [comment]
Just tested that one, seems to be alright for me...  :)
Could you please upload your crashlog?
It can normally be found in "%localappdata%/Payday 2/crash.txt" (if it was your latest crash....)

**Comment by t40am** [comment]
I had the same issue some time ago. Just disable tab stats it wolfhud settings, that should help atleast.

**Comment by Swordsage** [comment]
I hate to say it, but I'm having the same problem. Disabling the tab stats hasn't helped, either. I've enclosed the crash.txt  for your examination.

[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/1424896/crash.txt)

**Comment by Thegryphonhunter** [comment]
Same here it is becouse of the achievement tracking! It is an awesome hud tho
