### ISSUE TITLE
Crash after the recent update

### ISSUE THREAD

**Issue by t40am** [Kamikaze94/WolfHUD#285]
The game crashes if you accept a player's request mid-game to join while in you are in Swan Song. 

crash.txt
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
         add_mugshot_by_unit()  lib/managers/hudmanager.lua:965                     
                    set_unit()  lib/managers/criminalsmanager.lua:359               
                                lib/managers/criminalsmanager.lua:900               
                            ()  =(tail                                              
                      call):-1  call_next_update_functions()                        
      lib/setups/setup.lua:183                                                      
      lib/setups/setup.lua:698  ()                                                  
                        =(tail  call):-1                                            
                                lib/setups/gamesetup.lua:643                        
                            ()  =(tail                                              
                      call):-1  update()                                            
lib/setups/networkgamesetup.lua:21                                                      
core/lib/setups/coresetup.lua:537  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

**Comment by putovoador** [comment]
got the same today but i wasn't on swan song, i was just killing some swat units
fucked up my 7 bags rats :/


Sat May 20 18:53:22 2017


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
         add_mugshot_by_unit()  lib/managers/hudmanager.lua:965                     
                    set_unit()  lib/managers/criminalsmanager.lua:359               
                                lib/managers/criminalsmanager.lua:900               
                            ()  =(tail                                              
                      call):-1  call_next_update_functions()                        
      lib/setups/setup.lua:183                                                      
      lib/setups/setup.lua:698  ()                                                  
                        =(tail  call):-1                                            
                                lib/setups/gamesetup.lua:643                        
                            ()  =(tail                                              
                      call):-1  update()                                            
lib/setups/networkgamesetup.lua:21                                                      
core/lib/setups/coresetup.lua:537  ()                                                  
                        =(tail  call):-1

**Comment by t40am** [comment]
I played some time after reporting this and yes it does appear to crash even without going into swan song and accepting a request.

**Comment by putovoador** [comment]
gonna disable the hud for now

**Comment by t40am** [comment]
Okay so now it's crashing every once in a while when a player joins xD

**Comment by FlamingFox911** [comment]
+1 on player join crash.

**Comment by putovoador** [comment]
I'm using:
Accumulator Perk Deck
Adaptative Resync
Announcer
Bain Can't Cook For Shit
Carry Stacker Reloaded
Delayed Calls Fix
Drag and Drop Invetory
Fast.net
Goonmod's Custom Waypoints
Iter
Keepers
Newbies Go Back To Overkill
Scrollable menus
Smoking Barrels
VELOSync
and Wolfhud
I don't think any of these mods caused that bug, but maybe i'm wrong.
I'm gonna keep using the hud and report future crashes.

**Comment by t40am** [comment]
Well I'm using these mods:
Adaptative Resync
VELOSync
Delayed Calls Fix
NGBTO
Custom FOV
and finally Wolfhud.
I don't think any of these mods causes the constant crashing whenever someone joins. I had to revert back to an older version of Wolfhud because of how annoying it is and believe it or not, it never crashes (the older version I mean the one that was released after the Sicario update).

**Comment by Ongjming** [comment]
Thu May 25 22:46:10 2017


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

For me it crashed when the game is not open yet and then accepting a request from friend to join.

**Comment by putovoador** [comment]
That crash I initially had never happened again. I think overkill maybe fucked up some things with the Henchmen Update.

**Comment by viytalic** [comment]
@putovoador I'm getting this as of June. Anyone else fixed it?
