### ISSUE TITLE
[Bug] Teammate Down Counters

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#288]
So your own down counter appears to work fine, but teammate down counters are empty until someone gets downed. After being downed it goes to 4, then 5 and so on I think, I'm not sure. One person I played with was at 5 then used a medic bag and it went to 3 even though he had Nine Lives Aced.

Here's an example. Was playing with my friend "Neck Snapper". He didn't have Nine Lives Aced but after being downed once his down counter went from blank to 4.
https://steamuserimages-a.akamaihd.net/ugc/787413668522653787/B1A43C19793B441647201D0C1133D9849C94DE8B/

**Comment by Lyon-CZ** [comment]
Yes, down counter for teammates is broken, looks like its not reseting correctly.

**Comment by t40am** [comment]
Can confirm it's the same for me.

**Comment by NerdVenom** [comment]
Looks like this has been fixed in the latest commit. I'll have to test it out and see.
