### ISSUE TITLE
tabstats crash

### ISSUE THREAD

**Issue by viashinobogofinado** [Kamikaze94/WolfHUD#29]
wolfhud is crashing sometimes on tabstats
last crash was on 'santas workshop' map, after 20-30 mins.

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:438: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.54.5
	CPU : AMD A6-3670 APU with Radeon(tm) HD Graphics (2 cores); SSE; SSE2; SSE3
	DirectX : 10.0 
	GPU : AMD Radeon R7 200 Series / aticfx32.dll[8.17.10.1452]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     416107    0MB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VIA Technologies, Inc. (Speakers (VIA High Definition Audio))

**Comment by Kamikaze94** [comment]
Okay, as the line mentioned in your crashlog calls a number of functions, I cannot directly say what the problem was here.
I changed the calculations now to be in a few more lines, each one having a default value, if the function returns nothing. This should fix your problem, unless another mod is doing weird things to the initalization, which would cause the panels not to exist, and tehrefore crashing you when you press tab the first time. (I guess that was not the case, as you said you crashed after 20-30 mins...?)

**Comment by viashinobogofinado** [comment]
i replaced the code of tabstats.lua and got crashed again.
i pressed tab lots of times during the game, this time the crash was when i pressed tab at the same time the bags was going down the chimmey. (6-7min)

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:444: attempt to index a nil value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.54.8
	CPU : AMD A6-3670 APU with Radeon(tm) HD Graphics (2 cores); SSE; SSE2; SSE3
	DirectX : 10.0 
	GPU : AMD Radeon R7 200 Series / aticfx32.dll[8.17.10.1395]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     416107    0MB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VIA Technologies, Inc. (Speakers (VIA High Definition Audio))

**Comment by Kamikaze94** [comment]
Hey, 
I added another check, if the day_wrapper_panel exists some time ago (not sure if you noticed, should probably have said something here...  :/)
As I'm still clueless how your crash is happening, I cannot test if its solved with that.

**Comment by viashinobogofinado** [comment]
i couldn't replicate the crash anymore, and im not sure if it was because i updated the files or because i changes some configs on this mod and in the lobbyplayerinfo, the tab-related ones.
i can't remember exactly with options was active or inactive during the crashes.
if someone else have random crashes when using the tab, can be usefull to know exactly with options are active or inactive in the tabstats part, during the last report i was able to replicate the problem pressing tab lots and lots of times during the santas workshop heist with relative ease.

**Comment by Kamikaze94** [comment]
Okay, as it doesn't seem to appear anymore, I'll close this now.
