### ISSUE TITLE
Cannot place shaped charge in stealth

### ISSUE THREAD

**Issue by Lyon-CZ** [Kamikaze94/WolfHUD#291]
Title. Its impossible to place shaped charge, when in stealth. After "placing animation" nothing happens. Definitely caused by wolfhud, after disabling its working again.

Pretty annoying in for example crime spree FBI server heist, when you need to place C4 on doors.

**Comment by Kamikaze94** [comment]
Was a feature @BangL added in PR #213.
You need to double tab the key, for it to work in stealth.
This behaviour can be disabled in the options. (Mod Options -> WolfHUD Settings -> Inventory Tweak)

**Comment by Lyon-CZ** [comment]
I know i have to double tap it. Once more - animation of planting C4 starts, finishes and then nothing, shaped charge is not planted. Tested many times.

**Comment by BangL** [comment]
so one of the last updates broke it.
im gonna look into it..

**Comment by Lyon-CZ** [comment]
Comment added to #292.
