### ISSUE TITLE
Crashed upon Swan Song and Sentry being placed

### ISSUE THREAD

**Issue by Towyd** [Kamikaze94/WolfHUD#293]
Yes I know, this has been posted before but still...
As said the game crashed upon swan song ending:

Mon May 29 02:08:51 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

and placing a sentry gun:

Mon May 29 02:06:36 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/EquipmentTweaks.lua:26: attempt to call method '_switch_fire_mode' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

I already tried removing every other mod and such things but only seems to happen when I have WolfHUD in the game. Also tried SydneyHUD just to compare- it crashed only upon a sentry gun being placed but not on ssong ending. And yes, I did already de- and reinstal my game completely as instructed by Overkill_Tobias in Payday 2-Steamgroup/discussions. Still does not seem to help..  Hope you can find a fix or have some advice for me because I really like this mod.
Thanks :D

**Comment by johnneijzen** [comment]
Please download the Dev Version of WolfHUD. You can grab it from this site, just click Clone/Download and remove old wolfHUD and place this version of wolfHUD

This known Issues on non-dev version of WolfHUD #280  and #261 and #267
