### ISSUE TITLE
Shooting through bots doesn't seem to work

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#295]
WolfHUD used to allow me to shoot through bots and Jokered cops, but I can't seem to do that recently, I think since the Bot update but potentially since before. I looked for an option to toggle that, thinking I might have disabled it accidentally, but I couldn't find one.

**Comment by BangL** [comment]
Not a bug and also not your fault. That feature got removed on purpose a view weeks ago:
https://github.com/Kamikaze94/WolfHUD/commit/427022c788df082f60ccb6d510909c69e0271e68

**Comment by Malidictus** [comment]
Well, that's rather disappointing. That was one of the main reasons I like WolfHUD in the first place... I'll grab the standalone, then, thank you. Although... There's a note of it only working if the crew's using their default masks, and no mention of it working on team AI...

**Comment by OfficialEsco** [comment]
BangL on that change note it says "enabled force ready on friends at any time", is that support for Force Ready or is it in WolfHUD? If so, how do i do it?

**Comment by BangL** [comment]
by double-clicking "ready" as host
