### ISSUE TITLE
C++ exception attempt to index a number value related crashes

### ISSUE THREAD

**Issue by Ongjming** [Kamikaze94/WolfHUD#298]
I think I will close the arrowlua one since it doesn't crash giving that anymore after this new game update.

Here's the 3 crash logs:

Sat Jun 10 02:22:00 2017

Application has crashed: C++ exception
attempt to index a number value

SCRIPT STACK
-------------------------------
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

Sun Jun 11 02:21:09 2017

Application has crashed: C++ exception
attempt to index a number value

SCRIPT STACK
-------------------------------
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                           ???  (???)     ??? 

Mon Jun 12 01:21:39 2017

Application has crashed: C++ exception
attempt to index a number value

SCRIPT STACK
-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlRunOnceBeginInitialize                           
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlAllocateHeap                                     
                           ???  (???)     ???

**Comment by Kahoy** [comment]
Got the same crash twice yesterday.
Log if it helps

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.71.251
	CPU : Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 670 / nvldumd.dll[22.21.13.8205]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16346MB 96KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VIA Technologies, Inc. (Lautsprecher (VIA HD Audio))

**Comment by Ongjming** [comment]
Another 2:
Mon Jun 12 02:03:17 2017

Application has crashed: C++ exception
[string "core/lib/managers/coreportalmanager.lua"]:597: attempt to index a number value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlFreeHeap

Tue Jun 13 03:41:28 2017

Application has crashed: C++ exception
attempt to index a number value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlRunOnceBeginInitialize                           
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlFreeHeap

**Comment by viytalic** [comment]
I too have had the ones above but am getting this one below on Swan song.

Mon Jun 12 22:55:14 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.256
	CPU : AMD Athlon(tm) X4 860K Quad Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon R9 200 Series / aticfx32.dll[22.19.165.512]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8135MB 52KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (USB Audio Device))

**Comment by Bloodwake393** [comment]
Contributing to the post. Crashing constantly as well myself. Here are my logs.

Mon Jun 12 15:22:33 2017


Application has crashed: C++ exception
attempt to index a number value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.256
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8189]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16340MB 828KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster ZxR))



----------------------------------------------------------------------

Mon Jun 12 15:37:24 2017


Application has crashed: C++ exception
attempt to index a number value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.256
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8189]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16340MB 828KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster ZxR))



----------------------------------------------------------------------

Mon Jun 12 15:41:03 2017


Application has crashed: C++ exception
attempt to index a number value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.256
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8189]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16340MB 828KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster ZxR))



----------------------------------------------------------------------

Mon Jun 12 15:42:31 2017


Application has crashed: C++ exception
attempt to index a number value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.256
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8189]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16340MB 828KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster ZxR))



----------------------------------------------------------------------

Mon Jun 12 15:45:58 2017


Application has crashed: C++ exception
attempt to index a number value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.256
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8189]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16340MB 828KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster ZxR))



----------------------------------------------------------------------

Mon Jun 12 15:49:58 2017


Application has crashed: C++ exception
attempt to index a number value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.256
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[22.21.13.8189]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16340MB 828KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster ZxR))

**Comment by OfficialEsco** [comment]
Can all of you reinstall BLT + Mod (Clean install)? I think blt have broken after a few updates

**Comment by Ongjming** [comment]
Hi OfficialEsco,
Is it this link for the latest downloadable BLT? : https://github.com/JamesWilko/Payday-2-BLT-Lua
Then after activating in game it should be updated to R15 right?

**Comment by OfficialEsco** [comment]
I've just downloaded BLT from Paydaymods, but that seems to be the same version yeah

I already had to reinstall after the update today so the mods break very easily sometimes...

**Comment by viytalic** [comment]
@OfficialEsco @Ongjming  Mine says version 1 when i got LUA mods and hover over BLT, how are you seeing R15?

**Comment by VandenPlause** [comment]
Try going to https://github.com/JamesWilko/Payday-2-BLT/releases/tag/1.08

There is a download link for 1.08 (BLT_r15_r5.zip) which was released May 2 2017.

**Comment by Ongjming** [comment]
I didn't crash much this few days, today it crashed again.

Wed Jun 28 21:45:07 2017

Application has crashed: C++ exception
attempt to index a number value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlFreeHeap
