### ISSUE TITLE
Swan song crash on Dev version + new crash log.

### ISSUE THREAD

**Issue by viytalic** [Kamikaze94/WolfHUD#299]
# I have the Dev version but it is currently crashing on swan song.  Below this one is another new crash that i have been getting randomly as well.

Mon Jun 12 22:55:14 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

## **The second crash that i get randomly**

Mon Jun 12 22:46:46 2017

Application has crashed: C++ exception
attempt to index a number value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

**Comment by OfficialEsco** [comment]
I've seen the "attempt to index a number value" ALOT lately, so i reinstalled my BLT + Mods, no crash, do the same see if you still crash =)
