### ISSUE TITLE
Game crashes at random moment

### ISSUE THREAD

**Issue by silfi0** [Kamikaze94/WolfHUD#304]
Hello, game crashes at random moment at the begining of heist, when i join other games or when i press restart heist button. Almost unreal to play after last update, games crashes like every 15-20 minutes.
Here the last two crashes from crashlog

Sat Jun 17 10:49:54 2017
Application has crashed: C++ exception
[string "core/lib/managers/coreportalmanager.lua"]:597: attempt to index a number value
SCRIPT STACK
-------------------------------
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
-------------------------------
Current thread: Main
-------------------------------
System information:
	Application version : 1.72.257
	CPU : Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 770 / nvd3dum.dll[22.21.13.8189]
	Language : @ID69065f31945c7d82@
	Memory :     12252MB 888KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Динамики (Realtek High Definition Audio))
----------------------------------------------------------------------

Sat Jun 17 10:58:03 2017
Application has crashed: C++ exception
attempt to index a number value

SCRIPT STACK
-------------------------------
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Current thread: Main
-------------------------------
System information:
	Application version : 1.72.257
	CPU : Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 770 / nvd3dum.dll[22.21.13.8189]
	Language : @ID69065f31945c7d82@
	Memory :     12252MB 888KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Динамики (Realtek High Definition Audio))

**Comment by HamishWHC** [comment]
How can you tell it is WolfHUD causing the problem. I have the same problem.

**Comment by Ongjming** [comment]
Wed Jun 21 23:26:00 2017

Application has crashed: C++ exception
[string "core/lib/managers/coreportalmanager.lua"]:597: attempt to index a number value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlFreeHeap 

Just happened to me as well, the exact circumstance is that my window low batt warning popped up exiting me from game's full screen (game got minimized into task bar), then clicked back in game, it ran for a bit then froze and crashed giving this.

At that time I recently just toggled on the pingchecker thing (the one in wolfhud but not under customhud).
