### ISSUE TITLE
Crash after Swan Song runs out.

### ISSUE THREAD

**Issue by WarpAngel** [Kamikaze94/WolfHUD#306]
I was in the middle of the goat simulator heist, when my swan song triggered and after it ran out I crashed.
Sun Jun 18 15:53:23 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???

**Comment by CyberGhost2** [comment]
Had the same problem, ended up reinstalling BLT and WolfHud, that fixed it.

**Comment by SirNick11** [comment]
Still crashes after reinstalling :(
