### ISSUE TITLE
Can't host any games without crashing

### ISSUE THREAD

**Issue by 09ymmit07** [Kamikaze94/WolfHUD#307]
Whenever I start a game my game blackscreens and shuts down. Joining other people raises no issues.

**Comment by 09ymmit07** [comment]
Now the game doesn't boot anymore at all.

**Comment by 09ymmit07** [comment]
Here are the crashlogs. I have an RX480 8GB, 8GB of RAM and an i7-3770

**Comment by Ongjming** [comment]
I am not an expert, just a noob, however I saw the same thing happened to my friend earlier, he ended up verifying the game files, fixed a few corrupted files and everything is ok again. Just saying.

**Comment by Manipulator1312** [comment]
Try updating all your drivers and verify your game files. Good luck.
