### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by ZataraTMM** [Kamikaze94/WolfHUD#308]
It keeps telling me there is a new Wolf textures and Federal Inventory update, when i try to download them, my whole game gets stuck on 0kb/0kb and i have to alt f4.

**Comment by BangL** [comment]
thats nothing we could fix. the blt servers are overloaded due to so many new players.

**Comment by BangL** [comment]
https://cloud.bangl.de/index.php/s/ChphO9kMVjq2G1f
