### ISSUE TITLE
Crash after placing a turret with Auto AP enabled.

### ISSUE THREAD

**Issue by NevanNedall** [Kamikaze94/WolfHUD#309]
I'm getting a full game crash with no error pop up whenever I place a turret, whether I'm host or not, while only using WolfHud. I'm not currently using the beta. This only occurs when Auto AP is enabled using WolfHud

**Comment by BangL** [comment]
crashlog?

**Comment by NevanNedall** [comment]
I'm unsure of how to find it. I found -a- log but it didn't seem to hold any information about the crash.

**Comment by BangL** [comment]
"%localappdata%\PAYDAY 2\crash.txt"  is the latest crash.
"%localappdata%\PAYDAY 2\crashlog.txt"  is the full history of all crashes you ever had.

**Comment by NevanNedall** [comment]
----------------------------------------------------------------------

Tue Jun 20 12:17:32 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/EquipmentTweaks.lua:26: attempt to call method '_switch_fire_mode' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.257
	CPU : Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[22.21.13.8233]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16323MB 128KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Speakers (4- Logitech G933 Gaming Headset))



----------------------------------------------------------------------

Tue Jun 20 12:24:20 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/EquipmentTweaks.lua:26: attempt to call method '_switch_fire_mode' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.257
	CPU : Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[22.21.13.8233]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16323MB 128KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Speakers (4- Logitech G933 Gaming Headset))



----------------------------------------------------------------------

**Comment by BangL** [comment]
ah so i guess youre not using the latest dev-version?
#261

**Comment by NevanNedall** [comment]
I am not, now. Woops. Is there any way to opt into dev version updates or do I have to isntall them manually?

**Comment by BangL** [comment]
Manually until kamikaze pushes updates to blt again. (Dont ask me why he
doesnt) that term is already discussed in the issue i linked though.

On 22 Jun 2017 16:07, "NevanNedall" <notifications@github.com> wrote:

I am not, now. Woops. Is there any way to opt into dev version updates or
do I have to isntall them manually?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Kamikaze94/WolfHUD/issues/309#issuecomment-310390829>,
or mute the thread
