### ISSUE TITLE
Crashing game when joining friends through Steam

### ISSUE THREAD

**Issue by Manipulator1312** [Kamikaze94/WolfHUD#311]
I have just experienced this after the update for Federal Inventory and WolfHUD Textures popped up. I tried to update but it said 0kB/0kB for a while so I tried alt+f4. After restarting Payday 2 Mod menu said all mods are updated and my game started crashing when I tried joining games through Steam.
Sadly I don't have any crash reports cause I  am currently reinstalling Payday 2 after trying to manually remove mods 1 by 1 to try to find the problem(nothing seemed to fix the crashes).
You should try to look into this, but I'll reinstall WolfHUD after reinstalling Payday 2 and if the problem comes up again i'll get those logs.

Haven't tried reinstalling BLT, I see other issues have been fixed by reinstalling all the mods and the BLT.****

**Comment by Manipulator1312** [comment]
Haven't tried reinstalling BLT, I see other issues might be fixed by reinstalling all the mods and the BLT.

**Comment by SaintHF** [comment]
This is something that happened to me with another mod. All you gotta do is go into the manual update manager and force updates for everything that you cancelled via alt+F4. That should fix it.
