### ISSUE TITLE
Immediately crashing after placing down a turret which was equipped in secondary slot

### ISSUE THREAD

**Issue by HetNeSS** [Kamikaze94/WolfHUD#314]
Yup. Right as you guessed it. 04:42:01 AM Lua: Found a json error, attempting to use old json loader! Only your mod is installed. Already texted it out to the [issues list of payday 2 blt](https://github.com/JamesWilko/Payday-2-BLT/issues/71), they've told it's something about a custom json thing and it should be reverted to the original one.

[2017_06_25_log.txt](https://github.com/Kamikaze94/WolfHUD/files/1100055/2017_06_25_log.txt)

**Comment by HetNeSS** [comment]
Being fixed by disabling "AP rounds turret autoselection" in "settings > mod options >wolfhud settings > equipment tweaks"

**Comment by BangL** [comment]
Youre not using the latest version. Get the dev version from here.

**Comment by Orgjas05** [comment]
The crash is because there is an OPTION inside the mod that says "Auto AP" and it makes the game crash. Instead just turn off the auto AP and it's solved.

**Comment by BangL** [comment]
Again: youre not using the latest dev version. It is working well in the latest dev version.
And i will now unsubscribe from the whole issue tracker, i cant handle seeing the same bs every morning any longer

**Comment by BangL** [comment]
#261
