### ISSUE TITLE
Pager count won't work

### ISSUE THREAD

**Issue by Squipplepuff** [Kamikaze94/WolfHUD#315]

**Comment by papydeath95** [comment]
* Are you using the Dev/GitHub version?
* Is in every map on just one?
* Did you try to reinstall WolfHUD?

**Comment by Squipplepuff** [comment]
I am on github it's on every map but I have not tried to reinstall wolfhud

**Comment by Squipplepuff** [comment]
Actually sorry correction I'm on dev

**Comment by Squipplepuff** [comment]
re downloading it did nothing
