### ISSUE TITLE
Crash on game leave

### ISSUE THREAD

**Issue by Mazawrath** [Kamikaze94/WolfHUD#323]
Sometimes after leaving a game, I get a game crash, outputting this error on crashlog.txt

```
Application has crashed: C++ exception
[string "lib/units/equipment/ecm_jammer/ecmjammerbas..."]:130: attempt to index a nil value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.72.257
	CPU : Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[22.21.13.8205]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16342MB 744KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (VS248-4 (NVIDIA High Definition Audio))
```

**Comment by Skimown** [comment]
I have the same issue, and this is on the latest update of both BLT and WolfHud.

`Sun Jul 09 15:39:03 2017


Application has crashed: C++ exception
[string "lib/units/equipment/ecm_jammer/ecmjammerbas..."]:130: attempt to index a nil value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     SbSelectProcedure                                   
                         ntdll  (???)     RtlGetCurrentServiceSessionId                       


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.275.
	CPU : AMD FX(tm)-8350 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : Radeon RX 580 Series / aticfx32.dll[22.19.171.257]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8091MB 516KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Headphones (Realtek High Definition Audio))



`

**Comment by chromKa** [comment]
[string "lib/units/equipment/ecm_jammer/ecmjammerbas..."]:130: attempt to index a nil value
