### ISSUE TITLE
Game crashes after few minutes of playing 

### ISSUE THREAD

**Issue by Bobbi225** [Kamikaze94/WolfHUD#324]
Thu Jun 29 21:03:50 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.73.269
	CPU : Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD Radeon HD 8570 / aticfx32.dll[21.19.164.1]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8132MB 852KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Sluchátko u sluchátek s mikrofonem (HyperX 7.1 Audio))

Can anyone help me ???

**Comment by KajTorvaldGrey** [comment]
Hey @Bobbi225 

Do you get this message every time you start the game or does it appear randomly? 

Is it the first time you're using WolfHUD or have you used it before and did it work then?

Also are you using other mods at the same time as WolfHud?

Thanks!

**Comment by Bobbi225** [comment]
i get this meessage every time it crashes. It is second time it's happening. I am using Better bots, carry stacker and Wolfhud
