### ISSUE TITLE
crash when I convert enemy

### ISSUE THREAD

**Issue by mcproprot** [Kamikaze94/WolfHUD#326]
mods/WolfHUD/lua/CustomWaypoints.lua:606: attempt to index local 'name_table' (a nil value)

**Comment by HugoZink** [comment]
Same problem. The crash seems to happen when converting the new Zeal sniper in crime sprees.

`Application has crashed: C++ exception
mods/WolfHUD/lua/CustomWaypoints.lua:606: attempt to index local 'name_table' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.73.269
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[21.21.13.7653]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8174MB 644KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

`

**Comment by Myszax** [comment]
I have the same problem. New Zeal SWAT with sniper from new crime spree update.
Got crashed and my crime spree broke... :/

**Comment by khoopa** [comment]
A shame this happens since I want to use it as a convert.

**Comment by MEXAHOTABOP** [comment]
you tried git version after https://github.com/Kamikaze94/WolfHUD/commit/48bc6936dce23150118de5e9329208f780aa5c0f?

**Comment by mcproprot** [comment]
its working again thx
