### ISSUE TITLE
Conflict with Oh Shit! More Profiles! mod

### ISSUE THREAD

**Issue by Data-Zero** [Kamikaze94/WolfHUD#327]
The github version crashes when Oh Shit! More Profiles is installed.

Modifying value in multiprofilemanager.lua line to be larger than 15 causes problems:

	local wanted_amount = (VALUE) --Changes Amount of profile sets.(Default: 5)

Crash log is as follows:

Crash date: 1.07.2017 21:24:47

PAYDAY 2 Crash log
Application has crashed: C++ exception
mods/WolfHUD/lua/ProfileMenu.lua:345: attempt to index field '_profile_menu_btn' (a nil value)
SCRIPT STACK
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
-------------------------------

**Comment by NerdVenom** [comment]
Stop using that old mod, and start using "Custom Profile Sets"
http://modwork.shop/18071
