### ISSUE TITLE
crash leaving heist as client in stealth

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#33]
Not sure about this crash
Application has crashed: C++ exception
mods/WolfHUD dev/lua/EquipmentTweaks.lua:61: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlQueryPerformanceCounter                          

-------------------------------

Current thread: Main

-------------------------------

**Comment by Kamikaze94** [comment]
Hmm, strange....
Probably something with the Network session Manager.
By leaving, you mean completing or disconnecting?
Also, while an ECM or Feedback is active?

**Comment by Hulkfog** [comment]
Quitting the heist, not sure if an ecm was active

**Comment by Kamikaze94** [comment]
Okay, removed the check, if its your ECM in the destroy now, as unregistereing an listener that never got setup does nothing wrong. 
This should fix the problems, where thenetwork session gets destroyed too quickly.
Thanks for the report, and sorry that it took so long  :P
