### ISSUE TITLE
crashing on converted zeal cop?

### ISSUE THREAD

**Issue by Sylthaya** [Kamikaze94/WolfHUD#334]
crash when ever a zeal cop is converted, how to fix it?

**Comment by MEXAHOTABOP** [comment]
you tried git version after https://github.com/Kamikaze94/WolfHUD/commit/48bc6936dce23150118de5e9329208f780aa5c0f ?

what game write in logs? https://github.com/Kamikaze94/WolfHUD#bug-reports

**Comment by Sylthaya** [comment]
i dont believe so i will download that and update
