### ISSUE TITLE
Crashed when tried to convert a special enemy in Crime Spree

### ISSUE THREAD

**Issue by HerrEdwyn** [Kamikaze94/WolfHUD#335]
I tried to convert a special unit (the one with the sniper rifle, which is one of the modifiers). My game stopped for a few seconds and then crashed. Here is my log for the last hour:

> 06:13:06 PM Log: Initiating Hook
06:13:06 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
06:13:06 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:13:06 PM Lua: [Mods] Loading mods for state (table: 52A83100)
06:13:06 PM Lua: [Mods] Loading mod: base...
06:13:06 PM Lua: [Mods] Loading mod: VELOSync...
06:13:06 PM Lua: [Mods] Loading mod: WolfHUD...
06:13:07 PM Log: Initiating Hook
06:13:07 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
06:13:07 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:13:07 PM Lua: [Mods] Loading mods for state (table: 67110E20)
06:13:07 PM Lua: [Mods] Loading mod: base...
06:13:07 PM Lua: [Mods] Loading mod: VELOSync...
06:13:07 PM Lua: [Mods] Loading mod: WolfHUD...
06:13:07 PM Log: Initiating Hook
06:13:07 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
06:13:07 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:13:07 PM Lua: [Mods] Loading mods for state (table: 2B0A2000)
06:13:07 PM Lua: [Mods] Loading mod: base...
06:13:07 PM Lua: [Mods] Loading mod: VELOSync...
06:13:07 PM Lua: [Mods] Loading mod: WolfHUD...
06:13:31 PM Lua: Jukebox deselected
06:15:10 PM Lua: [1] SYSTEM: HerrEdwyn unlocked asset: Grenade Case.
06:15:10 PM Lua: [1] SYSTEM: HerrEdwyn unlocked asset: Ammo Bag.
06:15:10 PM Lua: [1] SYSTEM: HerrEdwyn unlocked asset: Doctor Bag.
06:23:52 PM Log: CURL CLOSED
06:24:08 PM Log: CURL INITD
06:24:21 PM Log: Initiating Hook
06:24:42 PM Log: Initiating Hook
06:24:42 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
06:24:42 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:24:42 PM Lua: [Mods] Loading mods for state (table: 001C0460)
06:24:42 PM Lua: [Mods] Loading mod: base...
06:24:42 PM Lua: [Mods] Loading mod: VELOSync...
06:24:42 PM Lua: [Mods] Loading mod: WolfHUD...
06:24:42 PM Log: Initiating Hook
06:24:42 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
06:24:42 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:24:42 PM Lua: [Mods] Loading mods for state (table: 001C04A0)
06:24:42 PM Lua: [Mods] Loading mod: base...
06:24:42 PM Lua: [Mods] Loading mod: VELOSync...
06:24:42 PM Lua: [Mods] Loading mod: WolfHUD...
06:24:44 PM Log: Initiating Hook
06:24:44 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
06:24:44 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
06:24:44 PM Lua: [Mods] Loading mods for state (table: 25E73120)
06:24:44 PM Lua: [Mods] Loading mod: base...
06:24:44 PM Lua: [Mods] Loading mod: VELOSync...
06:24:44 PM Lua: [Mods] Loading mod: WolfHUD...
06:27:11 PM Log: Incoming HTTP Request/Request
06:27:11 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=wolfhud&mod[3]=wolfhud_textures&mod[4]=fed_inv
06:27:11 PM Log: 770
06:27:11 PM Log: Launching Async HTTP Thread
06:27:11 PM Lua: [Updates] Attempting to remove temporary hook dll...
06:27:11 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
06:27:20 PM Lua: [Updates] Received update data for 'wolfhud_textures', server revision: 8
06:27:20 PM Lua: [Updates] Received update data for 'fed_inv', server revision: 14
06:27:20 PM Lua: [Updates] Received update data for 'payday2blt', server revision: 15
06:27:20 PM Lua: [Updates] Received update data for 'wolfhud', server revision: 20
06:27:20 PM Lua: [Updates] Received update data for 'payday2bltdll', server revision: 5
06:27:44 PM Lua: [Updates] Attempting to remove temporary hook dll...
06:27:44 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
06:29:10 PM Lua: [Updates] Attempting to remove temporary hook dll...
06:29:10 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
06:47:08 PM Log: CURL CLOSED

>

**Comment by MEXAHOTABOP** [comment]
update mod to https://github.com/Kamikaze94/WolfHUD/commit/48bc6936dce23150118de5e9329208f780aa5c0f

**Comment by HerrEdwyn** [comment]
what??Can you explain what you said pls

**Comment by MEXAHOTABOP** [comment]
https://github.com/Kamikaze94/WolfHUD#installation-direct-download
