### ISSUE TITLE
WolfHud settings keep resetting every heist startup???

### ISSUE THREAD

**Issue by Tenkomanker** [Kamikaze94/WolfHUD#337]
I've been having this issue lately that after restarting my computer and opening Payday 2, all my settings turned to hide and disabled, so I fixed them all and then started a heist, none of my preferences were onscreen, I go check, all back to hide and disabled. So then I change them again, do the map reset, and AGAIN, ALL SETTINGS SET TO HIDE AND DISABLED. Is this a problem on my end or is it something with WolfHud??

**Comment by SC2Mitch** [comment]
I think this is on your end, I'm not having any of the issues you're reporting.

**Comment by Tenkomanker** [comment]
@SC2Mitch Yea I got it solved, it was really annoying though. I just had to uninstall Wolfhud, uninstall Payday, then restart steam, reinstall payday, THEN reinstall Wolfhud. Took a while but it worked.
