### ISSUE TITLE
Crash when pressing tab

### ISSUE THREAD

**Issue by Verlynx** [Kamikaze94/WolfHUD#338]
the crashlog said:

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:409: attempt to call method '_is_active' (a nil value)

**Comment by Jeremy850407** [comment]
me too

**Comment by SC2Mitch** [comment]
This appears to be happening after the most recent update Overkill published, Update 150.

**Comment by Kamikaze94** [comment]
Overkill removed the first underscore in that functions name.
Should be fixed in the latest commit :)

**Comment by glebtus** [comment]
And there is that on 491th line

**Comment by robotboy655** [comment]
Temporary fix for those in need:

Replace the ```managers.crime_spree:_is_active()``` with ```managers.crime_spree and managers.crime_spree._is_active and managers.crime_spree:_is_active()``` on lines 491 and 409.

This is not a proper fix and crime spree difficulty will not be displayed anymore. Wait for BLT / WolfHUD update I guess.

**Comment by robotboy655** [comment]
Actually NVM, it was fixed, redownload the HUD.
