### ISSUE TITLE
Remember Gadget State issue

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#34]
While Payday 2 now has an option to "remember gadget state," that option doesn't work with WolfHud enabled. I tried it with both the version currently on PaydayMods and this one here on GitHub. With the PaydayMods version, I had to force Remember Gadget State in order for the option to work. Disabling it failed to remember gadget state. The GitHub version doesn't have that option, thus my gadget states are not being remembered. Disabling WolfHud via the "Lua Mods" menu allows weapons to remember their gadget state, but re-enabling it breaks the functionality once again.

Is it possible to re-enable the option in the mod temporarily?

**Comment by Kamikaze94** [comment]
Hey, thanks for the report.
Had to readd a variable call, with the "new" saved gadget state.
The bug caused the laser to get always turned on, if the weapon had one, and all gadgets off, if the weapon had no laser.
Changed that in commit 4a97bbdeefba9375280198fabb2f004be793744b, should be fixed.

Oh, and yes, the option is gone, because the code is gone, gadget states are handled by the base game now, not gonna mess with it (unless overkill breaks things, :P )

**Comment by Malidictus** [comment]
Follow-up: Remembering gadget state when swapping weapons now works correctly. However, there are still issues with it. Gadget state is "forgotten" in the following two situations:

1. When entering the Bipod state. Gadget is reset to "off" when that happens. If a gadget is activated while in the Bipod state, it's reset to "off" when leaving it. If "Automatic Laser On" is enabled, the laser is enabled in both cases instead of the gadget being turned off.

2. When exiting a vehicle. Any gadget state from before entering the vehicle is lost, and the gadget is reset to "off" when exiting it. If "Automatic Laser On" is enabled, the laser is enabled when leaving the vehicle.

**Comment by Kamikaze94** [comment]
Uhm, didn't notice your edit until now. (Edits don't trigger a new notification :P)
Yeah, the Overkill implementation only saves the Gadget state, when you unequip you weapon, or it gets disabled for another reason.
I added back the manual save of the state, as it seems easier and better controlable than working with Overkills version and analyzing, where which bug exactily happens.
Tested the vehicle szenario, and got it working there. I'm not sure, if the bipod problem still persists.

**Comment by Malidictus** [comment]
Everything seems to be working correctly now, yes. My gadget retains its state while using the bipod and it now even retains its state when exiting a vehicle, which other mods haven't done. Prior to WolfHud, I used PocoHud and that mod's gadget state saving did break when entering vehicles. Everything I tried works so far, which is good :)

I managed to break WolfHud upon reinstalling (WinRAR put the WolfHud folder inside a WolfHud folder) and I did notice that without the mod, Payday 2 does manage to handle gadget states when going into a bipod correctly, but does not handle gadget states while going into a vehicle correctly. It seems like WolfHud does something to induce the loss of gadget state persistence when using the bipod when gadget state saving is disabled. I don't know if that means anything, but it's worth noting.

I also seem to have lost my "opaque" laser sights in this version. The "self._brush = Draw:brush(self._themes[self._theme_type].brush)" line seems to be gone, and I can't find the custom laser colour Lua file to add it back in myself. I realise this seems off-topic, but persistent lasers are one reason I brought this up, and I can't see the lasers without that option very well :)

**Comment by Kamikaze94** [comment]
Yeah, like you already mentioned on paydaymods, the brush causes some errors, like sniper lasers for dropins, lasers drawing through flashbangs, ...
I'm not sure, how to either fix those problems, give it an option, or just drop it, as I cannot think of a hughe demand for that. And you can always remove the comment in front of the line after an update ( I always try to not push too many... :) or or make it a small 4 lines standalone mod, as it just needs a posthook into the init function and redefine the self._brush field....
Still undecided on which way is the best to go :P

**Comment by Malidictus** [comment]
That's completely understandable. It does cause the issues you mentioned and possibly more. I could see it as an option, but I don't mind manually uncommenting a line in the code, either. Push come to shove, I can always add the line in myself. The hardest part was finding it, since you seem to have merged the custom laser Lua with the rest of the gadgets :)

I also noticed that while the "remember gadget state" functionality is back, the option to toggle it on or off is still missing, meaning it's always on. I presume this is because an option for "off" is no longer applicable with the game having partial support itself?

In either case, I tested this as much as I could and can find no further issues with gadget state remembrance. It even persists across vehicle use, which I've never seen before. This seems fixed.

**Comment by Kamikaze94** [comment]
Yes, I kept the option out, because disabling now would mean, it uses the default beaviour.
Thats would still save the gadget state. So ther wouldn't be much point in having an option for that.

Thanks for confirming, the gadget state remember is working with bipods now.  :)
