### ISSUE TITLE
Profile selector misalignment with Desync Update

### ISSUE THREAD

**Issue by jtmal0723** [Kamikaze94/WolfHUD#343]
The Desync update (update 150) released their own profile selector. However, with the addition of that button, it causes misalignment if WolfHUD's own profile selector button (the spade icon) in both the inventory screen and the heist loadout screen. See attached.
![20170706173518_1](https://user-images.githubusercontent.com/2731183/27934023-cb6969c2-6271-11e7-86bf-b3ddd97a9f95.jpg)
![20170706173545_1](https://user-images.githubusercontent.com/2731183/27934024-cb9aedee-6271-11e7-8464-ccdb5e299d06.jpg)

**Comment by jtmal0723** [comment]
I forgot to check before reporting and this appears to be already reported. However, it is in a "feature request" issue so I guess I'll keep this separate from the feature request. My bad.

**Comment by Tenkomanker** [comment]
@jtmal0723 I'm having this issue too, and as of now I still haven't found a way to disable either of them :/
