### ISSUE TITLE
[string "lib/units/weapons/npcraycastweaponbase.lua"]:144: attempt to perform arithmetic on field 'fire_rate' (a nil value)

### ISSUE THREAD

**Issue by Wibble199** [Kamikaze94/WolfHUD#344]
My friend and I are encountering this issue with the latest update. It usually occurs around 10 minutes or so into a heist. We've not been able to find a reliable way of forcefully reproducing the issue.

```
Application has crashed: C++ exception
[string "lib/units/weapons/npcraycastweaponbase.lua"]:144: attempt to perform arithmetic on field 'fire_rate' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     zip_get_name
                       avcuf32  (???)     AvcGetJumpCode
                         ntdll  (???)     RtlRunOnceBeginInitialize
                         ntdll  (???)     RtlGetCurrentServiceSessionId

-------------------------------
```

We're happy to help diagnose the issue if needed.

**Comment by SC2Mitch** [comment]
Do you have any other modifications apart from WolfHud?

**Comment by Wibble199** [comment]
My friend's using:
- Disable crimespree reset on crash
- More weapon stats

I'm using:
- Disable crimespree reset on crash
- More weapon stats
- Use Non-Silenced Sound
- Weapons attachments customizer

**Comment by MEXAHOTABOP** [comment]
can you try to reproduce this with wolfhud only?

**Comment by SC2Mitch** [comment]
Non-Silenced Sounds & More Weapon Stats might be effecting this as it's trying to do some math on fire_rate so it might be affecting it, can you remove the mods and give this a try?

**Comment by Wibble199** [comment]
So we've tried a regular heist both with and without the other mods and couldn't get the error to happen again. I forgot to mention that the error occurred during a crime spree heist rather than a normal one. It's maybe also worth noting that we had the modifier for the zeal snipers active during the spree.

Unfortunately (probably due to removing the crime spree crash mod) our crime spree has now failed and so we won't be able to try a crime spree with the zeal snipers, although we may try a crime spree anyway.

**Comment by Kuziz** [comment]
Did some testing, crash stopped occuring once I removed More Weapon Stats.

**Comment by SC2Mitch** [comment]
I've tried this on a unmodded and modded PD2 game and it's still the same crash reason.

**Comment by Kamikaze94** [comment]
Yep, seems to be a vanilla issue: 
https://www.reddit.com/r/paydaytheheist/comments/6ltvpf/can_someone_please_figure_out_what_this_crash_is/
