### ISSUE TITLE
Crash in Golden Grin when pressing a tab button.

### ISSUE THREAD

**Issue by Zoyseth** [Kamikaze94/WolfHUD#347]
Please fix it. For tab info, i used lobby player info and wolfhud.

**Comment by SC2Mitch** [comment]
This has been fixed in the latest update of WolfHud, I'd highly recommend you reinstall.

**Comment by zoyseth** [comment]
Okay thanks, no crash anymore. But how do i know when updates are available in GitHub? I press update WolfHud in game, but it said up to date.

**Comment by Zoyseth** [comment]
@SC2Mitch

**Comment by SC2Mitch** [comment]
I don't think the in-game feature is being supported as much, the best way to check if there has been a recent update is to check the top bar and see if there has been a "Last Commit" which was an hour ago. Happy Heisting.

**Comment by MEXAHOTABOP** [comment]
`git clone` to clone repo in /PAYDAY 2/mods 
and subscribe or if you want just keep mod up to date write simple script for auto run `git fetch && git pull `on every game run

**Comment by Zoyseth** [comment]
How to do that? @MEXAHOTABOP

**Comment by Zoyseth** [comment]
i mean git pull script @MEXAHOTABOP

**Comment by MEXAHOTABOP** [comment]
on linux this like
steam launch string `LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so"  SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 SDL_AUDIODRIVER=pulse ./launcher.sh %command% -skip_intro`
in launcher.sh
```
#!/bin/sh

cd mods/WolfHUD
git pull
cd ../../
"$@"

```
how on windows i dont know

**Comment by GoogleMaster** [comment]
there is no more method managers.crime_spree:_is_active() . change it to managers.crime_spree:is_active() at all files i found it

**Comment by MEXAHOTABOP** [comment]
already fixed in https://github.com/Kamikaze94/WolfHUD/commit/3ec16c30ea933a5ed2a8ac63863faad272a7385f
