### ISSUE TITLE
How to know if updates are available for WolfHud in GitHub?

### ISSUE THREAD

**Issue by Zoyseth** [Kamikaze94/WolfHUD#349]
In game update button says it's up to date.

**Comment by Jowy12** [comment]
You have to check this site frequently, that's the only way for now.

**Comment by Cyberbeni** [comment]
I use SourceTree and it has an option to "check default remotes for updates every x minutes"

If you also want to pull the changes automatically then this seemed good: https://github.com/Keenpoint/git-auto-pull

**Comment by Zoyseth** [comment]
@Cyberbeni how to use it?

**Comment by Zoyseth** [comment]
i mean the auto pull @Cyberbeni

**Comment by Cyberbeni** [comment]
@Zoyseth never used it but there is a readme

**Comment by Zoyseth** [comment]
@Cyberbeni what about source tree then?
i don't know how to use it
