### ISSUE TITLE
Attempt to compare number with string

### ISSUE THREAD

**Issue by unrealxqt** [Kamikaze94/WolfHUD#351]
I got crashed with the error the title says.

Details:

Me and my teammates were doing a Crime Spree, I was using Dragon Breath Shotgun, which causes a burn effect on enemies. (I personally think that might have caused some error, like handling fraction numbers incorrectly)

crash.log:

`Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string`

Last entry in cashlog.log:

Fri Jul 07 12:38:29 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/DamagePopup.lua:12: attempt to compare number with string

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.272.
	CPU : Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 660 Ti / nvd3dum.dll[22.21.13.8205]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8138MB 704KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Hangszórók (Realtek High Definition Audio))

**Comment by MEXAHOTABOP** [comment]
dupe https://github.com/Kamikaze94/WolfHUD/issues/320
