### ISSUE TITLE
Crash when attempting to melee ZEAL Sniper

### ISSUE THREAD

**Issue by 1indey** [Kamikaze94/WolfHUD#352]
Meleeing him with Buzzer or Electric Knuckles crashes the game.

Fri Jul 07 16:58:02 2017

Application has crashed: C++ exception
[string "lib/units/weapons/npcraycastweaponbase.lua"]:144: attempt to perform arithmetic on field 'fire_rate' (a nil value)

SCRIPT STACK

-------------------------------

**Comment by KouRyuu2** [comment]
The issue isn't wolfhud related as it wasn't present in update 149. It's a new issue in U150. There's 2 mods that currently fixes the issue (One that removes them outright and one that fixes a few lines of code) on Modworkshop currently

**Comment by Kamikaze94** [comment]
I'll just drop this here:
https://modworkshop.net/mydownloads.php?action=view_down&did=20362
It fixes the missing fire rate for those units, until Overkill pushs out a fix.

Also, duplicate of issue #344. Thanks for the additional info though :)
