### ISSUE TITLE
Cant change weapon names back to ingame names

### ISSUE THREAD

**Issue by Fishrence** [Kamikaze94/WolfHUD#355]
Hi, thanks for your effort in this project.

My problem is that i cant switch back to ingame names. It makes no difference, if i check the box for "real weapon names" or not.

**Comment by Kamikaze94** [comment]
It needs a game restart/map change, due to how localizations get loaded.

**Comment by Fishrence** [comment]
Problem still exists. Even after a mapchange it would not change to the "game names", i tried mapchange and restarting the game. Thx for the quick response!

**Comment by Fishrence** [comment]
Oh dear, i found my error, i was absolutly my fault. I got this Wolfhud version from github yesterday and i renamed the old Wolfhud folder, but it was still in the mods folder. Moved the old folder elsewhere and it works fine! Sorry for bothering you and keep the great work going, thx!

**Comment by Tenkomanker** [comment]
@Fishrence close the topic please
