### ISSUE TITLE
New Update, do we need to update?

### ISSUE THREAD

**Issue by SC2Mitch** [Kamikaze94/WolfHUD#356]
There was a new update to PD2, do we need to update our HUD or do anything at all? You know how OV is with their update record 👍 
@Kamikaze94

**Comment by robotboy655** [comment]
Yes, there is a crash fix in this repo.

**Comment by Lyon-CZ** [comment]
We definitely need some update. My game turned into pure crash fest after 150.1 update.

**Comment by Srki94** [comment]
One of the crashes happens when you hit Tab in game after the Desync beta went live. I haven't tested further to see can I prevent it somehow.

**Comment by SC2Mitch** [comment]
^
This was fixed in the most recent update.

**Comment by SC2Mitch** [comment]
After testing this out, I dont see any major issues with it. 
Closed
