### ISSUE TITLE
Aggregate Hostages Crash

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#36]
When customising HudList, attempting use the Aggregate Hostages causes crashing issues. Before the latest fix (for gadget state), attempting to set the option for the first time would crash the client (don't have a crash-log of that, my computer died today). After that fix, setting the option works fine, but crashes the game when attempting to start a heist. Disabling the option seems to work fine.

`Application has crashed: C++ exception
mods/WolfHUD/lua/HUDList.lua:581: attempt to index local 'data' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.54.9
	CPU : Intel(R) Core(TM) i7 CPU M 620 @ 2.67GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA Quadro FX 880M / nvd3dum.dll[9.18.13.4084]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     48047    0MB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : IDT (Speakers / HP (IDT High Definition Audio CODEC))

`

**Comment by Kamikaze94** [comment]
There was an item declaration missing in HUDlist.
Added that, should be working now.

**Comment by Malidictus** [comment]
I was able to enable the Aggregate Hostages option without crashing and play heists without crashing, either. I can confirm that it's fixed as far as I can tell :)

**Comment by Kamikaze94** [comment]
Thanks for confirming.
I'll close the issue now.  :D
