### ISSUE TITLE
Tab Stats Crash

### ISSUE THREAD

**Issue by Daveedeq** [Kamikaze94/WolfHUD#360]
Sun Jul 09 18:52:39 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:491: attempt to call method '_is_active' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

**Comment by SC2Mitch** [comment]
Update your client, a fix was released a few days ago.
