### ISSUE TITLE
wolfHud crashes while attempting to connect or joining someones game

### ISSUE THREAD

**Issue by bugarin714** [Kamikaze94/WolfHUD#363]
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/1134518/crashlog.txt)

Sun Jul 09 22:38:16 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/HUDChat.lua:57: attempt to index field 'SIZE' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlSetLastWin32Error                                

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.275.
	CPU : AMD FX(tm)-8350 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon (TM) R9 Fury Series / aticfx32.dll[22.19.171.257]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16332MB 300KB
	OS : 6.1.7600 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (2- Realtek High Definition Audio))

----------------------------------------------------------------------

Sun Jul 09 22:39:42 2017

Application has crashed: C++ exception
[string "lib/managers/menu/newheistsgui.lua"]:134: attempt to index field '_dummy_item' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlSetLastWin32Error                                

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.275.
	CPU : AMD FX(tm)-8350 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon (TM) R9 Fury Series / aticfx32.dll[22.19.171.257]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16332MB 300KB
	OS : 6.1.7600 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (2- Realtek High Definition Audio))

----------------------------------------------------------------------

Sun Jul 09 22:40:22 2017

Application has crashed: C++ exception
[string "lib/managers/menu/newheistsgui.lua"]:134: attempt to index field '_dummy_item' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlSetLastWin32Error                                

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.275.
	CPU : AMD FX(tm)-8350 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon (TM) R9 Fury Series / aticfx32.dll[22.19.171.257]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16332MB 300KB
	OS : 6.1.7600 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (2- Realtek High Definition Audio))

----------------------------------------------------------------------

Sun Jul 09 22:42:23 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/HUDChat.lua:57: attempt to index field 'SIZE' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlSetLastWin32Error                                

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.275.
	CPU : AMD FX(tm)-8350 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon (TM) R9 Fury Series / aticfx32.dll[22.19.171.257]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16332MB 300KB
	OS : 6.1.7600 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (2- Realtek High Definition Audio))

**Comment by OmegaLeFoxWolf** [comment]
Same cpu, same error, different code. mine crashes at when you click join at crime.net and it loads the players screen
