### ISSUE TITLE
Chat 

### ISSUE THREAD

**Issue by Aprius** [Kamikaze94/WolfHUD#366]
The chat keeps changing to the left and to right is are only 2 players in a room without the bots =[

**Comment by Kamikaze94** [comment]
It's coded to always take the side that is emptier.
Which sides do you have player and teammates hud on and on which scales?
A Screenshot of your layout might be useful...
Also do you mean 2 players aside from yourself or 2 including you?

**Comment by Aprius** [comment]
Hey, hm.. Sorry for not sending any pictures or screenshots or whatever.
Well, I'm not from USA so my english is not perfect but well...
It's me +1 player (my friend)
Here's some pictures of the conf menu, my friend is offline now so I can't
take any screenshots ingame. (Sorry senpai)
[image: Imagem inline 1][image: Imagem inline 2]
Can I code something to the chat allways be on the right or something?
Or maybe an hidden option where I can change this?

Well, Sorry for bothering you...
If I can help you in any way just gimme a call, my steam is Aprius, just
like in the pictures =]

2017-07-10 19:10 GMT-03:00 Kamikaze94 <notifications@github.com>:
