### ISSUE TITLE
Using TAB crashes my game. (Tab to open info menu)

### ISSUE THREAD

**Issue by Wolfhudluvr** [Kamikaze94/WolfHUD#368]
On payday 2 when activating the info menu via TAB, the game crashes. Here is the log from PAYDAY 2/mods/logs

Not sure if you can make anything of this.

04:01:41 PM Log: CURL INITD
04:01:46 PM Log: Initiating Hook
04:01:53 PM Log: Initiating Hook
04:01:54 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:01:54 PM Lua: [Mods] Loading mods for state (table: 001E0480)
04:01:54 PM Lua: [Mods] Loading mod: base...
04:01:54 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:01:54 PM Lua: [Mods] Loading mod: Disconnect a player...
04:01:54 PM Lua: [Mods] Loading mod: Fast Quit...
04:01:54 PM Lua: [Mods] Loading mod: KillFeed...
04:01:54 PM Lua: [Mods] Loading mod: Meth Helper...
04:01:54 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:01:54 PM Lua: [Mods] Loading mod: WolfHUD...
04:01:54 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:01:54 PM Log: Initiating Hook
04:01:54 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:01:54 PM Lua: [Mods] Loading mods for state (table: 001E04C0)
04:01:54 PM Lua: [Mods] Loading mod: base...
04:01:54 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:01:54 PM Lua: [Mods] Loading mod: Disconnect a player...
04:01:54 PM Lua: [Mods] Loading mod: Fast Quit...
04:01:54 PM Lua: [Mods] Loading mod: KillFeed...
04:01:54 PM Lua: [Mods] Loading mod: Meth Helper...
04:01:54 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:01:54 PM Lua: [Mods] Loading mod: WolfHUD...
04:01:54 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:01:57 PM Log: Initiating Hook
04:01:57 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:01:57 PM Lua: [Mods] Loading mods for state (table: 2C3C3BA0)
04:01:57 PM Lua: [Mods] Loading mod: base...
04:01:57 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:01:57 PM Lua: [Mods] Loading mod: Disconnect a player...
04:01:57 PM Lua: [Mods] Loading mod: Fast Quit...
04:01:57 PM Lua: [Mods] Loading mod: KillFeed...
04:01:57 PM Lua: [Mods] Loading mod: Meth Helper...
04:01:57 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:01:57 PM Lua: [Mods] Loading mod: WolfHUD...
04:01:57 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:02:12 PM Log: Incoming HTTP Request/Request
04:02:12 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=wolfhud&mod[3]=wolfhud_textures&mod[4]=fed_inv&mod[5]=DAP&mod[6]=DifficultyScreenAnimation&mod[7]=kill_feed
04:02:12 PM Log: 1187
04:02:12 PM Log: Launching Async HTTP Thread
04:02:12 PM Lua: [Updates] Attempting to remove temporary hook dll...
04:02:12 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
04:02:15 PM Lua: [Updates] Received update data for 'kill_feed', server revision: 17
04:02:15 PM Lua: [Updates] Received update data for 'fed_inv', server revision: 14
04:02:15 PM Lua: [Updates] Received update data for 'wolfhud_textures', server revision: 8
04:02:15 PM Lua: [Updates] Received update data for 'DifficultyScreenAnimation', server revision: 2
04:02:15 PM Lua: [Updates] Received update data for 'DAP', server revision: 2
04:02:15 PM Lua: [Updates] Received update data for 'payday2blt', server revision: 15
04:02:15 PM Lua: [Updates] Received update data for 'wolfhud', server revision: 20
04:02:15 PM Lua: [Updates] Received update data for 'payday2bltdll', server revision: 5
04:02:16 PM Lua: [Updates] Downloading mod data for kill_feed
04:02:16 PM Log: Incoming HTTP Request/Request
04:02:16 PM Log: http://download.paydaymods.com/download/latest/kill_feed
04:02:16 PM Log: 1163
04:02:16 PM Log: Launching Async HTTP Thread
04:02:16 PM Lua: [Updates] Started http download: 2
04:02:17 PM Lua: [Updates] Finished http download: 2
04:02:17 PM Lua: [Updates] Finished downloading mod data for kill_feed
04:02:17 PM Lua: [Updates] Saving mod to file path: mods/downloads/kill_feed.zip
04:02:17 PM Lua: [Error] Could not remove directory: mods/KillFeed/loc/
04:02:17 PM Log: Extracting to mods//KillFeed/
04:02:17 PM Log: Extracting to mods//KillFeed/killfeed.lua
04:02:17 PM Log: Extracting to mods//KillFeed/LICENSE
04:02:17 PM Log: Extracting to mods//KillFeed/loc/
04:02:17 PM Log: Extracting to mods//KillFeed/loc/english.txt
04:02:17 PM Log: Extracting to mods//KillFeed/loc/french.txt
04:02:17 PM Log: Extracting to mods//KillFeed/loc/german.txt
04:02:17 PM Log: Extracting to mods//KillFeed/loc/italian.txt
04:02:17 PM Log: Extracting to mods//KillFeed/mod.txt
04:02:17 PM Log: Extracting to mods//KillFeed/README.md
04:03:23 PM Log: CURL CLOSED
04:03:36 PM Log: CURL INITD
04:03:42 PM Log: Initiating Hook
04:03:48 PM Log: Initiating Hook
04:03:48 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:03:48 PM Lua: [Mods] Loading mods for state (table: 001E0480)
04:03:48 PM Lua: [Mods] Loading mod: base...
04:03:48 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:03:48 PM Lua: [Mods] Loading mod: Disconnect a player...
04:03:48 PM Lua: [Mods] Loading mod: Fast Quit...
04:03:48 PM Lua: [Mods] Loading mod: KillFeed...
04:03:48 PM Lua: [Mods] Loading mod: Meth Helper...
04:03:48 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:03:48 PM Lua: [Mods] Loading mod: WolfHUD...
04:03:48 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:03:48 PM Log: Initiating Hook
04:03:48 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:03:48 PM Lua: [Mods] Loading mods for state (table: 001E04C0)
04:03:48 PM Lua: [Mods] Loading mod: base...
04:03:48 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:03:48 PM Lua: [Mods] Loading mod: Disconnect a player...
04:03:48 PM Lua: [Mods] Loading mod: Fast Quit...
04:03:48 PM Lua: [Mods] Loading mod: KillFeed...
04:03:48 PM Lua: [Mods] Loading mod: Meth Helper...
04:03:48 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:03:49 PM Lua: [Mods] Loading mod: WolfHUD...
04:03:49 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:03:51 PM Log: Initiating Hook
04:03:51 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:03:51 PM Lua: [Mods] Loading mods for state (table: 2C3D3BA0)
04:03:51 PM Lua: [Mods] Loading mod: base...
04:03:51 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:03:51 PM Lua: [Mods] Loading mod: Disconnect a player...
04:03:51 PM Lua: [Mods] Loading mod: Fast Quit...
04:03:51 PM Lua: [Mods] Loading mod: KillFeed...
04:03:51 PM Lua: [Mods] Loading mod: Meth Helper...
04:03:51 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:03:51 PM Lua: [Mods] Loading mod: WolfHUD...
04:03:51 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:04:12 PM Log: Incoming HTTP Request/Request
04:04:12 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=wolfhud&mod[3]=wolfhud_textures&mod[4]=fed_inv&mod[5]=DAP&mod[6]=DifficultyScreenAnimation&mod[7]=kill_feed
04:04:12 PM Log: 1003
04:04:12 PM Log: Launching Async HTTP Thread
04:04:12 PM Lua: [Updates] Attempting to remove temporary hook dll...
04:04:12 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
04:04:13 PM Lua: [Updates] Received update data for 'kill_feed', server revision: 17
04:04:13 PM Lua: [Updates] Received update data for 'fed_inv', server revision: 14
04:04:13 PM Lua: [Updates] Received update data for 'wolfhud_textures', server revision: 8
04:04:13 PM Lua: [Updates] Received update data for 'DifficultyScreenAnimation', server revision: 2
04:04:13 PM Lua: [Updates] Received update data for 'DAP', server revision: 2
04:04:13 PM Lua: [Updates] Received update data for 'payday2blt', server revision: 15
04:04:13 PM Lua: [Updates] Received update data for 'wolfhud', server revision: 20
04:04:13 PM Lua: [Updates] Received update data for 'payday2bltdll', server revision: 5
04:05:47 PM Lua: [1] SYSTEM: 50 Blessings is joining.
04:05:59 PM Log: Initiating Hook
04:05:59 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:05:59 PM Lua: [Mods] Loading mods for state (table: 2BF422A0)
04:05:59 PM Lua: [Mods] Loading mod: base...
04:05:59 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:05:59 PM Lua: [Mods] Loading mod: Disconnect a player...
04:05:59 PM Lua: [Mods] Loading mod: Fast Quit...
04:05:59 PM Lua: [Mods] Loading mod: KillFeed...
04:05:59 PM Lua: [Mods] Loading mod: Meth Helper...
04:05:59 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:05:59 PM Lua: [Mods] Loading mod: WolfHUD...
04:05:59 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:05:59 PM Log: Initiating Hook
04:05:59 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:06:00 PM Lua: [Mods] Loading mods for state (table: 45691640)
04:06:00 PM Lua: [Mods] Loading mod: base...
04:06:00 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:06:00 PM Lua: [Mods] Loading mod: Disconnect a player...
04:06:00 PM Lua: [Mods] Loading mod: Fast Quit...
04:06:00 PM Lua: [Mods] Loading mod: KillFeed...
04:06:00 PM Lua: [Mods] Loading mod: Meth Helper...
04:06:00 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:06:00 PM Lua: [Mods] Loading mod: WolfHUD...
04:06:00 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:06:00 PM Log: Initiating Hook
04:06:00 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:06:00 PM Lua: [Mods] Loading mods for state (table: 267022E0)
04:06:00 PM Lua: [Mods] Loading mod: base...
04:06:00 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:06:00 PM Lua: [Mods] Loading mod: Disconnect a player...
04:06:00 PM Lua: [Mods] Loading mod: Fast Quit...
04:06:00 PM Lua: [Mods] Loading mod: KillFeed...
04:06:00 PM Lua: [Mods] Loading mod: Meth Helper...
04:06:00 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:06:00 PM Lua: [Mods] Loading mod: WolfHUD...
04:06:00 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:06:17 PM Lua: [1] 50 Blessings: bring what
04:06:17 PM Lua: Jukebox deselected
04:06:17 PM Lua: [1] SYSTEM: Fortis Fortuna Adiuvat is joining.
04:06:17 PM Lua: [1] SYSTEM: someone's Duk is joining.
04:06:25 PM Lua: [1] someone's Duk: sentry guns
04:06:27 PM Lua: Jukebox deselected
04:06:38 PM Lua: [1] 50 Blessings: y not
04:06:39 PM Lua: [1] _-TehEpicPotato-_: Stealth right..?
04:06:44 PM Lua: [1] 50 Blessings: nah
04:06:44 PM Lua: [1] 50 Blessings: nah
04:06:47 PM Lua: Jukebox deselected
04:06:59 PM Lua: [1] _-TehEpicPotato-_: Stealth gone wrong then?
04:07:03 PM Lua: [1] Fortis Fortuna Adiuvat: i didnt read your msg, joined late
04:07:04 PM Lua: [1] 50 Blessings: yeah
04:07:14 PM Lua: [1] Fortis Fortuna Adiuvat: cant place sentry now
04:07:20 PM Lua: [1] _-TehEpicPotato-_: Mouse sensitivity is off..
04:07:21 PM Lua: [1] _-TehEpicPotato-_: gah
04:07:42 PM Lua: [1] _-TehEpicPotato-_: 1 sec
04:08:02 PM Lua: [1] 50 Blessings: that's one weird mask mate
04:08:42 PM Lua: [1] _-TehEpicPotato-_: Better.
04:08:45 PM Lua: [1] _-TehEpicPotato-_: Haha ikr.
04:09:09 PM Lua: [1] _-TehEpicPotato-_: Welcome to payday btw.
04:09:18 PM Lua: [1] 50 Blessings: who?
04:09:22 PM Lua: [1] _-TehEpicPotato-_: You
04:09:26 PM Lua: [1] 50 Blessings: me?
04:09:28 PM Lua: [1] 50 Blessings: why
04:09:29 PM Lua: [1] _-TehEpicPotato-_: Yea haha
04:09:32 PM Lua: [1] _-TehEpicPotato-_: lvl 66?
04:09:35 PM Lua: [1] 50 Blessings: uhh
04:09:36 PM Lua: [1] _-TehEpicPotato-_: Did you reset or something.
04:09:42 PM Log: CURL CLOSED
04:10:02 PM Log: CURL INITD
04:10:09 PM Log: Initiating Hook
04:10:17 PM Log: Initiating Hook
04:10:17 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:10:17 PM Lua: [Mods] Loading mods for state (table: 001E0480)
04:10:17 PM Lua: [Mods] Loading mod: base...
04:10:17 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:10:17 PM Lua: [Mods] Loading mod: Disconnect a player...
04:10:17 PM Lua: [Mods] Loading mod: Fast Quit...
04:10:17 PM Lua: [Mods] Loading mod: KillFeed...
04:10:17 PM Lua: [Mods] Loading mod: Meth Helper...
04:10:17 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:10:17 PM Lua: [Mods] Loading mod: WolfHUD...
04:10:17 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:10:17 PM Log: Initiating Hook
04:10:17 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:10:17 PM Lua: [Mods] Loading mods for state (table: 001E04C0)
04:10:17 PM Lua: [Mods] Loading mod: base...
04:10:17 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:10:17 PM Lua: [Mods] Loading mod: Disconnect a player...
04:10:17 PM Lua: [Mods] Loading mod: Fast Quit...
04:10:17 PM Lua: [Mods] Loading mod: KillFeed...
04:10:17 PM Lua: [Mods] Loading mod: Meth Helper...
04:10:17 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:10:17 PM Lua: [Mods] Loading mod: WolfHUD...
04:10:17 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:10:20 PM Log: Initiating Hook
04:10:20 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:10:20 PM Lua: [Mods] Loading mods for state (table: 2C353BA0)
04:10:20 PM Lua: [Mods] Loading mod: base...
04:10:20 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:10:20 PM Lua: [Mods] Loading mod: Disconnect a player...
04:10:20 PM Lua: [Mods] Loading mod: Fast Quit...
04:10:20 PM Lua: [Mods] Loading mod: KillFeed...
04:10:20 PM Lua: [Mods] Loading mod: Meth Helper...
04:10:20 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:10:20 PM Lua: [Mods] Loading mod: WolfHUD...
04:10:20 PM Lua: [Mods] Mod 'mods/Meth Helper/' is disabled!
04:11:21 PM Log: Incoming HTTP Request/Request
04:11:21 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=wolfhud&mod[3]=wolfhud_textures&mod[4]=fed_inv&mod[5]=DAP&mod[6]=DifficultyScreenAnimation&mod[7]=kill_feed
04:11:21 PM Log: 1367
04:11:21 PM Log: Launching Async HTTP Thread
04:11:21 PM Lua: [Updates] Attempting to remove temporary hook dll...
04:11:21 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
04:11:22 PM Lua: [Updates] Received update data for 'kill_feed', server revision: 17
04:11:22 PM Lua: [Updates] Received update data for 'fed_inv', server revision: 14
04:11:22 PM Lua: [Updates] Received update data for 'wolfhud_textures', server revision: 8
04:11:22 PM Lua: [Updates] Received update data for 'DifficultyScreenAnimation', server revision: 2
04:11:22 PM Lua: [Updates] Received update data for 'DAP', server revision: 2
04:11:22 PM Lua: [Updates] Received update data for 'payday2blt', server revision: 15
04:11:22 PM Lua: [Updates] Received update data for 'wolfhud', server revision: 20
04:11:22 PM Lua: [Updates] Received update data for 'payday2bltdll', server revision: 5
04:15:33 PM Log: CURL CLOSED
04:15:54 PM Log: CURL INITD
04:15:59 PM Log: Initiating Hook
04:16:06 PM Log: Initiating Hook
04:16:06 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:16:06 PM Lua: [Mods] Loading mods for state (table: 001E0480)
04:16:06 PM Lua: [Mods] Loading mod: base...
04:16:06 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:16:06 PM Lua: [Mods] Loading mod: Disconnect a player...
04:16:06 PM Lua: [Mods] Loading mod: Fast Quit...
04:16:06 PM Lua: [Mods] Loading mod: KillFeed...
04:16:06 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:16:06 PM Lua: [Mods] Loading mod: WolfHUD...
04:16:06 PM Log: Initiating Hook
04:16:06 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:16:06 PM Lua: [Mods] Loading mods for state (table: 001E04C0)
04:16:06 PM Lua: [Mods] Loading mod: base...
04:16:06 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:16:06 PM Lua: [Mods] Loading mod: Disconnect a player...
04:16:06 PM Lua: [Mods] Loading mod: Fast Quit...
04:16:06 PM Lua: [Mods] Loading mod: KillFeed...
04:16:06 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:16:06 PM Lua: [Mods] Loading mod: WolfHUD...
04:16:08 PM Log: Initiating Hook
04:16:08 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:16:08 PM Lua: [Mods] Loading mods for state (table: 2C3C3AE0)
04:16:08 PM Lua: [Mods] Loading mod: base...
04:16:08 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:16:08 PM Lua: [Mods] Loading mod: Disconnect a player...
04:16:08 PM Lua: [Mods] Loading mod: Fast Quit...
04:16:08 PM Lua: [Mods] Loading mod: KillFeed...
04:16:08 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:16:08 PM Lua: [Mods] Loading mod: WolfHUD...
04:16:45 PM Log: Incoming HTTP Request/Request
04:16:45 PM Log: http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=wolfhud&mod[3]=wolfhud_textures&mod[4]=fed_inv&mod[5]=DAP&mod[6]=DifficultyScreenAnimation&mod[7]=kill_feed
04:16:45 PM Log: 1370
04:16:45 PM Log: Launching Async HTTP Thread
04:16:45 PM Lua: [Updates] Attempting to remove temporary hook dll...
04:16:45 PM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
04:16:45 PM Lua: [Updates] Received update data for 'kill_feed', server revision: 17
04:16:45 PM Lua: [Updates] Received update data for 'fed_inv', server revision: 14
04:16:45 PM Lua: [Updates] Received update data for 'wolfhud_textures', server revision: 8
04:16:45 PM Lua: [Updates] Received update data for 'DifficultyScreenAnimation', server revision: 2
04:16:45 PM Lua: [Updates] Received update data for 'DAP', server revision: 2
04:16:45 PM Lua: [Updates] Received update data for 'payday2blt', server revision: 15
04:16:45 PM Lua: [Updates] Received update data for 'wolfhud', server revision: 20
04:16:45 PM Lua: [Updates] Received update data for 'payday2bltdll', server revision: 5
04:17:22 PM Log: Initiating Hook
04:17:22 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:17:22 PM Lua: [Mods] Loading mods for state (table: 40221C60)
04:17:22 PM Lua: [Mods] Loading mod: base...
04:17:22 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:17:22 PM Lua: [Mods] Loading mod: Disconnect a player...
04:17:22 PM Lua: [Mods] Loading mod: Fast Quit...
04:17:22 PM Lua: [Mods] Loading mod: KillFeed...
04:17:22 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:17:22 PM Lua: [Mods] Loading mod: WolfHUD...
04:17:22 PM Log: Initiating Hook
04:17:22 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:17:22 PM Lua: [Mods] Loading mods for state (table: 40450A80)
04:17:22 PM Lua: [Mods] Loading mod: base...
04:17:22 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:17:22 PM Lua: [Mods] Loading mod: Disconnect a player...
04:17:22 PM Lua: [Mods] Loading mod: Fast Quit...
04:17:22 PM Lua: [Mods] Loading mod: KillFeed...
04:17:22 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:17:22 PM Lua: [Mods] Loading mod: WolfHUD...
04:17:22 PM Log: Initiating Hook
04:17:22 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
04:17:22 PM Lua: [Mods] Loading mods for state (table: 431D2260)
04:17:22 PM Lua: [Mods] Loading mod: base...
04:17:22 PM Lua: [Mods] Loading mod: Difficulty Screen Animation...
04:17:22 PM Lua: [Mods] Loading mod: Disconnect a player...
04:17:22 PM Lua: [Mods] Loading mod: Fast Quit...
04:17:22 PM Lua: [Mods] Loading mod: KillFeed...
04:17:22 PM Lua: [Mods] Loading mod: Steam Profile Redirection...
04:17:22 PM Lua: [Mods] Loading mod: WolfHUD...
04:17:35 PM Lua: Jukebox deselected
04:17:54 PM Log: CURL CLOSED

And here is the appdata/local/payday 2 Crashlog

Tue Jul 11 16:17:51 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:409: attempt to call method '_is_active' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
         payday2_win32_release  (???)     zip_get_name                                        
               windows.storage  (???)     CreateItemArrayFromObjectArray                      
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.278.
	CPU : Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 950M / nvldumd.dll[22.21.13.8476]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16299MB 72KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Sennheiser (Headset Earphone (Sennheiser Communication Audio))

I hope you'll be able to fix this, love your mod, everyone does, very appreciative of your work.
So summary being the only thing crashing me is the instance in which I press tab. Not sure if this is a wolfhud related issue or one of the other ones I have installed.

**Comment by Wolfhudluvr** [comment]
Oh wow, I'm the 100th issue threat. Yay.

**Comment by robotboy655** [comment]
Update your HUD.

**Comment by Wolfhudluvr** [comment]
I went to update it and it gave me the non-dev version, so now the tab issue is gone but I crash on swan song..

**Comment by Wolfhudluvr** [comment]
Need to fix swan song crash mayun.

**Comment by Jowy12** [comment]
https://github.com/Kamikaze94/WolfHUD Click Clone/Download to get the Dev version.
