### ISSUE TITLE
Crash when Converting enemy (PocoHud and WolfHud incompatibility).

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#37]
Application has crashed: C++ exception
mods/PocoHud3/poco/common.lua:63: attempt to call field 'S' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                

-------------------------------

Code, I think:

		message = _.S(message)
		if managers and managers.chat and managers.chat._receivers and managers.chat._receivers[1] then
			for __,rcv in pairs( managers.chat._receivers[1] ) do
				rcv:receive_message( name or "*", message, color or tweak_data.chat_colors[5] )
			end
		else

Application has crashed: C++ exception
mods/PocoHud3/poco/common.lua:214: attempt to call field 'S' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     ZwCreateFile                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                

-------------------------------
Code:

	W = function(...)io.stdout:write(_.S(...)..'\n')end,

**Comment by Kamikaze94** [comment]
Okay, first of all, thanks  for reporting. I saw this issue a few times already, but couldn't get the line causing the problem.
But I'm fairly confident, I found the line in HUDList, that has potentially overwritten Poco's "_"-function-collection.
I accidentally used the underscore for a "don't care return variable", that seems to have been accidental global.
Got that fixed in the Dev Version here on GitHUB now.
Please try that version and confirm wether it solved the problem or not.
Thanks a lot!

**Comment by Tatsugi** [comment]
Confirm. It's workning now. Thank you.)
Proof.
![218620_20160816040227_1](https://cloud.githubusercontent.com/assets/19766576/17684748/91a3a17c-6366-11e6-9896-fc8957a23bc0.png)

**Comment by Kamikaze94** [comment]
Well, glad it worked out.
Guess I can mark this as fixed then + clase the issue.
Thanks for the confirmation :)
(That screenshot reminds me, still need to find out where I can move the subtitles a little upwards....  :/)
