### ISSUE TITLE
Random crash while in-heist and on heist end

### ISSUE THREAD

**Issue by Aurani** [Kamikaze94/WolfHUD#370]
I just did a Bank Cash heist with my friend and my game crashed 2 times during it.
This is the crash entries for the 2 crashes.

Tue Jul 11 22:56:05 2017

Application has crashed: access violation

-------------------------------

Current thread: Main
Script stack:
_get_unit_intimidation_action()  lib/units/beings/player/states/playerstandard.lua:3521  
    _start_action_intimidate()  lib/units/beings/player/states/playerstandard.lua:3608  
                                lib/units/beings/player/states/playerstandard.lua:2244  
                            ()  =(tail                                              
                      call):-1  _update_check_actions()                             
lib/units/beings/player/states/playerstandard.lua:909  update_original()                                   
lib/units/beings/player/states/playerstandard.lua:413  update()                                            
@mods/WolfHUD/lua/BurstFire.lua:196                                                      
lib/units/beings/player/playermovement.lua:275  ()                                                  
                        =(tail  call):-1                                            
                            ()  =(tail                                              
                                call):-1                                            

-------------------------------

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 780 / nvd3dum.dll[22.21.13.8165]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     12255MB 144KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Tue Jul 11 23:01:24 2017

Application has crashed: access violation

-------------------------------

Current thread: Main
Script stack:
              set_AI_enabled()  lib/managers/group_ai_states/groupaistatebase.lua:285  
                    at_enter()  lib/states/missionendstate.lua:147                  
                    at_enter()  lib/states/victorystate.lua:14                      
                                lib/states/gamestate.lua:22                         
                            ()  =(tail                                              
                      call):-1  _do_state_change()                                  
core/lib/utils/game_state_machine/coregamestatemachine.lua:124  end_update()                                        
core/lib/utils/game_state_machine/coregamestatemachine.lua:104  end_update()                                        
      lib/setups/setup.lua:755  end_update()                                        
  lib/setups/gamesetup.lua:719  end_update()                                        
lib/setups/networkgamesetup.lua:33                                                      
core/lib/setups/coresetup.lua:580  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

**Comment by sikwititone** [comment]
----------------------------------------------------------------------
Wed Jul 12 11:06:27 2017


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
              set_AI_enabled()  lib/managers/group_ai_states/groupaistatebase.lua:285  
                    at_enter()  lib/states/missionendstate.lua:147                  
                    at_enter()  lib/states/victorystate.lua:14                      
                                lib/states/gamestate.lua:22                         
                            ()  =(tail                                              
                      call):-1  _do_state_change()                                  
core/lib/utils/game_state_machine/coregamestatemachine.lua:124  end_update()                                        
core/lib/utils/game_state_machine/coregamestatemachine.lua:104  end_update()                                        
      lib/setups/setup.lua:755  end_update()                                        
  lib/setups/gamesetup.lua:719  end_update()                                        
lib/setups/networkgamesetup.lua:33                                                      
core/lib/setups/coresetup.lua:580  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980M / nvldumd.dll[22.21.13.8476]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16322MB 572KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded

**Comment by Jowy12** [comment]
I don't think was caused by WolfHUD, as far as i know this has something to do with Gameplay Changing Mod.

**Comment by Aurani** [comment]
Well I only have WolfHUD installed, the first crash specifically mentioned WolfHUD's mod folder as the cause.
