### ISSUE TITLE
Swan Song Crash

### ISSUE THREAD

**Issue by Dex353** [Kamikaze94/WolfHUD#372]
After swan song is activated, at the end of the duration, instead of falling to the ground, the game crash.
[2017_07_13_log.txt](https://github.com/Kamikaze94/WolfHUD/files/1145741/2017_07_13_log.txt)

**Comment by MEXAHOTABOP** [comment]
first of all log w/o crash 
if you need help we need exactly crash log

but i can try guess what problem you have
1) you use old version of wolfhud not from github and have https://github.com/Kamikaze94/WolfHUD/issues/163 then you need download lasted version from github https://github.com/Kamikaze94/WolfHUD#installation-direct-download
2) you have some problems with blt (as i can see by many errors in log) you need delete mods dir and reinstall blt and all mods
3) as i see from log you use other mods try disable em and reproduce error
