### ISSUE TITLE
Hud No Longer Tracking Teammate Downs Accurately 

### ISSUE THREAD

**Issue by TheCreamSoda** [Kamikaze94/WolfHUD#377]
When the crimespree/desync updates were pushed out, it seems that the down counters for team mates no longer update when a player goes down. This a known issue? Or do I have something hidden in settings that is messed up?

**Comment by MEXAHOTABOP** [comment]
download last hud versuib from github
https://github.com/Kamikaze94/WolfHUD#installation-direct-download
its bug been fixed by https://github.com/Kamikaze94/WolfHUD/commit/51467a7f9a6bc0922cb6aec8f975ce85fc509c9d

**Comment by TheCreamSoda** [comment]
Thank you for the heads up, sorry for the dumb issue post. I will download this right away!
