### ISSUE TITLE
crash when get the bag

### ISSUE THREAD

**Issue by OAWERF** [Kamikaze94/WolfHUD#379]
Sat Jul 15 17:46:02 2017

Application has crashed: C++ exception
[string "lib/managers/hudmanagerpd2.lua"]:1556: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

**Comment by MEXAHOTABOP** [comment]
1) how to reproduce?
2) you use other mods?
3) logs?

**Comment by OAWERF** [comment]
1.idk
2.yes
3. what log?

**Comment by MEXAHOTABOP** [comment]
try reproduce with other mods disabled 
https://github.com/Kamikaze94/WolfHUD#bug-reports
