### ISSUE TITLE
[string "lib/managers/missionassetsmanager.lua"]:556: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by kratosgow342** [Kamikaze94/WolfHUD#380]
My friend use HoxHUD and host Crime Spree until near the end my game crashed and I tried to join back but it keep crashing when it nearly finish loading on loadout screen here Crashlog

Sun Jul 16 18:37:41 2017

Application has crashed: C++ exception
[string "lib/managers/missionassetsmanager.lua"]:556: attempt to index field '?' (a nil value)

SCRIPT STACK

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlInterlockedPushEntrySList                        
                         ntdll  (???)     SbSelectProcedure                                   
                         ntdll  (???)     RtlGetCurrentServiceSessionId                       

Current thread: Main

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 740M / nvldumd.dll[22.21.13.8476]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8113MB 192KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (2- ASTRO MixAmp Pro           ))

**Comment by MEXAHOTABOP** [comment]
need blt log https://github.com/Kamikaze94/WolfHUD#bug-reports
you use other mods?

**Comment by kratosgow342** [comment]
Yes I wish I can reproduce the crash but it's really difficult cause it's Crime Spree.

**Comment by MEXAHOTABOP** [comment]
you have too many mods try disable em all except wolfhud and try reproduce
