### ISSUE TITLE
Crash after success

### ISSUE THREAD

**Issue by kittykiller** [Kamikaze94/WolfHUD#381]
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/1151145/crash.txt)

It doesn't crash all the time but it does happen often.

**Comment by MEXAHOTABOP** [comment]
need blt log https://github.com/Kamikaze94/WolfHUD#bug-reports
you use other mods?

**Comment by kittykiller** [comment]
[2017_07_16_log.txt](https://github.com/Kamikaze94/WolfHUD/files/1151152/2017_07_16_log.txt)

no I don't use any other mods

**Comment by MEXAHOTABOP** [comment]
you host?
if not what mods used by host? 

can you try reproduce this bug w/o mods enabled?

(wolfhud dont hook set_AI_enabled function and i think what problem somewhere else)

**Comment by kittykiller** [comment]
I don't host.
I just join random games so I don't know what they would be using.

I going to try to do a fresh install and see if that fixes anything

**Comment by kittykiller** [comment]
After doing some looking on the steam forums it seems like lots of people are getting this crash even without mods. :(
