### ISSUE TITLE
Application Crash : C++ 

### ISSUE THREAD

**Issue by foxneigio** [Kamikaze94/WolfHUD#382]
Hello, 
First i'd say, thanks a LOT for this HUD. It really rocks.
But i got crash and i dont know why. I think it's link to turret but i dont know. Here is the crash.txt file.
I didnt had crash before, but somebody use a turret, and short after i crashed. 
Thanks a lot for the help ! 
See y a !

Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:1643: attempt to index local 'unit' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD Radeon R9 200 Series / aticfx32.dll[21.19.137.1]
	Language : @IDaadeda58d8e5a71d@
	Memory :     8172MB 864KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Haut-parleurs (Logitech G930 Gaming Headset))

**Comment by MEXAHOTABOP** [comment]
need blt log https://github.com/Kamikaze94/WolfHUD#bug-reports

you use other mods?

**Comment by foxneigio** [comment]
Here is BLT Log i think.



https://pastebin.com/miWJJv8w
