### ISSUE TITLE
Game crashes when I straight up launch it.

### ISSUE THREAD

**Issue by KennyTheBlackSheep** [Kamikaze94/WolfHUD#383]
So i just got payday 2 like 1 week ago, and when i realized i can download mods, i straight up did. The 1st thing that i obv downloaded is the blt beardlib and VELOsync. Later that day I downloaded Wolfhud-master, put it in the mods file, renamed it to Wolfhud only, launched the game, asked me 2 download fed-inv and update something then restart my game. I exit out of the game, and when I launch it, it just fucking wont launch. It's not even trying 2 open up the game, it says its Running and then it suddenly exits and saves... I tried reinstalling it, looking up on youtube whats wrong. Nothin seemed to work soo i dont know really.

**Comment by kratosgow342** [comment]
Overkill launch desync update both Velosync and Adaptive Resync are useless and will crash the game so delete those mod.
