### ISSUE TITLE
Crime Spree Crash

### ISSUE THREAD

**Issue by kratosgow342** [Kamikaze94/WolfHUD#385]
I manage to reproduce this crash by disable all mod except WolfHUD the worst part is appear happened to be at random person not every person I join in Crime Spree lobby affected by this and it's really annoying can you point out what cause is this?

Wed Jul 19 13:57:40 2017

Application has crashed: C++ exception
[string "lib/managers/menu/crimespreemissionsmenucom..."]:776: attempt to compare nil with number

SCRIPT STACK

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlInterlockedPushEntrySList                        
                         ntdll  (???)     SbSelectProcedure                                   
                         ntdll  (???)     RtlGetCurrentServiceSessionId                       

Current thread: Main

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 740M / nvldumd.dll[22.21.13.8476]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8113MB 192KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (2- ASTRO MixAmp Pro           ))

**Comment by kratosgow342** [comment]
here's BLT log
https://pastebin.com/WRSk9y5z

**Comment by PJzuza** [comment]
Hmm I've tested this crashed before and even you've disabled all mods including deleted all mods and BLT. It won't stop this crashing. Here is my bug thread I've posted in the bug forum in PD2 community : http://steamcommunity.com/app/218620/discussions/14/2217311444334844490/ it has written the only solution I and some of my friend has found out. If you found the real solution I'd love to hear it :) but for now let's point out which one caused the problem.

**Comment by kallak** [comment]
Can you give any more information on how to reproduce the crash? Also are you using the latest version of WolfHud from github?

**Comment by kratosgow342** [comment]
Yes I used the latest version. I disable all mods except for WolfHUD and join some In Lobby Crime Spree like I said it's completely random which lobby that the game gonna crashed and after that I tested it again with WolfHUD turn off and nothing happened it seem like WolfHUD indirectly cause this issue.

**Comment by kallak** [comment]
Hmm. I'm not sure but this may be related to the [latest bug entry](https://github.com/Kamikaze94/WolfHUD/issues/387). I can set up a branch which has a possible fix, but as I said in the other thread, I'm not sure how to reproduce the bug.

**Comment by kallak** [comment]
While I try to figure out how to reproduce this bug I have created a [possible fix](https://github.com/kallak/WolfHUD/tree/Lobby_Crash_Fix) if you would like to try.

**Comment by kratosgow342** [comment]
unfortunately your fix is not work on my Crime Spree crash problem
