### ISSUE TITLE
Fix Weapon Names (Real Weapon Names and Multi Language)

### ISSUE THREAD

**Issue by justalemon** [Kamikaze94/WolfHUD#386]
I find certain problem with the gun names, with or without the mod. The name change is applied to Steam Market Searches. And for languages other than English, the name is also applied (check images below).

This affect the game but is not a huge problem, but i think that should be asked like Federal Inventory in the first mod execution because can also generate confusion with weapon names.

WolfHUD should ask to apply "Weapon Names" and also should have a option to fix the weapon names in non English languages.

**Comment by papydeath95** [comment]
Real Weapon Names:
![With Mod](https://user-images.githubusercontent.com/11861253/28365939-8d6cdd0c-6c58-11e7-930e-7e3f87c48a85.jpg)
Vanilla (Game on Spanish):
![Without Mod](https://user-images.githubusercontent.com/11861253/28365955-9f7a6a3c-6c58-11e7-9063-0847dd88904e.jpg)
Vanilla (Manually Fixed):
![20170719075848_1](https://user-images.githubusercontent.com/11861253/28365984-bb1b5058-6c58-11e7-8bf9-59dac9236e66.jpg)

**Comment by kallak** [comment]
I'll take a look into fixing the name when redirecting to the community market. Until then if the bug is causing problems for you then Real Weapon Names can be disabled from the options. Specifically "Inventory Tweak Options" then "Real Weapon Names".

**Comment by kallak** [comment]
This appears to also be a game bug. When a non-English language (or whenever the weapon names are changed) the redirect will always lead to the incorrect place. I'm working on a fix, however it may take some time.
