### ISSUE TITLE
Game session join crash (at lobby still)

### ISSUE THREAD

**Issue by OmegaLeFoxWolf** [Kamikaze94/WolfHUD#387]
Thu Jul 20 22:10:01 2017

Application has crashed: C++ exception
mods/WolfHUD-master/lua/Utils/LoadoutPanel.lua:929: attempt to compare nil with number

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.281.
	CPU : AMD FX(tm)-8350 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 760 (192-bit) / nvldumd.dll[22.21.13.8476]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8191MB 236KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by kallak** [comment]
By any chance did one of the players not have a perk deck equipped?

If so then it looks like its this snippet of code:
`if tonumber(deck_level) < 9 then`

This could be fixed if deck_level is checked before being converting to a number. Like so:
`if deck_level ~= nil and tonumber(deck_level) < 9 then`

However I'm unsure of exactly how lua handles if statements and I'm not sure how to reproduce the bug.

**Comment by kallak** [comment]
While I try to figure out how to reproduce this bug I have created a [possible fix](https://github.com/kallak/WolfHUD/tree/Lobby_Crash_Fix) if you would like to try.

**Comment by OmegaLeFoxWolf** [comment]
Downloading and testing now!

**Comment by OmegaLeFoxWolf** [comment]
But, I think it may be possible of no perk deck, right after i test this, and if it works, play a little longer for stability, ill comment.

**Comment by OmegaLeFoxWolf** [comment]
It works wonders! I haven't crashed yet!

**Comment by kallak** [comment]
Glad I could help. Tell me if you encounter the problem again.
