### ISSUE TITLE
WolfHUD crash issue

### ISSUE THREAD

**Issue by FabxBs** [Kamikaze94/WolfHUD#393]
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

This happens everytime in a loud mission when i die.

**Comment by pascaldulieu** [comment]
Getting the same crash as soon as i finish a mission

----------------------------------------------------------------------

Thu Jul 27 02:20:23 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3: bad argument #3 to 'format' (string expected, got table)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlSetCurrentDirectory_U                            
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------
