### ISSUE TITLE
Unable to save user settings (randomly happened for no reason)

### ISSUE THREAD

**Issue by Gentlemanbunny** [Kamikaze94/WolfHUD#394]
Below is The code I belive applies to it from the LOG file basically I can't save any settings it was fine one min like this the next any ideas ? 

12:33:48 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:34:18 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:34:46 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:35:15 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:36:24 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:37:02 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:37:12 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:38:15 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:39:21 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:39:31 AM Lua: [WolfHUD] ERROR: Error while saving, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:41:24 AM Lua: [1] SYSTEM: Restarting in 5 seconds.
12:41:25 AM Lua: [1] SYSTEM: Restarting in 4 seconds.
12:41:26 AM Lua: [1] SYSTEM: Restarting in 3 seconds.
12:41:27 AM Lua: [1] SYSTEM: Restarting in 2 seconds.
12:41:28 AM Lua: [1] SYSTEM: Restarting in 1 seconds.
12:41:29 AM Lua: [1] SYSTEM: Restarting in 0 seconds.
12:41:29 AM Log: Initiating Hook
12:41:29 AM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
12:41:29 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
12:41:29 AM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
12:41:29 AM Lua: [Mods] Loading mods for state (table: 538608C0)
12:41:29 AM Lua: [Mods] Loading mod: base...
12:41:29 AM Lua: [Mods] Loading mod: BeardLib...
12:41:29 AM Lua: [Mods] Loading mod: BuilDB...
12:41:29 AM Lua: [Mods] Loading mod: Counter taze animation restoration...
12:41:29 AM Lua: [Mods] Loading mod: Infamy Card Priority...
12:41:29 AM Lua: [Mods] Loading mod: Reconnect to server...
12:41:29 AM Lua: [Mods] Loading mod: Side Jobs in Lobby...
12:41:29 AM Lua: [Mods] Loading mod: WolfHUD...
12:41:29 AM Lua: [Error] Could not load revision file for Payday 2 BLT DLL!
12:41:29 AM Log: Initiating Hook
12:41:29 AM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
12:41:29 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
12:41:29 AM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
12:41:29 AM Lua: [Mods] Loading mods for state (table: 54130920)
12:41:29 AM Lua: [Mods] Loading mod: base...
12:41:29 AM Lua: [Mods] Loading mod: BeardLib...
12:41:29 AM Lua: [Mods] Loading mod: BuilDB...
12:41:29 AM Lua: [Mods] Loading mod: Counter taze animation restoration...
12:41:29 AM Lua: [Mods] Loading mod: Infamy Card Priority...
12:41:29 AM Lua: [Mods] Loading mod: Reconnect to server...
12:41:29 AM Lua: [Mods] Loading mod: Side Jobs in Lobby...
12:41:29 AM Lua: [Mods] Loading mod: WolfHUD...
12:41:29 AM Lua: [Error] Could not load revision file for Payday 2 BLT DLL!
12:41:30 AM Log: Initiating Hook
12:41:30 AM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
12:41:30 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
12:41:30 AM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
12:41:30 AM Lua: [Mods] Loading mods for state (table: 23900A60)
12:41:30 AM Lua: [Mods] Loading mod: base...
12:41:30 AM Lua: [Mods] Loading mod: BeardLib...
12:41:30 AM Lua: [Mods] Loading mod: BuilDB...
12:41:30 AM Lua: [Mods] Loading mod: Counter taze animation restoration...
12:41:30 AM Lua: [Mods] Loading mod: Infamy Card Priority...
12:41:30 AM Lua: [Mods] Loading mod: Reconnect to server...
12:41:30 AM Lua: [Mods] Loading mod: Side Jobs in Lobby...
12:41:30 AM Lua: [Mods] Loading mod: WolfHUD...
12:41:30 AM Lua: [Error] Could not load revision file for Payday 2 BLT DLL!

**Comment by kallak** [comment]
Can you check if the settings file is in read-only mode?

**Comment by Gentlemanbunny** [comment]
I found the problem for some reason be it update or whatever the Saves file had disappeared

**Comment by Gentlemanbunny** [comment]
you can close
