### ISSUE TITLE
Game crashes in Cook Off

### ISSUE THREAD

**Issue by TimLS** [Kamikaze94/WolfHUD#401]
Sat Jul 29 20:08:23 2017
Application has crashed: C++ exception
mods/WolfHUD/lua/EquipmentTweaks.lua:26: attempt to call method '_switch_fire_mode' (a nil value)
SCRIPT STACK
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                       WINHTTP  (???)     WinHttpOpenRequest                                  
                           ???  (???)     ???                                                 
                       nvspcap  (???)     QueryShadowPlayInterfaceVersionRange                
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                       nvspcap  (???)     QueryShadowPlayInterfaceVersionRange                
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                         ole32  (???)     DdeBindToObject                                     
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Sat Jul 29 20:09:19 2017
Application has crashed: C++ exception
mods/WolfHUD/lua/EquipmentTweaks.lua:26: attempt to call method '_switch_fire_mode' (a nil value)
SCRIPT STACK
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                       nvspcap  (???)     QueryShadowPlayInterfaceVersionRange                
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                         ole32  (???)     DdeBindToObject                                     
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------

Played PayDay 2 with friend and game crashes consistently when sentry is placed anywhere on the Cook Off map (outside or inside the house).

**Comment by johnneijzen** [comment]
i think you are using stable version on wolfhud try using dev version of wolfhud

**Comment by TimLS** [comment]
You are wrong because I am using the latest version from github. If I was using the stable version, I would have posted it there.

**Comment by johnneijzen** [comment]
Weird based on code in EquipmentTweaks.lua on line 26 it should work fine maybe BLT is corrupt

 line 26 is `self:_set_fire_mode(true)` that is calling sentrygunweapon.lua you can check it [here](https://github.com/DrNewbie/payday-2-lua/blob/master/lib/units/weapons/sentrygunweapon.lua) basically it set `self._use_armor_piercing = true `

but i am gonna test it tomorrow if i get same problems

**Comment by johnneijzen** [comment]
![20170802013148_1](https://user-images.githubusercontent.com/1343960/28838913-72331fa2-7724-11e7-9544-669220335a74.jpg)
Seem work fine i have tested Cook off and safehouse raid and lab rat no crashes or errors.

Also i have upload video how i have install BLT and wolfhud here this may help:
https://www.youtube.com/watch?v=eow7_NMQD8I

**Comment by TimLS** [comment]
Thanks, I reinstalled BLT and WolfHUD.

**Comment by johnneijzen** [comment]
This issue can be closed :)
