### ISSUE TITLE
Crash when enter and exit truck on Aftershock contract

### ISSUE THREAD

**Issue by Moonelfz** [Kamikaze94/WolfHUD#403]
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/1190621/crashlog.txt)

**Comment by johnneijzen** [comment]
seem that BLT is corrupted try to reinstall it use [new BLT](https://github.com/JamesWilko/Payday-2-BLT/releases) because BLT from [here](https://paydaymods.com/download) is not working

Here is video how to do it:
https://www.youtube.com/watch?v=eow7_NMQD8I&t=70s
