### ISSUE TITLE
Game crashes in goat simulator  day 2

### ISSUE THREAD

**Issue by reikasha** [Kamikaze94/WolfHUD#404]
----------------------------------------------------------------------

Tue Aug 01 17:19:54 2017

Application has crashed: C++ exception
[File] Cannot read from file "C:\Program Files\Steam\steamapps\common\PAYDAY 2\assets\mod_overrides\WolfHUD_Textures\guis/textures/contact_vlad.texture" => error code 998: Invalid access to memory location. (d:\jenkins\shared-workspace\diesel\engine\dieselx\dieselx\blobs\../utility/Archive.cpp:2487)

SCRIPT_STACK

_set_image() @mods/WolfHUD/lua/DrivingHUD.lua:510
init() @mods/WolfHUD/lua/DrivingHUD.lua:486
new() core/lib/utils/coreclass.lua:35
init() @mods/WolfHUD/lua/DrivingHUD.lua:75
new() core/lib/utils/coreclass.lua:35
create_driving_hud() @mods/WolfHUD/lua/DrivingHUD.lua:945
_setup_player_info_hud_pd2() @mods/WolfHUD/lua/DrivingHUD.lua:940
setup() 4
setup() lib/managers/hudmanager.lua:259
load_hud() lib/managers/hudmanager.lua:246
init_finalize() lib/managers/hudmanager.lua:159
init_finalize() lib/setups/gamesetup.lua:617
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:422
() =(tail call):-1

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                  _set_image()  @mods/WolfHUD/lua/DrivingHUD.lua:510                
                        init()  @mods/WolfHUD/lua/DrivingHUD.lua:486                
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  @mods/WolfHUD/lua/DrivingHUD.lua:75                 
                         new()  core/lib/utils/coreclass.lua:35                     
          create_driving_hud()  @mods/WolfHUD/lua/DrivingHUD.lua:945                
  _setup_player_info_hud_pd2()  @mods/WolfHUD/lua/DrivingHUD.lua:940                
                       setup()  4                                                   
                       setup()  lib/managers/hudmanager.lua:259                     
                    load_hud()  lib/managers/hudmanager.lua:246                     
               init_finalize()  lib/managers/hudmanager.lua:159                     
               init_finalize()  lib/setups/gamesetup.lua:617                        
               init_finalize()  lib/setups/networkgamesetup.lua:15                  
                                core/lib/setups/coresetup.lua:422                   
                            ()  =(tail                                              
                      call):-1  
-------------------------------

System information:
	Application version : 1.74.281.
	CPU : AMD E-350 Processor (1 core); SSE; SSE2; SSE3; SSSE3
	DirectX : 10.0 
	GPU : AMD Radeon HD 6310 Graphics / aticfx32.dll[8.17.10.1433]
	Language : @ID4176958b9b2622ce@
	Memory :     2301MB 440KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (32 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

----------------------------------------------------------------------

Tue Aug 01 17:49:48 2017

Application has crashed: C++ exception
Could not load texture because IDirect3D9::CreateTexture call failed.
Direct3D could not allocate sufficient memory to complete the call.

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlInitializeCriticalSectionAndSpinCount            
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlInitializeExceptionChain                         
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Renderer

-------------------------------

System information:
	Application version : 1.74.281.
	CPU : AMD E-350 Processor (1 core); SSE; SSE2; SSE3; SSSE3
	DirectX : 10.0 
	GPU : AMD Radeon HD 6310 Graphics / aticfx32.dll[8.17.10.1433]
	Language : @ID4176958b9b2622ce@
	Memory :     2301MB 440KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (32 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by johnneijzen** [comment]
go to C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\assets\mod_overrides and delete WolfHUD_Textures and Federal Inventory then you open payday 2 aging after deleting those two it will ask if you want update wolfHUD texture and Federal Inventory then click yes.

if still same problem still happens then try reinstall BLT and wolfhud
here is video i made to show you how to do it:
https://www.youtube.com/watch?v=eow7_NMQD8I&t=70s
