### ISSUE TITLE
Allow host to force start the game

### ISSUE THREAD

**Issue by Nothing4You** [Kamikaze94/WolfHUD#405]
Hey there,
sometimes the game gets stuck in a lobby for a while even though all players are ready, maybe related to someone crashing while joining or something like that.
How about allowing the host to force start the game?

It's already been implemented in [this snippet](https://www.unknowncheats.me/forum/payday-2/117604-skip-endscreen-and-force-ready.html) which appearently comes from HoxHud.

**Comment by hexagon62** [comment]
That's already in WolfHUD.

**Comment by Nothing4You** [comment]
How do I use it? Just toggling ready 5 times?
There doesn't seem to be any documentation about it in the readme nor any configuration for it.

**Comment by Nothing4You** [comment]
Alright a popup appears after 3x hitting ready asking me whether I want to force it. Documentation in the readme for that would be nice though.
