### ISSUE TITLE
Crash due to BurstFire.lua

### ISSUE THREAD

**Issue by hexagon62** [Kamikaze94/WolfHUD#406]
This was in a multiplayer game on Rats Day 1 on One Down, done with the latest version of WolfHUD I could download from here. I shot a normal ZEAL in the head (don't remember if it killed them) and the game immediately crashed afterwards. Not sure if that was the cause. I was using a Cavity 9mm (which I believe only supports single-fire).

Crash log:

```
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
_get_unit_intimidation_action()  lib/units/beings/player/states/playerstandard.lua:3521  
    _start_action_intimidate()  lib/units/beings/player/states/playerstandard.lua:3608  
                                lib/units/beings/player/states/playerstandard.lua:2244  
                            ()  =(tail                                              
                      call):-1  _update_check_actions()                             
lib/units/beings/player/states/playerstandard.lua:909  update_original()                                   
lib/units/beings/player/states/playerstandard.lua:413  update()                                            
@mods/WolfHUD/lua/BurstFire.lua:196                                                      
lib/units/beings/player/playermovement.lua:275  ()                                                  
                        =(tail  call):-1                                            
                            ()  =(tail                                              
                                call):-1                                            

-------------------------------

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 1080 / nvd3dum.dll[22.21.13.8165]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     32699MB 76KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))
```

**Comment by TimLS** [comment]
I got the same error with this BurstFirst.lua playing Diamond Store 1D (friend hosted it with no mod PayDay 2) when we finished mission and was standing in the square.

**Comment by johnneijzen** [comment]
interesting i try to backtrack code but i cant fully figout 
BurstFire.lua line 196 is calling update_original(self, t, ...) unless its counting comments.
but in [playerstandard.lua](https://github.com/DrNewbie/payday-2-lua/blob/master/lib/units/beings/player/playermovement.lua) there is no PlayerStandard.update unless im looking wrong

and looking at script stack where last thing that is call was [playermovement.lua:275](https://github.com/DrNewbie/payday-2-lua/blob/master/lib/units/beings/player/playermovement.lua)
`function PlayerMovement:play_redirect(redirect_name, at_time)
	local result = self._unit:play_redirect(Idstring(redirect_name), at_time)
	return result ~= Idstring("") and result
end`

**Comment by Slunkee** [comment]
Same here
