### ISSUE TITLE
Camera Loop timer stuck at [0.0] sec after reloop at the end till fully pass.

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#41]
When I reloop camera at 0.0 sec, timer continue showing 0.0 sec until timer disappear.
![218620_20160823115030_1](https://cloud.githubusercontent.com/assets/19766576/17889624/c945e292-6939-11e6-9f9f-dacbcadf8927.png)

**Comment by Kamikaze94** [comment]
Thanks for reporting!
