### ISSUE TITLE
Crash with swan song

### ISSUE THREAD

**Issue by slendypendy** [Kamikaze94/WolfHUD#411]
I noticed that everytime swan song ends, the game crashes. Tested in online 3 times and offline once
[2017_08_06_log.txt](https://github.com/Kamikaze94/WolfHUD/files/1202899/2017_08_06_log.txt)

**Comment by johnneijzen** [comment]
did you use dev version of wolfhud because stable version of wolfhud will crash with swan song like #163 please reinstall dev version wolfhud and update BLT 
here is version on how to do it : https://www.youtube.com/watch?v=eow7_NMQD8I

**Comment by HugoZink** [comment]
Maybe it would help if the newest dev version was pushed to the BLT auto updater. The "stable" version is incredibly crashy and I'm tired of these bug reports filling up the Github issues and the steam discussions.
