### ISSUE TITLE
Game randonly crashes and closes, happens VERY often [FIXED]

### ISSUE THREAD

**Issue by BREEZY1994** [Kamikaze94/WolfHUD#412]
----------------------------------------------------------------------

Sun Aug 06 03:05:26 2017

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
             _update_gfx_lod()  lib/managers/enemymanager.lua:113                   
                      update()  lib/managers/enemymanager.lua:47                    
                                lib/setups/gamesetup.lua:655                        
                            ()  =(tail                                              
                      call):-1  update()                                            
lib/setups/networkgamesetup.lua:21                                                      
core/lib/setups/coresetup.lua:537  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

System information:
	Application version : 1.75.288.
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980 Ti / nvldumd.dll[22.21.13.8494]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16324MB 368KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : A-Volute (Headphones (ASUS XONAR PHOEBUS))

----------------------------------------------------------------------

Mon Aug 07 22:40:27 2017

Application has crashed: C++ exception
[string "lib/units/equipment/ecm_jammer/ecmjammerbas..."]:130: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.75.288.
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980 Ti / nvldumd.dll[22.21.13.8494]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16324MB 368KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : A-Volute (Headphones (ASUS XONAR PHOEBUS))

----------------------------------------------------------------------

Tue Aug 08 00:34:37 2017

Application has crashed: C++ exception
[string "core/lib/managers/corelocalizationmanager.l..."]:161: attempt to concatenate local 'string_id' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlInterlockedPushEntrySList                        
                         ntdll  (???)     RtlGetCurrentServiceSessionId                       

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.75.288.
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980 Ti / nvldumd.dll[22.21.13.8494]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16324MB 368KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : A-Volute (Headphones (ASUS XONAR PHOEBUS))

----------------------------------------------------------------------

Tue Aug 08 00:46:58 2017

Application has crashed: C++ exception
[string "lib/managers/menu/crimespreemissionsmenucom..."]:776: attempt to compare nil with number

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlInterlockedPushEntrySList                        
                         ntdll  (???)     RtlGetCurrentServiceSessionId                       

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.75.288.
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980 Ti / nvldumd.dll[22.21.13.8494]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16324MB 368KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : A-Volute (Headphones (ASUS XONAR PHOEBUS))

----------------------------------------------------------------------

Tue Aug 08 00:57:29 2017

Application has crashed: C++ exception
[string "core/lib/managers/corelocalizationmanager.l..."]:161: attempt to concatenate local 'string_id' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.75.288.
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980 Ti / nvldumd.dll[22.21.13.8494]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16324MB 368KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : A-Volute (Headphones (ASUS XONAR PHOEBUS))

**Comment by johnneijzen** [comment]
of looks BLT is corrupted here is video how reinstall BLT and Wolfhud https://www.youtube.com/watch?v=eow7_NMQD8I you also need x86 2013 C++ Runtime but you probably have that already otherwise payday 2 would just crash anyway but just in in case here is link for that: http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x86.exe

**Comment by BREEZY1994** [comment]
I will try this, I had BLT and WolfHUD from the other website. Hopefully it wont crash anymore now.

Thanks for ur reply
