### ISSUE TITLE
Crash chance when someone drops a sentry in AP mode

### ISSUE THREAD

**Issue by Kannkor** [Kamikaze94/WolfHUD#42]
---

Sun Aug 21 21:24:17 2016

Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:1503: attempt to index local 'unit' (a nil value)

SCRIPT STACK

---

Callstack:

```
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
                       ???  (???)     ???                                                 
```

---

Current thread: Main

---

System information:
    Application version : 1.54.10
    CPU : Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
    DirectX : 10.0 
    GPU : NVIDIA GeForce GTX 960 / nvd3dum.dll[10.18.13.5582]
    Language : @ID94cca2fdaccfc2cd@
    Memory :     432666    0MB
    OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by Kamikaze94** [comment]
Okay, can you tell me, why you think its a WolfHUD bug?
As far as I can tell, the line mentioned in your crashlog is you receiving the sync of another palyer going down, missing the unit parameter. It doesn't seem affiliated to Sentries at all, AP mode or not.

I just double checked, every function WolfHUD hooks into in that class (none of them is the "arrested"-function) to pass over all parameters to the original function.
Never experienced the problem you describe, nor heard of anyone having those...

Are you on the lastbullet/paydaymods version or the dev build of WolfHUD and which other mos do you use?

**Comment by Kannkor** [comment]
I responded to this via email and not sure if you got it. Regardless it should be posted here for the record.

I play with a group of friends and one of them uses sentries.
I used to use HoxHUD back in the day, then I haven’t played in a year or 2, so I got wolfhud. Everything was fine.

I then told my friends about wolfhud, and they got it. I started crashing.

I googled and came across this thread: http://steamcommunity.com/app/218620/discussions/14/365172547937938720/
More specifically this post: http://steamcommunity.com/app/218620/discussions/14/365172547937938720/#c359543951710830528
“If I had to take a guess at what the problem might be, and this is really just a sort of blind guess, but I feel it may have something to do with an option of WolfHud allowing AP sentries to be placed right away instead of having to place a sentry then switch it to AP. I'm just basing this off a crash file trying to assign a null value to an NPC, which I assume the sentry to be.”

We started testing….
We got into a game, where we both had wolfhud on, and he started laying sentries. After a while, bam I crashed. I joined the game again, he kept doing it, bam I crashed.
Had him disable his wolfhud, and tried again (so they were placed then switched to AP mode after) and I haven’t crashed since.

Worth mentioning, before we did the tests above, I thought it may be related to old hoxhud. So I deleted my entire /payday 2/ folder, and redownloaded it via steam. Then verified it. All was good.
I then installed this: 
Payday 2 BLT: http://paydaymods.com/download/
Then installed this:
http://paydaymods.com/mods/298/wolfhud
Loaded the game, and did the updates via the automatic updater in game.

I assume I can check some where the version, but I did this a few hours before I submitted the bug (yesterday?), and downloaded directly from those links I pasted.

No other mods.

If there’s any other information I can help with/gather for you let me know. Or if you have any debug versions.

**Comment by Kamikaze94** [comment]
Hmm, thanks for the detailed report of your experience.
From what you wrote, and the crash log, I'd guess the problem is, the firemode switch can get executed too fast, so that the client hasn't fully created the sentry before.
I added a small dely to that + a check, if you can actualy switch the firemode, before the mod does.
And an actual cancel for the delayed callback, since we don't want it to get called, if the unit gets removed for some reason...  :P

If you don't mind, please try the GitHUB version and see if that crash still persists. 
(If you got time for that, otherwise, I'll look if I can convince someone to help me tomorrow, its quite late now :)

(Also, might be interesting how good your ping to your friend is, when that happens. So if it only happens when one of you is expereincing a lag spike or something...)

**Comment by Kannkor** [comment]
Myself and the guy with sentries just downloaded directly from GitHUB, then ran 1 map, and he spammed sentries. Was picking them up and putting them down a LOT.

I realize 1 map doesn't say it's fixed, but we never made it through 1 map previously. It's just all the time we had.

Really appreciate the quick work on resolving this!

**Comment by Kannkor** [comment]
Turns out this still isn't resolved.
Played last night and we did some more tests. 
If he disabled AP mode I never crashed. He turned back automatic AP mode and I crashed very shortly after (crash report below). 
He turned off the automatic AP mode and I never crashed again.

I'm on the latest stable build from the in-game patcher.

Sun Sep 04 23:02:59 2016


Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:1532: attempt to index local 'unit' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.54.12
	CPU : Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 960 / nvd3dum.dll[21.21.13.7254]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     432666    0MB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by Kamikaze94** [comment]
For the Sentry stuff, there is currently no difference in the release or dev version....
Maybe a difficult question, but do you think it happened less likely, or with no difference?
I'll do another update now, that does every possible check that comes into my mind, so checking for the interaction to be presen, making sure, you could interact yourself at the moment, etc.
If you still happen to crash then, it's either a bug in the base game (as you could have triggered it with interactiong yourself, if you manage to get far enough away from the sentry and interact after 50ms.
As I havn't asked yet, do you or your friend have any mod installed, that affects sentries, be it BLT, mod_override, .pdmod, or anything else, that you might have forgotten about?

**Comment by Kannkor** [comment]
I feel like it happened the same amount, so no difference. 

We both only downloaded this:
Payday 2 BLT: http://paydaymods.com/download/
Then WolfHUD.
Definitely no other mods at all.
The only option in WolfHUD I've changed is the interaction time from 5s to 1s (I can't imagine this matters, but I'm pretty much as 'stock' wolfhud as you can get).
