### ISSUE TITLE
Crash when enter stats screen in heist

### ISSUE THREAD

**Issue by EdGeXeNo** [Kamikaze94/WolfHUD#423]
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/1225412/crash.txt)
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/1225413/crashlog.txt)
[2017_08_15_log.txt](https://github.com/Kamikaze94/WolfHUD/files/1225414/2017_08_15_log.txt)
Crash after press tab to open stats screen.

**Comment by Aurani** [comment]
Known issue, go to Options -> Mod Options -> WolfHUD -> Wolfhud Settings -> Tabstats Settings, disable Clock Mode, untick Use Tabstats and Numberic Loot Counter.
