### ISSUE TITLE
Game crashes : error sentrygunweapon.lua

### ISSUE THREAD

**Issue by BREEZY1994** [Kamikaze94/WolfHUD#426]
Sat Aug 19 21:07:25 2017

Application has crashed: C++ exception
[string "lib/units/weapons/sentrygunweapon.lua"]:280: attempt to index field '_muzzle_effect_table' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     RtlInterlockedPushEntrySList                        
                         ntdll  (???)     RtlGetCurrentServiceSessionId                       

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.75.297.
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 980 Ti / nvldumd.dll[22.21.13.8494]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16324MB 368KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : A-Volute (Headphones (ASUS XONAR PHOEBUS))

**Comment by BREEZY1994** [comment]
Seems to only happen on COOK OFF

**Comment by johnneijzen** [comment]
hmm try to reinstall BLT and WolfHud because it seems like broken BLT i had someone similar problem #401
Here is video on how to do that: 
https://www.youtube.com/watch?v=eow7_NMQD8I
