### ISSUE TITLE
Crash on: Classics: Counterfeit

### ISSUE THREAD

**Issue by Kannkor** [Kamikaze94/WolfHUD#43]
When you place the printer plates it crashes.

Tue Aug 23 21:46:25 2016

Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:3363: attempt to call method 'apply_item_pickup' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.54.10
	CPU : Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 960 / nvd3dum.dll[21.21.13.7254]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     432666    0MB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by Kamikaze94** [comment]
With the latest update, Overkill added some check, if the 'apply_item_pickup'-function exists.
Looks like this was an base game error.
