### ISSUE TITLE
Client crashing when i try to place turret

### ISSUE THREAD

**Issue by SWATOPLUS** [Kamikaze94/WolfHUD#432]
I place turret and after 3-5 second my client crashes.

**Comment by SWATOPLUS** [comment]
Application has crashed: C++ exception
mods/WolfHUD/lua/EquipmentTweaks.lua:26: attempt to call method '_switch_fire_mode' (a nil value)

**Comment by johnneijzen** [comment]
same issue as #401 
BLT is corrupt here is video on install BLT and wolfhud here:
https://www.youtube.com/watch?v=eow7_NMQD8I

**Comment by SWATOPLUS** [comment]
Autoupdaters doesnt work. Latest github version works.

Btw, WolfHUD works perfectly with PocoHud3. I recommend to use it together.
