### ISSUE TITLE
Wolf master hud + poco hud Subtitle size fix please. -_-

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#44]
Wolf master hud + poco hud
Subtitle size fix please. -_-

wolfhud-master v2.30
![20160827043202_1](https://cloud.githubusercontent.com/assets/21234977/18019527/79a370a2-6c17-11e6-9093-27851ae236b4.jpg)
![20160827043946_1](https://cloud.githubusercontent.com/assets/21234977/18019606/de8fdba4-6c17-11e6-9f9c-f95b992a0152.jpg)

wolfhud v2.00
![20160827053639_1](https://cloud.githubusercontent.com/assets/21234977/18019715/598a3822-6c18-11e6-860b-38a6db80038c.jpg)

pocohud option...
![20160827043347_1](https://cloud.githubusercontent.com/assets/21234977/18019605/dbaa82a4-6c17-11e6-9877-cd250345c4e4.jpg)

**Comment by Kamikaze94** [comment]
Yeah, I added a line, in which I could potentially resize the subtitle font size, as I planned to add an option for that.
That line just set the font size to the saved one it should already have, as I was just playing around with that when moving the subtitles.
Seems like Poco resizes the actual text area, but doesn't change the save of the font size there....
Romoved that for now, until I get around actually doing something with it or removing it, ^^

So, should be working now....

**Comment by hud8614** [comment]
![20160828030754_1](https://cloud.githubusercontent.com/assets/21234977/18029852/ef63540c-6cde-11e6-8da1-f270dc4090b2.jpg)
![20160828043506_1](https://cloud.githubusercontent.com/assets/21234977/18029859/1e052664-6cdf-11e6-8a0e-3c08b7bffe76.jpg)

again.... T_T

**Comment by Kamikaze94** [comment]
Urgh?
Thats strange.
Just duoble checked, the line "--self:set_font(...)" starts with '--', so it doesn't get executed.
I don't modify the size there anywhere else, afaik.
I'll download Poco later, and try to figure something out...  :)

**Comment by hud8614** [comment]
![20160828181536_1](https://cloud.githubusercontent.com/assets/21234977/18033378/d4781be4-6d5d-11e6-8322-71ade39d267b.jpg)
Mission.....
![20160828202012_1](https://cloud.githubusercontent.com/assets/21234977/18033379/d49d01ac-6d5d-11e6-9c73-b7a7da02f006.jpg)
Safe House....

**Comment by Kamikaze94** [comment]
I found the problem.
I kinda indirectly reset the font size, by calling the complete "_on_resolution_changed"-function.
(Why does poco use an own field to store the font size, not overwrite the games one, q.q)
Anyways, got that changed now, and it seems to work.
If you notice it to appear anywhere else, please let me know. :)

**Comment by Tatsugi** [comment]
One offtopic question: when you begin to add a build number in version in Devs branch, like "WolfHUD v2.30-7" or "... v2.30.10" etc.? I like to see a new number of version each update. ^_^
