### ISSUE TITLE
Crash playing the game for a few seconds or sometimes in loadout

### ISSUE THREAD

**Issue by MaxiTorres** [Kamikaze94/WolfHUD#440]
BLT Log

> 01:09:50 AM Log:  (..\src\InitiateState.cpp:658) Initiating Hook
> 01:09:50 AM Lua: [BLT] Setup...
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTLogs
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTModManager
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTPersistScripts
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTLocalization
> 01:09:50 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
> 01:09:50 AM Lua: [BLT] Loading mods for state: table: 0x228c3900
> 01:09:50 AM Lua: [BLT] Loading mod: AFSF2
> 01:09:50 AM Lua: [BLT] Loading mod: base
> 01:09:50 AM Lua: [BLT] Loading mod: SteamInventoryInLobby
> 01:09:50 AM Lua: [BLT] Loading mod: WolfHUD
> 01:09:50 AM Lua: [BLT] Loading mod: _temp
> 01:09:50 AM Lua: [BLT] Could not read or find mod.txt in _temp
> 01:09:50 AM Lua: [BLT] Setting up mod: 	base
> 01:09:50 AM Lua: [BLT] Setting up mod: 	AFSF2
> 01:09:50 AM Lua: [BLT] Setting up mod: 	WolfHUD
> 01:09:50 AM Lua: [BLT] Setting up mod: 	SteamInventoryInLobby
> 01:09:50 AM Log:  (..\src\InitiateState.cpp:658) Initiating Hook
> 01:09:50 AM Lua: [BLT] Setup...
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTLogs
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTModManager
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTPersistScripts
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTLocalization
> 01:09:50 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
> 01:09:50 AM Lua: [BLT] Loading mods for state: table: 0x227c2b00
> 01:09:50 AM Lua: [BLT] Loading mod: AFSF2
> 01:09:50 AM Lua: [BLT] Loading mod: base
> 01:09:50 AM Lua: [BLT] Loading mod: SteamInventoryInLobby
> 01:09:50 AM Lua: [BLT] Loading mod: WolfHUD
> 01:09:50 AM Lua: [BLT] Loading mod: _temp
> 01:09:50 AM Lua: [BLT] Could not read or find mod.txt in _temp
> 01:09:50 AM Lua: [BLT] Setting up mod: 	base
> 01:09:50 AM Lua: [BLT] Setting up mod: 	AFSF2
> 01:09:50 AM Lua: [BLT] Setting up mod: 	WolfHUD
> 01:09:50 AM Lua: [BLT] Setting up mod: 	SteamInventoryInLobby
> 01:09:50 AM Log:  (..\src\InitiateState.cpp:658) Initiating Hook
> 01:09:50 AM Lua: [BLT] Setup...
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTLogs
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTModManager
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTPersistScripts
> 01:09:50 AM Lua: [BLT] Loading module: 	BLTLocalization
> 01:09:50 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
> 01:09:50 AM Lua: [BLT] Loading mods for state: table: 0x19b829a0
> 01:09:50 AM Lua: [BLT] Loading mod: AFSF2
> 01:09:50 AM Lua: [BLT] Loading mod: base
> 01:09:50 AM Lua: [BLT] Loading mod: SteamInventoryInLobby
> 01:09:50 AM Lua: [BLT] Loading mod: WolfHUD
> 01:09:50 AM Lua: [BLT] Loading mod: _temp
> 01:09:50 AM Lua: [BLT] Could not read or find mod.txt in _temp
> 01:09:50 AM Lua: [BLT] Setting up mod: 	base
> 01:09:50 AM Lua: [BLT] Setting up mod: 	AFSF2
> 01:09:50 AM Lua: [BLT] Setting up mod: 	WolfHUD
> 01:09:50 AM Lua: [BLT] Setting up mod: 	SteamInventoryInLobby
> 01:09:52 AM Lua: [Menus][Warning] Parent menu for child 'wolfhud_main_options_menu' is null, ignoring...    1
> 01:09:52 AM Lua: [Menus][Warning] Parent menu for child 'steam_inventory' is null, ignoring...    1
> 01:09:52 AM Lua: [Menus][Warning] Parent menu for child 'steam_inventory' is null, ignoring...    1
> 01:09:56 AM Lua: [1] SISTEMA: Pedrinho_Killer se está uniendo.
> 01:09:56 AM Lua: [1] SISTEMA: darktemplar2323 se está uniendo.
> 01:10:20 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED

Crash log

> Fri Sep 01 01:10:19 2017
> 
> 
> Application has crashed: C++ exception
> [string "lib/managers/missionmanager.lua"]:288: attempt to call method 'client_on_executed' (a nil value)
> 
> 
> 
> SCRIPT STACK
> 
> lib/network/handlers/unitnetworkhandler.lua:558
> 
> 
> -------------------------------
> 
> Callstack:
> 
>          payday2_win32_release  (???)     ???                                                 
>          payday2_win32_release  (???)     ???                                                 
> 
> 
> -------------------------------
> 
> Current thread: Main
> 
> -------------------------------
> 
> System information:
> 	Application version : 1.76.315.
> 	CPU : AMD FX(tm)-6300 Six-Core Processor (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
> 	DirectX : 12.0 
> 	GPU : AMD Radeon HD 7700 Series / aticfx32.dll[21.19.407.0]
> 	Language : @ID4176958b9b2622ce@
> 	Memory :     8189MB 564KB
> 	OS : 6.2.9200 () 0x100-0x1 (64 bits)
> 	Physics : threaded
> 	Renderer : DX9 threaded
> 	Sound : Microsoft (Altavoces (Dispositivo de High Definition Audio))

**Comment by todka** [comment]
Same crash.

**Comment by PhantomGamers** [comment]
This is the same as issue #438, I posted a temporary workaround in the comments there.
