### ISSUE TITLE
Crash when Joining lobby

### ISSUE THREAD

**Issue by ProvoloneCheese** [Kamikaze94/WolfHUD#441]
Consistently getting this issue when I am not the host. My friend who has an identical set of mods (wolf hud) also gets the same issue. Not sure if it is related to WolfHud or BLT so I will post to both.

12:15:53 AM FATAL ERROR:  (..\src\InitiateState.cpp:408) mods/WolfHUD-master/lua/GameInfoManager.lua:3802: attempt to index a nil value
stack traceback:
        mods/WolfHUD-master/lua/GameInfoManager.lua:3802: in main chunk
        [C]: in function 'dofile'
        mods/WolfHUD-master/Core.lua:1437: in main chunk
        [C]: in function 'dofile'
        mods/base/base.lua:120: in function 'RunHookFile'
        mods/base/base.lua:113: in function 'RunHookTable'
        mods/base/base.lua:142: in function 'require'
        [string "lib/player_actions/playeraction.lua"]:10: in main chunk
        [C]: in function 'require'
        mods/base/base.lua:141: in function 'require'
        [string "lib/setups/setup.lua"]:35: in main chunk
        [C]: in function 'require'
        mods/base/base.lua:141: in function 'require'
        [string "lib/setups/menusetup.lua"]:1: in main chunk
        [C]: in function 'require'
        mods/base/base.lua:141: in function 'require'
        [string "lib/entry.lua"]:13: in main chunk
        [C]: in function 'require'
        mods/base/base.lua:141: in function 'require'
        [string "core/lib/coreentry.lua"]:19: in main chunk
Lua State: 0463E240

**Comment by PhantomGamers** [comment]
This should be fixed already, are you using the latest version?

**Comment by ProvoloneCheese** [comment]
Ok so far I have 49 mins in without a crash.
This version of wolfhud: https://steamcommunity.com/linkfilter/?url=https://cdn.discordapp.com/attachments/198281587404570624/353042120312881153/WolfHUD.zip

Download BLT version 2.0 AND 1.08 install 2.0 normally but delete and replace the base folder with the one from 1.08

BLT Downloads: https://github.com/JamesWilko/Payday-2-BLT/releases

Thanks for the help guys I did not come up with this fix; I got info for it from this thread... http://steamcommunity.com/app/218620/discussions/8/1474221865186057356/
Hope this fixes it for you guys to.
