### ISSUE TITLE
Crashing on game loading

### ISSUE THREAD

**Issue by Skippady** [Kamikaze94/WolfHUD#443]
Iv been trying different options different trouble shoots and no matter what i do i cant find a fix

When ever i load the game with WolfHUD mod in the BLT mod folder then try loading the game the second i get to the "press any key" screen it instantly crashes and closes on me, iv done testing if it was other mods removing them adding them one by one and it all seems to be with wolfhud, iv tried with the new version of wolfhuf with old and same issues and this is WITH AND WITHOUT the BLT 2.0 temp fix

I have also done with fresh installs of both mods and it just seems to only happen with this one any ideas how to fix this or any chance of ETA for a new working update not sure if its this mod or BLT thats having the issue on this one

01:49:52 AM Log:  (..\src\http\http.cpp:44) CURL_INITD
01:49:56 AM Log:  (..\src\InitiateState.cpp:658) Initiating Hook
01:49:59 AM Log:  (..\src\InitiateState.cpp:658) Initiating Hook
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
01:49:59 AM Lua: [Mods] Loading mods for state (table: 0x00d00440)
01:49:59 AM Lua: [Mods] Loading mod: base...
01:49:59 AM Lua: [Mods] Loading mod: WolfHUD-master...
01:49:59 AM Log:  (..\src\InitiateState.cpp:658) Initiating Hook
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
01:49:59 AM Lua: [Mods] Loading mods for state (table: 0x00d00460)
01:49:59 AM Lua: [Mods] Loading mod: base...
01:49:59 AM Lua: [Mods] Loading mod: WolfHUD-master...
01:49:59 AM Lua: [WolfHUD] ERROR: Error while loading, settings file could not be opened (mods/saves/WolfHUD_v2.json)
01:49:59 AM FATAL ERROR:  (..\src\InitiateState.cpp:408) mods/WolfHUD-master/lua/GameInfoManager.lua:3802: attempt to index a nil value
stack traceback:
	mods/WolfHUD-master/lua/GameInfoManager.lua:3802: in main chunk
	[C]: in function 'dofile'
	mods/WolfHUD-master/Core.lua:1437: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:126: in function 'call_require_hook'
	mods/base/base.lua:140: in function 'require'
	[string "lib/player_actions/playeraction.lua"]:10: in main chunk
	[C]: in function '_require_orig'
	mods/base/base.lua:139: in function 'require'
	[string "lib/setups/setup.lua"]:35: in main chunk
	[C]: in function '_require_orig'
	mods/base/base.lua:139: in function 'require'
	[string "lib/setups/menusetup.lua"]:1: in main chunk
	[C]: in function '_require_orig'
	mods/base/base.lua:139: in function 'require'
	[string "lib/entry.lua"]:13: in main chunk
	[C]: in function '_require_orig'
	mods/base/base.lua:139: in function 'require'
	[string "core/lib/coreentry.lua"]:19: in main chunk
01:49:59 AM Log:  (..\src\InitiateState.cpp:658) Initiating Hook
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
01:49:59 AM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
01:49:59 AM Lua: [Mods] Loading mods for state (table: 0x27141620)
01:49:59 AM Lua: [Mods] Loading mod: base...
01:49:59 AM Lua: [Mods] Loading mod: WolfHUD-master...
01:50:00 AM Lua: [Menus][Warning] Parent menu for child 'wolfhud_main_options_menu' is null, ignoring...    1
01:50:06 AM Log:  (..\src\InitiateState.cpp:489) Incoming HTTP Request/Request
01:50:06 AM Log:  (..\src\InitiateState.cpp:503) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt&mod[1]=payday2bltdll&mod[2]=wolfhud&mod[3]=wolfhud_textures&mod[4]=fed_inv - 1353
01:50:06 AM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
01:50:06 AM Lua: [Updates] Attempting to remove temporary hook dll...
01:50:06 AM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
01:50:08 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED

**Comment by GameEngine1** [comment]
they haven't changed a function that is used by BLT yet, you need to delete the "base" folder in your mods folder and insert, an older version of BLT's "base" folder into mods, as a temporary fix. this means however that only outdated mods can be run, without crashing and the BLT mod manager will look like the old.

(I quite fancy the new BLT mod manager, but I think it needs shortcuts (shift click to check for update aso.))

**Comment by Skippady** [comment]
Yeah iv tested all that and i have the same issue every time when wolfhud is not in my mods folder the game crashes every single time i know a few other people having this same issue, iv tried fresh installs of the old blt the new blt new blt folder with old base folder old version VERY old versions of wolfhud and its the same every single time but other mods work just fine so i don't know whats happening i listed the error the log was giving me and i cant see any other post on here having that issue similar but not the last bit of the error

01:50:06 AM Lua: [Updates] Attempting to remove temporary hook dll...
01:50:06 AM Lua: [Warning] Could not remove hook dll: IPHLPAPI_temp.dll: No such file or directory
