### ISSUE TITLE
Player level and spade not showing up sometimes

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#45]
This is a bit complicated to explain. When players are walking around in the environment, over their heads is floating text in the player's individual colour. Normally that would show me the player's name, infamy and level along with a spade symbol for Infamous. Sometimes, however, none of that displays and the player is left with just their name in the overhead floating text. Both level and infamy are still displayed in the actual HUD by the player's name there, it's just the floating text that this happens to.

So far, I've only ever seen it happen to players who join a heist in progress, and it fixes itself at the end of the heist day. Worse, it doesn't happen every time. Sometimes players will join and show all information, but a lot of times new joiners will come in with just a name. I don't have any consistent reproduction steps to offer, unfortunately.

**Comment by Kamikaze94** [comment]
Actually, it was intended once, to not show the Spade and Infamy/Rank in that label, because it is already part of the HUD. But I only found the "HUDManager:update_name_label_by_peer"-function, and it seems to be setted initialy elsewhere, thats probably why its that inconsistent.

Strangely, I thought I removed that call long ago, lol....  :P
Anyways, going to remove it now.
Thanks for the reminder, I guess ^^

**Comment by Malidictus** [comment]
I'm a little confused. Is the level and spade supposed to show up over players' heads or not? Can't tell which is the bugged behaviour :) In either case, I prefer having that information over people's heads as well as in the UI. If you decide to disable it, can you put in an option to leave it enabled? It's handy to see at a glance and I guess it's what I'm used to.

**Comment by Kamikaze94** [comment]
Uhm, the spade and level are there by default.

**Comment by Malidictus** [comment]
Right, I haven't played Vanilla in quite a while so I wasn't sure :) I was just confused as to what you were saying, but I'm clear now.

So far, the spade, level and infamy seem to work as intended, but I didn't test them too extensively. Thanks for having a look.

**Comment by Malidictus** [comment]
Having played with this some more, I can confirm that player level, infamy and spade seem to show up all the time for drop-in players. This seems fixed.
