### ISSUE TITLE
WolfHUD does not have the textures or Federal Inventory install?

### ISSUE THREAD

**Issue by fatcatonmars** [Kamikaze94/WolfHUD#450]
Not that I use FedInv, but aren't the WolfHUD textures required?

**Comment by BreakinBenny** [comment]
Doesn't seem like it, because I got rid of FedInv and had absolutely no problems from it.

**Comment by BreakinBenny** [comment]
But honestly, why does Federal Inventory no longer come with this? Should we update it ourselves?
