### ISSUE TITLE
im Crash! :(

### ISSUE THREAD

**Issue by NgayTraTien** [Kamikaze94/WolfHUD#452]
in the log
[Menus][Warning] Parent menu for child 'wolfhud_main_options_menu' is null, ignoring...    1

in the PAYDAY2 Crash

Application has crashed: C++ exception
mods/WolfHUD-master/Core.lua:1427: attempt to concatenate a nil value

SCRIPT STACK

_add_version_string() @mods/base/req/core/Hooks.lua:267
original() lib/managers/menu/menunodegui.lua:1771
_setup_item_rows() @mods/base/req/core/Hooks.lua:260
init() core/lib/managers/menu/reference_renderer/coremenunodegui.lua:64
init() lib/managers/menu/menunodegui.lua:68
new() core/lib/utils/coreclass.lua:35
show_node() core/lib/managers/menu/reference_renderer/coremenurenderer.lua:81
lib/managers/menu/menurenderer.lua:63
_call_callback() core/lib/managers/menu/coremenulogic.lua:329
core/lib/managers/menu/coremenulogic.lua:96
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537

**Comment by PhantomGamers** [comment]
Core.lua shouldn't even have 1427 lines, so you are not using the current version of WolfHUD
