### ISSUE TITLE
The Aleeso Heist missing from "Custom Heist Tracks"

### ISSUE THREAD

**Issue by LB-TheProtector** [Kamikaze94/WolfHUD#454]
Recently, I went to see if Aleeso was in custom heist tracks so that I could change the music, but when I tried to find it, it wasn't there. (Screenshot taken and edited approx. 10 min. before time of writing)
Unknown whether or not anyone else is not seeing Aleeso as well. Further investigation is requested, from the community, before issuse should recieve your precious time. Love the hud btw.

![aleeso missing](https://user-images.githubusercontent.com/31606466/30011707-126f2756-90ff-11e7-8459-4149ebbb2f58.png)

**Comment by RaraFolf** [comment]
This is like this as well in the stock game.

If you've actually played the Alesso heist, you would've known that it has a custom song just for the heist that can not be turned off without disabling sound all together.
