### ISSUE TITLE
Well Whenever I Launch the Game I Crash

### ISSUE THREAD

**Issue by RAMSTER678** [Kamikaze94/WolfHUD#459]
I don't even get further than the first black screen and this only began to happen when I installed the new Wolf-Hud 

Any ideas would be greatly appriciated!

CrashLog 
Fri Sep 08 18:00:02 2017

Application has crashed: C++ exception
mods/Postal Dude/BodhiDude.lua:6: attempt to index field 'localization' (a nil value)

SCRIPT STACK

_BuyAllAssets_localize_text() @mods/Mr Foster/RenameWickToFoster.lua:8
text() @mods/BuyAllAssetsV3/script.lua:10
func() @mods/WolfHUD-master/Core.lua:1327
Call() @mods/base/req/core/Hooks.lua:109
init() @mods/base/lua/LocalizationManager.lua:9
new() core/lib/utils/coreclass.lua:35
core/lib/setups/coresetup.lua:340

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlSubscribeWnfStateChangeNotification              
                         ntdll  (???)     RtlSubscribeWnfStateChangeNotification              
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
 _BuyAllAssets_localize_text()  @mods/Mr                                            
                                Foster/RenameWickToFoster.lua:8                     
                        text()                                                      
@mods/BuyAllAssetsV3/script.lua:10  func()                                              
                                @mods/WolfHUD-master/Core.lua:1327                  
                        Call()                                                      
@mods/base/req/core/Hooks.lua:109  init()                                              
                                @mods/base/lua/LocalizationManager.lua:9            
                         new()                                                      
core/lib/utils/coreclass.lua:35  core/lib/setups/coresetup.lua:340                   

![modoverrides](https://user-images.githubusercontent.com/29823204/30222780-f484e78e-94bf-11e7-9e14-fd2c93bc477d.PNG) - Mod Overrides

![modfolder](https://user-images.githubusercontent.com/29823204/30222771-ec87dbae-94bf-11e7-8cc6-04a0e266268d.PNG) - Mods

**Comment by jtmal0723** [comment]
This is not a WolfHUD related crash. As stated in the crash log you posted, it is an issue with a mod called "Postal Dude" conflicting with something. First remove this mod, rename WolfHUD-master to WolfHUD (as explained in the installation directions), launch again and see if you still have issues.
