### ISSUE TITLE
Crash after trying to press tab

### ISSUE THREAD

**Issue by papin97** [Kamikaze94/WolfHUD#46]
Everytime I press tab in-heist, the game crashes
Crash date: 28/08/2016 22.00.31

PAYDAY 2 Crash log
Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:438: attempt to index a nil value
SCRIPT STACK

**Comment by Kamikaze94** [comment]
Did you use the _release version_ from lastbullet/paydaymods or the GitHUB _dev build_?
There is Issue #29 already, where someone had the same problem.
There were several checks added, to prevent this bug, but the actual cause remained unknown.
Also, which _TabStats options_ do you use?

**Comment by papin97** [comment]
I am using _release_ version from paydaymods (never heard of dev build).
I think it's triggered after first assault complete / control phase (tried Hoxton Breakout day 1 after going into the building, assault complete, press tab, then crash).
I actually _unchecked_ Use TabStats option.

**Comment by Kamikaze94** [comment]
The dev build is the version that can be downloaded here.
(Click on Code in the top of this site, and you see the green 'Clone or download'-button.)
Actually I added a few more checks for the settings instant apply, in caseyou have TabStats disabled now, as that could have caused errors previously.
If you could test if your problem still persists with that version, that would help me a lot, as I'm planning to push that as an update not to far away.
And as always: Thanks for reporting :)
