### ISSUE TITLE
game crashed during playing

### ISSUE THREAD

**Issue by repoman728** [Kamikaze94/WolfHUD#460]
Payday 2 crashed during plaing
here is crashlog

Fri Sep 08 20:59:34 2017

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
              spawn_original()  lib/units/equipment/sentry_gun/sentrygunbase.lua:113  
                           o()  @mods/WolfHUD-master/lua/GameInfoManager.lua:2558   
                    do_spawn()  trainer/tools/origbackuper.lua:143                  
                        clbk()  trainer/experimental/stealth_v2.lua:103             
                                trainer/tools/pubinfloopv2.lua:176                  
                       pcall()                                                      
                          =[C]  trainer/tools/pubinfloopv2.lua:143                  

-------------------------------

System information:
	Application version : 1.76.327.
	CPU : Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 870M / nvldumd.dll[22.21.13.8541]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16267MB 32KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Intel(R) Corporation (LCD TV (Audio dla wyświetlaczy Intel(R)))
any ideas 
thanks 
Reg

**Comment by MEXAHOTABOP** [comment]
seems like problem in other mod what you used 
try disable em

**Comment by repoman728** [comment]
Hi it is still crashing I had to remove it to run the game .
any progress with new version
reg

2017-12-09 16:55 GMT+01:00 stale[bot] <notifications@github.com>:

**Comment by repoman728** [comment]
I have tried already  and it coming back to wolfhud. I really like that mod.
no problem I wait
Reg

2017-12-10 8:42 GMT+01:00 stale[bot] <notifications@github.com>:

**Comment by repoman728** [comment]
I have tried again and that came out

Sun Dec 10 10:37:18 2017


Application has crashed: C++ exception
[string "core/lib/managers/mission/coremissionscriptel..."]:113: attempt to
index a nil value



SCRIPT STACK

on_executed() lib/managers/mission/missionscriptelement.lua:18
_on_script_activated() core/lib/managers/mission/coremissionmanager.lua:514
activate() core/lib/managers/mission/coremissionmanager.lua:505
activate() lib/managers/missionmanager.lua:412
activate_script() core/lib/managers/mission/coremissionmanager.lua:154
activate_script() lib/managers/missionmanager.lua:283
_activate_mission() core/lib/managers/mission/coremissionmanager.lua:137
parse() core/lib/managers/mission/coremissionmanager.lua:84
init_game() lib/setups/gamesetup.lua:598
core/lib/setups/coresetup.lua:402


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???

         payday2_win32_release  (???)     zip_get_name

         payday2_win32_release  (???)     zip_get_name



-------------------------------

Current thread: Main

-------------------------------

System information:
    Application version : 1.84.463.
    CPU : Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (2 cores); SSE; SSE2;
SSE3; SSSE3; SSE4.1; SSE4.2
    DirectX : 12.0
    GPU : NVIDIA GeForce GTX 870M / nvldumd.dll[23.21.13.8859]
    Language : english
    Memory :     16267MB 32KB
    OS : 6.2.9200 () 0x100-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : Intel(R) Corporation (LCD TV (Audio dla wyświetlaczy Intel(R)))

reg


2017-12-10 8:46 GMT+01:00 James White <repoman728@gmail.com>:
