### ISSUE TITLE
Remember Gadget State Is In Base Game Now

### ISSUE THREAD

**Issue by NIKITAzed** [Kamikaze94/WolfHUD#463]
There is absolutely no need to have it as a mod, it exists in the base game, for me it just shows 1 laser instead of 2 when switching to akimbo weapons with wolfhud and there is no where to disable remember gadget state to fix it.
https://www.youtube.com/watch?v=r70IuQen-HU 
https://i.imgur.com/GiQ7VRW.jpg

as a P.S. The mission objective UI is different with the WolfHud, and I can't find where to turn it off as well

**Comment by Kamikaze94** [comment]
Removed the gadget state save related hooks in commit 10e6df719fd00536654ab82339f20764acaaf9d5.

_Had them removed when they added this function to the game at first, but back then it always reset, when steering in a vehicle. Thats why I readded it back then... :)_
