### ISSUE TITLE
Italian Localization

### ISSUE THREAD

**Issue by AleCraftNapoli** [Kamikaze94/WolfHUD#466]
Hi,
I would like to do the Italian localization of this mod, if I can please answer this.
Thanks
Alessio

**Comment by MEXAHOTABOP** [comment]
feel free to contribute

as far as i know your pull request can be rejected because:
1) you are not author and dont have permission from author of commited code
2) your commit breaks entire mod 
3) your commit was made for old revision and cannot be merged
