### ISSUE TITLE
Preplanning not saving plans

### ISSUE THREAD

**Issue by talmanau** [Kamikaze94/WolfHUD#469]
Preplanning is not saving plans. I was able to fix this by creating the directory /Preplanned in the /Payday2/mods/saves

**Comment by Srki94** [comment]
Confirming issue and fix.

**To reproduce the issue:** 
The mission planning phase
Enter the preplanning 
Create some modifications to the plan
Save plan -> Message that plan was saved successfully appears
Start the heist
Restart the heist
Enter Preplanning
Load plan -> There is no plan

**The fix from the first post works:** 
Navigate to PAYDAY2/mods/saves/
Create folder named "Preplanned"

**Comment by MrSkittlesROTR** [comment]
that sort of works.
it creates the json file for the preplan however the json is blank, so no preplan data is saved.
