### ISSUE TITLE
Can't get Wolfhud to work

### ISSUE THREAD

**Issue by ALE854** [Kamikaze94/WolfHUD#470]
Need some help when installning Wolfhud. I Downloaded the latest version Payday-2-BLT-Lua-master from here but the zipped folder didn't contain any IPHLPAPI.dll so I downloaded BLT_release_r7_r18 instead and put the WolfHUD-master in the mod folder but I can't get it to work. The game runs perfectly but it seems like no mods or BLT are installed. Would someone please help me with this. Got bad hands and not having to press a key all the time when picking a lock is God sent for me.

**Comment by kaizoku-kuma** [comment]
https://github.com/JamesWilko/Payday-2-BLT/releases

**Comment by ALE854** [comment]
That's the one I used and installed but it doesn't show up in my game?

**Comment by ALE854** [comment]
Do I leave the IPHLPAPI.dll in the BLT_release_r7_r18 folder together with the mods folder or do I place it in the root folder?

**Comment by kaizoku-kuma** [comment]
extract everything in "..\Steam\steamapps\common\PAYDAY 2"
that's all you need to do

**Comment by ALE854** [comment]
I have but it doesn't work. Is BLT_release_r7_r18 compatible with  WolfHUD-master? Do you know why there is no IPHLPAPI.dll  in Payday-2-BLT-Lua-master

**Comment by kaizoku-kuma** [comment]
use the link i provided, there is a IPHLPAPI.dll ..

**Comment by ALE854** [comment]
Finally got it to work. Thanks so much for your help:)
