### ISSUE TITLE
Settings?

### ISSUE THREAD

**Issue by mrpepsi** [Kamikaze94/WolfHUD#471]
Since the latest update me and some of my friends cant seem to find the options for wolfhud in the mod options, for me it wasnt such a big deal till now because i had set all the settings exactly how i wanted them, but now i got a new monitor and everything is bigger and i wanted to change them :/
(i have the latest stable version of blt and i have a couple of other mods but none of them conflicts with wolfhud)

**Comment by jtmal0723** [comment]
Have you updated your WolfHUD completely lately? It should have restored itself in the options menu after you have done so.
