### ISSUE TITLE
Berserker buff displays in HUDList even when disabled

### ISSUE THREAD

**Issue by killrhythm09** [Kamikaze94/WolfHUD#48]
I typically disable this option because I know when Berserker is active and I don't need to know the exact percentage boost it's giving me, but it stays there no matter what...

If I'm using a build with Frenzy, it's there at the start of the heist.

I have seen this behavior with other buffs/debuffs also (like Quick Fix), which stay active once the timer reaches 0.0s.

**Comment by killrhythm09** [comment]
Also, what are the "show reload timer" and "show melee charge" options for? Are they related to HUDList or is it a legacy setting? I ask because those also show up in the HUDList buffs area even when I turn those options off.

**Comment by killrhythm09** [comment]
Also also, I've noticed there are a lot of typos/spelling mistakes in the options menus. What would be the best way for me to help fix those?

And thanks for the mod, it's been great discovering all the nice little features. :)

**Comment by Kamikaze94** [comment]
Okay, just gave it aquick test, and quick fix as well as berserker are disappearing if they aren't active (anymore). (Using the latest dev build here from GitHUB)
If you are already using it, or those bugs happen to you on that version too, some info on your used settings might be useful. Also making sure it does happen also if you run WolfHUD with no mods alongside, or which combination of mods make it break.

The "show reload timer" and "show melee charge" options just enable those timers beeing shown as an interaction (the center circle). 
When adding those timers to HUDList, I made HUDList's timers just show, if you disabled the interaction 
timers. The setting might seem a little strange, as HUDList needs a map restat to enable or disable thsoe timers, but the interaction gets shown/hidden instant.

For typos, either post/upload a corrected version here, or just some strings you see problems with.
Or you could fork the repo, edit the localizations in your copy of the repo and send me a pull-request.

**Comment by Kamikaze94** [comment]
Okay, as this seems to be done from my side, I'll go ahead and close it for now.
If you think there are any bugs left, or I overlooked something, feel freee to notify me about it.
Thanks for reporting my mistake with the berserker buff setting. :D
Closed.
