### ISSUE TITLE
Game crashing when opening up the tab menu

### ISSUE THREAD

**Issue by Necronn** [Kamikaze94/WolfHUD#481]
Sat Oct 21 19:15:22 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:1017: attempt to call method 'feed_heist_time' (a nil value)

SCRIPT STACK

update() lib/managers/gameplaycentralmanager.lua:202
update() lib/setups/gamesetup.lua:666
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???

**Comment by MisterOizo** [comment]
Quite similar for me:

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:1017: attempt to call method 'feed_heist_time' (a nil value)

SCRIPT STACK

original() lib/managers/gameplaycentralmanager.lua:202
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/gamesetup.lua:666
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name
