### ISSUE TITLE
Crashes when pressing tab (Locke and Load Day 3)

### ISSUE THREAD

**Issue by DRagon630** [Kamikaze94/WolfHUD#484]
It seems everyone using wolfhud is getting this problem.
I don't get an error message, my game just crashes without warning.
I disabled the tabstats option and it's still happening.

**Comment by Srki94** [comment]
Confirmed.

I even tried to disable Tab Stats.
I think it's related to the new Achievements UI which is now available when Tab is pressed.

**Comment by DRagon630** [comment]
I deleted the old version, downloaded the new one, not only is tabstats still there, but the problem is also there.
Side note/Off topic: I love it when Overkill marginalizes and essentially rims there modding community, which has been a big reason why Payday 2 is as popular as it is.

**Comment by SirFireNewt** [comment]
Same as issue #480 #481 #483 
I just redownloaded it and tabstats has been removed, and the crash solved. 
redownload it again; make sure you don't download from releases but "clone or download" as a zip.

**Comment by preduuu2** [comment]
i reinstalled my game and the new version and i still have tab stats the only difference is that i cant my game crashes when i try to start a heist

**Comment by HadesDurin** [comment]
is it possible, that one of the reasons for these crashes is the BLT mod?

**Comment by SirFireNewt** [comment]
I think it could, but in this case Overkill did make a lot of changes to
tabstats and the latest commit said that a heavy rewrite would be needed.
