### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by ershiozer** [Kamikaze94/WolfHUD#485]
I tried to open the game after I dragged the folders into mods folder but it didn't open.it just stucks on startup screen then closes up itself

here is the crash report of game;
----------------------------------------------------------------------

Sun Oct 22 15:47:14 2017

Application has crashed: C++ exception
mods/WolfHUD/Core.lua:1277: attempt to index global 'BLT' (a nil value)

SCRIPT STACK

Call() @mods/base/req/hooks.lua:107
init() @mods/base/lua/LocalizationManager.lua:9
new() core/lib/utils/coreclass.lua:35
core/lib/setups/coresetup.lua:340

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      kernel32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlInitializeExceptionChain                         
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
                        Call()  @mods/base/req/hooks.lua:107                        
                        init()  @mods/base/lua/LocalizationManager.lua:9            
                         new()  core/lib/utils/coreclass.lua:35                     
                                core/lib/setups/coresetup.lua:340                   

-------------------------------

**Comment by TheBlueChocolate** [comment]
same problem for me.
