### ISSUE TITLE
Do we Even Still need Custom Laser colors? 

### ISSUE THREAD

**Issue by Seyaboy** [Kamikaze94/WolfHUD#489]
well is it the new update that They added lasers that you could change the color built in, if we do we even still need the custom lasers on the WolfHUD Mod. the colors doesnt show on the game but maybe its because of the custom lasers color of WolfHUD

**Comment by DRagon630** [comment]
The colors you select directly through the weapon mod will be what other players see.

**Comment by Malidictus** [comment]
I'd argue we need an option to override people's chosen laser and flashlight settings with WolfHUD's (or override WorlfHUD's with those in the game). Would keep people from trolling me with red lasers and would prevent me having to hand-set all of my weapons' lasers and flashlights, while still keeping the option to default to what's in the game.

**Comment by sprylog** [comment]
yeah i would like this option to disable it too
