### ISSUE TITLE
WolfHUD crash - starting heist with recent update (U162)

### ISSUE THREAD

**Issue by jtmal0723** [Kamikaze94/WolfHUD#493]
With the addition of Duke and the new perkdeck with Update 162, WolfHUD has an immediate crash when starting any heist. Crashes when using the perkdeck, crashes without using perkdeck.

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3682: attempt to call method '_total_armor' (a nil value)

SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3680
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3680
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3553
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3553
@mods/WolfHUD/lua/GameInfoManager.lua:3553
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update() @mods/WolfHUD/lua/MenuTweaks.lua:588
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:790
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.411.
	CPU : Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 / nvldumd.dll[23.21.13.8792]
	Language : english
	Memory :     16346MB 928KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Realtek HD Audio 2nd output (Realtek High Definition Audio))

**Comment by NicoTine34** [comment]
same error

**Comment by Necronn** [comment]
Same error. Might have something to do with the perk deck? Since it adds the armor as HP instead.
Wed Oct 25 22:03:05 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3681: attempt to call method '_total_armor' (a nil value)



SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3679
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3679
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3552
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3552
@mods/WolfHUD/lua/GameInfoManager.lua:3552


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by Evixious** [comment]
Disabling lines 
```
if armor >= self:_total_armor() then
	ARMOR_GRIND_ACTIVE = false
	managers.gameinfo:event("player_action", "deactivate", "anarchist_armor_regeneration")
	managers.gameinfo:event("player_action", "deactivate", "standard_armor_regeneration")
end
```
(3682 - 3686) did it for me. But some circles look a bit buggy now.

**Comment by jtmal0723** [comment]
@Evixious this helps a lot. I also recommend that if anyone does this workaround, to turn off the Custom HUD in the hud options for now so you can at least see your health and armor circles. The stamina display is broken but manageable for now.

**Comment by Evixious** [comment]
I'm glad that helped! Hope Kamikaze can fix the issue. :)

**Comment by Speedy905** [comment]
I use WolfHud without the CustomHud (as I always do) and it still crashes the game. What I suggest right now is disabling the mod until Kamikaze hopefully creates a temp fix. 

Here's a crashlog for more info:
----------------------------------------------------------------------

Wed Oct 25 16:41:03 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3682: attempt to call method '_total_armor' (a nil value)



SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3680
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3680
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3553
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3553
@mods/WolfHUD/lua/GameInfoManager.lua:3553
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update_actual() @mods/WolfHUD/lua/MenuTweaks.lua:588
update() @mods/translucentmissionbriefinggui/ingamewaitingforplayers.lua:145
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:790
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.411.
	CPU : Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD Radeon (TM) R9 380 Series / aticfx32.dll[22.19.685.0]
	Language : english
	Memory :     12239MB 200KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Evixious** [comment]
@Speedy905 you should read my previous answer. :)

**Comment by Speedy905** [comment]
@Evixious well i mustve missed that.

**Comment by HueboWasTaken** [comment]
replacing all cases of "_total_armor" to "_max_armor" in gameinfomanager.lua will fix it

**Comment by Evixious** [comment]
@HueboWasTaken thanks! :)

**Comment by HueboWasTaken** [comment]
nevermind it still crashes for me LOL

**Comment by Evixious** [comment]
Rip. You can try my temporary solution maybe. :)

**Comment by HueboWasTaken** [comment]
Oh wait it did work, I just forgot to save the file haha

**Comment by jtmal0723** [comment]
Both methods do work, just leaves a really screwed up health circle on the custom hud, or a really wonky one without the custom hud. Either way, it'll work until Kamikaze94 gets around to fixing the mod. At least it didn't break more than just the health representations and such. This time.

**Comment by jtmal0723** [comment]
The origination of this crash has been fixed thus I will close out this issue.
