### ISSUE TITLE
Is there a way to update wolfhud without it resetting all of my settings?

### ISSUE THREAD

**Issue by ctran2131** [Kamikaze94/WolfHUD#494]
Every time I update wolfhud I need to manually enter all of my old settings. Is there a way that I can keep my settings after updating?

**Comment by NicoTine34** [comment]
In C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\mods\saves 
there is files : WolfHUD.txt, WolfHUD_Colors.txt, WolfHUD_InventoryNames.txt and WolfHUD_v2.json.

**Comment by ctran2131** [comment]
Would I just copy these files and replace the new ones in the updated version?

**Comment by asdf1324** [comment]
I always just overwrite all the files from downloaded ZIP to previous wolfhud folder. It works well, at least for me.
