### ISSUE TITLE
Crashing after Duke update

### ISSUE THREAD

**Issue by Tsagu** [Kamikaze94/WolfHUD#495]
ed Oct 25 18:07:09 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3682: attempt to call method '_total_armor' (a nil value)

SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3680
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3680
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3553
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3553
@mods/WolfHUD/lua/GameInfoManager.lua:3553
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update() @mods/WolfHUD/lua/MenuTweaks.lua:588
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:790
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.411.
	CPU : AMD FX(tm)-6350 Six-Core Processor (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 760 / nvldumd.dll[22.21.13.8494]
	Language : english
	Memory :     8139MB 36KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by jtmal0723** [comment]
This has already been noted in #493 but thanks for the report!
