### ISSUE TITLE
Crash after today's update

### ISSUE THREAD

**Issue by ConSaw** [Kamikaze94/WolfHUD#497]
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3691: attempt to call method '_total_armor' (a nil value)

SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3689
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3689
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3562
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3562
@mods/WolfHUD/lua/GameInfoManager.lua:3562

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.411.
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 / nvldumd.dll[23.21.13.8792]
	Language : english
	Memory :     16269MB 272KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (HeadPhone/Digital Output (Realtek High Definition Audio))

**Comment by xanaguy** [comment]
That's a bug on overkill's part, believe it or not. By swapping profiles to something of another perk deck, you can gain the benefits of both perk decks! Unfortunately, this will also cause WolfHUD to crash the game. So...

**Comment by ConSaw** [comment]
Thanks for the info. I had just deleted lines 3688 to 3696 of GameInfoManager.lua as a quick fix and it worked. Probably not the best way to do it though....

**Comment by xanaguy** [comment]
I wasn't specific enough on which perkdeck though... You start the match with a Stoic, and swap profiles to something else in the planning phase, you'll get the benefits of both Stoic and the other perk deck... Kinda. It also somehow is making WolfHud crash without your quickfix.

**Comment by Impact009** [comment]
It might be heist-specific. I switched to a different perk deck during Day 2 of Firestarter, and I didn't crash.
