### ISSUE TITLE
Duke name on health bar

### ISSUE THREAD

**Issue by ElReyZero1201** [Kamikaze94/WolfHUD#498]
Duke's name on health bar is hym or something like that, can you fix it?

**Comment by jtmal0723** [comment]
The health bar displays Duke's name as "myh". Picture is attached to show this.
![20171025233030_1](https://user-images.githubusercontent.com/2731183/32033862-2b86788c-b9dd-11e7-8779-55bd00a57e16.jpg)

**Comment by xanaguy** [comment]
That's because it's a recently added character. His model/character name isn't registered with the hud yet. So it just went with his model/string name.
