### ISSUE TITLE
Crash when tightening TAB

### ISSUE THREAD

**Issue by CPTMateus** [Kamikaze94/WolfHUD#499]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                set_progress()  lib/managers/menu/extendeduielemets.lua:627         
                set_progress()  lib/managers/menu/extendeduielemets.lua:677         
             update_progress()  lib/managers/hud/newhudstatsscreen.lua:55           
             update_original()  lib/managers/hud/newhudstatsscreen.lua:438          
                          cb()  @mods/WolfHUD-master/lua/TabStats.lua:187           
                      update()  lib/managers/hudmanager.lua:642                     
                      update()  lib/setups/gamesetup.lua:663                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537                   

-------------------------------

System information:
	Application version : 1.80.411.
	CPU : Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 210  / nvd3dum.dll[21.21.13.4201]
	Language : english
	Memory :     4051MB 900KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Alto-falantes (Realtek High Definition Audio))

**Comment by SilbernerDolch** [comment]
This error occurs for me as well, but ONLY when I pin some achievments . Without any pinned, everything works fine for me.
