### ISSUE TITLE
Health Bars on converted enemies (Jokers) are misaligned/broken on the Hud Display in U162

### ISSUE THREAD

**Issue by jtmal0723** [Kamikaze94/WolfHUD#500]
Title pretty much explains it all really. The health bar display for converted enemies (Jokers) on the HUD display in the upper left are not scaled properly, thus only showing the top right corner of the circles. Picture shows this. It displays this way for both the CustomHUD and the "VanillaHUD" option.
![20171025233105_1](https://user-images.githubusercontent.com/2731183/32033833-f0306ffe-b9dc-11e7-9226-78ae95adaa69.jpg)

**Comment by samvdkris** [comment]
Just wanted to say I have the same problem. I was going to make an issue, but saw this one. I'm on U162 as well.

![2017-10-26_08-32-23](https://user-images.githubusercontent.com/22723225/32038252-5047dd04-ba29-11e7-9f4d-a96910536396.png)

**Comment by jtmal0723** [comment]
Looks like this was fixed in a commit after I downloaded this last night. Marking this as closed and fixed. Thanks a bunch!
