### ISSUE TITLE
Cannot install latest version of WolfHUD

### ISSUE THREAD

**Issue by TheBlueChocolate** [Kamikaze94/WolfHUD#502]
I can't install wolfhud update. Whenever I try to, my game crash on launch. And the older version I'm using now crash on heist launch.

**Comment by bolgy** [comment]
Same problem, All versions of wolfhud leads to crash on launch of any heist

**Comment by kallak** [comment]
Can either of you (or both) provide a crash log?

**Comment by kallak** [comment]
Also are your BLTs updated to the latest version?

**Comment by filko** [comment]
Note: this is from BLT4linux, I'm unable to test on Windows.

Lua runtime error: mods/WolfHUD/lua/GameInfoManager.lua:3673: attempt to call method '_total_armor' (a nil value)

stack traceback:
	mods/WolfHUD/lua/GameInfoManager.lua:3673: in function 'set_armor_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3671: in function 'set_armor_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3671: in function 'set_armor'
	[string "lib/units/beings/player/playerdamage.lua"]:533: in function '_regenerate_armor'
	[string "lib/units/beings/player/playerdamage.lua"]:519: in function 'replenish'
	[string "lib/units/beings/player/playerdamage.lua"]:33: in function 'init_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3544: in function 'init_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3544: in function 'init_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3544: in function <mods/WolfHUD/lua/GameInfoManager.lua:3543>
	[C]: in function 'spawn_unit'
	[string "lib/network/base/networkpeer.lua"]:2126: in function 'spawn_unit'
	[string "lib/network/base/basenetworksession.lua"]:1498: in function 'spawn_players'
	[string "lib/states/ingamewaitingforplayers.lua"]:262: in function 'update_original'
	mods/WolfHUD/lua/MenuTweaks.lua:588: in function 'update'
	[string "core/lib/utils/game_state_machine/coregamesta..."]:92: in function 'update'
	[string "lib/setups/setup.lua"]:790: in function 'update'
	[string "lib/setups/gamesetup.lua"]:654: in function 'update'
	[string "lib/setups/networkgamesetup.lua"]:21: in function 'update'
	[string "core/lib/setups/coresetup.lua"]:537: in function <[string "core/lib/setups/coresetup.lua"]:459>

**Comment by TheBlueChocolate** [comment]
I also crash if I try to install latest version of BLT (BLT 2)

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3676: attempt to call method '_total_armor' (a nil value)



SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3674
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3674
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3547
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3547
@mods/WolfHUD/lua/GameInfoManager.lua:3547
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update() @mods/WolfHUD/lua/MenuTweaks.lua:588
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:790
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

I found a way to use wolfhud anyway: I just replaced the old "lua" folder with the new one I don't know why but it worked.
