### ISSUE TITLE
_total_armor crashing Payday 2 again today.

### ISSUE THREAD

**Issue by Impact009** [Kamikaze94/WolfHUD#504]
I had updated to the new commit yesterday to fix this issue. It seems like it's happening again after this morning's update.

`Thu Oct 26 12:03:26 2017

Application has crashed: C++ exception
mods/WolfHUD-master/lua/HUDList.lua:6185: attempt to call method '_total_armor' (a nil value)

SCRIPT STACK

_update_value() @mods/WolfHUD-master/lua/HUDList.lua:6200
_check_buffs() @mods/WolfHUD-master/lua/HUDList.lua:6055
@mods/WolfHUD-master/lua/HUDList.lua:6020
clbk() @mods/WolfHUD-master/lua/HUDList.lua:983
_listener_callback() @mods/WolfHUD-master/lua/GameInfoManager.lua:1469
@mods/WolfHUD-master/lua/GameInfoManager.lua:1355
event() @mods/WolfHUD-master/lua/GameInfoManager.lua:610
set_synced_cocaine_stacks() @mods/WolfHUD-master/lua/GameInfoManager.lua:3021
update_synced_cocaine_stacks_to_peers() lib/managers/playermanager.lua:3073
_update_damage_dealt() lib/managers/playermanager.lua:1329
update() lib/managers/playermanager.lua:569
update() lib/setups/setup.lua:773
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
orig__update() core/lib/setups/coresetup.lua:537
trainer/tools/pubinfloopv2.lua:141

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.413.
	CPU : AMD Ryzen 3 1200 Quad-Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970 / nvldumd.dll[22.21.13.8569]
	Language : english
	Memory :     8125MB 88KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))`

Edit: It only happened on Stealing Xmas so far. I played through an entire Firestarter heist just fine.

**Comment by jabalbinot** [comment]
After yesterday Payday update, mine is facing the same issue.

----------------------------------------------------------------------

Thu Oct 26 22:53:16 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3683: attempt to call method '_total_armor' (a nil value)



SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3681
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3681
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3554
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3554
@mods/WolfHUD/lua/GameInfoManager.lua:3554
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update() @mods/WolfHUD/lua/MenuTweaks.lua:588
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:790
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.413.
	CPU : AMD FX(tm)-8120 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon HD 7800 Series / aticfx32.dll[22.19.162.4]
	Language : english
	Memory :     16358MB 696KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Alto-falantes (2- Wireless Stereo Headset))

**Comment by Impact009** [comment]
Mine's a different issue. I'm having a problem with HUDList.lua, not GameInfoManager.lua.

**Comment by Data-Zero** [comment]
just change _total_armor to _max_armor in lua/hudlists.lua and in lua/GameInfoManager.lua

fixed for me

**Comment by cswiz1996** [comment]
I tried it however the health and armor bar are messed up and I cant see my health until its mostly gone.
