### ISSUE TITLE
Cannot start game with wolfhud

### ISSUE THREAD

**Issue by Dogdogman** [Kamikaze94/WolfHUD#506]
Application has crashed: C++ exception
mods/WolfHUD-master/Core.lua:1281: attempt to index global 'BLT' (a nil value)

SCRIPT STACK

Call() @mods/base/req/hooks.lua:107
original() @mods/base/lua/LocalizationManager.lua:9
init() @mods/base/req/hooks.lua:258
new() core/lib/utils/coreclass.lua:35
core/lib/setups/coresetup.lua:340

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name

**Comment by kallak** [comment]
Are your BLT and WolfHud updated to the latest version?

**Comment by Dogdogman** [comment]
They were not... Thanks for bringing that up, problems fixed now!
