### ISSUE TITLE
_total_armor crashing game upon joining an in-progress game

### ISSUE THREAD

**Issue by KrazyBigJ** [Kamikaze94/WolfHUD#508]
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3682: attempt to call method '_total_armor' (a nil value)

SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3680
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3680
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3553
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3553
@mods/WolfHUD/lua/GameInfoManager.lua:3553

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.413.
	CPU : Intel(R) Core(TM) i5 CPU 760 @ 2.80GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 750 Ti / nvldumd.dll[23.21.13.8792]
	Language : english
	Memory :     8181MB 572KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by KrazyBigJ** [comment]
happened when i joined shadow raid and big bank in progress
also occurred when starting a bank heist

**Comment by jabalbinot** [comment]
Same thing here...

----------------------------------------------------------------------

Thu Oct 26 22:53:16 2017


Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3683: attempt to call method '_total_armor' (a nil value)



SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3681
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3681
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3554
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3554
@mods/WolfHUD/lua/GameInfoManager.lua:3554
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update() @mods/WolfHUD/lua/MenuTweaks.lua:588
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:790
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.80.413.
	CPU : AMD FX(tm)-8120 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon HD 7800 Series / aticfx32.dll[22.19.162.4]
	Language : english
	Memory :     16358MB 696KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Alto-falantes (2- Wireless Stereo Headset))

**Comment by Data-Zero** [comment]
just change _total_armor to _max_armor lua/hudlists.lua and in lua/GameInfoManager.lua

fixed for me

**Comment by KrazyBigJ** [comment]
i had a file named **lua/HUDList.lua** instead of lua.hudlists.lua
but yeah after changing those two in those two files my game ran
thanks
leaving this issue open so people see it and kamikaze fixes it
