### ISSUE TITLE
Crash on startup, eventhough I downloaded latest version

### ISSUE THREAD

**Issue by wobble12** [Kamikaze94/WolfHUD#511]
[2017_10_27_log.txt](https://github.com/Kamikaze94/WolfHUD/files/1423011/2017_10_27_log.txt)

**Comment by kallak** [comment]
Is your BLT also updated to the latest version?

**Comment by wobble12** [comment]
Yeah, it was BLT apparenlty which caused crashes. Sorry I posted this here then, and thanks for the tip
