### ISSUE TITLE
TabStats weirdness

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#517]
In the latest version of WolfHUD (from yesterday), TabStats seems to have regained partial functionality. I see my kills breakdown in the right panel. However, the left panel is almost completely blank, crucially preventing me from seeing how many bags I've secured.

**Comment by Kamikaze94** [comment]
Most info on the left side got moved into TabStats. This includes mandatory7bonus bags amounts as well as values and current instant cash value.
Left side just displays the current objective, Mutators/Tracked achievments, body bags and current track.
Have made some tests to dispaly relevant sidejobs for your current mission/loadout on the left side, if you have no tracked achievments, but the problem currently is, deciding which one is relevant, as finding the requirements prooves to be rather difficult...   :/

Anyways, your loot bag counter is on the right side, if you havn't found it by now :)

**Comment by Malidictus** [comment]
I had not! I didn't even think to look for it there :) I just saw the big black window and assumed... Thanks for the advise, I'll have another look when I'm in-game. That one's gonna' be embarrasing to explain to my friends.
