### ISSUE TITLE
Crash when leaving heist before end

### ISSUE THREAD

**Issue by Didjahtul** [Kamikaze94/WolfHUD#52]
Joined on another using the new quick join and get this crash when leaving via menu before end of heist.  Currently using the git version of wolfhud with the drill fix.

```
Sun Sep 04 09:42:58 2016


Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:2026: attempt to index a nil value



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlQueryPackageClaims                               
                         ntdll  (???)     NtQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name
```

ps First time posting one of these so if you need more info let me know.  Ty for all your hard work.

**Comment by Kamikaze94** [comment]
Alright, seems like the network session/the local peer was already destructed, when the contour function was called.
Should be fixed, by relying on the playermanager now.

Was there an ECM or ECM Feedback  activated/running out during the time you wanted to disconnect?
Not mandatory to know, just interesting :)

Anyways, should be fixed, reply if you find a way to still trigger it.
Thanks for reporting!

**Comment by Didjahtul** [comment]
Not sure on the ECM feedback. Haven't had it happen again. (on fixed vers) Wasn't sure what could be causing it but I'll try triggering it with ECMs under diff conditions. Seems fixed though from quick tests.
