### ISSUE TITLE
After Day10 Update,tap TAB=crash

### ISSUE THREAD

**Issue by FR0Z3** [Kamikaze94/WolfHUD#520]
Sun Oct 29 02:18:58 2017

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                set_progress()  lib/managers/menu/extendeduielemets.lua:627         
                set_progress()  lib/managers/menu/extendeduielemets.lua:677         
             update_progress()  lib/managers/hud/newhudstatsscreen.lua:55           
             update_original()  lib/managers/hud/newhudstatsscreen.lua:438          
                          cb()  @mods/WolfHud/lua/TabStats.lua:187                  
                      update()  lib/managers/hudmanager.lua:642                     
                      update()  lib/setups/gamesetup.lua:663                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537

**Comment by FR0Z3** [comment]
oh,after the event ends,go ahead and update the hug

**Comment by Srki94** [comment]
Can you clarify your last post, please?
I updated to the latest commit available and I still crash. 

> Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                set_progress()  lib/managers/menu/extendeduielemets.lua:627         
                set_progress()  lib/managers/menu/extendeduielemets.lua:677         
             update_progress()  lib/managers/hud/newhudstatsscreen.lua:55           
             update_original()  lib/managers/hud/newhudstatsscreen.lua:438          
                          cb()  @mods/WolfHUD/lua/TabStats.lua:187                  
                      update()  lib/managers/hudmanager.lua:642                     
                      update()  lib/setups/gamesetup.lua:663                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537                   

-------------------------------

System information:
	Application version : 1.81.426.
	CPU : AMD Athlon(tm) X4 750K Quad Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon HD 7700 Series / aticfx32.dll[22.19.677.257]
	Language : english
	Memory :     8150MB 936KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by FR0Z3** [comment]
Sry,I was be able to reply the email every 13 days,yea,everytime I click the tab button,game will crash.
I don’t think I have something that conflict with WolfHUD


________________________________
