### ISSUE TITLE
Lost update Revision keys/files for Federal Inventory, WolfHUD textures, and WolfHUD itself

### ISSUE THREAD

**Issue by TheRathour** [Kamikaze94/WolfHUD#522]
On game start, with WolfHUD installed:

02:26:49 PM Lua: [Mods] Loading mod: WolfHUD...
02:26:49 PM Lua: [Error] Could not add automatic update for mods/WolfHUD/ as it has no revision key!
02:26:49 PM Lua: [Error] Could not add automatic update for WolfHUD Textures as it has no revision key!
02:26:49 PM Lua: [Error] Could not add automatic update for Federal Inventory as it has no revision key!
02:26:52 PM Log:  (..\src\http\http.cpp:49) CURL CLOSED
___
Sifting through the mod.txt I can see the current version of WolfHUD is missing a few lines that a previous version had, being:

"revision" : 20,
"revision" : "./assets/mod_overrides/WolfHUD_Textures/revision.txt",
"revision" : "./assets/mod_overrides/Federal Inventory/revision.txt",
___
When I throw these lines into my current mod.txt I get a new, different error:

02:36:54 PM Lua: [Mods] Loading mod: WolfHUD...
02:36:54 PM Lua: [Error] Could not load revision file for WolfHUD Textures!
02:36:54 PM Lua: [Error] Could not load revision file for Federal Inventory!
02:36:55 PM Log:  (..\src\http\http.cpp:49) CURL CLOSED
___
Meaning I appear to be missing the files that WolfHUD asks you to download through the auto updater, with the problem being I can't use the auto-updater to get these specific files because I can't start my game with WolfHUD installed period.
There's one other person who has posted with a similar issue to mine, however they received no response.

**Comment by Kamikaze94** [comment]
Same issue as #511 .
BLT 2.0 doesn't use a revision number anymore. Instead it uses the directory hash of the mods directory.
Please make sure, your BLT installation is up to date :)
