### ISSUE TITLE
Achievement Tracking Tab Crash.

### ISSUE THREAD

**Issue by freemysou1** [Kamikaze94/WolfHUD#527]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                set_progress()  lib/managers/menu/extendeduielemets.lua:627         
                set_progress()  lib/managers/menu/extendeduielemets.lua:677         
             update_progress()  lib/managers/hud/newhudstatsscreen.lua:55           
             update_original()  lib/managers/hud/newhudstatsscreen.lua:438          
                          cb()  @mods/WolfHUD-master/lua/TabStats.lua:187           
                      update()  lib/managers/hudmanager.lua:642                     
                      update()  lib/setups/gamesetup.lua:663                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537                   

When you track an achievement and press tab during a heist your game CTD due to the standard PAYDAY 2 Achievement Tracking UI trying to override WolfHUD Stats UI. Well this isn't a critical issue it's something worth noting.

**Comment by robotboy655** [comment]
#537 #534 #533 Are all duplicates of this one
