### ISSUE TITLE
PocoHud's drill indicator doesn't disappearing.

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#53]
I don't know is it related just with PocoHud or this happening partly because of WolfHUD, but...
![20160903123042_1](https://cloud.githubusercontent.com/assets/19766576/18268850/42460902-742e-11e6-85dd-c08f4373eeb2.jpg)

**Comment by hud8614** [comment]
uHUD Vanilla+ drill timer......icon.....

**Comment by Tatsugi** [comment]
As it appears "uHUD Vanilla+" is part of PocoHud because I don't use "uHUD Vanilla+", so it's just PocoHud problem, but that bug didn't appear until last game update... Okay, will report it in PocoMods community.
