### ISSUE TITLE
Crash after pressing Tab

### ISSUE THREAD

**Issue by Cyberguard25** [Kamikaze94/WolfHUD#533]
For a while, every time i play a heist and press tab during the heist it crashes which has caused me to lose progress in a heist more than once. I also lose the money which i used to pay for the heist. I've disabled tab stats and anything to do with tab but it just keeps on crashing. Can someone please tell me how to stop this?

**Comment by deepjb** [comment]
the only thing I did for now is removing the mod folder (just WOLFHUD), and yeah it sucks cuz I also wanted to play PD2 with this HUD but it crashes a lot

**Comment by freemysou1** [comment]
@Cyberguard25 @deepjb Simple quick fix for the moment is to go Tabstats and disable it, The problem is that Achievement tracking is trying to override WolfHUD Stats.
