### ISSUE TITLE
Laser Color

### ISSUE THREAD

**Issue by Paquismakis** [Kamikaze94/WolfHUD#536]
The laser color doesn't change when I modify it from the gadget customization menu. I think this is because the game prioritizes the HUD's laser color modifyer. Can we utilize the game's laser color modifyer,  but with WolfHUD features like Rainbow Laser?

**Comment by Srki94** [comment]
Same. It started happening few days after the Laser color update. Before that, the game prioritized gadget colors. I kind of always hoped that it would be addressed.

I can't see a way to turn off laser modification for specific groups (ex. Player, Sniper, Teammates, etc.)
If you could add an off switch for each group, that would be awesome. 
(... as in, just turn off the color modification from Wolf HUD)
