### ISSUE TITLE
TabStats.lua still crashing

### ISSUE THREAD

**Issue by EliseMRX** [Kamikaze94/WolfHUD#537]
Hello!
This file still make the game crash when the user press the tab key. I commented all the code in this file to not crash anymore and still use the HUD.

**Comment by WeaselKek** [comment]
I think it crashes only when you track achievemnts. Haven't confirmed it still.

**Comment by stan-potapov** [comment]
It's quite strange, I'm pretty sure that the achievements were trackable when it first got updated to support the new tabscreen layout.

**Comment by asdf1324** [comment]
Sat Nov 04 21:48:30 2017


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                set_progress()  lib/managers/menu/extendeduielemets.lua:627         
                set_progress()  lib/managers/menu/extendeduielemets.lua:677         
             update_progress()  lib/managers/hud/newhudstatsscreen.lua:55           
             update_original()  lib/managers/hud/newhudstatsscreen.lua:438          
                          cb()  @mods/WolfHUD-master/lua/TabStats.lua:187           
                      update()  lib/managers/hudmanager.lua:642                     
                      update()  lib/setups/gamesetup.lua:663                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537                   

Same thing happens to me, too. Tracked some halloween mask achievements, and it started to crash as I press tab, or Shift + tab. Does not crash when none of the achievements are tracked, and pretty sure it's not another mods' fault, as it won't crash when tracking achievements without Wolfhud.
