### ISSUE TITLE
wolfhud dev crash before main menu

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#54]
Application has crashed: C++ exception
mods/WolfHUD dev/Core.lua:507: bad argument #1 to 'pairs' (table expected, got nil)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlQueryPerformanceCounter

**Comment by Kamikaze94** [comment]
Ah, just found out I can reference issues in commits, ^^

Anyways, seemed like there is a problem to the "updates" part of your mod.txt....
Did you modify anything there?
In any case, you might want to check, it's the same as the uploaded one here.
Commit just added some fallbacks, so the 'nil'-value shouldn't appear there anymore....
