### ISSUE TITLE
Not saving Preplanning plans

### ISSUE THREAD

**Issue by HerrKai** [Kamikaze94/WolfHUD#540]
Hello. Today I downloaded the newest version of Wolfhud and when I save a plan ingame and then go to load the plan shows up. However after I finish or fail a heist, the plan is gone.

**Comment by HadesDurin** [comment]
have the same problem on my pre planning

**Comment by Kamikaze94** [comment]
Maybe its failing at creating the folder in "mods/saves/Preplanned".
There were some people which had problems with it and had to manually create it. (issue #469)
Not entirely sure, why its happening, always thinking it might be related to write permissions missing on said fodlers for the process, but not entirely sure... :S

**Comment by HerrKai** [comment]
I am going to try creating that folder, hang on...

**Comment by HerrKai** [comment]
Btw that feature worked for me in one of the previous versions.

**Comment by HerrKai** [comment]
After I created the folder the game crashed while loading a job. After a restart it worked and the plans get saved in that folder. If you have problems with creating a folder, just save all the data in one file.

Thx for helping :)

**Comment by HadesDurin** [comment]
@Kamikaze94 The problem is, if you download WolfHud from here 
and use it, there is no "mods/saves/Preplanned"-Folder to use.

**Comment by HerrKai** [comment]
Then he should either script that it creates a folder if there is none or you add a useless file in a Preplanned folder, then the next push will have that folder i think
