### ISSUE TITLE
WolfHud doesn't work anymore

### ISSUE THREAD

**Issue by Magnum180** [Kamikaze94/WolfHUD#541]
With the new updates the mod doesn't work anymore and there no menu option in the main menu. In the game option i can see that all the files has been changed. How can i fix it ?

**Comment by gg30433043** [comment]
Im going to test it right now. Try deleting all the files in WolfHud and then drag and drop the new ones.

**Comment by Magnum180** [comment]
It doesn't work. Even if i re-download the mod. When i look to the mod section in the Options of the game the file who is change is called "guis/textures/contact_vlad.textures" and a whole bunch of them in Federal inventory.

**Comment by gg30433043** [comment]
The Wolfhud Option are in Options>ModOptions>WolfHud Settings

**Comment by Magnum180** [comment]
The only thing i have is Options>Mods>Federal Inventory / WolfHud_Texures, but no WolfHud Settings

**Comment by HadesDurin** [comment]
problem might be that your Wolfhud is inside another folder which cannot be read by BLT
it should look like this http://prntscr.com/h5db75

**Comment by Kamikaze94** [comment]
@Magnum180 
BLT mods have their configuration menu located in >Options > __Mod Options__.
It's a menu added by BLT. If doesn't exist, please check that you have BLT installed correctly and it's working as intended.
  
The normal "Mods" menu is added by the base game and is an overview about your installed mod_overrides and visualizes conflicts, if 2 texture mods try to replace the same texture.

**Comment by Magnum180** [comment]
@HadesDurin 
It looks like this

@Kamikaze94 
BLT is installed corretly i put the mods folder and the IPHLPAPI.dll in the Payday 2 folder. Then i put the WolfHUD folder in mods
