### ISSUE TITLE
Saved ''Preplanning'' disappears after reset heist (Problem solved)

### ISSUE THREAD

**Issue by Patriot99** [Kamikaze94/WolfHUD#549]
After taking 'Preplanning' and saving it, I start the heist and when it resets the saved heist, 'Preplanning' does not exist. As if he had disappeared after the start of the heist.

**Comment by HadesDurin** [comment]
you have to create a folder called "Preplanned" inside your saves folder:
steamapps\common\PAYDAY 2\mods\saves\Preplanned
http://prntscr.com/h68b8b

**Comment by Patriot99** [comment]
@HadesDurin 
Since last update, WolfHud has stopped working for me, but after creating a folder everything works, thanks
I did not think about checking it out.
Problem solved and subject to closure.
