### ISSUE TITLE
Weapon Gadget Color

### ISSUE THREAD

**Issue by Kircata420** [Kamikaze94/WolfHUD#550]
I think now you can remove the gadget color setting for the player, since now there are options in the game where you can change the colors. Also my friends see the color green all the time even tough i changed it to lets say red.

OR you can make an option if you want custom colors to be enabled or not.

**Comment by PointyDev** [comment]
@Kamikaze94 Would like to see a per setting toggle to enable/disable each of the following settings below, per what was mentioned above.
> OR you can make an option if you want custom colors to be enabled or not.

![](https://pointy.needs-to-s.top/ed3f0e.png)

**Comment by Malidictus** [comment]
I agree with the option to override the Vanilla game's customisation settings with WolfHUD's optionally, as well as the other way around. I'd also suggest looking into syncing WolfHUD's customisation to other players in the lobby. They currently see default values only.

**Comment by Malidictus** [comment]
I agree with the option to override the Vanilla game's customisation settings with WolfHUD's optionally, as well as the other way around. I'd also suggest looking into syncing WolfHUD's customisation to other players in the lobby. They currently see default values only.

**Comment by Srki94** [comment]
This was addressed in https://github.com/Kamikaze94/WolfHUD/commit/7e558d29db34e5e3a940dd51e184d78ac305ef9f 

You can now disable some overrides.
