### ISSUE TITLE
Crash in loading into a midgame safehouse raid.

### ISSUE THREAD

**Issue by Ongjming** [Kamikaze94/WolfHUD#551]
Application has crashed: C++ exception
[string "core/lib/utils/corecode.lua"]: 100: attempt to index local 'obj' (a boolean value)

SCRIPT STACK

_spawn_trail_effect() lib/units/weapons/newnpcraycastweaponbase.lua:654
_fire_raycast() lib/units/weapons/newnpcraycastweaponbase.lua:583
fire() lib/units/weapons/raycastweaponbase.lua:459
singleshot() lib/units/weapons/newnpcraycastweaponbase.lua:186
update() lib/units/enemies/cop/actions/upper_body/copactionshoot.lua:491
_upd_actions() lib/units/enemies/cop/copmovement.lua:586
_upd_actions() lib/units/player_team/huskteamaimovement.lua:40
update() lib/units/enemies/cop/copmovement.lua:549
lib/units/player_team/teamaimovement.lua:433

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by FriendlyGoy** [comment]
Same thing happened to me this morning but It was Diamond Heist loud that was already mid game...
