### ISSUE TITLE
Down Counters Are Bugged

### ISSUE THREAD

**Issue by Evixious** [Kamikaze94/WolfHUD#553]
You probably are aware that down counters are bugged right now. They always show 0 or wrong numbers. Hope you can fix it. Keep up good work! :)

**Comment by HadesDurin** [comment]
After paying attention to this:
Well they are bugged, but for me my only counter works(in loud).
For my teammates i can say its weird shows 0 most of the time...

**Comment by Ongjming** [comment]
Eh, but it will always show 0 for your teammates right from the start, then increases when they get downed. For own counter it will countdown from 3 (or 4 if you have nine lives aced).

**Comment by BangL** [comment]
Ongjming is right.
The Down Counters always have been like this on purpose.
The reason for this is: The game only knows about your own state of "nine lives" being skilled. So you cant be sure if it's 3 or 4 for them.

**Comment by Evixious** [comment]
Ohh.. Didn't notice it was working like that before. I'll close this this thread then. Thanks for the replies. :)

**Comment by Evixious** [comment]
Solution is me being dumb. Case closed.
