### ISSUE TITLE
Crash when starting heist

### ISSUE THREAD

**Issue by SirTartcube** [Kamikaze94/WolfHUD#554]
Really not sure if this is a WolfHud or BLT issue, but here's the log. I'll bold the part that I think is the issue.

06:49:26 PM Lua: [BLT] Setup...
06:49:26 PM Lua: [BLT] Loading module: 	BLTLogs
06:49:26 PM Lua: [BLT] Loading module: 	BLTModManager
06:49:26 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
06:49:26 PM Lua: [BLT] Loading module: 	BLTPersistScripts
06:49:26 PM Lua: [BLT] Loading module: 	BLTLocalization
06:49:26 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
06:49:26 PM Lua: [BLT] Loading mods for state: table: 0x001e0440
06:49:26 PM Lua: [BLT] Loading mod: base
06:49:26 PM Lua: [BLT] Loading mod: WolfHUD
06:49:26 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
06:49:26 PM Lua: [BLT] Setting up mod: 	base
06:49:26 PM Lua: [BLT] Setting up mod: 	WolfHUD
06:49:26 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
06:49:26 PM Lua: [BLT] Setup...
06:49:26 PM Lua: [BLT] Loading module: 	BLTLogs
06:49:26 PM Lua: [BLT] Loading module: 	BLTModManager
06:49:26 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
06:49:26 PM Lua: [BLT] Loading module: 	BLTPersistScripts
06:49:26 PM Lua: [BLT] Loading module: 	BLTLocalization
06:49:26 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
06:49:26 PM Lua: [BLT] Loading mods for state: table: 0x001e0460
06:49:26 PM Lua: [BLT] Loading mod: base
06:49:26 PM Lua: [BLT] Loading mod: WolfHUD
06:49:26 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
06:49:26 PM Lua: [BLT] Setting up mod: 	base
06:49:26 PM Lua: [BLT] Setting up mod: 	WolfHUD
06:49:27 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
06:49:27 PM Lua: [BLT] Setup...
06:49:27 PM Lua: [BLT] Loading module: 	BLTLogs
06:49:27 PM Lua: [BLT] Loading module: 	BLTModManager
06:49:27 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
06:49:27 PM Lua: [BLT] Loading module: 	BLTPersistScripts
06:49:27 PM Lua: [BLT] Loading module: 	BLTLocalization
06:49:27 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
06:49:27 PM Lua: [BLT] Loading mods for state: table: 0x280a0a60
06:49:27 PM Lua: [BLT] Loading mod: base
06:49:27 PM Lua: [BLT] Loading mod: WolfHUD
06:49:27 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
06:49:27 PM Lua: [BLT] Setting up mod: 	base
06:49:27 PM Lua: [BLT] Setting up mod: 	WolfHUD
06:49:54 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:49:54 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt - 1930
06:49:54 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:49:54 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:49:54 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2bltdll - 1931
06:49:54 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:49:54 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:49:54 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud - 1932
06:49:54 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:49:54 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:49:54 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud_textures - 1935
06:49:54 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:49:54 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:49:54 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=fed_inv - 1936
06:49:54 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:49:56 PM Lua: [Updates] Received update data for 'payday2blt'
06:49:57 PM Lua: [Updates] Comparing hash data:
Server: dd606e7e10e0d02d3527b6d38ca6f4d2aa58910d56d81753b16b808ae859244a
 Local: dd606e7e10e0d02d3527b6d38ca6f4d2aa58910d56d81753b16b808ae859244a
06:49:57 PM Lua: [Updates] Received update data for 'payday2bltdll'
06:49:506:51:02 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
06:51:06 PM Log:  (..\src\http\http.cpp:44) CURL_INITD
06:51:06 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
06:51:06 PM Lua: [BLT] Setup...
06:51:06 PM Lua: [BLT] Loading module: 	BLTLogs
06:51:06 PM Lua: [BLT] Loading module: 	BLTModManager
06:51:06 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
06:51:06 PM Lua: [BLT] Loading module: 	BLTPersistScripts
06:51:06 PM Lua: [BLT] Loading module: 	BLTLocalization
06:51:06 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
06:51:06 PM Lua: [BLT] Loading mods for state: table: 0x001e0440
06:51:06 PM Lua: [BLT] Loading mod: base
06:51:06 PM Lua: [BLT] Loading mod: WolfHUD
06:51:06 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
06:51:06 PM Lua: [BLT] Setting up mod: 	base
06:51:06 PM Lua: [BLT] Setting up mod: 	WolfHUD
06:51:06 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
06:51:06 PM Lua: [BLT] Setup...
06:51:06 PM Lua: [BLT] Loading module: 	BLTLogs
06:51:06 PM Lua: [BLT] Loading module: 	BLTModManager
06:51:06 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
06:51:06 PM Lua: [BLT] Loading module: 	BLTPersistScripts
06:51:06 PM Lua: [BLT] Loading module: 	BLTLocalization
06:51:06 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
06:51:06 PM Lua: [BLT] Loading mods for state: table: 0x001e0460
06:51:06 PM Lua: [BLT] Loading mod: base
06:51:06 PM Lua: [BLT] Loading mod: WolfHUD
06:51:06 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
06:51:06 PM Lua: [BLT] Setting up mod: 	base
06:51:06 PM Lua: [BLT] Setting up mod: 	WolfHUD
06:51:07 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
06:51:07 PM Lua: [BLT] Setup...
06:51:07 PM Lua: [BLT] Loading module: 	BLTLogs
06:51:07 PM Lua: [BLT] Loading module: 	BLTModManager
06:51:07 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
06:51:07 PM Lua: [BLT] Loading module: 	BLTPersistScripts
06:51:07 PM Lua: [BLT] Loading module: 	BLTLocalization
06:51:07 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
06:51:07 PM Lua: [BLT] Loading mods for state: table: 0x28090520
06:51:07 PM Lua: [BLT] Loading mod: base
06:51:07 PM Lua: [BLT] Loading mod: WolfHUD
**06:51:07 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...**
06:51:07 PM Lua: [BLT] Setting up mod: 	base
06:51:07 PM Lua: [BLT] Setting up mod: 	WolfHUD
06:51:19 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:51:19 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt - 1676
06:51:19 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:51:19 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:51:19 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2bltdll - 1679
06:51:19 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:51:19 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:51:19 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud - 1673
06:51:19 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:51:19 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:51:19 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud_textures - 1664
06:51:19 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:51:19 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
06:51:19 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=fed_inv - 1663
06:51:19 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
06:51:19 PM Lua: [Updates] Received update data for 'payday2blt'
06:51:19 PM Lua: [Updates] Comparing hash data:
Server: dd606e7e10e0d02d3527b6d38ca6f4d2aa58910d56d81753b16b808ae859244a
 Local: dd606e7e10e0d02d3527b6d38ca6f4d2aa58910d56d81753b16b808ae859244a
06:51:19 PM Lua: [Updates] Received update data for 'payday2bltdll'
06:51:1

**Comment by HadesDurin** [comment]
i recommend to update both and see if it happens again

**Comment by SirTartcube** [comment]
I've updated both from github and paydaymods

**Comment by HadesDurin** [comment]
delete wolfhud and try only blt
atm it looks like blt is missing stuff
Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...

**Comment by Kamikaze94** [comment]
Maybe taking a look at the actual crash report will shine some light ("%localappdata%/Payday 2/crash.txt").
That one should tell you the exact reason why its crashing.
Other than that, you probably should look into why the blt_data.txt is missing or create it if necessary.
(_That file stores info on which of your mods are enabled, which update checks are enabled and the keybinds you set up._)

**Comment by SirTartcube** [comment]
I cannot find any crash.txt just the general log files. How could I go about making the bltdata_txt. I know how to create and name a txt file but is there anything that needs to be in said txt file?
