### ISSUE TITLE
Random crashes - unitnetworkhandler.lua:1164

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#56]
Please, can you check if this crash causing by WolfHUD in code strings?

Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:1164: attempt to index local 'unit' (a nil value)

SCRIPT STACK
---

Callstack:

```
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     zip_get_name                                        
                     ntdll  (???)     RtlReAllocateHeap                                   
                     ntdll  (???)     ZwQueryVirtualMemory                                
                KERNELBASE  (???)     VirtualQueryEx                                      
                KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                KERNELBASE  (???)     SetUnhandledExceptionFilter                         
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     zip_get_name                                        
```
---

**Comment by Malidictus** [comment]
Is that with the latest Dev Build? Both I and a few others were having this issue today and yesterday, but it seemed to fix itself when we got the Dev Build.

**Comment by Kamikaze94** [comment]
Crash is about Sentry Health ratio sync.
Might be related to changes made for issue #42.

**Comment by Tatsugi** [comment]
Yes, I'm using latest dev build, but it's just random crashes, no any Sentry on the heist. It can be get even just by minimize and expand game window in preplanning, game will stay with black screen some seconds then crash.
