### ISSUE TITLE
Uninstall an Re-Download

### ISSUE THREAD

**Issue by Magnum180** [Kamikaze94/WolfHUD#566]
Hello, due to a bug, i want to completly uninstall the mod and BLT and re-download the latest version.
So, can someone tell me how to copletly uninstall both of them and how re-install them ? (it's been a while since the first download i don't remember)

**Comment by johnneijzen** [comment]
to remove BLT and WolfHud
first go to payday 2 folder and remove IPHLPAPI.dll and mods folder. 
if you have download game before BLT 2 check in
assets if there is mod_overrides folder and delete it
