### ISSUE TITLE
Suggestion: Player name fading when using the bipod

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#57]
Right now, if you aim down sights and aim in the direction of players, their floating name labels disappear. This is done, I presume, to clear line of sight and prevent the name labels from obscuring targets. This is good and I like it very much.

However, this doesn't work when a bipod is deployed. When bipodded, team-mate names will often obscure my targets if I'm trying to assist them, and I can't "aim down sights" to make them go away - there's no ADS with a bipod. I would suggest applying the same logic for clearing name labels when one is in a bipod state as when one is aiming down sights.

**Comment by Kamikaze94** [comment]
Hmm, this one is a little problematic.
If I define the Pipod state as "is_steelsight", you ADS while in Bipod, obscuring your screen even more. :P
To edit this behaviour, I'd either have to temporairly exchange the function, that determines, if you are in steelsight, and hope no other function calls it in the meantime (bad idea, better not to do, ^^), or copy'n'paste a whole bunch of Overkills code, that will break, if they decide to update it...  (Currently functional, but who knows for how long...?)

Have you tried reporting that to the Bug Reporting section on steam and get Overkill themselfes to fix this?
It would take them literaly 45 chars to fix.
_(Just adding something like 'or managers.player:current_state() == "bipod"' to the condition for 'local in_steelsight')_

**Comment by Malidictus** [comment]
Oh, I didn't realise that was a base game function! Sorry, I'll try and bring that up with Overkill. Although given them, I doubt it will accomplish anything :) Nevertheless, thanks for having a look. Feel free to close this.
