### ISSUE TITLE
"wolfhud textures" and "federal inventory" never finish installing

### ISSUE THREAD

**Issue by AxelYEY** [Kamikaze94/WolfHUD#571]
Hello, the recent updates from the download manager are not installed, it is never finished verifying.
Is it a bug only in my case or general?

**Comment by deepjb** [comment]
it also happens to me

**Comment by HadesDurin** [comment]
just relog into the game and do the update again, then it should work

**Comment by AxelYEY** [comment]
still no update

**Comment by ThisisturtiM** [comment]
me 2

**Comment by deepjb** [comment]
I did this after the download process:
1- close the game
2- navigate to "C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\assets" and create a folder called "mod_overrides"
3- navigate to "C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\mods\downloads"
4- decompress both zip archives "fed_inv" and "wolfhud_textures" inside "mod_overrides"
5- launch the game and check

**Comment by AxelYEY** [comment]
Solved just by creating the folder "mod_overrides", thanks Deepjb

**Comment by Habbsy1** [comment]
hey i made the mod overrides folder but that dint do anything and i dont have the zips for fed_inv or wolfhud_texures where can i get them from as they are not in my wolfhud mod files

**Comment by EAwemond02** [comment]
how do i decompress them

**Comment by NexExMachina** [comment]
I also have this issue mod_overrides folder already existed

**Comment by Kamikaze94** [comment]
paydaymods.com is quite unstable and not responding a lot.
You can always try to manually download federal inventory:
http://download.paydaymods.com/download/latest/fed_inv
Then extract the archive into the mod_overrides folder, as described previously.

The latest version of WolfHUD requires SuperBLT now and comes with wolfhud_textures. 
So it's no longer needed after the update :)
