### ISSUE TITLE
Question: How does one control WolfHUD Textures and Federal Inventory?

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#572]
Unlike WolfHUD itself, neither WolfHUD Textures nor Federal Inventory show up in the BLT Mods menu (because they're not BLT mods, I know). Is there any way to control those from inside the game, however? In particular, I'd like to not use the Federal Inventory icons but I'd also like to not have a permanent 1 mod to update. Is there any way I can download the icons but optionally not use them? Say, an option in WolfHUD's own options menu where "real weapon names" are toggled on and off?

**Comment by deepjb** [comment]
well I did this and it is working for me...
find a file named "Core.lua" within "C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\mods\WolfHUD" open it using a text editor like notepad or notepad++ and look for
`MOD_OVERRIDES = {
				fed_inv									= true,
			},`
and change it for
`MOD_OVERRIDES = {
				fed_inv									= false,
			},`
it only will disable Federal Inventory Icons

**Comment by Malidictus** [comment]
Thank you for the advise. I'll try that myself. I was kind of hoping for some in-game option to do that, though - I presume there isn't one?

**Comment by Malidictus** [comment]
Come to think of it, can I re-phrase this as a suggestion? Can we have the option to display or hide the Federal Inventory icons?
