### ISSUE TITLE
Game crush when mission started after black screen

### ISSUE THREAD

**Issue by GitssacFao** [Kamikaze94/WolfHUD#579]
----------------------------------------------------------------------

Sat Nov 18 23:33:53 2017

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3273: attempt to call method '_total_armor' (a nil value)

SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3271
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3271
_regenerate_armor() lib/units/beings/player/playerdamage.lua:533
replenish() lib/units/beings/player/playerdamage.lua:519
init_original() lib/units/beings/player/playerdamage.lua:33
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3147
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3147
@mods/WolfHUD/lua/GameInfoManager.lua:3147
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2126
spawn_players() lib/network/base/basenetworksession.lua:1498
update_original() lib/states/ingamewaitingforplayers.lua:262
update() @mods/WolfHUD/lua/MenuTweaks.lua:284
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:784
update() lib/setups/gamesetup.lua:654
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 760 / nvldumd.dll[23.21.13.8813]
	Language : english
	Memory :     16311MB 1016KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Głośniki (Realtek High Definition Audio))

**Comment by GitssacFao** [comment]
I've Silent Assassin Mod and game working without WolfHUD.

**Comment by Kamikaze94** [comment]
Duplicate of #493.
Also fixed, you just need to update with the latest version. 
(Green button in the top right of the main github repo, labeled "Clone or download" )

**Comment by GitssacFao** [comment]
Thanks!
