### ISSUE TITLE
CustomWaypoints & EnemyHealthbar need an update with the H3H3 update release

### ISSUE THREAD

**Issue by jtmal0723** [Kamikaze94/WolfHUD#585]
# Prerequisites

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Hovering over the new heisters Hila and Ethan should state their name correctly on the health bar that appears - "Hila" for Hila, and "Ethan" for Ethan.

# Current Behavior

Hovering over the new heisters' health bars shows their in game code name of "ecp_male" for Ethan, and "ecp_female" for Hila.

**Comment by namhbnam** [comment]
im lost the music game
