### ISSUE TITLE
Tab Charater.....icon....fix..

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#59]
![20160909054506_1](https://cloud.githubusercontent.com/assets/21234977/18366268/fa68d3e2-7650-11e6-833b-07203efd411d.jpg)
![20160909054541_1](https://cloud.githubusercontent.com/assets/21234977/18366269/fa6f2c56-7650-11e6-884b-724ce965bac8.jpg)
![20160909054621_1](https://cloud.githubusercontent.com/assets/21234977/18366275/ff424ccc-7650-11e6-9d84-a855ec37134e.jpg)
![20160909054355_1](https://cloud.githubusercontent.com/assets/21234977/18366271/fa8506f2-7650-11e6-9ae6-a5aae0930b51.jpg)
![20160909054237_1](https://cloud.githubusercontent.com/assets/21234977/18366270/fa7629ac-7650-11e6-96b2-160cfb64f393.jpg)

clover.....Tab.....Charater.....icon.....;;;;fix please....

**Comment by Kamikaze94** [comment]
Lol, lots of screens, ^^
And yep, seems like the texture path is fcked up.
Will fix that in a sec :)

**Comment by Tatsugi** [comment]
Maybe you will add an option to disable entire icon? Beacuse it's too huge and to be honest this multicolored masks annoying me.
