### ISSUE TITLE
Disable Federal Inventory?

### ISSUE THREAD

**Issue by FaizanMughal** [Kamikaze94/WolfHUD#591]
I would really like there to be an option to disable Federal Inventory. It was there before but it's gone now? the BLT updater asks me to update Federal Inventory if I delete its files and there's that blaring red indicator. I can't find any option to disable Federal Inventory. I tried adding a revision.txt to the Federal Inventory folder but the BLT updater rejects it, asks me to update the mod, and then ends up removing my revisions.txt file. WolfHUD no longer has an option in the settings to disable Federal Inventory and even when I opened the Core.lua file for WoldHUD and set fed_inv to false, the BLT still insists I update Federal Inventory. 

An option to exclude Federal Inventory from WolfHUD would be VERY much appreciated.

**Comment by DeadneM** [comment]
Mod.txt remove depencies and update
