### ISSUE TITLE
Crash when joining any lobby

### ISSUE THREAD

**Issue by Solid6969** [Kamikaze94/WolfHUD#592]
Everytime I use wolfhud and joining any lobby the game crashes and the crash log doesnt say anything related to wolfhud but just this
-------------------------------------------------------------------------------------------------------------------
Sat Nov 25 11:59:01 2017

Application has crashed: C++ exception
[string "core/lib/managers/mission/coremissionscriptel..."]:113: attempt to index a nil value

SCRIPT STACK

on_executed() lib/managers/mission/missionscriptelement.lua:18
_on_script_activated() core/lib/managers/mission/coremissionmanager.lua:514
activate() core/lib/managers/mission/coremissionmanager.lua:505
activate() lib/managers/missionmanager.lua:412
activate_script() core/lib/managers/mission/coremissionmanager.lua:154
activate_script() lib/managers/missionmanager.lua:283
_activate_mission() core/lib/managers/mission/coremissionmanager.lua:137
parse() core/lib/managers/mission/coremissionmanager.lua:84
init_game() lib/setups/gamesetup.lua:598
core/lib/setups/coresetup.lua:402

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.455.
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960M / nvldumd.dll[23.21.13.8831]
	Language : english
	Memory :     12173MB 672KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

-------------------------------------------------------------------------------------------------------------------
Or sometimes this
-------------------------------------------------------------------------------------------------------------------
Sat Nov 25 03:47:25 2017

Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:121: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:422

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.455.
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960M / nvldumd.dll[23.21.13.8831]
	Language : english
	Memory :     12173MB 672KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Rathard** [comment]
Same for me

**Comment by deepjb** [comment]
just crashed loading Boiling Point
```
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                                lib/units/cameras/fpcameraplayerbase.lua:1743       
               play_redirect()                                                      
                          =[C]  play_redirect()                                     
                                lib/units/cameras/fpcameraplayerbase.lua:1145       
               play_redirect()                                                      
lib/units/beings/player/playercamera.lua:110  _start_action_equip()                               
                                lib/units/beings/player/states/playerstandard.lua:1677  
                      _enter()                                                      
lib/units/beings/player/states/playerstandard.lua:276  enter_original()                                    
                                lib/units/beings/player/states/playerstandard.lua:201  
                       enter()                                                      
@mods/WolfHUD/lua/Interaction.lua:75  change_state()                                      
                                lib/units/beings/player/playermovement.lua:259      
        _change_player_state()                                                      
lib/managers/playermanager.lua:928  spawned_player_original()                           
                                lib/managers/playermanager.lua:904                  
              spawned_player()                                                      
@mods/WolfHUD/lua/GameInfoManager.lua:2732  set_unit()                                          
                                lib/network/base/networkpeer.lua:2249               
lib/network/handlers/unitnetworkhandler.lua:48  

```

**Comment by HadesDurin** [comment]
check your blt version and if its up to date
