### ISSUE TITLE
Crash When Press TAB

### ISSUE THREAD

**Issue by Keinzo913** [Kamikaze94/WolfHUD#594]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [v] I am running the latest version
- [ ] I made sure this issue doesn't persist without this mod
- [v] I checked to make sure that this issue has not already been filed

game crash when I press TAB in the heist

this the crash log

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:1017: attempt to call method 'feed_heist_time' (a nil value)

SCRIPT STACK

update() lib/managers/gameplaycentralmanager.lua:202
update() lib/setups/gamesetup.lua:665
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.455.
	CPU : Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 920M / nvldumd.dll[23.21.13.8831]
	Language : english
	Memory :     6063MB 804KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Conexant (Speakers (Conexant SmartAudio HD))

**Comment by MEXAHOTABOP** [comment]
feed_heist_time and modify_heist_time now in hudmanagerpd2
as tempory workaround you can in file 
https://github.com/Kamikaze94/WolfHUD/blob/master/lua/TabStats.lua#L1269
change 
`elseif string.lower(RequiredScript) == "lib/managers/hudmanager" then`
with
`elseif string.lower(RequiredScript) == "lib/managers/hudmanagerpd2" then`
and comment or remove update_stats_screen and change_tabstats_setting functions 

right now i dont have pd2 to test it but i think after this changes game will work

**Comment by Keinzo913** [comment]
@MEXAHOTABOP thanks it's work, but when i shoot the police or NPC, then i get force close, here the crashlog : 

Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:907: attempt to call method 'update_stats_screen' (a nil value)



SCRIPT STACK

_on_damage_received() @mods/WolfHUD/lua/TabStats.lua:870
damage_explosion() lib/units/enemies/cop/copdamage.lua:1305
detect_and_give_dmg() lib/managers/explosionmanager.lua:409
_detonate() lib/units/weapons/grenades/fraggrenade.lua:92
func() lib/units/weapons/grenades/fraggrenade.lua:56
body_collision_callback() core/lib/units/coreunitdamage.lua:1522
lib/units/unitdamage.lua:92


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.83.455.
	CPU : Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 920M / nvldumd.dll[23.21.13.8831]
	Language : english
	Memory :     6063MB 804KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Conexant (Speakers (Conexant SmartAudio HD))

**Comment by MEXAHOTABOP** [comment]
my bad add 
`elseif string.lower(RequiredScript) == "lib/managers/hudmanager" then` 
before 
`function HUDManager:update_stats_screen(item)`

**Comment by HadesDurin** [comment]
do you have any tracked achievments?

**Comment by Keinzo913** [comment]
@MEXAHOTABOP thank you so much it's supper working 👍

**Comment by MEXAHOTABOP** [comment]
its not solution this just workaround
better keep bug opened until @Kamikaze94 fix this or say what was wrong

**Comment by HadesDurin** [comment]
@Keinzo913 are you tracking achievments?

**Comment by xBlInDx** [comment]
----------------------------------------------------------------------

Fri Jan 26 22:19:30 2018


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                set_progress()  lib/managers/menu/extendeduielemets.lua:706         
                set_progress()  lib/managers/menu/extendeduielemets.lua:767         
             update_progress()  lib/managers/hud/newhudstatsscreen.lua:57           
             update_original()  lib/managers/hud/newhudstatsscreen.lua:440          
                          cb()  @mods/WolfHUD-master/lua/TabStats.lua:187           
                      update()  lib/managers/hudmanager.lua:710                     
                      update()  lib/setups/gamesetup.lua:705                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537                   

-------------------------------
I am getting same issue now with new PD2 patch (UPDATE 171) that came yesterday. Any ideas on how to fix it or if update is coming in soon?
