### ISSUE TITLE
core.lua issues

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#6]
The mod still runs, but the log fills with the below
```
Lua: [Hooks] Error: Could not hook function '
FATAL ERROR: mods/WolfHUD/Core.lua
FATAL ERROR: mods/WolfHUD/Core.lua:532: attempt to index global 'HUDManager' (a nil value)
 Lua: [Hooks] Error: Could not hook function '
```

**Comment by Kamikaze94** [comment]
Hmm, that stuff down there is quite experimental, tried to add levels in kick menu and joining dialog, as well as removing level in players 'over-head' labels....
Only the kick levels seem to work, the rest is kinda broken and needs some more work....  :/

Added a check for HUDManager for now, so that error goes away.
Not quite sure, which of the other two Hooks isn't possible to hook into, will try that out later...

**Comment by Hulkfog** [comment]
I thought kick levels were in the base game?
https://bitbucket.org/YaPh1l/payday-2-lua/src/17e0723084141b791a4ce490a022ba5c43f58bd1/lib/managers/menumanager.lua?at=master&fileviewer=file-view-default
```
KickPlayer = KickPlayer or class()
function KickPlayer:modify_node(node, up)
	node:clean_items()
	if managers.network:session() then
		for _, peer in pairs(managers.network:session():peers()) do
			local params = {
				name = peer:name(),
				text_id = peer:name() .. " (" .. (peer:rank() > 0 and managers.experience:rank_string(peer:rank()) .. "-" or "") .. (peer:level() or "") .. ")",
				callback = "kick_player",
				to_upper = false,
				rpc = peer:rpc(),
				peer = peer,
				help_id = peer:is_host() and managers.localization:text("menu_vote_kick_is_host") or managers.vote:option_vote_kick() and managers.vote:help_text() or "",
				localize = false,
				localize_help = false
			}
			local new_item = node:create_item(nil, params)
			if peer:is_host() or managers.vote:option_vote_kick() and not managers.vote:available() then
				new_item:set_enabled(false)
			end
			node:add_item(new_item)
		end
	end
	managers.menu:add_back_button(node)
	return node
end
```

Try BaseNetworkSession for the joining dialog  and menumanagerdialog

**Comment by Kamikaze94** [comment]
Uhm, how could I overlook that.... removed it now.
Now I feel stupid, xD

The other errors resulted out of the 'MenuNodeMainGui' not beeing present, when Core.lua got called.
Added a check for that now.

Also moved the other stuff out of core, into more apprpriate places.
Yeah, for the joining, I'm already in menumanagerdialog, but I'm not quite sure, if my code isn't working, or the level just syncing too late. Only tested it with 2 or 3 players, and for those it didn't show up...

**Comment by Hulkfog** [comment]
Managed to get the player rank to show
```
function MenuManager:show_person_joining(id, nick)
		local dialog_data = {}
		local peer = managers.network:session():peer(id)
		local name = nick
		name = name .. " (" .. (peer:rank() > 0 and managers.experience:rank_string(peer:rank()) .. "-" or "") .. peer:level() .. ")"
		dialog_data.title = managers.localization:text("dialog_dropin_title", {
			USER = string.upper(name)
		})
		dialog_data.text = managers.localization:text("dialog_wait") .. " 0%"
		dialog_data.id = "user_dropin" .. id
		dialog_data.no_buttons = true
		managers.system_menu:show(dialog_data)
	end
```
