### ISSUE TITLE
Crash Coplogicattack

### ISSUE THREAD

**Issue by benya00** [Kamikaze94/WolfHUD#602]
good evening, voila, I had several times a crash which is caused by the CopLogicattack.Lua, knew you that it is done off for more to have problem.

Regards Benya00

---------------------------------------------------------------------

Fri Dec 08 22:22:41 2017

Application has crashed: C++ exception
[string "lib/units/enemies/cop/logics/coplogicattack.lua"]:1080: attempt to index field 'weapon_range' (a nil value)

SCRIPT STACK

clbk() lib/units/player_team/logics/teamailogictravel.lua:225
_execute_queued_task() lib/managers/enemymanager.lua:549
_update_queued_tasks() lib/managers/enemymanager.lua:558
update() lib/managers/enemymanager.lua:49
update() lib/setups/gamesetup.lua:659
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.84.463.
	CPU : Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960 / nvldumd.dll[23.21.13.8831]
	Language : french
	Memory :     7865MB 452KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Haut-parleurs (C-Media USB Headphone Set  ))

**Comment by MEXAHOTABOP** [comment]
looks like not a wolfhud problem
you use other mods?

**Comment by benya00** [comment]
I have BeardLib for some custom music , KeepTheMusic , and WolfHud

**Comment by MEXAHOTABOP** [comment]
try remove all mods except base and wolfhud

**Comment by benya00** [comment]
ok i try this
