### ISSUE TITLE
Attempt to index field on blt4l

### ISSUE THREAD

**Issue by dasJ** [Kamikaze94/WolfHUD#603]
# Prerequisites

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

I expect WolfHud to work on [blt4l](https://github.com/blt4linux/blt4l).

# Current Behavior

The game shows "Loading" with the spinner, then the screen blanks. When checking the console, it seems to loop forever with the same messages.
```
Error: lua_call: error in lua_pcall: [string \"core/lib/setups/coresetup.lua\"]:468: attempt to index field 'controller' (a nil value)
Error: lua_call: error in lua_pcall: [string \"core/lib/setups/coresetup.lua\"]:577: attempt to index field 'camera' (a nil value)
Error: lua_call: error in lua_pcall: [string \"core/lib/setups/coresetup.lua\"]:599: attempt to index field 'portal' (a nil value)
Error: lua_call: error in lua_pcall: [string \"core/lib/setups/coresetup.lua\"]:608: attempt to index field 'viewport' (a nil value)
```

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install blt4l
2. Install WolfHud
3. Start the game

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Arch Linux (running native steam)
* BLT version: blt4l 2.0 RC1
* Other mods installed:
  * Flashing Swan Song
  * Lobby Player Info
  * Reload Then Run
  * RestoreDLCNames
  * Side Jobs in Lobby
  * StraightToMainMenu

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

> The folder wasn't created. I hope the log above helps.

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

> The folder wasn't created. I hope the log above helps.
> Also, I don't have `%LOCALAPPDATA%`

**Comment by MEXAHOTABOP** [comment]
first of all try reinstall blt4l  
mods/logs/ is part of base mod 

next check:
1) with only base mod installed
2) with your mods and without wolfhud
3) with wolfhud and base mod and without any other mods

**Comment by dasJ** [comment]
My base mod was out of date. Switching to the new one fixed it
