### ISSUE TITLE
Confusion [Not a Bug]

### ISSUE THREAD

**Issue by Lisbonmaru** [Kamikaze94/WolfHUD#606]
# My Apologies

Sorry for deleting the template, but it was confusing and I didn't understand how to use any of it. It's 6 am by the time I've sent this. So, that's my excuse.

# The Issue

I have just about no clue why or how this happened, I've followed all of the steps correctly, and most of the parts of the mods work. The only issue is that when I go into BLT Mods it says I need to download 2 updates for WolfHUD. Being: WolfHUD textures, and Federal Inventory.  Most of the Federal inventory worked even before I manually downloaded it, but when I would restart my game, it would still say that I need to update Federal Inventory and WolfHUD.
**V V V V   The actually Useful Part   V V V V**
I download both of them until it reaches the "Verifying..." part, but it does it forever. I've waited 10 minutes and it hasn't changed. Also, I cant seem to find the settings for the WolfHud mod.

# Screenshot from Steam

https://steamuserimages-a.akamaihd.net/ugc/878630070085158683/9C6B9B376FE2BAB15C3860208864128AAB7F6CBE/

**Any help or suggestions, questions would be appreciated!**

**Comment by svenified** [comment]
I solved this issue by creating the same folder structure from the mods if you would have downloaded them separately. You are most likely missing a directory called "mod_overrides" from your "Payday2/assets" directory. Just add that directory. It should be "PAYDAY2/assets/mod_overrides". Reboot your game, then try the update again.

**Comment by Lisbonmaru** [comment]
> I solved this issue by creating the same folder structure from the mods if you would have downloaded them separately. You are most likely missing a directory called "mod_overrides" from your "Payday2/assets" directory. Just add that directory. It should be "PAYDAY2/assets/mod_overrides". Reboot your game, then try the update again.

Thank you very much, it worked! But now I have the issue of when I fully load into a game, my game crashes.

**Comment by svenified** [comment]
Would you mind posting your most recent entry of your crash log?

**Comment by Lisbonmaru** [comment]
Im sorry but I didnt get one when my game decided to die. Unless its somewhere saved in my files, if so, where?
