### ISSUE TITLE
Crash on the new Reservoir Dogs heist

### ISSUE THREAD

**Issue by Dxngoh** [Kamikaze94/WolfHUD#608]
EDIT: Vanilla issue, patched in latest update.
You can still complete the heist but can't use this button ( https://i.imgur.com/KC0q9e2.png ). Happened on Day 1 at the end of the heist.

Application has crashed: C++ exception
[string "lib/units/interactions/interactionext.lua"]:230: attempt to index a nil value

SCRIPT STACK

_update_targeted_original() lib/managers/objectinteractionmanager.lua:378
_update_targeted() @mods/WolfHUD/lua/Interaction.lua:480
update_original() lib/managers/objectinteractionmanager.lua:54
update() @mods/WolfHUD/lua/GameInfoManager.lua:2098
update() lib/setups/gamesetup.lua:699
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

**Comment by xanaguy** [comment]
That issue is vanilla. There is something here highlighted in yellow when you get close. The crash happens immediately after. Do NOT get close to it. https://imgur.com/TRNG5QF (After choosing to escape and after blasting the doors)

**Comment by Ongjming** [comment]
http://store.steampowered.com/news/externalpost/steam_community_announcements/2442505391476375910
It just gotten a hotfix patch.
