### ISSUE TITLE
Not really a bug, just naming (New NPC from new heist)

### ISSUE THREAD

**Issue by Ongjming** [Kamikaze94/WolfHUD#610]
The new guy Mr blonde in day 1 (pasted over with day 2) when you hover over him to show his name using the hud, it defaults to Locke.
I forgot about the other 2 NPC but I think they have some generic name too.

Mr Blond named as Locke in that heist was more memorable.

**Comment by xanaguy** [comment]
Mr. Blond = Locke. Mr. Pink = Taxman 

Kamikaze94, the internal name is "rvd" for when you get around to it.

**Comment by svenified** [comment]
For Ethan and Hila there are some placeholders showing for their names.
