### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Hunter7090** [Kamikaze94/WolfHUD#612]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version
- [ yes] I made sure this issue doesn't persist without this mod
- [ yes] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* BLT version:
* Other mods installed:
* ...

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   [Please paste your BLT log here.]

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   [Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
            _do_action_melee()  lib/units/beings/player/states/playerstandard.lua:2684  
         _check_action_melee()  lib/units/beings/player/states/playerstandard.lua:2478  
       _update_check_actions()  lib/units/beings/player/states/playerstandard.lua:884  
             update_original()  lib/units/beings/player/states/playerstandard.lua:424  
                      update()  @mods/WolfHUD-master/lua/BurstFire.lua:212          
                                lib/units/beings/player/playermovement.lua:324      

-------------------------------

System information:
	Application version : 1.86.491.
	CPU : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0 
	GPU : NVIDIA GeForce 210  / nvd3dum.dll[21.21.13.4200]
	Language : spanish
	Memory :     16330MB 340KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoces (Realtek High Definition Audio))

]

Sorry if i not complete all the questionary. my english is not good. but im sure the bug is for a update. i hope the crash log can be useful for future fix

**Comment by Shad0wlife** [comment]
Seriously? Please fill the form that you posted so nicely, but sadly empty. Then it would be much easier to troublshoot.
