### ISSUE TITLE
Crash while loading heist

### ISSUE THREAD

**Issue by DrWuppmann** [Kamikaze94/WolfHUD#613]
# Prerequisites

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [ ] I checked to make sure that this issue has not already been filed

# Expected Behavior

The Game should launch into the selected heist

# Current Behavior

The game freezes when loading the heist, after clicking on ready. After a few seconds, the game crashes to desktop.

# Failure Information (for bugs)
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to launch into a offline heist (I tried multiple heists and configurations of WolfHUD)
2. Click ready
3. Game will freeze and crash shortly thereafter

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux (Manjaro)
* Other mods installed: Disable Crimespree Reset on Crash (bleh), Jump

## BLT log

PS: Removed Jump Mod, still crashing

<details> 
  <summary>BLT Log</summary>

09:44:11 AM Info: Loading BLT Base
09:44:11 AM Lua: [Mods] Loading mods for state (table: 0x0a87ff00)
09:44:11 AM Lua: [Mods] Loading mod: base...
09:44:11 AM Lua: [Mods] Loading mod: bleh...
09:44:11 AM Lua: [Mods] Loading mod: Jump...
09:44:11 AM Lua: [Mods] Loading mod: WolfHUD...
09:44:11 AM Lua: [Error] Could not load revision file for WolfHUD Textures!
09:44:11 AM Lua: [Error] Could not load revision file for Federal Inventory!
09:44:11 AM Error: LUAErrRun loading LUA file mods/Jump/jump.lua
09:44:11 AM Error: mods/Jump/jump.lua:1: attempt to index global 'PlayerStandard' (a nil value)
09:44:11 AM Error: LUAErrRun loading LUA file mods/WolfHUD/lua/GameInfoManager.lua
09:44:11 AM Error: mods/WolfHUD/lua/GameInfoManager.lua:3430: attempt to index a nil value

</details>

## Crash log(s)

<details> 
  <summary>Crash.txt</summary>

   Lua runtime error: mods/WolfHUD/lua/GameInfoManager.lua:3273: attempt to call method '_total_armor' (a nil value)

stack traceback:
	mods/WolfHUD/lua/GameInfoManager.lua:3273: in function 'set_armor_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3271: in function 'set_armor_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3271: in function 'set_armor'
	[string "lib/units/beings/player/playerdamage.lua"]:578: in function '_regenerate_armor'
	[string "lib/units/beings/player/playerdamage.lua"]:564: in function 'replenish'
	[string "lib/units/beings/player/playerdamage.lua"]:33: in function 'init_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3147: in function 'init_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3147: in function 'init_original'
	mods/WolfHUD/lua/GameInfoManager.lua:3147: in function <mods/WolfHUD/lua/GameInfoManager.lua:3146>
	[C]: in function 'spawn_unit'
	[string "lib/network/base/networkpeer.lua"]:2151: in function 'spawn_unit'
	[string "lib/network/base/basenetworksession.lua"]:1511: in function 'spawn_players'
	[string "lib/states/ingamewaitingforplayers.lua"]:277: in function 'update_original'
	mods/WolfHUD/lua/MenuTweaks.lua:284: in function 'update'
	[string "core/lib/utils/game_state_machine/coregamesta..."]:92: in function 'update'
	[string "lib/setups/setup.lua"]:844: in function 'update'
	[string "lib/setups/gamesetup.lua"]:696: in function 'update'
	[string "lib/setups/networkgamesetup.lua"]:21: in function 'update'
	[string "core/lib/setups/coresetup.lua"]:537: in function <[string "core/lib/setups/coresetup.lua"]:459>

</details>

**Comment by johnneijzen** [comment]
hmm weird I don't that much about Linux but something tells me that BLT4L is not running properly.
maybe try to reinstall BLT4L https://github.com/blt4linux/blt4l using clone repository and run install.sh

**Comment by moge42** [comment]
I have the same problem using windows with newest BLT update and only wolfhud installed

**Comment by repoman728** [comment]
gents 
as much I like  wolfhud  and Have tried few combinations to run it as it has crashed during loading  the heist. also have been waiting for new   fixed release so now I am fed up with that hud and changed to Syndeyhud : https://modworkshop.net/mydownloads.php?action=view_down&did=18716, tested and this one works fine even after game update, I recommend sydneyhud for everybody who likes wolfhud , it is very much  similar  !!
