### ISSUE TITLE
Chinese localization text

### ISSUE THREAD

**Issue by CoolLKK** [Kamikaze94/WolfHUD#615]
Hello, I used WolfHUD, but I can not switch to Chinese
As the game does not support Chinese, I tried to change the BLT language to Chinese, no effect, so I am here to make suggestions
1.WolfHUD should automatically recognize the BLT language, because the game itself is not Chinese, I will provide the Chinese patch, because the Chinese localized text must be operated under the Chinese patch
https://drive.google.com/folderview?id=1wG_Jhvtzh_CzdIoiddqVdMHFaYWuMwST
2.I made a change to the Chinese localization text, but it is not completely modified. Below is a link, I will provide an update on the Chinese localization text in this link
https://drive.google.com/folderview?id=1ifzoeCjQCOFHfNnaJfP4fsyZDCJhx5CN

At the same time I updated WolfHUD in the past is a failure, which impressed me, I hope later WolfHUD can be updated normally
And hope mod can appear in paydaymod website, I use this website more often

MOD FEEDBACK
In the "endless police assault," should prompt the player's message is: Endless police assault in progress        ///        leave as soon as possible
Use 8 + 8 times the space key
Hope to adopt, this mod is very nice

**Comment by zhongfly** [comment]
use pull requests to update my chinese translation
If you want to use chinese in this mod, just rename "chinese.json" to "english.json"
