### ISSUE TITLE
Compatibility with Lobby Player Info

### ISSUE THREAD

**Issue by WeaselKek** [Kamikaze94/WolfHUD#616]
This issue persisted ever since the Lobby player info mod was updated [LPI](http://paydaymods.com/mods/41/LPI)
This is the current behavior where the player info overlaps with the other tab stats: [Image](https://i.imgur.com/DabhGqj.jpg).
In the earlier versions player info was always under tab stats.

**Comment by PJzuza** [comment]
Duplicate issue of #575 

Read it and you will understand.
