### ISSUE TITLE
Wolfhud not showing up

### ISSUE THREAD

**Issue by Zsalz** [Kamikaze94/WolfHUD#618]
Sorry, my original post didn't show up correctly. Was using mobile and messed it up. So I've been trying to use BLT to add Wolfhud to Payday 2. I followed all the instructions and put the mods folder and .dll into my payday folder. Then I downloaded Wolfhud and extracted those files to the mods folder. The first day I installed, it was working fine. I played for around 3 hours and stopped, and the next time I loaded up the game, I had no BLT interface on the main menu. Wolfhud wasn't working in game, and I had no mod options. When I went to options>mods, there was only Wolfhud_Textures and Federal Reserve, no mod options. I've tried re-installing BLT and Wolfhud, uninstalling and reinstalling my C++, I've re-installed the game twice, tried compatibility modes, unchecked "disable fullscreen optimization", and done just about everything else I've come across. The only thing I've found that I haven't yet tried is going back from Windows 10 1703 to 1607, which from what I've found seems to only be possible now if I re-install windows, which is more of a hassle than I'm really looking for. Any help or suggestions are much appreciated.

Screen shot of my Payday 2 folder
![screenshot payday 2](https://user-images.githubusercontent.com/35344249/34906272-1e1589a6-f838-11e7-939e-7f16d49a5bf6.png)

**Comment by Ongjming** [comment]
Where did you paste the wolfhud folder at? Also did you get the latest BLT? I once had some trouble getting BLT to work and it doesn't show any mod up at all in that case. Did you have other working mod?

**Comment by Zsalz** [comment]
Put BLT file in Payday 2 folder, wolfhud folder is inside the mods folder that was added by BLT. As I said, it's running BLT 2.3, which I believe is the current version. Not running any other mods (haven't ever used any except hoxhud, but I've deleted and reinstalled payday 2 since then). It's just weird to me that it worked at first and now BLT doesn't even show mod info in game. Not sure if it matters, but when I delete wolfhud and BLT folders, It still shows Federal Inventory and Wolfhud Textures in my mods options in game. Don't know if logs or anything would be helpful, but I've searched through tens of threads trying to find info on what's going wrong and haven't found a fix. I've tried running in compatibility mode, running older versions of BLT and/or Wolfhud and still no luck. I appreciate the response

**Comment by Ongjming** [comment]
Ah no need to do so drastic a thing as to downgrade the window version as mine works fine still.
Probably is the BLT, I am just a lay person but I think it is because the BLT updates in game and during that 3 hours for some reason it didn't update properly?
That is why wolfhud does not show up anymore and only federal reserve and wolfhud texture showed up.
Last time I had this too, I reinstalled BLT completely and had it working somehow.......
Maybe can try re copy pasting the BLT after deleting it from the payday folder. Remember the IPHLPAPI.dll in the main folder too.
Sorry that I cannot help more.
