### ISSUE TITLE
Kill counters and down counters still appear when disabled in options

### ISSUE THREAD

**Issue by killrhythm09** [Kamikaze94/WolfHUD#62]
Pretty much exactly as the title says. Even if I disable them, they show up (not persistently, seems to be a periodic thing where they pop up and then go away for a bit). Not sure if it's a WolfHUD thing or a conflict with another mod. I do use Poco, so I can turn that off and test if needed.

**Comment by Kamikaze94** [comment]
Alright, thge down counter had a little bug in its visibility logic.
Got that fixed now.
Thanks for the report! :)

For the Kill Counter, it didn't seem to become visible at any point. (Did about 110 Kills...)
Are you using CustomHUD, and what are your KillCounter settings?

**Comment by killrhythm09** [comment]
I don't use CustomHUD, so that may make a difference if you were using it. Here's an example screenshot I saved the other day:

http://i.imgur.com/eE1VVC6.jpg

See how it's showing up just for that one guy on the left? In this case, I have accuracy, specials, headshots, etc. disabled in addition to actually having the kill counter itself off. But it shows up on its own with different settings, and it also shows up for AI regardless of whether I turn theirs off (personally, I'm not really interested in knowing the AI killcounts).

**Comment by Kamikaze94** [comment]
The problem with the KillCounter with CustomHUD was probably, it changed visibility when the player state changed, based on your "Show Ai KillCounter"-setting.
At this point the general enable/disable setting got ignored.
Got that edited, so it should be fixed now.

**Comment by killrhythm09** [comment]
Down counters seem to be fixed, and kill counters are fixed for AI, but kill counters now show up at all times for other players when the option is disabled.

**Comment by killrhythm09** [comment]
Update: they don't show when the option is enabled. They do show when the option is disabled. Perhaps you got something backwards? :P

**Comment by Kamikaze94** [comment]
Yep, I messed up the conditions + there are unhandled situations.
Just pushed an update, that should take care of all situations.
And smoothed the detection animation, so it doesn't say detected combined with 40% or something 
(that bugged me for some time....  :P )

**Comment by killrhythm09** [comment]
Everything looks good now. As always, thanks for the quick fixes.
