### ISSUE TITLE
Game crashing when ECM active

### ISSUE THREAD

**Issue by X3n0n182** [Kamikaze94/WolfHUD#626]
# Expected Behavior

Heist should play out as normal.

# Current Behavior

Crashes my game every time I leave a heist by winning or by using the "quit to menu" option if an ECM is placed/active. The heist itself runs fine.

## Steps to Reproduce

1. Join a heist
2. Drop an ECM
3. Leave the heist by finishing it or leaving to the main menu
4. CRASHHH

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* BLT version: BLT2
* Other mods installed:

WolfHUD is the only thing I have installed that affects the HUD in any way.

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   Application has crashed: C++ exception
mods/WolfHUD-master/lua/GameInfoManager.lua:2227: attempt to index a nil value

SCRIPT STACK

destroy_original() lib/units/equipment/ecm_jammer/ecmjammerbase.lua:703
destroy_original() @mods/WolfHUD-master/lua/GameInfoManager.lua:2296
@mods/WolfHUD-master/lua/EquipmentTweaks.lua:61
unload_all_units() =[C]
core/lib/setups/coresetup.lua:625

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.86.519.
	CPU : AMD A8-7410 APU with AMD Radeon R5 Graphics (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R5 Graphics / aticfx32.dll[23.20.788.0]
	Language : english
	Memory :     7102MB 896KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : normal
	Renderer : DX9 threaded
	Sound : Razer (Speakers (Razer Surround Audio Controller))

</details>

**Comment by PJzuza** [comment]
Hmm. You don't have mods? like [Poser](https://modworkshop.net/mydownloads.php?action=view_down&did=19915)? [Bot Weapons and Equipment](https://modworkshop.net/mydownloads.php?action=view_down&did=12852)? Since those can crash the game on the end of the heist if you don't update them. Though your crash log is indeed related to WolfHUD.

**Comment by X3n0n182** [comment]
@PJzuza  Ah, don't got any of those. Only FSS, Better Bots, Iter, and Keepers that kinda relate to that. The rest I got are just FPS boosts and quality of life stuff like NGBTO, hide fog, hide modifiers tab etc. This problem didn't happen until today. All my mods are up to date.

**Comment by MEXAHOTABOP** [comment]
seems like bug 
@Kamikaze94 
https://github.com/Kamikaze94/WolfHUD/blob/master/lua/GameInfoManager.lua#L2225 for some reason called in menu
