### ISSUE TITLE
Crash on Loading Cards.

### ISSUE THREAD

**Issue by Patriot99** [Kamikaze94/WolfHUD#627]
# Prerequisites

- [Yes ] I am running the latest version

# Expected Behavior

The game crashes when the host leaves the game while loading the card hand at the end of heist

## Steps to Reproduce

1. Loading cards in progress.
2. The host leaves the game when loading.
3. The game crashes to the desktop.

## Context

* Operating System: Windows 10 Home
* BLT version: 2.3
* Other mods installed:

BadassCamera
BeardLib
Cheater Kicker
Colored Camera
CustomFOV
Day & Night Full
Disable Safehouse Raid
Drag and Drop Inventory
Hidden Content Updates
HopLib
InventoryChatAndPlayerStates
KillFeed
Lobby Inspect
Look My Gun
MainMenuStreamliner
Mod List Lite
Newbies go back to overkill
No Contract Broker Images
RandomDrillSkin
req_hide_modifiers
ToggleInteract (Script from Wolf Hud)
WolfHUD

## Crash log(s)

<details> 
  <summary>Crash.txt</summary>

Mon Feb 05 19:26:35 2018

Application has crashed: C++ exception
[string "lib/managers/hud/hudlootscreen.lua"]:1078: attempt to concatenate field 'selected' (a nil value)

SCRIPT STACK

update_original() lib/managers/menu/lootdropscreengui.lua:186
update() @mods/WolfHUD/lua/MenuTweaks.lua:644
update() lib/managers/menu/menucomponentmanager.lua:570
update() @mods/base/lua/MenuComponentManager.lua:12
update() lib/setups/setup.lua:830
update() lib/setups/gamesetup.lua:696
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
[Crash Log.txt](https://github.com/Kamikaze94/WolfHUD/files/1696487/Crash.Log.txt)

</details>

**Comment by MEXAHOTABOP** [comment]
seems like problem with other mod 
"selected" not used in post desync update code
