### ISSUE TITLE
look, for some reason wolfhud's settings just don't save after a loading screen.

### ISSUE THREAD

**Issue by SeriousCereal** [Kamikaze94/WolfHUD#629]
I've been searching the web for about an hour now, and its midnight. I'm really tired. Please Kamikaze94, just tell me how I can get my settings to save again. <3

**Comment by MEXAHOTABOP** [comment]
i dont have game right now and can say wrong patch 
you have directory PAYDAY 2/mods/saves or something like this? 
if yes: you have rights to write there?
if no: try reinstall blt because this part of main mod

**Comment by SeriousCereal** [comment]
I didn't have a saves folder, thank you very much, i reinstalled payday 2 blt and lemme check if it works

**Comment by SeriousCereal** [comment]
it works perfectly! thanks again!
