### ISSUE TITLE
Possible Sentry bug again, but not sure...

### ISSUE THREAD

**Issue by Tatsugi** [Kamikaze94/WolfHUD#63]
...maybe just game bug or incompatibility of mods.
I played with friend on Rats D1, we picked Sentries, then deployed them and when BCCFS waypoint had to marking ingredient the game crashes (with Meth Helper all is fine). But when we played on Golden Grin Casino with Sentries we don't get any crashes (because BCCFS wasn't involved respectively).
I just tested in solo with Sentries on Rats D1 with Enabled BCCFS but didn't get crash, so it can be crash in online when someone else deploying Sentry.

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
          generate_positions()  @mods/BCCFS/lua/bccfs.lua:109                       
                        init()  @mods/BCCFS/lua/bccfs.lua:126                       
                queue_dialog()  @mods/BCCFS/lua/bccfs.lua:169                       
                 on_executed()  lib/managers/mission/elementdialogue.lua:23         
          client_on_executed()  lib/managers/mission/elementdialogue.lua:10         
  client_run_mission_element()  lib/managers/missionmanager.lua:250                 
                                lib/network/handlers/unitnetworkhandler.lua:469     

-------------------------------

**Comment by hud8614** [comment]
BCCFS......Crash....
http://paydaymods.com/mods/157/BCCFS
....-_-

**Comment by Kamikaze94** [comment]
From that Callstack, it looks like a problem with BCCFS....
The part with the unitnetworkhandler is about syncing fire damage or melee damage 
(the line numbers aren't necessary the right ones in our "source", as its decompiled not necessary the games original one.)
Maybe that helps on reproducing the bug...?

I cannot really see the relation to WolfHUD. with the damage functions, I'd think of the DamagePopups, but those are using the Waypointsmanager (made by Seven), which are an independent class, with its own vars n stuff. That would definetly show up in the callstack, if it caused any problem....  :/

**Comment by Tatsugi** [comment]
Because of recent bug with Sentry I thought that it is some incompatibility BCCFS with WolfHUD, but if you say so... I'll try to make my friend to reproduce this bug with me.
