### ISSUE TITLE
Shock & Awe Aced Skill Crash

### ISSUE THREAD

**Issue by AndyIsCool5463** [Kamikaze94/WolfHUD#630]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [Yes] I am running the latest version
- [Yes] I made sure this issue doesn't persist without this mod
- [Yes] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting
Melee is suppose to knock down shields.
# Current Behavior

What is the current behavior?
Crashes when I hit the front side of the shield with Shock & Awe Aced
# Failure Information (for bugs)
## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Get Shock & Awe Aced
2. Hit the front side of a shield with your melee
3. Crash :D

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* BLT version: 2.3
* Other mods installed: Wolfhud
* ...

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

its too long. heres a link to it
https://paste.ee/p/DAgKj

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>
Application has crashed: access violation

-------------------------------

Callstack:

                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
       _process_popup_damage()  @mods/WolfHUD/lua/DamagePopup.lua:64                
         _on_damage_received()  @mods/WolfHUD/lua/DamagePopup.lua:8                 
           original_function()  lib/units/enemies/cop/copdamage.lua:1832            
                damage_melee()  @mods/Enhanced                                      
                                Hitmarkers/lua/copdamage.lua:6                      
   _do_melee_damage_original()                                                      
lib/units/beings/player/states/playerstandard.lua:2896  _do_melee_damage()                                  
                                @mods/WolfHUD/lua/GameInfoManager.lua:3344          
_update_melee_timers_original()                                                      
lib/units/beings/player/states/playerstandard.lua:3002  _update_melee_timers()                              
                                @mods/WolfHUD/lua/Interaction.lua:133               
       _update_check_actions()                                                      
lib/units/beings/player/states/playerstandard.lua:845  update_original()                                   
                                lib/units/beings/player/states/playerstandard.lua:424  
                      update()                                                      
@mods/WolfHUD/lua/BurstFire.lua:212  original()                                          
                                lib/units/beings/player/playermovement.lua:324      
@mods/base/req/core/Hooks.lua:260  
-------------------------------

System information:
	Application version : 1.87.524.
	CPU : Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 860M / nvldumd.dll[23.21.13.9065]
	Language : english
	Memory :     16296MB 280KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

</details>

**Comment by MEXAHOTABOP** [comment]
seems like dupe of #268 
probably caused by one of mods what you use (blt log says what you use lots of them)
