### ISSUE TITLE
Connection with Host

### ISSUE THREAD

**Issue by Blastixe** [Kamikaze94/WolfHUD#631]
Every time I finish a job, doesn't matter If I'm Host or Not, I always crash. This is very annoying. Any solution?

**Comment by MEXAHOTABOP** [comment]
hello 
need some more information about crash
https://github.com/Kamikaze94/WolfHUD#bug-reports

**Comment by Blastixe** [comment]
The problem is that It's not the game crashing, but It's the lobby. I wasn't clear.

**Comment by Rremingegk** [comment]
I just installed the most recent version of wolfhud and this same problem occurs.
