### ISSUE TITLE
Disable Joker Information

### ISSUE THREAD

**Issue by Blitzoreo** [Kamikaze94/WolfHUD#633]
When you corrupt a cop, that is make him a Joker or something, not too fond of PayDay 2 terms, you get this big HUD with a circle and kill counter.

It distracts and bothers me, I find it unnecessary.

An option to toggle (enable/disable) that would be a godsend.

In the meantime, is there any way to remove it from the code?

**Comment by Ongjming** [comment]
You can toggle this in the mod settings, I can't access the game right now so I forgot what to press exactly, but it is there, and it is able to be toggled as is with all the other things you can see in the HUD. I think most things toggled off would just display what you see in vanilla hud.

**Comment by Blitzoreo** [comment]
Damn, bad UI (not to blame the developer of WolfHUD) made me stupid.

I 'fixed' the 'issue', thanks.
