### ISSUE TITLE
Game crashes when trying to play The Cursed Kill Room

### ISSUE THREAD

**Issue by TokiZensekai** [Kamikaze94/WolfHUD#636]
So ever since the new update, the Cursed Kill Room is freaking out from WolfHud and I'm not entirely sure where the problem lies exactly. Here's my crash log.

Crash date: 3/2/2018 9:38:49 AM

PAYDAY 2 Crash log
Application has crashed: C++ exception
mods/WolfHUD-master/lua/CustomWaypoints.lua:9: attempt to index a nil value
SCRIPT STACK
on_executed() lib/managers/mission/elementwaypoint.lua:34
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
_on_script_activated() core/lib/managers/mission/coremissionmanager.lua:514
activate() core/lib/managers/mission/coremissionmanager.lua:505
activate() lib/managers/missionmanager.lua:424
activate_script() core/lib/managers/mission/coremissionmanager.lua:154
activate_script() lib/managers/missionmanager.lua:295
_activate_mission() core/lib/managers/mission/coremissionmanager.lua:137
parse() core/lib/managers/mission/coremissionmanager.lua:84
init_game() lib/setups/gamesetup.lua:640
core/lib/setups/coresetup.lua:405
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
-------------------------------
Current thread: Main
-------------------------------
System information:
	Application version : 1.87.537.
	CPU : Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0 
	GPU : NVIDIA GeForce GTX 960M / nvd3dum.dll[10.18.13.6869]
	Language : english
	Memory :     16273MB 36KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (USB PnP Audio Device))

**Comment by MEXAHOTABOP** [comment]
wired 
you can try add in function HUDManager:add_waypoint 
```
function HUDManager:add_waypoint(id, data, ...)
    if data == nil then
        return
    end
    add_waypoint_original(self, id, data, ...)
......
```
https://github.com/Kamikaze94/WolfHUD/blob/master/lua/CustomWaypoints.lua

but this is really wired because game will crash anyway if data is nil
(i dont have game to test)

**Comment by TokiZensekai** [comment]
Yeah, I tested that and got this:

Crash date: 3/3/2018 11:14:34 AM

PAYDAY 2 Crash log
Application has crashed: C++ exception
mods/WolfHUD-master/lua/CustomWaypoints.lua:12: attempt to index a nil value
SCRIPT STACK

Also I'd like to note that the game crashes before it gets to the pre-planning part and so far it only seems to be the Cursed Kill Room that is doing this.

**Comment by MEXAHOTABOP** [comment]
https://github.com/Kamikaze94/WolfHUD/blob/master/.github/ISSUE_TEMPLATE.md#blt-log

**Comment by TokiZensekai** [comment]
[2018_03_03_log.txt](https://github.com/Kamikaze94/WolfHUD/files/1777749/2018_03_03_log.txt)
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/1777756/crash.txt)

Here's the additional information.

**Comment by MEXAHOTABOP** [comment]
you use too many mods include other HUD's im almost sure what problem in conflict with some other mod

**Comment by TokiZensekai** [comment]
Any idea which mods could be conflicting?
