### ISSUE TITLE
Lobby crash

### ISSUE THREAD

**Issue by abduja** [Kamikaze94/WolfHUD#640]
Hello. Getting instant crash when host lobby or join to someones lobby.
wolfhud version is 9 march 2018.
Without the mod it's ok

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                     steam_api  (???)     SteamAPI_ISteamVideo_IsBroadcasting                 
                     steam_api  (???)     SteamAPI_ISteamVideo_IsBroadcasting                 
                     steam_api  (???)     SteamAPI_ISteamVideo_IsBroadcasting                 
                     steam_api  (???)     SteamAPI_RunCallbacks                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                      update()  lib/network/matchmaking/networkmatchmakingsteam.lua:233  
                      update()  lib/network/base/networkmanager.lua:302             
                      update()  lib/setups/menusetup.lua:339                        
                      update()  @mods/base/lua/MenuSetup.lua:6                      
                                core/lib/setups/coresetup.lua:540                   

-------------------------------

**Comment by Jacob218** [comment]
Do you have Pirate Perfection installed? Personally, i had the same "Application has crashed: access violation" i wondered why and after much research i assumed it was PP. (I used it for DLC Unlocker cause dlc too damn overpriced.) So if you do have PP installed then move along to another HUD, now i decided that i realllly want to use WolfHUD. All you need to do is delete the PP folder from your mods folder and it should work. Reinstall BLT just to be sure because i did the same and payday working for me now. If you don't have PP or this solution doesn't work for you, AND you reinstalled BLT, then i have no clue how to fix it. Hope this helped.

**Comment by Eybog** [comment]
Same. 
Mon Apr 30 17:44:59 2018


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

**Comment by Ghost9910** [comment]
Same. ;-;
