### ISSUE TITLE
Suggestion: Language selector

### ISSUE THREAD

**Issue by Kazenin** [Kamikaze94/WolfHUD#642]
Is possible to develop this feature?

**Comment by PJzuza** [comment]
Of course. It's possible. a lot of mods has that features. For example; [Nepgearsy Main Menu](https://modworkshop.net/mydownloads.php?action=view_down&did=21386), [RSS ingame](https://modworkshop.net/mydownloads.php?action=view_down&did=16986), [Lobby Inspect](https://modworkshop.net/mydownloads.php?action=view_down&did=16238), [Newbies go back to overkill](https://modworkshop.net/mydownloads.php?action=view_down&did=14571), etc. Though you have to rewrite make a new function and call it in `LocalizationManagerPostInit` And to show a language properly. You need to have a font for your language. Let's say it's not a hard work but if you want to do then good luck with that :)

**Comment by Kamikaze94** [comment]
Added with commit bb4e6b11fcdb349f400b13158495ba4fa93b45f5.

**Comment by Kazenin** [comment]
Thank you so much @Kamikaze94 you are the best
