### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by idfk1** [Kamikaze94/WolfHUD#648]
I have Windows 8 and I am constantly crashing when trying to load a mission. I have the latest version of BLT and WolfHUD
Tue Jan 16 02:45:57 2018

Application has crashed: C++ exception
mods/base/lua/CoreMenuItemSlider.lua:22: attempt to index local 'row_item' (a nil value)

SCRIPT STACK

reload() @mods/WolfHUD-master/lua/MenuTweaks.lua:581
reload_item() lib/managers/menu/menunodegui.lua:1083
core/lib/managers/menu/reference_renderer/coremenurenderer.lua:164
_call_callback() core/lib/managers/menu/coremenulogic.lua:329
dirty_callback() core/lib/managers/menu/coremenulogic.lua:336
dirty_callback() core/lib/managers/menu/coremenunode.lua:259
dirty() core/lib/managers/menu/items/coremenuitem.lua:156
set_value_original() @mods/base/lua/CoreMenuItemSlider.lua:16
set_value() @mods/WolfHUD-master/lua/MenuTweaks.lua:566
modify_node() lib/managers/menumanager.lua:10165
refresh_func() lib/managers/menumanager.lua:9999
core/lib/managers/menu/coremenulogic.lua:139
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:826
update() lib/setups/menusetup.lua:336
update() @mods/base/lua/MenuSetup.lua:6
orig__update() core/lib/setups/coresetup.lua:537
trainer/tools/pubinfloopv2.lua:141

**Comment by Astaweth** [comment]
Same problem, I have the latest version of BLT and Wolfhud, pretty weird.

**Comment by alduin47** [comment]
Yeah i got the same issue too. Everything was going smoothly and when i installed this mod, now every time i try and join or make a new lobby i CTD.

**Comment by PJzuza** [comment]
It is because of BLT itself. Not WolfHUD. To fix it. You need to add [some lines](https://github.com/JamesWilko/Payday-2-BLT-Lua/pull/79/files) in your current BLT(BLT 2.3) Or you can use [The modified BLT2.3](https://drive.google.com/open?id=14Rk5aT3eb37_CFQGwlmrVk_Fz5wmXQoI) which I have added those lines thanks to TdlQ for the lua code.

**Comment by alduin47** [comment]
@PJzuza 
I used the modified BLT and it still crashed when joining a lobby

**Comment by PJzuza** [comment]
@alduin47 if that's the case then why others don't have a problem? I don't have. Others don't have. Are you sure that your mods don't cause any conflicts? Only you can check it yourself btw.
