### ISSUE TITLE
Suggestion: option for disabling stamina bar

### ISSUE THREAD

**Issue by killrhythm09** [Kamikaze94/WolfHUD#65]
It is useful, but I've gotten used to using Poco's so I keep looking at the top of the screen instead. Also, I feel that the health bar gets somewhat cluttered with maniac/ex-president stuff going on there as well.

**Comment by Kamikaze94** [comment]
In case you didn't notice, I added that option today.
I changed the KillCounter/Accuracy/DownCounter Options to the System CustomHUD is using.
Therefore the Option is in "WolfHUD Settings -> General HUD Options -> Player Panel -> Show Stamina".
I'm aware, that the location of that option might not be optimal, as all other options, besides Stamina and DownCounter Options in that menu only affect CustomHUD, but I'm not sure yet, if and how I could improve that, without cascading even more menus into eachother. (Guess it's kinda confusing with all the menus we have already... :P )

Please note, while CustomHUD will instantly apply the changed option, the the vanilla HUD will need a day change/map restart for the change to take effect.

**Comment by killrhythm09** [comment]
The only suggestion I would make is perhaps including a note in the description for the settings under the CustomHUD menu that also affect vanilla HUD.

Might also be a good idea to do the same for setting stat screen and loot screen skip delay to 0 for disabling them, since people may not realize that's how it works if they don't read the commits in the repository here.
