### ISSUE TITLE
Crashing when going fullscreen

### ISSUE THREAD

**Issue by ElReyZero1201** [Kamikaze94/WolfHUD#652]
- [x ] I am running the latest version
- [x ] I made sure this issue doesn't persist without this mod
- [ x] I checked to make sure that this issue has not already been filed

# Current Behavior

What is the current behavior?
Payday is crashing when going into fullscreen
# Failure Information (for bugs)

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
Application has crashed: C++ exception
mods/base/lua/CoreMenuItemSlider.lua:22: attempt to index local 'row_item' (a nil value)

SCRIPT STACK

reload_original() @mods/base/req/core/Hooks.lua:260
reload() @mods/WolfHUD/lua/MenuTweaks.lua:596
reload_item() lib/managers/menu/menunodegui.lua:1083
core/lib/managers/menu/reference_renderer/coremenurenderer.lua:164
_call_callback() core/lib/managers/menu/coremenulogic.lua:329
dirty_callback() core/lib/managers/menu/coremenulogic.lua:336
dirty_callback() core/lib/managers/menu/coremenunode.lua:259
dirty() core/lib/managers/menu/items/coremenuitem.lua:156
set_value_original() @mods/base/lua/CoreMenuItemSlider.lua:16
set_value() @mods/WolfHUD/lua/MenuTweaks.lua:581
modify_node() lib/managers/menumanager.lua:10233
refresh_func() lib/managers/menumanager.lua:10067
core/lib/managers/menu/coremenulogic.lua:139
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:837
update() lib/setups/menusetup.lua:340
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.89.575.
	CPU : AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R6 Graphics / aticfx32.dll[21.19.144.257]
	Language : english
	Memory :     7628MB 232KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoces (Realtek High Definition Audio))

</details>

**Comment by PJzuza** [comment]
duplicated issue of #648 check it out and you see an answer there
