### ISSUE TITLE
New akimbo shotguns will only fire single shots when Wolfhud is active

### ISSUE THREAD

**Issue by asdf1324** [Kamikaze94/WolfHUD#653]
Probably something to do with the gun fire mode thing, since it enables player to fire only single shot from akimbo guns. I cannot change the firing modes of the new akimbo shotguns, though.

**Comment by dribbleondo** [comment]
change it to burst mode with weapon mode change (by default it's V)

**Comment by asdf1324** [comment]
"I cannot change the firing modes of the new akimbo shotguns"

**Comment by mradzkii** [comment]
i've noticed this too

**Comment by Kamikaze94** [comment]
Fixed in commit bb4e6b11fcdb349f400b13158495ba4fa93b45f5.
