### ISSUE TITLE
Lobby loading crash.

### ISSUE THREAD

**Issue by Eybog** [Kamikaze94/WolfHUD#656]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

Help please. D:

**Comment by Ghost9910** [comment]
I'm having the exact same problem. Any info on this would be amazing.
