### ISSUE TITLE
Needing to restore hitflash somehow

### ISSUE THREAD

**Issue by Zapharus** [Kamikaze94/WolfHUD#657]
I depend on hit flash for indication to cover and it is always removed when installing WolfHUD. Everything runs fine but I need an option to restore it. I tried using external mods like this one (https://modworkshop.net/mydownloads.php?action=view_down&did=17411), but it doesnt seem to fix the issue or do anything (it was mostly a desperate attempt).

**Comment by MEXAHOTABOP** [comment]
try rewrite issue using this template https://github.com/Kamikaze94/WolfHUD/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Zapharus** [comment]
Seriously...

Problem: Hit Flash is removed (Done on purpose I'm sure of it)
Request: An option to restore it.

**Comment by Zapharus** [comment]
Problem: Hit flash upon damage is removed upon installing the mod even when alone (pretty sure its done on purpose)

Request: An option to restore it.
