### ISSUE TITLE
Wolf HUD + Private Perfection

### ISSUE THREAD

**Issue by Remenix** [Kamikaze94/WolfHUD#665]
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/2036200/crashlog.txt)

When Wolf HUD and Private Perfection are installed, the game crashes when I get into a heist.

**Comment by MEXAHOTABOP** [comment]
this is not wolfhud problem

**Comment by BangL** [comment]
maybe play the game without cheats, you scrub
