### ISSUE TITLE
Game is always crushing at start of a heist

### ISSUE THREAD

**Issue by Golem666** [Kamikaze94/WolfHUD#667]
Whenever I tick READY in preplanning the game shows me the skulls but then it drops.

* Operating System: Windows 10 home
* BLT version: r7_r19
* Other mods installed: Better bots, stack loader reloaded, beardlip, keepers

[2018_05_31_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2058327/2018_05_31_log.txt)

## Crash log(s)

[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/2058344/crash.txt)

**Comment by MEXAHOTABOP** [comment]
download latest wolfhud from github this issue was fixed somewhere in 2017

**Comment by Golem666** [comment]
Thanks man

Dne čt 31. 5. 2018 15:45 uživatel MEXAHOTABOP <notifications@github.com>
napsal:
