### ISSUE TITLE
Can't download the Wolfhud_Texture and Federal Inventory

### ISSUE THREAD

**Issue by AncientKoala** [Kamikaze94/WolfHUD#669]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  

-  I am running the latest version
-  I made sure this issue doesn't persist without this mod
-  I checked to make sure that this issue has not already been filed

# Current Behavior

I can't download the Wolfhud_textures and Federal inventory.

* Operating System:
* BLT version: *SuperBLT*

I Hope you can find a solution for it.

**Comment by kappaaaaa** [comment]
i have the same problem
