### ISSUE TITLE
Super blt

### ISSUE THREAD

**Issue by LithTheKitten** [Kamikaze94/WolfHUD#677]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* BLT version:
* Other mods installed:
* ...

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   [Please paste your BLT log here.]

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   [Please paste your crash log here.]

</details>

**Comment by LithTheKitten** [comment]
could not check if the mod is already up to date. file to be version checked was missing on local machine.
and super blt had recently updated
its crashing and I now had to remove all the gun mods I had installed which were up to date
plus the superblt update file was marked as a harmful file by my Norton security thing.

**Comment by MEXAHOTABOP** [comment]
you need to fill prerequisites form
we cant help you without logs at least
