### ISSUE TITLE
Reload timer wont show up

### ISSUE THREAD

**Issue by Berk-Rider** [Kamikaze94/WolfHUD#678]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Should be showing the reload timer with the "show reload timer" option enabled

# Current Behavior

Even if the "show reload timer" is enabled it wont show the reload timer (both seconds and interaction circle)

## Steps to Reproduce

simply wont show the reload timer whenever i reload any weapon

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: w7
* BLT version: lastest super blt
* Other mods installed: a lot, but none of them ever inflicted with wolfhud

**Comment by MEXAHOTABOP** [comment]
we cannot help you without logs

and first of all you need test with all other mods disabled

**Comment by Berk-Rider** [comment]
nvm, looks like its something with beardlib or one of its mods...

**Comment by Berk-Rider** [comment]
looks like the reason was not related with blt mods but mod_overrides, "custom weapons anims fix" mod to be more specific
