### ISSUE TITLE
Crash on Meltdown

### ISSUE THREAD

**Issue by killrhythm09** [Kamikaze94/WolfHUD#68]
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/477626/crash.txt)

It was after the vault was open, but not immediately. Seemed to happen at some random point after that. Then it crashed again immediately when I tried to rejoin the lobby. I'll have to recheck the other crashlog, but I think the first one may have had a different cause.

Using latest dev build.

**Comment by killrhythm09** [comment]
Here's the crashlog for the first crash. Don't know if this one was related to WolfHUD.

[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/477635/crash.txt)

**Comment by Kamikaze94** [comment]
Added a check fot the crash in your first post.
Cannot see the relation to WolfHUD on the second, so not sure, how that was caused....

**Comment by Kamikaze94** [comment]
Nope, still no clue on the second crash.
Guess I'll close this for now.
If you happen to get that crash agin, feel free to reopen, or create a new issue, referencing this ones number.
Thanks for the report :)
