### ISSUE TITLE
crash when using hacker perk

### ISSUE THREAD

**Issue by NicoTine34** [Kamikaze94/WolfHUD#683]
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:1300: attempt to index a nil value

SCRIPT STACK

event() @mods/WolfHUD/lua/GameInfoManager.lua:625
speed_up_grenade_cooldown() @mods/WolfHUD/lua/GameInfoManager.lua:3103
value() lib/managers/playermanager.lua:5322
_notify() lib/utils/messagesystem.lua:60
update() lib/utils/messagesystem.lua:74
update() lib/managers/playermanager.lua:592
update() lib/setups/setup.lua:844
update() lib/setups/gamesetup.lua:701
_update() lib/setups/networkgamesetup.lua:21
update() @mods\PocoHud3\poco\common.lua:310
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by Kamikaze94** [comment]
That's odd, never got that crash...
Just updated some things for throwable abilities to work nicer with CustomHUD as well as adding new Hacker perk buffs to HUDList.
Please let me know, if the updated version runs you into any trouble :)

**Comment by NicoTine34** [comment]
no crash with the updated version thanks you !

**Comment by Kamikaze94** [comment]
Alright, happy to hear that :)
