### ISSUE TITLE
Need help with Wolfhud

### ISSUE THREAD

**Issue by TheBank23** [Kamikaze94/WolfHUD#687]
I need help, the problem I have is that when a game ends and I go to the lobby it crashes me and throws me out of the lobby, gives a slight tug of a time that lasts 20 seconds or less and when I am the host, I throw the other players who have lost connection

**Comment by MEXAHOTABOP** [comment]
we cannot help you without logs at least 
fill https://github.com/Kamikaze94/WolfHUD/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by TheBank23** [comment]
https://pastebin.com/R4J4Jv4D crashlog
PD: Take into account that some mods from there do not use them anymore and I deleted them

**Comment by MEXAHOTABOP** [comment]
looks like not wolfhud problem
disable other mods especially huds
