### ISSUE TITLE
stamina circle not showing on default hud

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#69]

**Comment by Kamikaze94** [comment]
Do you have "WolfHUD Options -> General GUD Options -> Player Panel -> Show Stamina" checked?

**Comment by Hulkfog** [comment]
The default hud uses PLAYER_SHOWSTAMINA, but customhud use PLAYER_STAMINA setting

**Comment by Kamikaze94** [comment]
Thanks.
Fixed that :)
