### ISSUE TITLE
Overkill broke WolfHUD, again. 

### ISSUE THREAD

**Issue by FriendlyGoy** [Kamikaze94/WolfHUD#692]
Update dropped earlier today and well I'm sure you know it's kilt WolfHUD again. Can't play at all, just crash when loading a heist.

**Comment by Tony134535** [comment]
Same thing, did you find a solution? In addition to removing?

**Comment by Lithimiis** [comment]
What do you mean by, "just copy and replace"?

**Comment by eXCoreX** [comment]
There are still some issues not resolved, i suggest you to play w/o hud for some time.

**Comment by Gurkoel** [comment]
Well you can open the tab "code" then download the whole wolfhud folder and place it inside your payday/mods folder.

Voilà the game doesnt crash in loading screen anymore. 
But i've had a few crashes while playing holdout mode. Dunno if its wolfhud or payday itself.
