### ISSUE TITLE
The message to update fed inv and wolfhud textures doens't prompt when i launch the game.

### ISSUE THREAD

**Issue by Symbiote231** [Kamikaze94/WolfHUD#698]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

The message that should prompt when i launch the game after installing wolfhud isnt showing

# Current Behavior

When i check the mods manager on wolfhud option it says with red letters:
Could not check if the mod is alredy up to date.
File to be version checked was missing on local machine.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 Pro
* BLT version: Lastest Super BLT IPH.dll version
* Other mods installed: Less Inaccurate Weapon Laser
More Weapon Stats
TwoClickSafeHouse
CreateEmptyLobby
InventoryChatAndPlayerStates
Stop the crimespree loss on crash
Drag and Drop Inventory
Mr. Dr. Fantastic!
Bag Contour
* ...

**Comment by eXCoreX** [comment]
Well, i think it's because paydaymods.com is currently offline(?), so you should download it manually elsewhere.

**Comment by Kamikaze94** [comment]
manual download links: 
download.paydaymods.com/download/latest/wolfhud_textures
download.paydaymods.com/download/latest/fed_inv

Both are mod_overrides and belong into "Payday 2/assets/mod_overrides/" folder.
Federal Inventory contains colored Inventory Icons and is optional.

**Comment by Symbiote231** [comment]
Ty both for answering, as u said @eXCoreX  i need to download it manually.
Thanjs for the links @Kamikaze94 .
