### ISSUE TITLE
seven updated remember gadget state to fix shotguns

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#7]

**Comment by Kamikaze94** [comment]
Thanks for the Information.
Added the fix.
It wasn't working with shotguns before?
( I'm not playing shotguns after the rebalance anymore...  :,(  )

**Comment by Hulkfog** [comment]
At the moment it only affects the beta, but whatever changed is likely to be included when the the new skills are added the release version
