### ISSUE TITLE
PayDay 2 crash if i install any HUD. Help Please

### ISSUE THREAD

**Issue by blackgangster144** [Kamikaze94/WolfHUD#700]
my game was buy in Steam -  license

**Comment by VolkJ-VJ** [comment]
My crash
`Application has crashed: C++ exception
mods/WolfHUD/lua/CustomHUD.lua:1993: attempt to call method 'modify_value' (a nil value)



SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
_build_panel() @mods/WolfHUD/lua/CustomHUD.lua:312
init() @mods/WolfHUD/lua/CustomHUD.lua:183
new() core/lib/utils/coreclass.lua:35
_create_teammates_panel() @mods/WolfHUD/lua/CustomHUD.lua:4108
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:647
_setup_player_info_hud_pd2_original() @mods/WolfHUD/lua/HUDList.lua:113
_setup_player_info_hud_pd2() @mods/WolfHUD/lua/DrivingHUD.lua:938
setup() 4
setup() lib/managers/hudmanager.lua:328
load_hud() lib/managers/hudmanager.lua:315
init_finalize() lib/managers/hudmanager.lua:217
init_finalize() lib/setups/gamesetup.lua:668
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:425


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name    `

**Comment by eXCoreX** [comment]
Make sure you have installed the latest version of the WolfHUD.

**Comment by eXCoreX** [comment]
@blackgangster144 First of all, this github page is for WolfHUD. And if you have installed VoidUI instead then check again, because yesterday there was an update for it.

**Comment by blackgangster144** [comment]
Could you give a link ?

**Comment by eXCoreX** [comment]
@blackgangster144 [here](https://modworkshop.net/mydownloads.php?action=view_down&did=20997). I'm suprised that you figured out how to ask here question, but still dont know how to use google.

**Comment by blackgangster144** [comment]
I know, how use google, but it give me a link to mod which was updated by 2016 year

**Comment by eXCoreX** [comment]
@blackgangster144 First link of searching "void ui" is the one i gave you...

**Comment by blackgangster144** [comment]
@eXCoreX Please, could you give a link to the lastest version of WolfHUD

**Comment by eXCoreX** [comment]
@blackgangster144 Welp, currently it's still crashing (you can check others' issues,) so i wouldn't recommend using it right now.

**Comment by dribbleondo** [comment]
...[well](https://i.imgur.com/CyQaJNp.png)

Also, as said above, WolfHUD has problems with Lockout and a few other things, so wait for those to be fixed.

**Comment by blackgangster144** [comment]
@eXCoreX  Thanks a lot

**Comment by NightmareNovix** [comment]
@eXCoreX Hi. Can you keep me remind me when WolfHUD is fixed and safe to play with? I don't have a lot of time on me to spend on focusing on the updates so I would really appreciate it if you could. Thanks a lot!
