### ISSUE TITLE
Where is the "revision.txt" file? 

### ISSUE THREAD

**Issue by Markusz001** [Kamikaze94/WolfHUD#701]
I cant remove federal shit cuz i ant find the revision.txt

**Comment by Kamikaze94** [comment]
BLT2 doesn't use a revision number for update checks anymore. They switched to compare hash values of the folder with the server version, the ReadMe is a little outdated there.
Only way you currently have, is deleting its folder from "Payday 2/assets/mod_overrides/"  and ignoring the update entry in BLT, not updating Federal inventory.
