### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by berkili** [Kamikaze94/WolfHUD#703]
Application has crashed: C++ exception
mods/WolfHUD-master/lua/CustomHUD.lua:1999: attempt to call method 'modify_value' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
_build_panel() @mods/WolfHUD-master/lua/CustomHUD.lua:312
init() @mods/WolfHUD-master/lua/CustomHUD.lua:183
new() core/lib/utils/coreclass.lua:35
_create_teammates_panel() @mods/WolfHUD-master/lua/CustomHUD.lua:4114
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:647
_setup_player_info_hud_pd2_original() @mods/WolfHUD-master/lua/HUDList.lua:113
_setup_player_info_hud_pd2() @mods/WolfHUD-master/lua/DrivingHUD.lua:938
setup() 4
setup() lib/managers/hudmanager.lua:328
load_hud() lib/managers/hudmanager.lua:315
init_finalize() lib/managers/hudmanager.lua:217
init_finalize() lib/setups/gamesetup.lua:668
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:425

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.677.
	CPU : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 / nvldumd.dll[24.21.13.9882]
	Language : english
	Memory :     16269MB 228KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Hoparlör/Kulaklık (Realtek High Definition Audio))

**Comment by MEXAHOTABOP** [comment]
iirc this was fixed

try download last wolfhud from github

**Comment by berkili** [comment]
thx problem is solved
