### ISSUE TITLE
Crash after installing wolfhud

### ISSUE THREAD

**Issue by Argantonio** [Kamikaze94/WolfHUD#704]
HI i have this crash only have installed BLT and after that installed wolfhud

**Crash from app data:**

Application has crashed: C++ exception
mods/WolfHUD/lua/AdvAssault.lua:16: attempt to call method 'is_safehouse_raid' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
_create_assault_corner() lib/managers/hudmanagerpd2.lua:716
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:663
_setup_player_info_hud_pd2_original() @mods/WolfHUD/lua/HUDList.lua:29
_setup_player_info_hud_pd2() @mods/WolfHUD/lua/DrivingHUD.lua:923
setup() 4
setup() lib/managers/hudmanager.lua:328
load_hud() lib/managers/hudmanager.lua:315
init_finalize() lib/managers/hudmanager.lua:217
init_finalize() lib/setups/gamesetup.lua:668
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:425

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.677.
	CPU : Intel(R) Core(TM)2 Quad CPU Q9300 @ 2.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce 9800 GT   / nvd3dum.dll[21.21.13.4201]
	Language : english
	Memory :     4095MB 116KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Altavoces (Dispositivo de High Definition Audio))

**log from BLT: (uploaded cause too large)**
[2018_08_21_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2305571/2018_08_21_log.txt)

**Comment by MEXAHOTABOP** [comment]
you have old wolfhud version download last from github

**Comment by MEXAHOTABOP** [comment]
just close issue
