### ISSUE TITLE
Game crash on heist loading with Wolfhud

### ISSUE THREAD

**Issue by Arfew** [Kamikaze94/WolfHUD#707]
- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Expected the game to work properly when loading into heists after a haitus.

# Current Behavior

Upon loading heists (offline and online), the game crashes before it gets into the lobby screen.

# Failure Information (for bugs)

Will not let me load into any heists I've bought.

## Steps to Reproduce

1: Start game
2: Wait for mods to load in.
3: Open contracts tab.
4: Select online/offline mode.
5: Buy contract (Shackelthorne, Art Gallery, Shadow Raid)
6: Game crashes before lobby.
## Context

I diabled all un-updarted mods and update the rest.  Pretty straight forward, just selecting a build for the hesits and buy it.

* Operating System: Windows 10.
* BLT version: Latest
* Other mods installed: The mods I use regularly and on a daily basis are Beardlib, Wolfhud, Better Bots, (some audio mods unlisted)
* ...

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   [
[2018_08_27_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2322790/2018_08_27_log.txt)
]

</details>

## Crash log(s)

<details> 
  <summary>Crash.txt</summary>

  
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/2322827/crash.txt)

</details>

**Comment by MEXAHOTABOP** [comment]
you need update wolfhud from github

**Comment by Arfew** [comment]
You are a saint, thank ya. I'm very disappointed in myself that it was that easy to fix

**Comment by 2tbc1887** [comment]
I tried to update from github but am still getting the crash

**Comment by JimMorrison723** [comment]
I think @Kamikaze94  should update the version number, it is confusing a little, that it is crashing with v2.60 but when i download it again from here it works and still v2.60 :)
