### ISSUE TITLE
Game is crashing after going to custody

### ISSUE THREAD

**Issue by MechanicTheGreat** [Kamikaze94/WolfHUD#709]
# Expected Behavior

Game not crashing after going to custody

# Current Behavior

Game is crashing after going to custody

## Steps to Reproduce

Go into custody

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Windows 10 Home
* BLT version: Latest Release from GitHub (2.3)
* Other mods installed:
* Lobby Player Info

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

01:13:01 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
01:13:01 PM Lua: [BLT] Setup...
01:13:01 PM Lua: [BLT] Loading module: 	BLTLogs
01:13:01 PM Lua: [BLT] Loading module: 	BLTModManager
01:13:01 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:13:01 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:13:01 PM Lua: [BLT] Loading module: 	BLTLocalization
01:13:01 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:13:01 PM Lua: [BLT] Loading mods for state: table: 0x3e3d7a80
01:13:01 PM Lua: [BLT] Loading mod: base
01:13:01 PM Lua: [BLT] Loading mod: Lobby Player Info
01:13:01 PM Lua: [BLT] Loading mod: WolfHUD
01:13:01 PM Lua: [BLT] Setting up mod: 	base
01:13:01 PM Lua: [BLT] Setting up mod: 	WolfHUD
01:13:01 PM Lua: [BLT] Setting up mod: 	Lobby Player Info
01:13:01 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
01:13:01 PM Lua: [BLT] Setup...
01:13:01 PM Lua: [BLT] Loading module: 	BLTLogs
01:13:01 PM Lua: [BLT] Loading module: 	BLTModManager
01:13:01 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:13:01 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:13:01 PM Lua: [BLT] Loading module: 	BLTLocalization
01:13:01 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:13:01 PM Lua: [BLT] Loading mods for state: table: 0x7e9ba4e0
01:13:01 PM Lua: [BLT] Loading mod: base
01:13:01 PM Lua: [BLT] Loading mod: Lobby Player Info
01:13:01 PM Lua: [BLT] Loading mod: WolfHUD
01:13:01 PM Lua: [BLT] Setting up mod: 	base
01:13:01 PM Lua: [BLT] Setting up mod: 	WolfHUD
01:13:01 PM Lua: [BLT] Setting up mod: 	Lobby Player Info
01:13:01 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
01:13:01 PM Lua: [BLT] Setup...
01:13:01 PM Lua: [BLT] Loading module: 	BLTLogs
01:13:01 PM Lua: [BLT] Loading module: 	BLTModManager
01:13:01 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:13:01 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:13:01 PM Lua: [BLT] Loading module: 	BLTLocalization
01:13:01 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:13:01 PM Lua: [BLT] Loading mods for state: table: 0x54c3bae0
01:13:01 PM Lua: [BLT] Loading mod: base
01:13:01 PM Lua: [BLT] Loading mod: Lobby Player Info
01:13:01 PM Lua: [BLT] Loading mod: WolfHUD
01:13:01 PM Lua: [BLT] Setting up mod: 	base
01:13:01 PM Lua: [BLT] Setting up mod: 	WolfHUD
01:13:01 PM Lua: [BLT] Setting up mod: 	Lobby Player Info
01:13:37 PM Lua: [1] SYSTEM: lolgameGon unlocked asset: Ammo Bag.
01:13:38 PM Lua: [1] SYSTEM: lolgameGon unlocked asset: Doctor Bag.
01:18:43 PM Log:  (..\src\http\http.cpp:49) CURL CLOSED
</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   Application has crashed: C++ exception
mods/WolfHUD/lua/HUDList.lua:6022: attempt to index local 'data' (a nil value)

SCRIPT STACK

clbk() @mods/WolfHUD/lua/HUDList.lua:1026
_listener_callback() @mods/WolfHUD/lua/GameInfoManager.lua:1516
@mods/WolfHUD/lua/GameInfoManager.lua:1358
event() @mods/WolfHUD/lua/GameInfoManager.lua:655
chk_wild_kill_counter() @mods/WolfHUD/lua/GameInfoManager.lua:3054
_on_death() lib/units/enemies/cop/copdamage.lua:3103
die() lib/units/enemies/cop/huskcopdamage.lua:40
sync_damage_bullet() lib/units/enemies/cop/copdamage.lua:2375
lib/network/handlers/unitnetworkhandler.lua:330

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

</details>

**Comment by MEXAHOTABOP** [comment]
you need update wolfhud from github

**Comment by MechanicTheGreat** [comment]
It happens with this latest version

**Comment by MEXAHOTABOP** [comment]
you are sure?

if so then weird why this is not a mass problem

right now i cannot test it myself

**Comment by MechanicTheGreat** [comment]
I am sure. But I installed SuperBLT + WolfHUD-superBLT and problem is gone
