### ISSUE TITLE
Crash Log...

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#71]
PAYDAY 2 Crash log
Application has crashed: C++ exception
mods/WolfHUD-master/lua/CustomHUD.lua:3761: attempt to perform arithmetic on field '?' (a nil value)
SCRIPT STACK.......

PAYDAY 2 Crash log
Application has crashed: C++ exception
[string "lib/managers/occlusionmanager.lua"]:41: attempt to index local 'obj' (a number value)
SCRIPT STACK

**Comment by Kamikaze94** [comment]
First one is because of the changes I made to the positioning.
Reset your settings or change the Position for palyer and teammate position once.

Second, I have no idea. decompiled occlusionmanager has only about 30 lines, so I cannot tell what the problem might have been, sorry....
