### ISSUE TITLE
Again crashing when loading a heist

### ISSUE THREAD

**Issue by TrapStoner** [Kamikaze94/WolfHUD#711]
- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

The game to load the heist properly and me to start heistin.

# Current Behavior

The game crashes upon loading screen.

# Failure Information (for bugs)
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open the game
2. get your ears blown (jk)
3. buy a contract
4. click start the heist
5. wait for it to get to the loading screen
6. then watch the game freez and crash 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 1607
* BLT version: latest
* Other mods installed: too many check the blt log xd
* ...

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   https://pastebin.com/is2znc53

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   https://pastebin.com/jfgCTQg2

</details>

**Comment by MEXAHOTABOP** [comment]
seems like you use pirate perfection its incompatible with wolfhud and this is not wolfhud problem

**Comment by TrapStoner** [comment]
oh thanks... i guess im gonna get their skin unlocker and delete the rest xd
