### ISSUE TITLE
Downloaded WolfHUD today, crashes when I join a heist.

### ISSUE THREAD

**Issue by Eerisu** [Kamikaze94/WolfHUD#712]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Just running normally

# Current Behavior

While trying to join an offline/online game PAYDAY 2 crashes before the briefing screen.

# Failure Information (for bugs)
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Have WolfHUD enabled
2. Join a heist
3. Crash
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 Pro 64-bit
* BLT version: 2.0
* Other mods installed: Ahegao-background
* ...

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   [
[2018_09_04_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2349180/2018_09_04_log.txt)
]

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   [
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/2349178/crash.txt)
]

</details>

**Comment by MEXAHOTABOP** [comment]
update wolfhud from github

**Comment by Eerisu** [comment]
@MEXAHOTABOP >update wolfhud from github
But I just downloaded it from here an hour ago?
Am I supposed to download it from somewhere else than the front page?

**Comment by MEXAHOTABOP** [comment]
https://github.com/Kamikaze94/WolfHUD/archive/master.zip

**Comment by Eerisu** [comment]
It crashed again.

**Comment by MEXAHOTABOP** [comment]
well give then new logs

previous log was from version 2.40 its 2016 year and not supposed to work

**Comment by Eerisu** [comment]
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/2349268/crash.txt)

**Comment by MEXAHOTABOP** [comment]
seems like you continue to use old version

give me blt log

**Comment by Eerisu** [comment]
[2018_09_04_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2349589/2018_09_04_log.txt)
