### ISSUE TITLE
Crash when loading a mission

### ISSUE THREAD

**Issue by Kirill72** [Kamikaze94/WolfHUD#713]
_I'm using the latest version_

Application has crashed: C++ exception
mods/WolfHUD/lua/CustomHUD.lua:1999: attempt to index field 'modifiers' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
_build_panel() @mods/WolfHUD/lua/CustomHUD.lua:312
init() @mods/WolfHUD/lua/CustomHUD.lua:183
new() core/lib/utils/coreclass.lua:35
_create_teammates_panel() @mods/WolfHUD/lua/CustomHUD.lua:4127
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:644
_setup_player_info_hud_pd2_original() @mods/WolfHUD/lua/HUDList.lua:113
_setup_player_info_hud_pd2() @mods/WolfHUD/lua/DrivingHUD.lua:938
setup() 4
setup() lib/managers/hudmanager.lua:328
load_hud() lib/managers/hudmanager.lua:315
init_finalize() lib/managers/hudmanager.lua:217
init_finalize() lib/setups/gamesetup.lua:668
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:425

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.89.606.
	CPU : Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) HD Graphics 3000 / nvumdshim.dll[23.21.13.9135]
	Language : russian
	Memory :     4003MB 168KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VB-Audio Software (VoiceMeeter Input (VB-Audio VoiceMeeter VAIO))

**Comment by MEXAHOTABOP** [comment]
your installation is old download wolfhud from github

**Comment by Kirill72** [comment]
I downloaded the latest version in github

**Comment by MEXAHOTABOP** [comment]
then give me blt log

**Comment by Kirill72** [comment]
10:49:59 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
10:50:06 AM Log:  (..\src\http\http.cpp:44) CURL_INITD
10:50:06 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
10:50:07 AM Lua: [BLT] Setup...
10:50:07 AM Lua: [BLT] Loading module: 	BLTLogs
10:50:07 AM Lua: [BLT] Loading module: 	BLTModManager
10:50:07 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
10:50:07 AM Lua: [BLT] Loading module: 	BLTPersistScripts
10:50:07 AM Lua: [BLT] Loading module: 	BLTLocalization
10:50:07 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
10:50:07 AM Lua: [BLT] Loading mods for state: table: 0x010a87c0
10:50:07 AM Lua: [BLT] Loading mod: Achievements
10:50:07 AM Lua: [BLT] Loading mod: Anticheat
10:50:07 AM Lua: [BLT] Loading mod: base
10:50:07 AM Lua: [BLT] Loading mod: delete
10:50:07 AM Lua: [BLT] Could not read or find mod.txt in delete
10:50:07 AM Lua: [BLT] Loading mod: Skins
10:50:07 AM Lua: [BLT] Loading mod: WolfHUD
10:50:07 AM Lua: [BLT] Setting up mod: 	base
10:50:07 AM Lua: [BLT] Setting up mod: 	WolfHUD
10:50:07 AM Lua: [BLT] Setting up mod: 	Skins
10:50:07 AM Lua: [BLT] Setting up mod: 	Anticheat
10:50:07 AM Lua: [BLT] Setting up mod: 	Achievements
10:50:07 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
10:50:07 AM Lua: [BLT] Setup...
10:50:07 AM Lua: [BLT] Loading module: 	BLTLogs
10:50:07 AM Lua: [BLT] Loading module: 	BLTModManager
10:50:07 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
10:50:07 AM Lua: [BLT] Loading module: 	BLTPersistScripts
10:50:07 AM Lua: [BLT] Loading module: 	BLTLocalization
10:50:07 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
10:50:07 AM Lua: [BLT] Loading mods for state: table: 0x010a87a0
10:50:07 AM Lua: [BLT] Loading mod: Achievements
10:50:07 AM Lua: [BLT] Loading mod: Anticheat
10:50:07 AM Lua: [BLT] Loading mod: base
10:50:07 AM Lua: [BLT] Loading mod: delete
10:50:07 AM Lua: [BLT] Could not read or find mod.txt in delete
10:50:07 AM Lua: [BLT] Loading mod: Skins
10:50:07 AM Lua: [BLT] Loading mod: WolfHUD
10:50:07 AM Lua: [BLT] Setting up mod: 	base
10:50:07 AM Lua: [BLT] Setting up mod: 	WolfHUD
10:50:07 AM Lua: [BLT] Setting up mod: 	Skins
10:50:07 AM Lua: [BLT] Setting up mod: 	Anticheat
10:50:07 AM Lua: [BLT] Setting up mod: 	Achievements
10:50:09 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
10:50:09 AM Lua: [BLT] Setup...
10:50:09 AM Lua: [BLT] Loading module: 	BLTLogs
10:50:09 AM Lua: [BLT] Loading module: 	BLTModManager
10:50:09 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
10:50:09 AM Lua: [BLT] Loading module: 	BLTPersistScripts
10:50:09 AM Lua: [BLT] Loading module: 	BLTLocalization
10:50:09 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
10:50:09 AM Lua: [BLT] Loading mods for state: table: 0x290f5e40
10:50:09 AM Lua: [BLT] Loading mod: Achievements
10:50:09 AM Lua: [BLT] Loading mod: Anticheat
10:50:09 AM Lua: [BLT] Loading mod: base
10:50:09 AM Lua: [BLT] Loading mod: delete
10:50:09 AM Lua: [BLT] Could not read or find mod.txt in delete
10:50:09 AM Lua: [BLT] Loading mod: Skins
10:50:09 AM Lua: [BLT] Loading mod: WolfHUD
10:50:09 AM Lua: [BLT] Setting up mod: 	base
10:50:09 AM Lua: [BLT] Setting up mod: 	WolfHUD
10:50:09 AM Lua: [BLT] Setting up mod: 	Skins
10:50:09 AM Lua: [BLT] Setting up mod: 	Anticheat
10:50:09 AM Lua: [BLT] Setting up mod: 	Achievements
10:52:20 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
10:52:20 AM Lua: [BLT] Setup...
10:52:20 AM Lua: [BLT] Loading module: 	BLTLogs
10:52:20 AM Lua: [BLT] Loading module: 	BLTModManager
10:52:20 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
10:52:20 AM Lua: [BLT] Loading module: 	BLTPersistScripts
10:52:20 AM Lua: [BLT] Loading module: 	BLTLocalization
10:52:20 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
10:52:20 AM Lua: [BLT] Loading mods for state: table: 0x361ae740
10:52:20 AM Lua: [BLT] Loading mod: Achievements
10:52:20 AM Lua: [BLT] Loading mod: Anticheat
10:52:20 AM Lua: [BLT] Loading mod: base
10:52:20 AM Lua: [BLT] Loading mod: delete
10:52:20 AM Lua: [BLT] Could not read or find mod.txt in delete
10:52:20 AM Lua: [BLT] Loading mod: Skins
10:52:20 AM Lua: [BLT] Loading mod: WolfHUD
10:52:20 AM Lua: [BLT] Setting up mod: 	base
10:52:20 AM Lua: [BLT] Setting up mod: 	WolfHUD
10:52:20 AM Lua: [BLT] Setting up mod: 	Skins
10:52:20 AM Lua: [BLT] Setting up mod: 	Anticheat
10:52:20 AM Lua: [BLT] Setting up mod: 	Achievements
10:52:21 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
10:52:21 AM Lua: [BLT] Setup...
10:52:21 AM Lua: [BLT] Loading module: 	BLTLogs
10:52:21 AM Lua: [BLT] Loading module: 	BLTModManager
10:52:21 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
10:52:21 AM Lua: [BLT] Loading module: 	BLTPersistScripts
10:52:21 AM Lua: [BLT] Loading module: 	BLTLocalization
10:52:21 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
10:52:21 AM Lua: [BLT] Loading mods for state: table: 0x353867c0
10:52:21 AM Lua: [BLT] Loading mod: Achievements
10:52:21 AM Lua: [BLT] Loading mod: Anticheat
10:52:21 AM Lua: [BLT] Loading mod: base
10:52:21 AM Lua: [BLT] Loading mod: delete
10:52:21 AM Lua: [BLT] Could not read or find mod.txt in delete
10:52:21 AM Lua: [BLT] Loading mod: Skins
10:52:21 AM Lua: [BLT] Loading mod: WolfHUD
10:52:21 AM Lua: [BLT] Setting up mod: 	base
10:52:21 AM Lua: [BLT] Setting up mod: 	WolfHUD
10:52:21 AM Lua: [BLT] Setting up mod: 	Skins
10:52:21 AM Lua: [BLT] Setting up mod: 	Anticheat
10:52:21 AM Lua: [BLT] Setting up mod: 	Achievements
10:52:21 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
10:52:21 AM Lua: [BLT] Setup...
10:52:21 AM Lua: [BLT] Loading module: 	BLTLogs
10:52:21 AM Lua: [BLT] Loading module: 	BLTModManager
10:52:21 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
10:52:21 AM Lua: [BLT] Loading module: 	BLTPersistScripts
10:52:21 AM Lua: [BLT] Loading module: 	BLTLocalization
10:52:21 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
10:52:21 AM Lua: [BLT] Loading mods for state: table: 0x370ef720
10:52:21 AM Lua: [BLT] Loading mod: Achievements
10:52:21 AM Lua: [BLT] Loading mod: Anticheat
10:52:21 AM Lua: [BLT] Loading mod: base
10:52:21 AM Lua: [BLT] Loading mod: delete
10:52:21 AM Lua: [BLT] Could not read or find mod.txt in delete
10:52:21 AM Lua: [BLT] Loading mod: Skins
10:52:21 AM Lua: [BLT] Loading mod: WolfHUD
10:52:21 AM Lua: [BLT] Setting up mod: 	base
10:52:21 AM Lua: [BLT] Setting up mod: 	WolfHUD
10:52:21 AM Lua: [BLT] Setting up mod: 	Skins
10:52:21 AM Lua: [BLT] Setting up mod: 	Anticheat
10:52:21 AM Lua: [BLT] Setting up mod: 	Achievements
10:53:21 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED

**Comment by MEXAHOTABOP** [comment]
need full log 
paste on https://gist.github.com/

**Comment by Kirill72** [comment]
Is it in the folder \mods\logs? right?

**Comment by MEXAHOTABOP** [comment]
yes

**Comment by Kirill72** [comment]
Look https://gist.github.com/Kirill72/1ce1b48e465a0976aaef727a1818b596
