### ISSUE TITLE
Crash after intro

### ISSUE THREAD

**Issue by TheMasterOfChaos** [Kamikaze94/WolfHUD#717]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

I open the game and i can play

# Current Behavior
I open the game, and after Intro it crashes

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.Start game
2.Watch Intro
3.Crash

## Context

* Operating System:Ubuntu 18.04
* BLT version:BLT4L

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   Lua runtime error: mods/WolfHUD/Core.lua:719: attempt to index field 'Mods' (a nil value)

stack traceback:
	mods/WolfHUD/Core.lua:719: in function 'getVersion'
	mods/WolfHUD/Core.lua:1448: in function 'func'
	mods/base/req/hooks.lua:265: in function '_add_version_string'
	[string "lib/managers/menu/menunodegui.lua"]:1771: in function '_setup_item_rows'
	[string "core/lib/managers/menu/reference_renderer/cor..."]:64: in function 'init'
	[string "lib/managers/menu/menunodegui.lua"]:68: in function 'init'
	[string "core/lib/utils/coreclass.lua"]:35: in function 'new'
	[string "core/lib/managers/menu/reference_renderer/cor..."]:81: in function 'show_node'
	[string "lib/managers/menu/menurenderer.lua"]:63: in function <[string "lib/managers/menu/menurenderer.lua"]:42>
	[string "core/lib/managers/menu/coremenulogic.lua"]:329: in function '_call_callback'
	[string "core/lib/managers/menu/coremenulogic.lua"]:96: in function <[string "core/lib/managers/menu/coremenulogic.lua"]:76>
	[string "core/lib/managers/menu/coremenulogic.lua"]:54: in function '_execute_action_queue'
	[string "core/lib/managers/menu/coremenulogic.lua"]:64: in function 'update'
	[string "core/lib/managers/menu/coremenumanager.lua"]:155: in function 'update'
	[string "lib/managers/menumanagerpd2.lua"]:20: in function 'update'
	[string "lib/setups/setup.lua"]:854: in function 'update'
	[string "lib/setups/menusetup.lua"]:336: in function 'update'
	mods/base/lua/MenuSetup.lua:6: in function 'update'
	[string "core/lib/setups/coresetup.lua"]:540: in function <[string "core/lib/setups/coresetup.lua"]:462>

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

  There is no crash.txt

**Comment by TheMasterOfChaos** [comment]
but if i clone it, it crashes after lobby with
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/2430755/crash.txt)

**Comment by MEXAHOTABOP** [comment]
looks like you missing base mod somewhere 
full blt log is needed

**Comment by TheMasterOfChaos** [comment]
[2018_09_29_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2432039/2018_09_29_log.txt)

**Comment by MEXAHOTABOP** [comment]
seems like you use old pre blt2 revision

you need download fresh blt4l

**Comment by TheMasterOfChaos** [comment]
Thank you it was my mistake
