### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Romang64** [Kamikaze94/WolfHUD#718]
* Operating System:win10 home for one language
* Lastset
* Other mods installed:Money in hud,Press2Hold
intel core i3 7100,geforce 1050TI,8GB ram 
Language:Russian
log:

[2018_10_05_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2450639/2018_10_05_log.txt)

**Comment by MEXAHOTABOP** [comment]
i see only PocoHud3 related errors 

я вижу только ошибки связанные с PocoHud3 
давай крашлог и попробуй запустить отключив другие моды

**Comment by repoman728** [comment]
Hi
First thanks for your work. I have small problem with big lobby mode and wolfhud . These somehow cannot work together, The game is always crash on start . could you help me with that, please, 
- something else then erasing big lobby ?  

Mon Nov 26 00:51:46 2018


Application has crashed: C++ exception
mods/WolfHUD/lua/CustomHUD.lua:4149: attempt to call method 'update' (a nil value)



SCRIPT STACK

update() lib/setups/gamesetup.lua:715
update() lib/setups/networkgamesetup.lua:21
orig__update() core/lib/setups/coresetup.lua:540
trainer/tools/pubinfloopv2.lua:141


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------
