### ISSUE TITLE
WolfHUD camera crash

### ISSUE THREAD

**Issue by Democreep** [Kamikaze94/WolfHUD#72]
Crash Log:
Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:760: attempt to index field '_cams' (a nil value)

SCRIPT STACK
It happens on every map that has cameras when I go from lobby to pre heist screen.

**Comment by Kamikaze94** [comment]
Find the other mod you have installed that uses Seven's GameInfoManager.
(For example his Mini-Map or Custom Waypoints. Or any other Hud mod that comes with HUDList.)
Remove one of the 2 versions of GameInfoManager. 
(Note: If you decide to remove WolfHUDs version, all additional Info I added to HUDList will not show up.)

**Comment by Democreep** [comment]
Lol, i'm a noob, that was exactly the problem.
I had both wolfhud and hudlist standalone running at the same time. Ever since I got rid of holohud due to instability, i've been swapping between wolfhud and PD:TH hud with pocohud and a few other minor mods in between. Anyway, thanks for solving my problem and I'll try to be more smart about handling the mods I have.
One more thing, this is an amazing mod and thank you for helping me!
