### ISSUE TITLE
Crash after pressing start heist in lobby

### ISSUE THREAD

**Issue by MisterOizo** [Kamikaze94/WolfHUD#720]
## BLT log

[2018_10_14_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2475933/2018_10_14_log.txt)

## Crash log(s)

Sun Oct 14 02:07:48 2018

Application has crashed: C++ exception
mods/WolfHUD/lua/CustomHUD.lua:1993: attempt to call method 'modify_value' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
_build_panel() @mods/WolfHUD/lua/CustomHUD.lua:312
init() @mods/WolfHUD/lua/CustomHUD.lua:183
new() core/lib/utils/coreclass.lua:35
_create_teammates_panel() @mods/WolfHUD/lua/CustomHUD.lua:4108
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:647
_setup_player_info_hud_pd2_original() @mods/WolfHUD/lua/HUDList.lua:113
_setup_player_info_hud_pd2() @mods/WolfHUD/lua/DrivingHUD.lua:938
setup() 4
setup() lib/managers/hudmanager.lua:328
load_hud() lib/managers/hudmanager.lua:315
init_finalize() lib/managers/hudmanager.lua:217
init_finalize() lib/setups/gamesetup.lua:668
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:425

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.687.
	CPU : Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0 
	GPU : NVIDIA GeForce GTX 1070 / nvd3dum.dll[24.21.13.9907]
	Language : english
	Memory :     8135MB 952KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Kaiuttimet (Logitech G633 Gaming Headset))

**Comment by MEXAHOTABOP** [comment]
download github version 
https://github.com/Kamikaze94/WolfHUD/archive/master.zip
version on release page was outdated in 2016
