### ISSUE TITLE
Interaction circles and damage indicator stuck.

### ISSUE THREAD

**Issue by demydemise** [Kamikaze94/WolfHUD#721]
In some cases the interacion circles and damage indicator stuck in the screen and never disappears until finishing the heist.

![20181017195042_1](https://user-images.githubusercontent.com/21368953/47187506-bc794d00-d30a-11e8-89c7-a3957722efc7.jpg)

**Comment by ThePenitence** [comment]
Since I tried using this I also have had my interaction circle stuck on screen. But I don't get any of the actual HUD parts like you do in this screenshot :c

**Comment by Kopzz** [comment]
This bug is still there and its really annoying. Interraction circle, damage indicator etc. is stuck at the screen almost every time I play :/
