### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TanJiaMing2** [Kamikaze94/WolfHUD#722]
Application has crashed: C++ exception
mods/WolfHUD/lua/AdvAssault.lua:16: attempt to call method 'is_safehouse_raid' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
_create_assault_corner() lib/managers/hudmanagerpd2.lua:716
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:663
_setup_player_info_hud_pd2_original() @mods/WolfHUD/lua/HUDList.lua:29
_setup_player_info_hud_pd2() @mods/WolfHUD/lua/DrivingHUD.lua:923
setup() 4
setup() lib/managers/hudmanager.lua:328
load_hud() lib/managers/hudmanager.lua:315
init_finalize() lib/managers/hudmanager.lua:217
init_finalize() lib/setups/gamesetup.lua:668
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:425

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name      

Please Fix I keep crashing when I loading the heist

**Comment by MEXAHOTABOP** [comment]
your wolfhud is outdated download new version from github
