### ISSUE TITLE
Crashing after converting any cop

### ISSUE THREAD

**Issue by Jiqegolo2671** [Kamikaze94/WolfHUD#725]
Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:2874: attempt to perform arithmetic on a nil value

SCRIPT STACK

@mods/WolfHUD-superblt/lua/GameInfoManager.lua:2038

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.703.
	CPU : Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 1070 / nvd3dum.dll[25.21.14.1634]
	Language : english
	Memory :     16346MB 904KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : C-MEDIA Inc. (Speakers (Bloody Gaming Audio Device))

**Comment by Jiqegolo2671** [comment]
Crash still persists with the new WolfHud update

**Comment by MEXAHOTABOP** [comment]
full blt logs needed
