### ISSUE TITLE
Crash upon starting White House heist

### ISSUE THREAD

**Issue by Teraman3** [Kamikaze94/WolfHUD#727]
My guess is it has to do with the fact that you spawn riding a helicopter. The crash still persists after turning off DrivingHUD.

Application has crashed: C++ exception
mods/WolfHUD-master/lua/DrivingHUD.lua:190: bad argument #1 to 'upper' (string expected, got nil)

SCRIPT STACK

set_vehicle_state() @mods/WolfHUD-master/lua/DrivingHUD.lua:190
set_driving_vehicle_state() @mods/WolfHUD-master/lua/DrivingHUD.lua:949
_update_driving_hud() @mods/WolfHUD-master/lua/DrivingHUD.lua:916
update() @mods/WolfHUD-master/lua/DrivingHUD.lua:921
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:876
update() lib/setups/gamesetup.lua:706
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.740.
	CPU : Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 / nvldumd.dll[25.21.14.1634]
	Language : english
	Memory :     16320MB 848KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster Z))

**Comment by jazzfowkes** [comment]
Until it's fixed, you can delete or move the /lua/DrivingHUD.lua file and the game won't crash. I renamed it to DrivingHUD.lua.disabled, personally.

**Comment by Malidictus** [comment]
I have the same issue. Seems like the opening helicopter ride is the culprit, as it's treated like a vehicle. Deleting the DrivingHUD file is not a bad idea as a stopgap, though - thanks.

**Comment by AronMercer** [comment]
Same here, crash on loading into White House. Please fix it soon, thanks :'>

**Comment by SkyDriv3r** [comment]
Question. Has this fix been added to the SuperBLT version? Because im using that one and it crashes upon starting the White House heist.
