### ISSUE TITLE
Bug - No stats on tab List

### ISSUE THREAD

**Issue by NicoTine34** [Kamikaze94/WolfHUD#730]
![20181103174801_1](https://user-images.githubusercontent.com/30953411/47955058-97cfd700-df92-11e8-9ea8-71a678122dd9.jpg)
I try with an older version of wolfhud and its working

**Comment by 8ranger22** [comment]
I have the same issue, I thought it was from messing around with other mods. Spent hours trying to fix it but I'm glad to see it's just a problem with the update.

**Comment by Kamikaze94** [comment]
Fixed in commit b1c857b05867b8b118767df5228ab62eaafe87f2.
Thanks for reporting 👍

**Comment by NicoTine34** [comment]
thank you very much :)
