### ISSUE TITLE
New crash

### ISSUE THREAD

**Issue by chromKa** [Kamikaze94/WolfHUD#735]
Application has crashed: C++ exception
[string "lib/units/beings/player/states/playerdriving.lua"]:185: attempt to index a nil value

SCRIPT STACK

change_state() lib/units/beings/player/playermovement.lua:239
_change_player_state() lib/managers/playermanager.lua:981
set_player_state() lib/managers/playermanager.lua:941
cb_leave() lib/units/beings/player/states/playerdriving.lua:617
_end_action_exit_vehicle() lib/units/beings/player/states/playerdriving.lua:491
_update_action_timers() lib/units/beings/player/states/playerdriving.lua:482
update() lib/units/beings/player/states/playerdriving.lua:256
lib/units/beings/player/playermovement.lua:271

**Comment by repoman728** [comment]
There is another crash , till yesterday worked normal but today that happened on start of heist
Sat Nov 17 16:55:25 2018


Application has crashed: C++ exception
mods/WolfHUD/lua/CustomHUD.lua:4149: attempt to call method 'update' (a nil value)



SCRIPT STACK

update() lib/setups/gamesetup.lua:715
update() lib/setups/networkgamesetup.lua:21
orig__update() core/lib/setups/coresetup.lua:540
trainer/tools/pubinfloopv2.lua:141


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.765.
	CPU : Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 870M / nvldumd.dll[25.21.14.1681]
	Language : english
	Memory :     16267MB 32KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded

**Comment by repoman728** [comment]
I have fixed thar so far - i deleted wolfhud  from mods/saves and  so foar so good
