### ISSUE TITLE
Typo in Buffs display submenu

### ISSUE THREAD

**Issue by SkyDriv3r** [Kamikaze94/WolfHUD#737]
There is a small typo in the buffs option under HUD Info. "Increaing" should be "Increasing"
![typo](https://user-images.githubusercontent.com/45074377/48566810-b3f44200-e8c9-11e8-82b3-21977a816cce.png)

**Comment by xBlInDx** [comment]
This is how you can fix that.
loc/english.json
in the Line #572 add missing 's' to the word and save.
