### ISSUE TITLE
Crash report something to do with crimspree/WolfHUD

### ISSUE THREAD

**Issue by Kesacoli** [Kamikaze94/WolfHUD#738]
Hi,

So my game boots normally, I can join lobbies, but when I launch a mission solo or in multiplayer game just instantly closes without a warning after the loading is complete, here is the crashlog and the line concerned :

**crashlog :**

Fri Apr 27 14:53:51 2018

Application has crashed: C++ exception [string "lib/managers/gameplaycentralmanager.lua"]:670: attempt to index a number value

SCRIPT STACK

load() lib/managers/gameplaycentralmanager.lua:960 load() lib/setups/gamesetup.lua:812 core/lib/setups/coresetup.lua:700

Callstack:

     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     zip_get_name                                        
     payday2_win32_release  (???)     zip_get_name          

                              
**Here is what's in the crash.txt :**

Application has crashed: C++ exception mods/WolfHUD-master/lua/CustomHUD.lua:1999: attempt to call method 'modify_value' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35 _build_panel() @mods/WolfHUD-master/lua/CustomHUD.lua:312 init() @mods/WolfHUD-master/lua/CustomHUD.lua:183 new() core/lib/utils/coreclass.lua:35 _create_teammates_panel() @mods/WolfHUD-master/lua/CustomHUD.lua:4114 _setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:647 _setup_player_info_hud_pd2_original() @mods/WolfHUD-master/lua/HUDList.lua:113 _setup_player_info_hud_pd2() @mods/WolfHUD-master/lua/DrivingHUD.lua:938 setup() 4 setup() lib/managers/hudmanager.lua:328 load_hud() lib/managers/hudmanager.lua:315 init_finalize() lib/managers/hudmanager.lua:217 init_finalize() lib/setups/gamesetup.lua:675 init_finalize() lib/setups/networkgamesetup.lua:15 core/lib/setups/coresetup.lua:425

Callstack:

     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     zip_get_name                                        
     payday2_win32_release  (???)     zip_get_name        
                                

**Here is what the line 1999 reads in the CustomHUD.lua :**

self._max_downs = managers.crime_spree:modify_value("PlayerDamage:GetMaximumLives"(Global.game_settings.one_down and 2 or tweak_data.player.damage.LIVES_INIT)) - 1

**Rig :**

System information:
	Application version : 1.89.576.
	CPU : Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvldumd.dll[23.21.13.9124]
	Language : french
	Memory :     16337MB 276KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Haut-parleurs (Périphérique High Definition Audio))

**BLT logs :**

09:42:25 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
09:42:33 PM Log:  (..\src\http\http.cpp:44) CURL_INITD
09:42:33 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
09:42:33 PM Lua: [BLT] Setup...
09:42:33 PM Lua: [BLT] Loading module: 	BLTLogs
09:42:33 PM Lua: [BLT] Loading module: 	BLTModManager
09:42:33 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
09:42:33 PM Lua: [BLT] Loading module: 	BLTPersistScripts
09:42:33 PM Lua: [BLT] Loading module: 	BLTLocalization
09:42:33 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
09:42:33 PM Lua: [BLT] Removing log:	2018_11_15_log.txt
09:42:33 PM Lua: [BLT] Loading mods for state: table: 0x001c8880
09:42:33 PM Lua: [BLT] Loading mod: base
09:42:33 PM Lua: [BLT] Loading mod: Better Bots
09:42:33 PM Lua: [BLT] Loading mod: BuilDB
09:42:33 PM Lua: [BLT] Loading mod: Lobby Player Info
09:42:33 PM Lua: [BLT] Loading mod: Lobby Settings
09:42:33 PM Lua: [BLT] Loading mod: More Weapon Stats
09:42:33 PM Lua: [BLT] Loading mod: No Shake
09:42:33 PM Lua: [BLT] Loading mod: Stop crime spree crash on join Extra
09:42:33 PM Lua: [BLT] Loading mod: Stop the crimespree loss on crash
09:42:33 PM Lua: [BLT] Loading mod: WolfHUD-master
09:42:33 PM Lua: [BLT] Setting up mod: 	base
09:42:33 PM Lua: [BLT] Setting up mod: 	Stop crime spree crash on join Extra
09:42:33 PM Lua: [BLT] Setting up mod: 	Lobby Settings
09:42:33 PM Lua: [BLT] Setting up mod: 	More Weapon Stats
09:42:33 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
09:42:33 PM Lua: [BLT] Setting up mod: 	No Shake
09:42:33 PM Lua: [BLT] Setting up mod: 	Stop the crimespree loss on crash
09:42:33 PM Lua: [BLT] Setting up mod: 	BuilDB
09:42:33 PM Lua: [BLT] Setting up mod: 	Better Bots
09:42:33 PM Lua: [BLT] Setting up mod: 	Lobby Player Info
09:42:33 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
09:42:33 PM Lua: [BLT] Setup...
09:42:33 PM Lua: [BLT] Loading module: 	BLTLogs
09:42:33 PM Lua: [BLT] Loading module: 	BLTModManager
09:42:33 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
09:42:33 PM Lua: [BLT] Loading module: 	BLTPersistScripts
09:42:33 PM Lua: [BLT] Loading module: 	BLTLocalization
09:42:33 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
09:42:33 PM Lua: [BLT] Loading mods for state: table: 0x001c8860
09:42:33 PM Lua: [BLT] Loading mod: base
09:42:33 PM Lua: [BLT] Loading mod: Better Bots
09:42:34 PM Lua: [BLT] Loading mod: BuilDB
09:42:34 PM Lua: [BLT] Loading mod: Lobby Player Info
09:42:34 PM Lua: [BLT] Loading mod: Lobby Settings
09:42:34 PM Lua: [BLT] Loading mod: More Weapon Stats
09:42:34 PM Lua: [BLT] Loading mod: No Shake
09:42:34 PM Lua: [BLT] Loading mod: Stop crime spree crash on join Extra
09:42:34 PM Lua: [BLT] Loading mod: Stop the crimespree loss on crash
09:42:34 PM Lua: [BLT] Loading mod: WolfHUD-master
09:42:34 PM Lua: [BLT] Setting up mod: 	base
09:42:34 PM Lua: [BLT] Setting up mod: 	Stop crime spree crash on join Extra
09:42:34 PM Lua: [BLT] Setting up mod: 	Lobby Settings
09:42:34 PM Lua: [BLT] Setting up mod: 	More Weapon Stats
09:42:34 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
09:42:34 PM Lua: [BLT] Setting up mod: 	No Shake
09:42:34 PM Lua: [BLT] Setting up mod: 	Stop the crimespree loss on crash
09:42:34 PM Lua: [BLT] Setting up mod: 	BuilDB
09:42:34 PM Lua: [BLT] Setting up mod: 	Better Bots
09:42:34 PM Lua: [BLT] Setting up mod: 	Lobby Player Info
09:42:34 PM FATAL ERROR:  (..\src\InitiateState.cpp:389) cannot open mods/No Shake/Special.lua: No such file or directory
09:42:35 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
09:42:35 PM Lua: [BLT] Setup...
09:42:35 PM Lua: [BLT] Loading module: 	BLTLogs
09:42:35 PM Lua: [BLT] Loading module: 	BLTModManager
09:42:35 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
09:42:35 PM Lua: [BLT] Loading module: 	BLTPersistScripts
09:42:35 PM Lua: [BLT] Loading module: 	BLTLocalization
09:42:35 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
09:42:35 PM Lua: [BLT] Loading mods for state: table: 0x2d3bc360
09:42:35 PM Lua: [BLT] Loading mod: base
09:42:35 PM Lua: [BLT] Loading mod: Better Bots
09:42:35 PM Lua: [BLT] Loading mod: BuilDB
09:42:35 PM Lua: [BLT] Loading mod: Lobby Player Info
09:42:35 PM Lua: [BLT] Loading mod: Lobby Settings
09:42:35 PM Lua: [BLT] Loading mod: More Weapon Stats
09:42:35 PM Lua: [BLT] Loading mod: No Shake
09:42:35 PM Lua: [BLT] Loading mod: Stop crime spree crash on join Extra
09:42:35 PM Lua: [BLT] Loading mod: Stop the crimespree loss on crash
09:42:35 PM Lua: [BLT] Loading mod: WolfHUD-master
09:42:35 PM Lua: [BLT] Setting up mod: 	base
09:42:35 PM Lua: [BLT] Setting up mod: 	Stop crime spree crash on join Extra
09:42:35 PM Lua: [BLT] Setting up mod: 	Lobby Settings
09:42:35 PM Lua: [BLT] Setting up mod: 	More Weapon Stats
09:42:35 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
09:42:35 PM Lua: [BLT] Setting up mod: 	No Shake
09:42:35 PM Lua: [BLT] Setting up mod: 	Stop the crimespree loss on crash
09:42:35 PM Lua: [BLT] Setting up mod: 	BuilDB
09:42:35 PM Lua: [BLT] Setting up mod: 	Better Bots
09:42:35 PM Lua: [BLT] Setting up mod: 	Lobby Player Info
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt - 1845
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2bltdll - 1846
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=LS - 1849
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=MWS - 1850
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud - 1851
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud_textures - 1852
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=fed_inv - 1853
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=BDB - 1854
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=BB - 1855
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:13 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
09:43:13 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=LPI - 1856
09:43:13 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
09:43:19 PM Lua: [Updates] Received update data for 'MWS'
09:43:19 PM Lua: [Updates] Comparing hash data:
Server: 849d02b9bb4965744710b4710e60fd6065e1bfdb624989fee24074d40fa6c585
 Local: 849d02b9bb4965744710b4710e60fd6065e1bfdb624989fee24074d40fa6c585
09:43:19 PM Lua: [Updates] Received update data for 'BB'
09:43:20 PM Lua: [Updates] Comparing hash data:
Server: d583d7b3ec91f882ae7d28c18dccd4e94750d4cb7a6f6d1a468416d4401b8a2b
 Local: d583d7b3ec91f882ae7d28c18dccd4e94750d4cb7a6f6d1a468416d4401b8a2b
09:43:20 PM Lua: [Updates] Received update data for 'LS'
09:43:20 PM Lua: [Updates] Comparing hash data:
Server: 91160662885c724b743eeb3a3efd3d0148c8d307c44f66d62123d0516cf9fede
 Local: 91160662885c724b743eeb3a3efd3d0148c8d307c44f66d62123d0516cf9fede
09:43:20 PM Lua: [Updates] Received update data for 'payday2blt'

**Comment by MEXAHOTABOP** [comment]
update your wolfhud from github https://github.com/Kamikaze94/WolfHUD/archive/master.zip

**Comment by zfikset** [comment]
I have the same problem, was able to solve?
