### ISSUE TITLE
Crashing [solved, close pls]

### ISSUE THREAD

**Issue by Michael3038** [Kamikaze94/WolfHUD#739]
Log:
Application has crashed: C++ exception
[string "lib/network/base/networkmanager.lua"]:123: attempt to index field '_session' (a nil value)

SCRIPT STACK

init_finalize() lib/setups/networkgamesetup.lua:17
core/lib/setups/coresetup.lua:425

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.775.
	CPU : Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 Ti / nvldumd.dll[25.21.14.1701]
	Language : english
	Memory :     8034MB 308KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

I honestly have no idea whats going on. I get rid of WolfHUD and it starts working.

It crashes just before loading into the preplanning screen.

**Comment by NeekeetoS2** [comment]
I have same problem 😐
