### ISSUE TITLE
new

### ISSUE THREAD

**Issue by chromKa** [Kamikaze94/WolfHUD#742]
Application has crashed: C++ exception
[string "lib/units/beings/player/huskplayerinventory.lua"]:173: attempt to index a nil value

SCRIPT STACK

lib/network/handlers/unitnetworkhandler.lua:81
send_to_peers_synched() @mods/Third Person/lua/basenetworksession.lua:52
send() lib/network/base/extensions/networkbaseextension.lua:11
_setup_laser() @mods/WolfHud/lua/WeaponGadgets.lua:361
on_enabled() @mods/WolfHud/lua/WeaponGadgets.lua:379
_place_selection() lib/units/beings/player/playerinventory.lua:448
equip_latest_addition() lib/units/beings/player/playerinventory.lua:333
add_unit() lib/units/beings/player/playerinventory.lua:145
add_unit_by_factory_blueprint() lib/units/beings/player/huskplayerinventory.lua:169
add_unit_by_factory_name() lib/units/beings/player/huskplayerinventory.lua:136
_perform_switch_equipped_weapon() lib/units/beings/player/huskplayerinventory.lua:29
synch_equipped_weapon() lib/units/beings/player/huskplayerinventory.lua:20
set_equipped_weapon() lib/network/handlers/unitnetworkhandler.lua:74
@mods/BeardLib/Hooks/NetworkHooks.lua:79

**Comment by MEXAHOTABOP** [comment]
you tried with other mods disabled?

ты же тут уже не в первый раз тут мог бы заполнить шаблон или хотя бы написать что
проверил без других модов и логи прикрепить без других модов
