### ISSUE TITLE
Crashing when opening BLT Options on fresh install of multiple computers

### ISSUE THREAD

**Issue by ktweed** [Kamikaze94/WolfHUD#744]
# Expected Behavior

Clicking on the option to update mods from the main page will open the BLT Updater

# Current Behavior

Game stops responding

# Failure Information

## Steps to Reproduce

1. Install BLT and WolfHUD Stable
2. Launch Payday2
3. Click the option in the main menu to update mods

## Context

* Operating System: Windows 10 1803
* BLT version: 2.7
* Other mods installed: None
## BLT log

BLT Log was too long to paste in, so I attached it as a file.
[2018_12_25_log.txt](https://github.com/Kamikaze94/WolfHUD/files/2709071/2018_12_25_log.txt)

## Crash log(s)

The game doesn't crash, it only freezes and stops responding. It won't respond to alt + F4 and has to be killed through task manager

## Other Information

This has happened on 2 separate computers, one brand new with a fresh install of both Windows and Payday 2. I'd love any help. Thanks!

**Comment by MEXAHOTABOP** [comment]
your wolfhud version from far 2016 
download new version from github https://github.com/Kamikaze94/WolfHUD/archive/master.zip

and as far as i know wolfhud in blt repository also too old to work so update is useless

**Comment by ktweed** [comment]
That worked, thank you so much!
