### ISSUE TITLE
Can you make this compatibility with PP (pirateperfection)???

### ISSUE THREAD

**Issue by DespereauxINC** [Kamikaze94/WolfHUD#748]
Can you make this compatibility with PP (pirateperfection) or is there a fix that i dont know of i know about the 1 to 1000 thing.

**Comment by MEXAHOTABOP** [comment]
this is not wolfhud problem

**Comment by DespereauxINC** [comment]
then is there a fix? because over at pp they say to change the priority in wolfhud mod.txt from 1 to 1000 but then the hud doesn't work.

**Comment by dribbleondo** [comment]
If you desperately want WolfHUD to work with a DLC unlocker mod, then the developer isn't the one who needs to change their attitude, mate.

**Comment by Impact009** [comment]
> then is there a fix? because over at pp they say to change the priority in wolfhud mod.txt from 1 to 1000 but then the hud doesn't work.

Time to nip this in the bud, because this gets reposted a lot here. Whenever you edit a mod.txt file, you have to do it in an editor like Notepad++. You cannot use regular Notepad, as it will break the mod.
