### ISSUE TITLE
HUD elements stuck on screen

### ISSUE THREAD

**Issue by manqche** [Kamikaze94/WolfHUD#749]
There are a couple threads for this issue, just fix it already.

**Comment by KoRaLLL** [comment]
https://old.reddit.com/r/paydaytheheistmods/comments/9za6ds/wolfhud_elements_constantly_getting_stuck_on/


https://github.com/Kamikaze94/WolfHUD/issues/721


https://steamcommunity.com/app/218620/discussions/15/3374780959379388119/


There's a lot of people complaining about it, but nobody seems to care

I can only reccomend you uninstall Wolfhud until they decide they want to fix it

**Comment by manqche** [comment]
I know, that's why I posted this thread
