### ISSUE TITLE
Crashing when starting crimespee 

### ISSUE THREAD

**Issue by zfikset** [Kamikaze94/WolfHUD#751]
Hello, by removing mods, I came to the conclusion that when you start a crime spree, it crashes because of WolfHud. please help solve this problem

> Wed Jan 23 01:14:04 2019 Application has crashed: C++ exception mods/WolfHUD-master/lua/RichPresence.lua:25: attempt to index field 'lobby_handler' (a nil value) SCRIPT STACK at_enter() lib/states/ingamewaitingforplayers.lua:463 trans_func() lib/states/gamestate.lua:22 _do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124 end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104 end_update() lib/setups/setup.lua:916 end_update() lib/setups/gamesetup.lua:787 end_update() lib/setups/networkgamesetup.lua:33 core/lib/setups/coresetup.lua:583 ------------------------------- Callstack: payday2_win32_release (???) ??? payday2_win32_release (???) zip_get_name payday2_win32_release (???) zip_get_name ------------------------------- Current thread: Main ------------------------------- System information: Application version : 1.92.786 CPU : Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2 DirectX : 12.0 GPU : NVIDIA GeForce 920M / nvldumd.dll[25.21.14.1771] Language : russian Memory : 3977MB 432KB OS : 6.2.9200 () 0x100-0x1 (64 bits) Physics : threaded Renderer : DX9 threaded Sound : Realtek Semiconductor Corp. (Динамики (Realtek High Definition Audio))

>

**Comment by zfikset** [comment]
upd. 

On the boot screen, a hang occurs and the game crashes.

**Comment by TeaPotMan123** [comment]
Same issue, but it doesn't work in general if you are starting a lobby offline or online. But for some reason it does work if you join someone else's session. 

Mon Jan 21 20:15:51 2019


Application has crashed: C++ exception
mods/WolfHUD-master/lua/RichPresence.lua:25: attempt to index field 'lobby_handler' (a nil value)



SCRIPT STACK

at_enter() lib/states/ingamewaitingforplayers.lua:463
trans_func() lib/states/gamestate.lua:22
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:916
end_update() lib/setups/gamesetup.lua:787
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:583

**Comment by MADAFACA078** [comment]
I need some help? Thank you!
Crash date: 2019/1/24 下午 07:29:20

PAYDAY 2 Crash log
Application has crashed: C++ exception
mods/WolfHUD-master/lua/RichPresence.lua:25: attempt to index field 'lobby_handler' (a nil value)
SCRIPT STACK
at_enter() lib/states/ingamewaitingforplayers.lua:463
trans_func() lib/states/gamestate.lua:22
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:916
end_update() lib/setups/gamesetup.lua:787
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:583
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
-------------------------------

**Comment by tmyl8** [comment]
Same issue as everyone else. Offline and online sprees cause me to crash, joining online and hosting my own heists seem to be fine. Seems to be only Wolfhud that's causing the issues. I'm afraid I'm new to all this and not sure what to do next.


Application has crashed: C++ exception
[string "lib/managers/moneymanager.lua"]:90: attempt to index local 'string' (a number value)



SCRIPT STACK

set_rich_presence() @mods/WolfHUD-master/lua/RichPresence.lua:45
at_enter() lib/states/ingamewaitingforplayers.lua:465
trans_func() lib/states/gamestate.lua:22
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:916
end_update() lib/setups/gamesetup.lua:787
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:583


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.786.
	CPU : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 Ti / nvldumd.dll[25.21.14.1735]
	Language : english
	Memory :     32644MB 512KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by tmyl8** [comment]
Follow up to the new lua edits, the game now crashes just before you get to the main menu.

Application has crashed: C++ exception
[string "lib/managers/playermanager.lua"]:1550: attempt to index a nil value



SCRIPT STACK

_aquire_feature() lib/managers/upgradesmanager.lua:477
_aquire_upgrade() lib/managers/upgradesmanager.lua:397
aquire() lib/managers/upgradesmanager.lua:356
_verify_loaded_data() lib/managers/skilltreemanager.lua:1514
load() lib/managers/skilltreemanager.lua:1381
_load_cache() lib/managers/savefilemanager.lua:1075
_load_done() lib/managers/savefilemanager.lua:912
lib/managers/savefilemanager.lua:1485

**Comment by MEXAHOTABOP** [comment]
full log please 
from what you paste this seems like not wolfhud problem

**Comment by tmyl8** [comment]
Sorry but what do you mean by full log? As in just copy and paste the entire crash log? Do you want the BLT log as well?
