### ISSUE TITLE
Crash on heist startup

### ISSUE THREAD

**Issue by PhilCrash** [Kamikaze94/WolfHUD#752]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

not crashing on heist loading screen

# Current Behavior

 crashing on heist loading screen

# Failure Information

## Steps to Reproduce

it crashes everytime i start a heist

1. step 1 get in game
2. step 2 try to start a heist
3. step 3 crash

## Context

* Operating System: win 10
* BLT version:2,0
* Other mods installed: as boosted as possible
 dynamic crosshair
enhanced hitmarkers
player randomizer
steaminvetoryinlobby
steelsights
better assault indicator
* ...

## BLT log

<details> 
  <summary>BLT Log</summary>

   [02:39:13 PM FATAL ERROR:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:285) mods/WolfHUD-master/lua/NumbericSuspicion.lua:18: attempt to index global 'OutlinedText' (a nil value)
stack traceback:
	mods/WolfHUD-master/lua/NumbericSuspicion.lua:18: in function 'init'
	[string "core/lib/utils/coreclass.lua"]:35: in function 'new'
	[string "lib/managers/hudmanagerpd2.lua"]:1360: in function '_create_suspicion'
	[string "lib/managers/hudmanagerpd2.lua"]:655: in function '_setup_player_info_hud_pd2_original'
	mods/WolfHUD-master/lua/HUDList.lua:113: in function '_setup_player_info_hud_pd2_original'
	mods/WolfHUD-master/lua/DrivingHUD.lua:943: in function '_setup_player_info_hud_pd2'
	[string "..."]:4: in function 'setup'
	[string "lib/managers/hudmanager.lua"]:328: in function 'setup'
	[string "lib/managers/hudmanager.lua"]:315: in function 'load_hud'
	[string "lib/managers/hudmanager.lua"]:217: in function 'init_finalize'
	[string "lib/setups/gamesetup.lua"]:680: in function 'init_finalize'
	[string "lib/setups/networkgamesetup.lua"]:15: in function 'init_finalize'
	[string "core/lib/setups/coresetup.lua"]:425: in function 'init'
	mods/pp/trainer/init.lua:6: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:130: in function 'RunHookFile'
	mods/base/base.lua:122: in function 'RunHookTable'
	mods/base/base.lua:152: in function 'OrigRequire'
	mods/BeardLib/Core.lua:215: in function 'require'
	[string "core/lib/coreentry.lua"]:19: in main chunk]

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   [Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.790
	CPU : AMD Ryzen 5 2600X Six-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 / nvldumd.dll[25.21.14.1771]
	Language : german
	Memory :     16335MB 308KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Lautsprecher (Logitech G633 Gaming Headset))

]
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/2825554/crash.txt)

</details>

**Comment by MEXAHOTABOP** [comment]
looks like your wolfhud installation is broken OutlinedText is part of the mod

**Comment by PhilCrash** [comment]
i tried reinstalling multiple times
