### ISSUE TITLE
Crash on disconnect from host

### ISSUE THREAD

**Issue by ogeraisi** [Kamikaze94/WolfHUD#753]
# Current Behavior

After receiving the rewards from a heist the host disconnected, I didn't click the confirmation message that I got disconnected and a few seconds later the game crashed.

* Operating System: Windows 10 x64 Pro
* BLT version: SuperBLT-R026-3.1.2
* Other mods installed: Difficulty Screen Animation, NGBTO, Solo Achievements

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

08:41:19 AM Lua: [BLT] Setup...
08:41:19 AM Lua: [BLT] Loading module: 	BLTLogs
08:41:19 AM Lua: [BLT] Loading module: 	BLTModManager
08:41:19 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
08:41:19 AM Lua: [BLT] Loading module: 	BLTPersistScripts
08:41:19 AM Lua: [BLT] Loading module: 	BLTLocalization
08:41:19 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
08:41:19 AM Lua: [BLT] Loading mods for state: table: 0x281612a0
08:41:19 AM Lua: [BLT] Loading mod: base
08:41:19 AM Lua: [BLT] Loading mod: Difficulty Screen Animation
08:41:19 AM Lua: [BLT] Loading mod: Newbies go back to overkill
08:41:19 AM Lua: [BLT] Loading mod: Solo Achievements
08:41:19 AM Lua: [BLT] Loading mod: The Fixes
08:41:19 AM Lua: [BLT] Loading mod: WolfHUD
08:41:19 AM Lua: [BLT] Setting up mod: 	base
08:41:19 AM Lua: [BLT] Setting up mod: 	WolfHUD
08:41:19 AM Lua: [BLT] Setting up mod: 	Newbies go back to overkill
08:41:19 AM Lua: [BLT] Setting up mod: 	Difficulty Screen Animation
08:41:19 AM Lua: [BLT] Setting up mod: 	Solo Achievements
08:41:19 AM Lua: [BLT] Setting up mod: 	The Fixes
08:41:19 AM Lua: Loading mod settings : nil
08:41:20 AM Lua: [Keybind] Registered keybind [BLTKeybind NewbieDW_keybind_id]
08:41:20 AM Lua: [Keybind] Registered keybind [BLTKeybind Newbie_Skill_Info_id]
08:41:20 AM Lua: [Keybind] Registered keybind [BLTKeybind NGBTO_manual_ban]
08:41:20 AM Lua: [Keybind] Registered keybind [BLTKeybind NGBTO_inspect]
08:41:20 AM Lua: Steam RP updated: At the main menu
08:41:20 AM Lua: Steam RP updated: In a lobby
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) https://znix.xyz/paydaymods/updates/meta.php?id=payday2blt - 3963
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) https://znix.xyz/paydaymods/updates/meta.php?id=payday2bltwsockdll - 4071
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.paydaymods.com/updates/retrieve/?mod[0]=PPRT_FE - 3918
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud - 3773
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud_textures - 3948
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.paydaymods.com/updates/retrieve/?mod[0]=fed_inv - 5656
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.paydaymods.com/updates/retrieve/?mod[0]=NGBTO - 5735
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.paydaymods.com/updates/retrieve/?mod[0]=DifficultyScreenAnimation - 3274
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.paydaymods.com/updates/retrieve/?mod[0]=SA - 3510
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) https://bitbucket.org/andole/the-fixes/raw/updates/info.json - 917
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Lua: [1] [NGBTO]: ogeraisi |06:17:34:51:12| Rogue 9/9
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.pd2stats.com/cheater/v3/?type=saf&id=76561198399859149&force=1 - 2801
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.pd2stats.com/cheater/v3/?type=saf&id=76561198032592833&force=1 - 3437
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) http://api.pd2stats.com/cheater/v3/?type=saf&id=76561198137012142&force=1 - 1327
08:41:20 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
08:41:21 AM Lua: [1] [NGBTO]: Ryze |10:07:00:25:13| Sicario 4/9
08:41:21 AM Lua: [Updates] Received update data for 'wolfhud'
08:41:21 AM Lua: [Updates] Invalid or corrupt update data for mod SA
08:41:21 AM Lua: [Updates] Received update data for 'wolfhud_textures'
08:41:21 AM Lua: [Updates] Comparing hash data for wolfhud:
Server: nil
 Local: c81971ab83c291490b1f8590ff635e05cfcd33c2bd3c25be0662fb31360527de
08:41:21 AM Lua: [Updates] Received update data for 'NGBTO'
08:41:21 AM Lua: [Updates] Comparing hash data for wolfhud_textures:
Server: f90cba4e248e477d91652d6057df675789db0e1748fc845c5f4132d706b5bd3a
 Local: f90cba4e248e477d91652d6057df675789db0e1748fc845c5f4132d706b5bd3a
08:41:21 AM Lua: [Updates] Comparing hash data for NGBTO:
Server: f767297649c2ad3132fff78ca2257f26197e470b28c3d594ab023c7526387d48
 Local: f767297649c2ad3132fff78ca2257f26197e470b28c3d594ab023c7526387d48
08:41:21 AM Lua: [Updates] Received update data for 'DifficultyScreenAnimation'
08:41:21 AM Lua: [Updates] Comparing hash data for DifficultyScreenAnimation:
Server: nil
 Local: a1d1ed6590a91555959839a47a54c0bd59dc5e4bf1937a7101bb970984f5fa7b
08:41:21 AM Lua: [1] [NGBTO]: Jake from State Farm |01:13:22:58:00| Rogue 9/9
08:41:21 AM Lua: [Updates] Invalid or corrupt update data for mod PPRT_FE
08:41:21 AM Lua: [Updates] Received update data for 'payday2blt'
08:41:21 AM Lua: [Updates] Comparing hash data for payday2blt:
Server: 77f4d9e3804d345872315a6f0f2a4a19292e50c14a3887f9019fc60bd841a980
 Local: 77f4d9e3804d345872315a6f0f2a4a19292e50c14a3887f9019fc60bd841a980
08:41:21 AM Lua: [Updates] Received update data for 'payday2bltwsockdll'
08:41:21 AM Lua: [Updates] Received update data for 'fed_inv'
08:41:21 AM Lua: [Updates] Comparing hash data for payday2bltwsockdll:
Server: 23a7ba81f4c1d473561e829e38f300c3db13c14fb47c79150b360a0719e615ee
 Local: 23a7ba81f4c1d473561e829e38f300c3db13c14fb47c79150b360a0719e615ee
08:41:22 AM Lua: [Updates] Comparing hash data for fed_inv:
Server: 59b28eff2e093eddfe0df3039ff6f936fb263a7034f6e4d424f29993e2567189
 Local: 59b28eff2e093eddfe0df3039ff6f936fb263a7034f6e4d424f29993e2567189
08:41:25 AM Lua: [1] SYSTEM: Jake from State Farm left.
08:41:25 AM Lua: Steam RP updated: In a lobby
08:41:26 AM Lua: [1] SYSTEM: Ryze left.
08:41:26 AM Lua: Steam RP updated: In a lobby
08:41:39 AM Lua: [1] [NGBTO]: I'm a paradox ._. |01:00:01:35:00| Hacker 9/9
08:41:50 AM Lua: [1] SYSTEM: I'm a paradox ._. disconnected.
08:41:51 AM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:57) CURL CLOSED

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

Application has crashed: C++ exception
mods/WolfHUD/lua/RichPresence.lua:26: attempt to index field 'lobby_handler' (a nil value)

SCRIPT STACK

refresh_rich_presence() lib/managers/platformmanager.lua:81
remove_peer() lib/network/base/basenetworksession.lua:348
remove_peer() lib/network/base/clientnetworksession.lua:644
on_peer_kicked() lib/network/base/basenetworksession.lua:609
_ping_timedout() lib/network/base/networkpeer.lua:1284
chk_timeout() lib/network/base/networkpeer.lua:1252
update() lib/network/base/basenetworksession.lua:661
update() lib/network/base/clientnetworksession.lua:468
update() lib/network/base/networkmanager.lua:306
update() lib/setups/menusetup.lua:343
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.790
	CPU : Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 Ti / nvldumd.dll[25.21.14.1881]
	Language : english
	Memory :     32697MB 0KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek(R) Audio))

</details>

**Comment by MEXAHOTABOP** [comment]
looks like a bug 
as workaround you can 
replace https://github.com/Kamikaze94/WolfHUD/blob/master/lua/RichPresence.lua#L25
`if not Global.game_settings.single_player then`
with
`if not Global.game_settings.single_player and managers.network.matchmake.lobby_handler then`
