### ISSUE TITLE
Вылетает игра при запуске миссии с Wolf-Hud

### ISSUE THREAD

**Issue by George332** [Kamikaze94/WolfHUD#759]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [+] I am running the latest version
- [+] I made sure this issue doesn't persist without this mod
- [+] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Launching the mission
2. Crash

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: 
 -8 GB of RAM
 -Radeon RX Sapphire 560 4GB
 -Amd Ryzen 3 1200
 -Windows 10
* BLT version: Last
* Other mods installed:
* Drag and Drop Inventory
* Fading Contour
* Goonmod's Custom Waypoints
* Iter
* Lobby Player Info
* MIT (Meth Ingredients Teller)
* Money In Hud
* Moveable Intimidated Cop
* No Confirm Dialogs v2
* SilentAssassin
* Simple Toggle Interaction
* WaveSurvived
* BeardLib

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   [[2019_04_23_log.txt](https://github.com/Kamikaze94/WolfHUD/files/3107560/2019_04_23_log.txt)]

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

   [[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/3107564/crash.txt)]

</details>

**Comment by MEXAHOTABOP** [comment]
устаревшая вресия худа скачай новую с гитхаба https://github.com/Kamikaze94/WolfHUD/archive/master.zip

**Comment by George332** [comment]
Сработало, спасибо

**Comment by MEXAHOTABOP** [comment]
без проблем 
правда в шаблоне который ты заполнил есть пункт о использовании последней версии худа

не забудь закрыть вопрос
