### ISSUE TITLE
No Mercy Heist Blood Extraction Problem

### ISSUE THREAD

**Issue by XerXesCZ** [Kamikaze94/WolfHUD#760]
When using WolfHUD latest version obtained here, I am not able to take away the blood extraction from the patient in the No Mercy heist.. Removing WolfHUD fixes this issue and the heist is doable with the vanilla UI.

**Comment by MEXAHOTABOP** [comment]
logs?

**Comment by XerXesCZ** [comment]
I am very sorry, but I am not very experienced in tracking issues in PD2 - I will help how I can, but I will need to know where the logs are located. I suppose it isn't crash log which is created whenever my game crashes. I will try to replicate the issue and post logs ASAP when I receive answer.
