### ISSUE TITLE
UI indicator (damage, cameras, etc.) sometimes stucks on screen

### ISSUE THREAD

**Issue by XerXesCZ** [Kamikaze94/WolfHUD#761]
Sometimes you can play hours without this problem, but from time to time, damage indicator, camera indicator or indicator when you are doing something (e.g. picking a lock) stucks on screen for the duration of the heist and you can't get rid of it. Not really gamebreaking though.

**Comment by MEXAHOTABOP** [comment]
looks like bug what was fixed in https://github.com/Kamikaze94/WolfHUD/commit/2c2a1a682e50702f5f853a41e1aa6899c14ddf2a

add logs at least

**Comment by XerXesCZ** [comment]
I am very sorry, but I am not very experienced in tracking issues in PD2 - I will help how I can, but I will need to know where the logs are located. I suppose it isn't crash log which is created whenever my game crashes. I will try to replicate the issue and post logs ASAP when I receive answer.

**Comment by MEXAHOTABOP** [comment]
https://github.com/Kamikaze94/WolfHUD/blob/master/.github/ISSUE_TEMPLATE.md#blt-log

**Comment by XerXesCZ** [comment]
I am attaching two log files and one screenshot, which was taken only minutes ago. The white damage indicator shown on screen is the one that is stucked. 

![20190424123339_1](https://user-images.githubusercontent.com/23483815/56653661-6a84fb80-668e-11e9-8d92-bdbe5d8c1ecf.jpg)
[2019_04_24_log.txt](https://github.com/Kamikaze94/WolfHUD/files/3111872/2019_04_24_log.txt)
[2019_04_23_log.txt](https://github.com/Kamikaze94/WolfHUD/files/3111873/2019_04_23_log.txt)

**Comment by XerXesCZ** [comment]
I am attaching both log files found in the logs directory, and one screenshot which was taken about an hour ago. The white damage indicator shown on screen is the one that is stuck. 
![20190424123339_1](https://user-images.githubusercontent.com/23483815/56654800-437bf900-6691-11e9-9c3d-d2b283890dc4.jpg)
[2019_04_24_log.txt](https://github.com/Kamikaze94/WolfHUD/files/3111935/2019_04_24_log.txt)
[2019_04_23_log.txt](https://github.com/Kamikaze94/WolfHUD/files/3111936/2019_04_23_log.txt)

**Comment by MEXAHOTABOP** [comment]
you can reproduce this without other mods?

**Comment by XerXesCZ** [comment]
Without all other mods I haven't tried. However, I did turn off those mods which in some ways interfere with HUD - like money in HUD, CustomFOV and waypoint system. 

If this is not enough, I can test it with vanilla PD2 only with WolfHUD enabled. I was searching the internet for a solution and I know I am not the only one with this problem. I will do my best to help resolve this problem because I really love WolfHUD and can't imagine my game w/o it.

Thanks for looking into this.

**Comment by coldblooded** [comment]
I can confirm that the damage indicators, progression bar and even the text that appears above the interaction/progression circle (like helping others players up) get stuck on a regular basis. It seems to happen more frequently when the animations in question is triggered very often.
When playing stoic for insatance and the damage is converted to damage over time and ticks down, the damage indicator seems to get stuck more often than playing other perks.
When interacting / reloading / taking a hostage or triggering the pregression circle multiple times in rapid succession it seems to get stuck more often.

Essentially when playing a loud heist with stoic on deathwish or above either the damage indicator or the progression circle get stuck about every second heist.

**Comment by kianoosh34** [comment]
This still happens for me too, it's not consistent and it resets after the heist but I'd like to add that sometimes the interaction wheel gets stuck on screen too, as well as other text such as the one that alerts when a teammate is down and other such things
