### ISSUE TITLE
Interaction Bug ($value)

### ISSUE THREAD

**Issue by SparkFct** [Kamikaze94/WolfHUD#762]
Hello Folks, 

I have a bug with the Interaction. Instead of the bag value, WolfHUD shows a $value. For the bag WolfHUD show me a $bag. Anyone has this bug too ? Any solutions ? 

Here's what i mean:
![20190425122549_1](https://user-images.githubusercontent.com/49981112/56729360-6374f080-6755-11e9-9d8b-386b369a588a.jpg)

**Comment by MEXAHOTABOP** [comment]
something broken in payday
$bag and  $value this is localization macro in payday

maybe here something in logs but i dont see any logs
