### ISSUE TITLE
Crash: When changing throwable

### ISSUE THREAD

**Issue by Demonlordjackdark** [Kamikaze94/WolfHUD#763]
### Error Description:

**So when I go to Any Loudout and want to change Throwable it can be on mission or outside the game crashes**

-------------------------------------
### Proof that WolfHud is giving the error:

When I have search the error in the CrashLog of payday 2 it have appear a code and in that code theres the words: WolfHUD-master

-------------------------------------

### CrashLog:

Sat May 18 01:34:27 2019

Application has crashed: C++ exception
mods/Inventory count/lua/deployables.lua:308: attempt to index a nil value

**SCRIPT STACK**

init() lib/managers/menu/blackmarketgui.lua:178
new() core/lib/utils/coreclass.lua:35
BlackMarketGui__setup_original() lib/managers/menu/blackmarketgui.lua:1972
_setup() @mods/WolfHUD-master/lua/MenuTweaks.lua:286
init() lib/managers/menu/blackmarketgui.lua:1803
new() core/lib/utils/coreclass.lua:35
create_blackmarket_gui() lib/managers/menu/menucomponentmanager.lua:2851
create() lib/managers/menu/menucomponentmanager.lua:2842
set_active_components() lib/managers/menu/menucomponentmanager.lua:481
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
update() lib/setups/setup.lua:854
update() lib/setups/menusetup.lua:340
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

**System information:**
	Application version : 1.92.790.
	CPU : Intel(R) Core(TM)2 Quad CPU Q8300 @ 2.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 240 / nvd3dum.dll[21.21.13.4201]
	Language : english
	Memory :     6143MB 52KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : C-MEDIA Inc. (Altifalantes (2- USB Audio Device))

**Comment by MEXAHOTABOP** [comment]
crash in mod `Inventory count` 
try disable or update him

**Comment by Demonlordjackdark** [comment]
It was that thk :D

Now I can keep throwing old javelin to some Bulldozer and do instakill with 2 javelins
