### ISSUE TITLE
Crash while loading into any lobby

### ISSUE THREAD

**Issue by Versteckte** [Kamikaze94/WolfHUD#764]
I am using a workaround fix, since it was crashing the game before it could load. I deleted the AdvAssualt.lua, DownCounter.lua and the BurstFire.lua.
How to reproduce it;
1. Install mod and download relevant updates for it
2. Restart game
3. Join ANY lobby, offline or online
4. Crashes while loading.

------------------------------------------------

OS; Windows 10 Pro, 64-bit.
BLT version: 2.0
Other mods installed: AFSF2, Beardlib, Better Bots, Invisible Armor, Slide & Bolt Catch, Meth Helper, Player responds to teammate calls (not loaded though)

------------------------------------------------

<details> 
  <summary>BLT Log</summary>

01:58:45 AM Lua: [BLT] Performing save...
01:58:45 AM Lua: [BLT] Save complete? true
02:36:44 AM Lua: [BLT] Performing save...
02:36:44 AM Lua: [BLT] Save complete? true
02:36:53 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED
02:37:10 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
02:37:14 AM Log:  (..\src\http\http.cpp:44) CURL_INITD
02:37:14 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
02:37:14 AM Lua: [BLT] Setup...
02:37:14 AM Lua: [BLT] Loading module: 	BLTLogs
02:37:14 AM Lua: [BLT] Loading module: 	BLTModManager
02:37:14 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:37:14 AM Lua: [BLT] Loading module: 	BLTPersistScripts
02:37:14 AM Lua: [BLT] Loading module: 	BLTLocalization
02:37:14 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:37:14 AM Lua: [BLT] Loading mods for state: table: 0x001c8a20
02:37:14 AM Lua: [BLT] Loading mod: AFSF2
02:37:14 AM Lua: [BLT] Loading mod: base
02:37:14 AM Lua: [BLT] Loading mod: BeardLib
02:37:14 AM Lua: [BLT] Loading mod: Better Bots
02:37:14 AM Lua: [BLT] Loading mod: Invisible Armor
02:37:14 AM Lua: [BLT] Loading mod: Meth Helper (Not spammy)
02:37:14 AM Lua: [BLT] Loading mod: Player Responds to Teammate Calls
02:37:14 AM Lua: [BLT] Loading mod: Slide and Bolt Catch
02:37:14 AM Lua: [BLT] Loading mod: WolfHUD
02:37:14 AM FATAL ERROR:  (..\src\InitiateState.cpp:361) mods/base/req/utils/json-1.0.lua:212: Failed to scan constant from string {
	"name" : "WolfHUD",
	"description" : "This is a Mod Collection of HUD altering scripts. \nIt uses CustomHUD, HUDPanelList, KillCounter, Press2Hold and WeaponLaserColor, made by Seven \n as well as TabStats, NumericSuspicion by friendlyfire, FlashlightExtender by Seven, Enemy Healthbar by Undeadsewer, and many more.\n\nFor a full list of included mods, go to the GitHUB repository, linked as contact.\nSome scripts are created or modified by me.\n\nLocalizations: \nRussian, made by chrom[K]a \nKorean, made by Я!zu \nChinese, made by 小熊饼干\n-",
	"author" : "Kamikaze94",
	"contact" : "https://github.com/Kamikaze94/WolfHUD",
	"version" : "2.40",
	"priority" : 1,
	"hooks" : [
		{ "hook_id" : "lib/setups/setup", 										"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menumanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menumanagerdialogs", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/chatmanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/localizationmanager", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/experiencemanager", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/moneymanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hudmanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hudmanagerpd2", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/statisticsmanager", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/objectinteractionmanager", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/missionassetsmanager", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/playermanager", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/enemymanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/huddriving", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudteammate", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudtemp", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudassaultcorner", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudobjectives", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudheisttimer", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudchat", 								"script_path" : "Core.lua" },	
		{ "hook_id" : "lib/managers/hud/hudstatsscreen", 						"script_path" : "Core.lua" },	
		{ "hook_id" : "lib/managers/hud/hudinteraction", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudsuspicion", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudhitdirection", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/group_ai_states/groupaistatebase", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/blackmarketgui", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/stageendscreengui", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/lootdropscreengui", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/skilltreeguinew", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/renderers/menunodeskillswitchgui", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/network/handlers/unitnetworkhandler", 				"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/props/timergui", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/props/digitalgui", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/props/securitylockgui", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/props/securitycamera", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/civilians/civiliandamage", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/enemies/cop/copdamage", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/cameras/fpcameraplayerbase", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/ammo_bag/ammobagbase", 				"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/bodybags_bag/bodybagsbagbase", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/doctor_bag/doctorbagbase", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/first_aid_kit/firstaidkitbase", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/ecm_jammer/ecmjammerbase", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/grenade_crate/grenadecratebase", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/sentry_gun/sentrygunbase", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/sentry_gun/sentrygundamage", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/interactions/interactionext", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/akimboweaponbase", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/sentrygunweapon", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/weaponlaser", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/weaponflashlight", 					"script_path" : "Core.lua" },
        { "hook_id" : "lib/units/weapons/raycastweaponbase", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/newraycastweaponbase", 				"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/playerdamage", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/playermovement", 				"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/huskplayermovement", 			"script_path" : "Core.lua" },
        { "hook_id" : "lib/units/beings/player/states/playercivilian", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/states/playerstandard", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/states/playerbleedout", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/vehicles/vehicledamage", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/vehicles/vehicledrivingext", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/utils/temporarypropertymanager", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractionbloodthirstbase", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractionexperthandling", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractionshockandawe", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractiondireneed", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractionunseenstrike", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractiontriggerhappy", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/states/ingamedriving", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/states/ingamewaitingforplayers", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/tweak_data/tweakdata", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/tweak_data/guitweakdata", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/tweak_data/assetstweakdata", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/tweak_data/timespeedeffecttweakdata", 				"script_path" : "Core.lua" },
		{ "hook_id" : "core/lib/managers/menu/items/coremenuitemslider", 		"script_path" : "Core.lua" },
		{ "hook_id" : "core/lib/managers/subtitle/coresubtitlepresenter", 		"script_path" : "Core.lua" }
	],
	"updates" : [
		{
			"revision" : 20,
			"identifier" : "wolfhud",
		},
		{
			"revision" : "./assets/mod_overrides/WolfHUD_Textures/revision.txt",
			"identifier" : "wolfhud_textures",
			"install_dir" : "assets/mod_overrides/",
			"install_folder" : "WolfHUD_Textures",
			"display_name" : "WolfHUD Textures"
		},
		{
			"revision" : "./assets/mod_overrides/Federal Inventory/revision.txt",
			"identifier" : "fed_inv",
			"install_dir" : "assets/mod_overrides/",
			"install_folder" : "Federal Inventory",
			"display_name" : "Federal Inventory"
		}
	]
}
 at starting position 7729
stack traceback:
	[C]: in function 'assert'
	mods/base/req/utils/json-1.0.lua:212: in function 'decode'
	mods/base/req/utils/json-1.0.lua:262: in function 'decode'
	mods/base/req/utils/json-1.0.lua:181: in function 'decode'
	mods/base/req/utils/json-1.0.lua:269: in function 'decode'
	mods/base/req/utils/json.lua:9: in function <mods/base/req/utils/json.lua:8>
	[C]: in function 'pcall'
	mods/base/req/utils/json.lua:8: in function 'decode'
	mods/base/base.lua:188: in function <mods/base/base.lua:187>
	[C]: in function 'pcall'
	mods/base/base.lua:187: in function 'FindMods'
	mods/base/base.lua:88: in function 'Setup'
	mods/base/base.lua:69: in function 'Initialize'
	mods/base/base.lua:223: in main chunk
02:37:14 AM Lua: Found a json error, attempting to use old json loader!
02:37:14 AM Lua: [BLT] Setting up mod: 	base
02:37:14 AM Lua: [BLT] Setting up mod: 	BeardLib
02:37:14 AM Lua: [BLT] Setting up mod: 	Slide and Bolt Catch
02:37:14 AM Lua: [BLT] Setting up mod: 	AFSF2
02:37:14 AM Lua: [BLT] Setting up mod: 	WolfHUD
02:37:14 AM Lua: [BLT] Setting up mod: 	Meth Helper (Not spammy)
02:37:14 AM Lua: [Keybind] Registered keybind [BLTKeybind MH-GUI_keybind]
02:37:14 AM Lua: [BLT] Setting up mod: 	Better Bots
02:37:14 AM Lua: [BLT] Setting up mod: 	Player Responds to Teammate Calls
02:37:14 AM Lua: [BLT] Setting up mod: 	Invisible Armor
02:37:14 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
02:37:14 AM Lua: [BLT] Setup...
02:37:14 AM Lua: [BLT] Loading module: 	BLTLogs
02:37:14 AM Lua: [BLT] Loading module: 	BLTModManager
02:37:14 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:37:14 AM Lua: [BLT] Loading module: 	BLTPersistScripts
02:37:14 AM Lua: [BLT] Loading module: 	BLTLocalization
02:37:14 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:37:14 AM Lua: [BLT] Loading mods for state: table: 0x001c8a00
02:37:14 AM Lua: [BLT] Loading mod: AFSF2
02:37:14 AM Lua: [BLT] Loading mod: base
02:37:14 AM Lua: [BLT] Loading mod: BeardLib
02:37:14 AM Lua: [BLT] Loading mod: Better Bots
02:37:14 AM Lua: [BLT] Loading mod: Invisible Armor
02:37:14 AM Lua: [BLT] Loading mod: Meth Helper (Not spammy)
02:37:14 AM Lua: [BLT] Loading mod: Player Responds to Teammate Calls
02:37:14 AM Lua: [BLT] Loading mod: Slide and Bolt Catch
02:37:14 AM Lua: [BLT] Loading mod: WolfHUD
02:37:14 AM FATAL ERROR:  (..\src\InitiateState.cpp:361) mods/base/req/utils/json-1.0.lua:212: Failed to scan constant from string {
	"name" : "WolfHUD",
	"description" : "This is a Mod Collection of HUD altering scripts. \nIt uses CustomHUD, HUDPanelList, KillCounter, Press2Hold and WeaponLaserColor, made by Seven \n as well as TabStats, NumericSuspicion by friendlyfire, FlashlightExtender by Seven, Enemy Healthbar by Undeadsewer, and many more.\n\nFor a full list of included mods, go to the GitHUB repository, linked as contact.\nSome scripts are created or modified by me.\n\nLocalizations: \nRussian, made by chrom[K]a \nKorean, made by Я!zu \nChinese, made by 小熊饼干\n-",
	"author" : "Kamikaze94",
	"contact" : "https://github.com/Kamikaze94/WolfHUD",
	"version" : "2.40",
	"priority" : 1,
	"hooks" : [
		{ "hook_id" : "lib/setups/setup", 										"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menumanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menumanagerdialogs", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/chatmanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/localizationmanager", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/experiencemanager", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/moneymanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hudmanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hudmanagerpd2", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/statisticsmanager", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/objectinteractionmanager", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/missionassetsmanager", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/playermanager", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/enemymanager", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/huddriving", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudteammate", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudtemp", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudassaultcorner", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudobjectives", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudheisttimer", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudchat", 								"script_path" : "Core.lua" },	
		{ "hook_id" : "lib/managers/hud/hudstatsscreen", 						"script_path" : "Core.lua" },	
		{ "hook_id" : "lib/managers/hud/hudinteraction", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudsuspicion", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/hud/hudhitdirection", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/group_ai_states/groupaistatebase", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/blackmarketgui", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/stageendscreengui", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/lootdropscreengui", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/skilltreeguinew", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/managers/menu/renderers/menunodeskillswitchgui", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/network/handlers/unitnetworkhandler", 				"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/props/timergui", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/props/digitalgui", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/props/securitylockgui", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/props/securitycamera", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/civilians/civiliandamage", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/enemies/cop/copdamage", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/cameras/fpcameraplayerbase", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/ammo_bag/ammobagbase", 				"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/bodybags_bag/bodybagsbagbase", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/doctor_bag/doctorbagbase", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/first_aid_kit/firstaidkitbase", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/ecm_jammer/ecmjammerbase", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/grenade_crate/grenadecratebase", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/sentry_gun/sentrygunbase", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/equipment/sentry_gun/sentrygundamage", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/interactions/interactionext", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/akimboweaponbase", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/sentrygunweapon", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/weaponlaser", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/weaponflashlight", 					"script_path" : "Core.lua" },
        { "hook_id" : "lib/units/weapons/raycastweaponbase", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/weapons/newraycastweaponbase", 				"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/playerdamage", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/playermovement", 				"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/huskplayermovement", 			"script_path" : "Core.lua" },
        { "hook_id" : "lib/units/beings/player/states/playercivilian", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/states/playerstandard", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/beings/player/states/playerbleedout", 			"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/vehicles/vehicledamage", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/units/vehicles/vehicledrivingext", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/utils/temporarypropertymanager", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractionbloodthirstbase", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractionexperthandling", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractionshockandawe", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractiondireneed", 		"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractionunseenstrike", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/player_actions/skills/playeractiontriggerhappy", 	"script_path" : "Core.lua" },
		{ "hook_id" : "lib/states/ingamedriving", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/states/ingamewaitingforplayers", 					"script_path" : "Core.lua" },
		{ "hook_id" : "lib/tweak_data/tweakdata", 								"script_path" : "Core.lua" },
		{ "hook_id" : "lib/tweak_data/guitweakdata", 							"script_path" : "Core.lua" },
		{ "hook_id" : "lib/tweak_data/assetstweakdata", 						"script_path" : "Core.lua" },
		{ "hook_id" : "lib/tweak_data/timespeedeffecttweakdata", 				"script_path" : "Core.lua" },
		{ "hook_id" : "core/lib/managers/menu/items/coremenuitemslider", 		"script_path" : "Core.lua" },
		{ "hook_id" : "core/lib/managers/subtitle/coresubtitlepresenter", 		"script_path" : "Core.lua" }
	],
	"updates" : [
		{
			"revision" : 20,
			"identifier" : "wolfhud",
		},
		{
			"revision" : "./assets/mod_overrides/WolfHUD_Textures/revision.txt",
			"identifier" : "wolfhud_textures",
			"install_dir" : "assets/mod_overrides/",
			"install_folder" : "WolfHUD_Textures",
			"display_name" : "WolfHUD Textures"
		},
		{
			"revision" : "./assets/mod_overrides/Federal Inventory/revision.txt",
			"identifier" : "fed_inv",
			"install_dir" : "assets/mod_overrides/",
			"install_folder" : "Federal Inventory",
			"display_name" : "Federal Inventory"
		}
	]
}
 at starting position 7729
stack traceback:
	[C]: in function 'assert'
	mods/base/req/utils/json-1.0.lua:212: in function 'decode'
	mods/base/req/utils/json-1.0.lua:262: in function 'decode'
	mods/base/req/utils/json-1.0.lua:181: in function 'decode'
	mods/base/req/utils/json-1.0.lua:269: in function 'decode'
	mods/base/req/utils/json.lua:9: in function <mods/base/req/utils/json.lua:8>
	[C]: in function 'pcall'
	mods/base/req/utils/json.lua:8: in function 'decode'
	mods/base/base.lua:188: in function <mods/base/base.lua:187>
	[C]: in function 'pcall'
	mods/base/base.lua:187: in function 'FindMods'
	mods/base/base.lua:88: in function 'Setup'
	mods/base/base.lua:69: in function 'Initialize'
	mods/base/base.lua:223: in main chunk

</details>

<details> 
  <summary>Crash.txt</summary>

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:3273: attempt to call method '_total_armor' (a nil value)

SCRIPT STACK

set_armor_original() @mods/WolfHUD/lua/GameInfoManager.lua:3271
set_armor() @mods/WolfHUD/lua/GameInfoManager.lua:3271
_regenerate_armor() lib/units/beings/player/playerdamage.lua:579
replenish() lib/units/beings/player/playerdamage.lua:565
init_original() lib/units/beings/player/playerdamage.lua:33
original() @mods/WolfHUD/lua/GameInfoManager.lua:3147
init_original() @mods/base/req/core/Hooks.lua:260
init_original() @mods/WolfHUD/lua/GameInfoManager.lua:3147
@mods/WolfHUD/lua/GameInfoManager.lua:3147
spawn_unit() =[C]
spawn_unit() lib/network/base/networkpeer.lua:2162
spawn_players() lib/network/base/basenetworksession.lua:1513
update_original() lib/states/ingamewaitingforplayers.lua:277
update() @mods/WolfHUD/lua/MenuTweaks.lua:284
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:876
update() lib/setups/gamesetup.lua:711
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.92.790.
	CPU : AMD FX(tm)-8350 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 Ti / nvldumd.dll[26.21.14.3064]
	Language : english
	Memory :     14318MB 116KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (Xbox Controller))

</details>

**Comment by MEXAHOTABOP** [comment]
your wolfhud version from far 2016 is too old 
update wolfhud from github https://github.com/Kamikaze94/WolfHUD/archive/master.zip

**Comment by Versteckte** [comment]
> your wolfhud version from far 2016 is too old
> update wolfhud from github https://github.com/Kamikaze94/WolfHUD/archive/master.zip

I downloaded WolfHUD from github though?

**Comment by MEXAHOTABOP** [comment]
you deleted previous wolfhud installation?
