### ISSUE TITLE
Frequent Crash During Heists

### ISSUE THREAD

**Issue by UnkemptBrewski** [Kamikaze94/WolfHUD#765]
Here's my crash log. It happens frequently on heists. During my crime sprees it happens at least every other heist. While trying to do Four Floors/Hotline Day 2, it happened three heist attempts in a row.

[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/3250040/crashlog.txt)
[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/3250041/crash.txt)

**Comment by MEXAHOTABOP** [comment]
try to disable `Replace jokers` mod

04.06.2019 4:10, UnkemptBrewski пишет:

**Comment by UnkemptBrewski** [comment]
Any way to get the two to work together? It's such a useful mod.

**Comment by MEXAHOTABOP** [comment]
try to disable all other mods and enable em one by one 

also paste here blt log files

**Comment by UnkemptBrewski** [comment]
> try to disable all other mods and enable em one by one
> 
> also paste here blt log files


I haven't been around for a few days, but after crashing again here's an update. This is my newest crash, no more mods seem to be conflicting with anything but it's still crashing for the same reason. I tried working with the mods on/off but I couldn't find an issue outside of WolfHUD itself.

I have absolutely no crash issues if I play solo, or if my teammates aren't using jokers. Something about teammates using or converting jokers is crashing my game. Any way to turn a setting off that prevents WolfHUD from trying to add/display whatever is triggering **HUDList.lua:4302: attempt to perform arithmetic on local 'max_mult'**?


[crash.txt](https://github.com/Kamikaze94/WolfHUD/files/3288099/crash.txt)

**Comment by UnkemptBrewski** [comment]
I'm still looking for a fix for this issue.
