### ISSUE TITLE
i keep crashing when i go to briefing ( the ready up room)

### ISSUE THREAD

**Issue by MrHeadcrabVR** [Kamikaze94/WolfHUD#768]
<details> 
  <summary>Crash.txt</summary>

   ----------------------------------------------------------------------

Fri Jul 05 16:10:59 2019

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.790.
	CPU : AMD Athlon(tm) X4 860K Quad Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 650 / nvldumd.dll[25.21.14.1967]
	Language : english
	Memory :     4043MB 32KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

</details>

**Comment by MEXAHOTABOP** [comment]
need more info 
fill https://github.com/Kamikaze94/WolfHUD/blob/master/.github/ISSUE_TEMPLATE.md


most likely this is other mod conflict/error
for example pirate perfection if so then this is not wolfhud problem

**Comment by MrHeadcrabVR** [comment]
oh okay thank you
