### ISSUE TITLE
Crash when terminating contract

### ISSUE THREAD

**Issue by Skyfry428** [Kamikaze94/WolfHUD#77]
It's only just now happened, but I was told to report it anyway.
Application has crashed: C++ exception
mods/WolfHUD/lua/TabStats.lua:487: attempt to index a nil value
 
 
 
SCRIPT STACK
 
 
 
-------------------------------
 
Callstack:
 
         payday2_win32_release  (???)     ???                                                
         payday2_win32_release  (???)     ???                                                
         payday2_win32_release  (???)     ???                                                
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                        
                         ntdll  (???)     ZwQueryVirtualMemory                                
 
 
-------------------------------
 
Current thread: Main
 
-------------------------------
 
System information:
    Application version : 1.54.14
    CPU : Intel(R) Core(TM) i5 CPU M 480 @ 2.67GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
    DirectX : 12.0
    GPU : Intel(R) HD Graphics / nvumdshim.dll[10.18.13.6143]
    Language : @ID94cca2fdaccfc2cd@
    Memory :     5876MB 300KB
    OS : 6.2.9200 () 0x300-0x1 (64 bits)
    Physics : threaded
    Renderer : DX9 threaded
    Sound : Realtek Semiconductor Corp. (Speakers / Headphones (Realtek High Definition Audio))

**Comment by Malidictus** [comment]
Something similar happened to me just now. I don't know if it's the same issue, but it seems related. I got this when I finished the Biker Heist Day 1. As soon as the game was supposed to go to that day's payout, it crashed. Crash log as follows:

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
           _update_waypoints()  lib/managers/hudmanager.lua:1383                    
                                lib/managers/hudmanager.lua:586                     
                            ()  =(tail                                              
                      call):-1  ()                                                  
                        =(tail                                                      
                      call):-1  ()                                                  
                        =(tail  call):-1                                            
                      update()  @mods/WolfHUD/lua/TabStats.lua:784                  
                                lib/setups/gamesetup.lua:526                        
                            ()  =(tail                                              
                      call):-1  update()                                            
lib/setups/networkgamesetup.lua:21                                                      
core/lib/setups/coresetup.lua:529  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

**Comment by Kamikaze94** [comment]
Replaced the part in question with a loop variat, that checks for existence before removing.
Should be fixed, closing this.
