### ISSUE TITLE
Bow drawing icon bug

### ISSUE THREAD

**Issue by dannymaguire** [Kamikaze94/WolfHUD#774]
![20190814214729_1](https://user-images.githubusercontent.com/46163662/63028607-b976cb00-bee1-11e9-8ed0-12b2976981f5.jpg)

FIX THIS..

**Comment by Frosthaven** [comment]
It looks like you need the wolfhud texture pack which isn't being automatically installed into assets/mod_overrides

https://download.paydaymods.com/download/latest/wolfhud_textures
