### ISSUE TITLE
Unable to update with SuperBLT

### ISSUE THREAD

**Issue by AlfeyBoi** [Kamikaze94/WolfHUD#775]
# Expected Behavior

Update WolfHUD

# Current Behavior

Failure to update (Missing assets such as federal inventory and WolfHUD textures)

# Failure Information

"Could not check if the mod is already up to date. File to be version checked was missing on local machine". This issue does not seem to occur with BLT 2. This issue occurs on a clean install of Payday 2.

## Steps to Reproduce

1. Install SuperBLT, downloaded from https://superblt.znix.xyz/
2. Install WolfHUD, downloaded from https://github.com/Kamikaze94/WolfHUD
3. Check installed BLT mods for error, view inventory for missing assets

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 Home 64 Bit
* BLT version: 2 (SuperBLT 1.1.5.1)
* Other mods installed: None (I require SuperBLT for other mods I intend to install)

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   02:20:59 PM Log:  (c:\users\znix\source\repos\superblt\src\debug\blt_debug.cpp:124) Command line: "C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\payday2_win32_release.exe"
02:20:59 PM Log:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:255) Scanning for signatures in payday2_win32_release.exe
02:20:59 PM Log:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:301) Scanned for 48 signatures in 15 milliseconds with 0 cache misses
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/LICENSE.md
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/README.md
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/XAudio Users Manual.md
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/base.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/blt.png
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/cht.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/de.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/en.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/es.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/fr.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/id.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/it.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/ru.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/sv.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/tr.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/loc/zh-cn.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/BaseNetworkSession.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/ChatManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/CoreMenuData.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/CoreMenuItemSlider.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/CoreMenuLogic.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/CorePatchLua.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/DynamicResourceManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/GameSetup.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/LocalizationManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/MenuComponentManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/MenuManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/MenuNodeGUI.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/MenuSetup.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/NetworkManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/lua/SystemMenuManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/mod.txt
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTDownloadManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTKeybindsManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTLocalization.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTLogs.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTMod.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTModDependency.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTModManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTModule.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTNotificationsManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTPersistScripts.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTUpdate.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/BLTUpdateCallbacks.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/core/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/core/DelayedCalls.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/core/Hooks.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/core/MenuHelper.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/core/Networking.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/supermod/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/supermod/BLTSuperMod.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/supermod/SuperModAssetLoader.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/BLTCustomComponent.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/BLTDownloadManagerGui.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/BLTMenuNodes.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/BLTModItem.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/BLTModsGui.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/BLTNotificationsGui.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/BLTUIControls.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/ui/BLTViewModGui.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/utils/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/utils/QuickMenu.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/utils/UtilsClass.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/utils/UtilsCore.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/utils/UtilsIO.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/utils/json-0.9.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/utils/json-1.0.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/utils/json.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/xaudio/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/xaudio/VoicelineManager.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/xaudio/XAudio.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/xaudio/XAudioBuffer.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/xaudio/XAudioMovement.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/xaudio/XAudioSource.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/req/xaudio/XAudioUnitSource.lua
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/wren/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/wren/base.wren
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/wren/native.wren
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/wren/private/
02:21:01 PM Log:  (c:\users\znix\source\repos\superblt\src\util\compression.cpp:132) Extracting to mods/base/wren/private/xml_loader.wren
02:21:05 PM Log:  (c:\users\znix\source\repos\superblt\src\debug\blt_debug.cpp:124) Command line: "C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\payday2_win32_release.exe"
02:21:05 PM Log:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:255) Scanning for signatures in payday2_win32_release.exe
02:21:05 PM Log:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:301) Scanned for 48 signatures in 0 milliseconds with 0 cache misses
02:21:05 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
02:21:07 PM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:51) CURL_INITD
02:21:07 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
02:21:07 PM Lua: [BLT] Setup...
02:21:07 PM Lua: [BLT] Loading module: 	BLTLogs
02:21:07 PM Lua: [BLT] Loading module: 	BLTModManager
02:21:07 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:21:07 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:21:07 PM Lua: [BLT] Loading module: 	BLTLocalization
02:21:07 PM Lua: [BLT] Creating missing directory mods/downloads
02:21:07 PM Lua: [BLT] Creating missing directory mods/saves
02:21:07 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:21:07 PM Lua: [BLT] Loading mods for state: table: 0x001c8a80
02:21:07 PM Lua: [BLT] Loading mod: base
02:21:07 PM Lua: [BLT] Loading mod: WolfHUD-master
02:21:07 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
02:21:07 PM Lua: [BLT] Setting up mod: 	base
02:21:07 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:21:07 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
02:21:07 PM Lua: [BLT] Setup...
02:21:07 PM Lua: [BLT] Loading module: 	BLTLogs
02:21:07 PM Lua: [BLT] Loading module: 	BLTModManager
02:21:07 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:21:07 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:21:07 PM Lua: [BLT] Loading module: 	BLTLocalization
02:21:07 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:21:07 PM Lua: [BLT] Loading mods for state: table: 0x001c8a60
02:21:07 PM Lua: [BLT] Loading mod: base
02:21:07 PM Lua: [BLT] Loading mod: WolfHUD-master
02:21:07 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
02:21:07 PM Lua: [BLT] Setting up mod: 	base
02:21:07 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:21:07 PM Lua: [WolfHUD] ERROR: Error while loading, settings file could not be opened (mods/saves/WolfHUD_v2.json)
02:21:07 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
02:21:07 PM Lua: [BLT] Setup...
02:21:07 PM Lua: [BLT] Loading module: 	BLTLogs
02:21:07 PM Lua: [BLT] Loading module: 	BLTModManager
02:21:07 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
02:21:07 PM Lua: [BLT] Loading module: 	BLTPersistScripts
02:21:07 PM Lua: [BLT] Loading module: 	BLTLocalization
02:21:07 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
02:21:07 PM Lua: [BLT] Loading mods for state: table: 0x29285340
02:21:07 PM Lua: [BLT] Loading mod: base
02:21:07 PM Lua: [BLT] Loading mod: WolfHUD-master
02:21:07 PM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
02:21:07 PM Lua: [BLT] Setting up mod: 	base
02:21:07 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
02:21:11 PM Lua: Steam RP updated: At the main menu
02:21:11 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
02:21:11 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) https://znix.xyz/paydaymods/updates/meta.php?id=payday2blt - 1857
02:21:11 PM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
02:21:11 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
02:21:11 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) https://znix.xyz/paydaymods/updates/meta.php?id=payday2bltwsockdll - 1854
02:21:11 PM Log:  (c:\users\znix\source\repos\superb

</details>

## Crash log(s)

No crash.

**Comment by MEXAHOTABOP** [comment]
wolfhud at this moment not support any update metod except plain manual update or standalone script 
because @Kamikaze94 dont want to maintain it and also no one else want to do this

here was superblt branch with update support but now this branch is outdated

**Comment by AlfeyBoi** [comment]
Yeah, I was debating posting here about it, but I saw some somewhat recent activity in terms of the issues being replied to and figured I would try my luck. Is there any way I can manually get a hold of the asset files?

**Comment by MEXAHOTABOP** [comment]
https://download.paydaymods.com/download/latest/fed_inv
https://download.paydaymods.com/download/latest/wolfhud_textures

**Comment by AlfeyBoi** [comment]
Thanks for the help man. It's pretty cool that you're helping people out still considering development has stalled.
