### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WolfHUFan** [Kamikaze94/WolfHUD#776]
- Yes I am running the latest version
- Yes I made sure this issue doesn't persist without this mod
- Yes I checked to make sure that this issue has not already been filed

Crash on heist startup: Tried anything even restarting game.

Still crashing.

* Operating System: Windows 10
* BLT version: Better Lua Injector
* Other mods installed: Achievements, Anticheat, Skins, DLCUnlock, Pirate Perfection Reborn Trainer, Beardlib, Casino, _temp which has nothing in Idk why, Bodycount gloves- Sydney, Federal Inventory, MurkyWater Faction Tweaks, Semi-Realistic Law Enforcement v7, Slayer Gloves-V7
* ...

## BLT log

stack traceback:
	mods/WolfHUD-master/lua/NumbericSuspicion.lua:18: in function 'init'
	[string "core/lib/utils/coreclass.lua"]:35: in function 'new'
	[string "lib/managers/hudmanagerpd2.lua"]:1360: in function '_create_suspicion'
	[string "lib/managers/hudmanagerpd2.lua"]:655: in function '_setup_player_info_hud_pd2_original'
	mods/WolfHUD-master/lua/HUDList.lua:113: in function '_setup_player_info_hud_pd2_original'
	mods/WolfHUD-master/lua/DrivingHUD.lua:943: in function '_setup_player_info_hud_pd2'
	[string "..."]:4: in function 'setup'
	[string "lib/managers/hudmanager.lua"]:328: in function 'setup'
	[string "lib/managers/hudmanager.lua"]:315: in function 'load_hud'
	[string "lib/managers/hudmanager.lua"]:217: in function 'init_finalize'
	[string "lib/setups/gamesetup.lua"]:675: in function 'init_finalize'
	[string "lib/setups/networkgamesetup.lua"]:15: in function 'init_finalize'
	[string "core/lib/setups/coresetup.lua"]:425: in function 'init'
	...tion Reborn Trainer! Free Edition/Trainer/setup/init.lua:6: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:120: in function 'RunHookFile'
	mods/base/base.lua:113: in function 'RunHookTable'
	mods/base/base.lua:142: in function 'OrigRequire'
	mods/BeardLib/Core.lua:222: in function 'require'
	[string "core/lib/coreentry.lua"]:19: in main chunk
02:49:00 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED

----------------------------------------------------------------------

Tue Sep 03 13:35:39 2019

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.765
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[22.19.180.1536]
	Language : english
	Memory :     3903MB 1000KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Tue Sep 03 13:59:36 2019

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  189                                                 
                   LoadAsset()  211                                                 
               get_unit_data()  @mods/BeardLib/Hooks/CoreSystem.lua:61              
                        exec()  trainer/menu/ingame/lego_menu.lua:215               
                 ppr_require()  @mods/[MOD]                                         
                                Pirate                                              
                    Perfection                                                      
                        Reborn  Trainer!                                            
                                Free                                                
Edition/Trainer/setup/__require.lua:157                                                      
trainer/menu/ingame/mod_menu.lua:29  xpcall()                                            
                                =[C]                                                
                    safecall()                                                      
 trainer/tools/marylog.lua:273  trainer/experimental/kbinput.lua:126                
                       pcall()  =[C]                                                
                                trainer/tools/pubinfloopv2.lua:143                  

-------------------------------

System information:
	Application version : 1.92.765
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[22.19.180.1536]
	Language : english
	Memory :     3903MB 1000KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Tue Sep 03 22:48:54 2019

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.765
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[22.19.180.1536]
	Language : english
	Memory :     3903MB 1000KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Tue Sep 03 22:59:55 2019

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.765
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[22.19.180.1536]
	Language : english
	Memory :     3903MB 1000KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Wed Sep 04 02:25:16 2019

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.765.
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[22.19.180.1536]
	Language : english
	Memory :     3903MB 1000KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Wed Sep 04 02:28:14 2019

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.765.
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[22.19.180.1536]
	Language : english
	Memory :     3903MB 1000KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Wed Sep 04 02:32:50 2019

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.765.
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[22.19.180.1536]
	Language : english
	Memory :     3903MB 1000KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

----------------------------------------------------------------------

Wed Sep 04 02:48:59 2019

Application has crashed: C++ exception
Pure virtual function call

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
                                core/lib/setups/coresetup.lua:309                   

-------------------------------

System information:
	Application version : 1.92.765.
	CPU : AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R4 Graphics / aticfx32.dll[22.19.180.1536]
	Language : english
	Memory :     3903MB 1000KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by MEXAHOTABOP** [comment]
pirate perfection is incompatible with wolfhud
this is not wolfhud problem

**Comment by WolfHUFan** [comment]
So if I remove it is it fixed?
Neither P2D Trainer?
Thanks for answer, I always wanted to try WolfHud
