### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by strdsk** [Kamikaze94/WolfHUD#783]
# Failure Information

Crash just when entering level (after planning)

## Context

* Operating System: Win 7
* BLT version: Latest (17/10/2019)
* Clean installation with BLT & WolfHUD only

## BLT log

<details> 
  <summary>BLT Log</summary>

01:35:15 PM Log:  (..\src\http\http.cpp:44) CURL_INITD
01:35:15 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
01:35:15 PM Lua: [BLT] Setup...
01:35:15 PM Lua: [BLT] Loading module: 	BLTLogs
01:35:15 PM Lua: [BLT] Loading module: 	BLTModManager
01:35:15 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:35:15 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:35:15 PM Lua: [BLT] Loading module: 	BLTLocalization
01:35:15 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:35:15 PM Lua: [BLT] Loading mods for state: table: 0x00310420
01:35:15 PM Lua: [BLT] Loading mod: base
01:35:15 PM Lua: [BLT] Loading mod: unused
01:35:15 PM Lua: [BLT] Could not read or find mod.txt in unused
01:35:15 PM Lua: [BLT] Loading mod: WolfHUD-master
01:35:16 PM Lua: [BLT] Setting up mod: 	base
01:35:16 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
01:35:16 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
01:35:16 PM Lua: [BLT] Setup...
01:35:16 PM Lua: [BLT] Loading module: 	BLTLogs
01:35:16 PM Lua: [BLT] Loading module: 	BLTModManager
01:35:16 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:35:16 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:35:16 PM Lua: [BLT] Loading module: 	BLTLocalization
01:35:16 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:35:16 PM Lua: [BLT] Loading mods for state: table: 0x00310440
01:35:16 PM Lua: [BLT] Loading mod: base
01:35:16 PM Lua: [BLT] Loading mod: unused
01:35:16 PM Lua: [BLT] Could not read or find mod.txt in unused
01:35:16 PM Lua: [BLT] Loading mod: WolfHUD-master
01:35:16 PM Lua: [BLT] Setting up mod: 	base
01:35:16 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
01:35:16 PM Lua: [WolfHUD] ERROR: Error while loading, settings file could not be opened (mods/saves/WolfHUD_v2.json)
01:35:18 PM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
01:35:18 PM Lua: [BLT] Setup...
01:35:18 PM Lua: [BLT] Loading module: 	BLTLogs
01:35:18 PM Lua: [BLT] Loading module: 	BLTModManager
01:35:18 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:35:18 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:35:18 PM Lua: [BLT] Loading module: 	BLTLocalization
01:35:18 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:35:18 PM Lua: [BLT] Loading mods for state: table: 0x256909e0
01:35:18 PM Lua: [BLT] Loading mod: base
01:35:18 PM Lua: [BLT] Loading mod: unused
01:35:18 PM Lua: [BLT] Could not read or find mod.txt in unused
01:35:18 PM Lua: [BLT] Loading mod: WolfHUD-master
01:35:18 PM Lua: [BLT] Setting up mod: 	base
01:35:18 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
01:36:13 PM Lua: Steam RP updated: At the main menu
01:36:14 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
01:36:14 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2blt - 1685
01:36:14 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
01:36:14 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
01:36:14 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=payday2bltdll - 1684
01:36:14 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
01:36:14 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
01:36:14 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud - 1681
01:36:14 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
01:36:14 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
01:36:14 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud_textures - 1680
01:36:14 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
01:36:14 PM Log:  (..\src\InitiateState.cpp:490) Incoming HTTP Request/Request
01:36:14 PM Log:  (..\src\InitiateState.cpp:504) http://api.paydaymods.com/updates/retrieve/?mod[0]=fed_inv - 1679
01:36:14 PM Log:  (..\src\http\http.cpp:144) Launching Async HTTP Thread
01:36:16 PM Lua: [Updates] Received update data for 'pay

</details>

## Crash log(s)

<details> 
  <summary>Crash.txt</summary>
Application has crashed: C++ exception
mods/WolfHUD-master/lua/AdvAssault.lua:18: attempt to call method 'should_display_waves' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
_create_assault_corner() lib/managers/hudmanagerpd2.lua:705
_setup_player_info_hud_pd2_original() lib/managers/hudmanagerpd2.lua:658
_setup_player_info_hud_pd2_original() @mods/WolfHUD-master/lua/HUDList.lua:113
_setup_player_info_hud_pd2() @mods/WolfHUD-master/lua/DrivingHUD.lua:943
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
init_finalize() lib/managers/hudmanager.lua:169
init_finalize() lib/setups/gamesetup.lua:621
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:422

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.82.445.
	CPU : Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : Intel(R) HD Graphics 5500 / nvumdshim.dll[21.21.13.7570]
	Language : english
	Memory :     4016MB 692KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Realtek HD Audio 2nd output (Realtek High Definition Audio))

</details>

**Comment by MEXAHOTABOP** [comment]
probably was update what rename some varibles 
sadly but i dont have game installed and here no other up to date source to track changes, so you can just temporally remove 
```
		{ "hook_id" : "lib/managers/localizationmanager", 						"script_path" : "lua/AdvAssault.lua" },
		{ "hook_id" : "lib/managers/hudmanagerpd2", 							"script_path" : "lua/AdvAssault.lua" },
		{ "hook_id" : "lib/managers/hud/hudassaultcorner", 						"script_path" : "lua/AdvAssault.lua" },

```
from https://github.com/Kamikaze94/WolfHUD/blob/master/mod.txt#L121

**Comment by strdsk** [comment]
thanks! will do.
btw, what will happen when advassault disabled?

**Comment by MEXAHOTABOP** [comment]
assault ui and wave information will be disabled

**Comment by strdsk** [comment]
issue closed. didnt notice that im using an old installation folder.
