### ISSUE TITLE
Clash

### ISSUE THREAD

**Issue by LaPrem** [Kamikaze94/WolfHUD#789]
Sorry for my poor English.

- [Yes ] I am running the latest version
- [Yes ] I made sure this issue doesn't persist without this mod
- [Yes ] I checked to make sure that this issue has not already been filed

Crash in the middle of Hoxton breakout day1.

* Operating System: Windows10
* BLT version: SuperBLT-R027-3.2.0-wsock
* Other mods installed: No

<details> 
  <summary>BLT Log</summary>
 
03:51:46 PM Lua: [BLT] Setup...
03:51:46 PM Lua: [BLT] Loading module: 	BLTLogs
03:51:46 PM Lua: [BLT] Loading module: 	BLTModManager
03:51:46 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
03:51:46 PM Lua: [BLT] Loading module: 	BLTPersistScripts
03:51:46 PM Lua: [BLT] Loading module: 	BLTLocalization
03:51:46 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
03:51:46 PM Lua: [BLT] Loading mods for state: table: 0x43dfb720
03:51:46 PM Lua: [BLT] Loading mod: base
03:51:46 PM Lua: [BLT] Loading mod: WolfHUD-master
03:51:46 PM Lua: [BLT] Setting up mod: 	base
03:51:46 PM Lua: [BLT] Setting up mod: 	WolfHUD-master
03:51:47 PM Lua: Loading mod settings : nil
03:56:18 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:57) CURL CLOSED

</details>

<details> 
  <summary>Crash.txt</summary>

Sun Nov 10 15:56:17 2019

Application has crashed: C++ exception
[string "lib/units/vehicles/animatedvehiclebase.lua"]:148: attempt to index local 'align_obj' (a nil value)

SCRIPT STACK

_function() core/lib/managers/coresequencemanager.lua:4563
activate_callback() core/lib/managers/coresequencemanager.lua:4538
activate() core/lib/managers/coresequencemanager.lua:2017
activate_callback() core/lib/managers/coresequencemanager.lua:2814
activate() core/lib/managers/coresequencemanager.lua:2017
run_sequence() core/lib/managers/coresequencemanager.lua:2478
run_sequence() core/lib/managers/coresequencemanager.lua:380
update_start_time_callbacks() core/lib/managers/coresequencemanager.lua:526
update() core/lib/managers/coresequencemanager.lua:479
core/lib/setups/coresetup.lua:493

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.93.845
	CPU : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 / nvldumd.dll[26.21.14.3160]
	Language : english
	Memory :     16340MB 600KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp.

</details>

**Comment by DenisBob** [comment]
See this mod:
https://modworkshop.net/mydownloads.php?action=view_down&did=25946

**Comment by LaPrem** [comment]
Wow thanks!!
I can now finish HoxOut.
