### ISSUE TITLE
Dozer damage size fix+ mask update....please.

### ISSUE THREAD

**Issue by hud8614** [Kamikaze94/WolfHUD#79]
1. dozer shotgun Damage size.....
![20161001025252_1](https://cloud.githubusercontent.com/assets/21234977/19002304/58e8763e-8786-11e6-8c20-8b9163d39f73.jpg)
![20161001041447_1](https://cloud.githubusercontent.com/assets/21234977/19003919/0122721c-878e-11e6-8f8a-d6a94241f812.jpg)
![20161001041606_1](https://cloud.githubusercontent.com/assets/21234977/19003922/06b267c8-878e-11e6-9436-428549ab14d7.jpg)
![20161001041449_1](https://cloud.githubusercontent.com/assets/21234977/19004013/93b711be-878e-11e6-8344-409b6c8a4bb7.jpg)
![20161001045316_1](https://cloud.githubusercontent.com/assets/21234977/19004900/fc6f2454-8792-11e6-9563-7c1fa3b44355.jpg)
748? siz....

2. mask icon update please.
![20161001043246_1](https://cloud.githubusercontent.com/assets/21234977/19004284/28f5c1c0-8790-11e6-90b2-5eadc7b8c83d.jpg)

add update..please.
http://lastbullet.net/mydownloads.php?action=view_down&did=16010

**Comment by Kamikaze94** [comment]
The Waypoints size recalculation should now work properly (I hope), so please report back, I you still notice it bugging out somewhere...

For the hat icon:
Yes, have made one the day that mask came out. 
_Edit: Pushed the update now._
