### ISSUE TITLE
Crash on heiststart while in VR

### ISSUE THREAD

**Issue by Gurkoel** [Kamikaze94/WolfHUD#793]
# Expected Behavior

I used to play VR while wolfhud was still installed, so I was able to switch easily between monitor and VR experience.

# Current Behavior

What is the current behavior?

The game crashes as soon as the heist starts.

# Failure Information (for bugs)
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Step 1. Start the game with VR
Step 2. Join a lobby (in my case with friends)
Step 3. Start the heist
Step 4. Crash

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Using latest superBLT version ("version" : "1.1.6.0", "blt_version" : 2)

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crash log.  
You can find your crash log in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>

Application has crashed: C++ exception
mods/WolfHUD-master/lua/CustomHUD.lua:2190: attempt to perform arithmetic on local 'amount' (a table value)

SCRIPT STACK

call_listeners() @mods/WolfHUD-master/lua/CustomHUD.lua:473
set_stamina() @mods/WolfHUD-master/lua/CustomHUD.lua:511
set_stamina() lib/managers/hudmanagervr.lua:560
update_stamina() lib/units/beings/player/playermovement.lua:316
original() lib/units/beings/player/playermovement.lua:285
@mods/base/req/core/Hooks.lua:260

-------------------------------

Callstack:

      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.1.1
	CPU : Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1080 Ti [Video:3072,Sys:0,Shared:1023,Vendor:0x10de]
	Language : english
	Memory :     16247MB 280KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX11 threaded
	Sound : Microsoft (Kopfhörer (2- Arctis 7 Game))

</details>

**Comment by MrDj200** [comment]
Is there any chance of this getting fixed?
