### ISSUE TITLE
New anarchist deck breaks WolfHud

### ISSUE THREAD

**Issue by Anxarch** [Kamikaze94/WolfHUD#8]
See:
https://www.reddit.com/r/paydaytheheistmods/comments/4j3rmr/feedback_hudlist_breaks_with_new_anarchist_deck/

I provided a workaround in the thread, and I can see people posting stuff on Last Bullet so they might want this too.

**Comment by Kamikaze94** [comment]
Thanks for the Info.
Someone told me about this bug on Lastbullet already.
I already fixed it in the dev version here. 
Just needs to be pushed out, once I can finish testing.

**Comment by Anxarch** [comment]
If it's already fixed, I'll wait. :)  Thanks for taking a look at this!
