### ISSUE TITLE
Damage direction indicator misalignment when being shot from below

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#80]
I'm not sure if this is intentional or not, but the damage direction indicator behaves very weirdly when enemies are shooting at me from below. The steeper the angle, the weirder it gets. For instance, I was fighting the SWAT Van Turret on Watchdogs Day 1 from the roof above it. The entire time I was shooting at it directly, it was shooting at me and the damage direction indicator kept telling me I was being shot from behind and to my left. I checked multiple times and there was never anyone behind me anywhere on the roof. It was the Turret's fire that was registering as coming from behind me despite clearly shooting me from the front.

I've seen this here and there before. It just seems like as soon as cops drop below my current elevation, the damage direction indicator starts pointing in weird directions.

**Comment by Kamikaze94** [comment]
Yep, I think that got reported once before....^^
Actually took it as the oportunity to rewrite the Damage Indicators and fully integrate them into the base game ones.
Hope this gets the error fixed.

**Comment by killrhythm09** [comment]
So what do you mean by integrate into the base game ones? How does it work now?

**Comment by Malidictus** [comment]
Ah, damn, I knew I'd forgotten something...

I tried out the latest GitHub build yesterday, and the damage direction indicator does indeed work like it should. When getting shot from in front of me, the damage direction indicator will list shots as coming from in front (top on the indicator) even if the enemy shooting at me happens to be on a lower physical elevation. So the indicator works as intended now.

My issue, though, is that the base game indicators are much dimmer than WolfHUDs. Since you're using the vanilla indicator graphics now, I have a harder time seeing the indicator. Is it possible to add controls for the opacity of those effects, or would that be reversing the changes you made to integrate with the base game system?

**Comment by Kamikaze94** [comment]
Previously, my code just suppressed the base game indicators and created my own ones.

Now it triggers the additional indicators for Friendly-fire and vehicles th "basegame way".
(do vehicles don't show damage indicators anymore? The function for that was blank in the extracted source for some reason....)
And it overrides the base game color and animation function with modified ones, that basically apply the settings.

_Edit: There are some Hard-overrides in place, so it might not work too well with other mods modifying those parts. In that case, consider disabling WolfHUD's Damage indicators._

**Comment by Malidictus** [comment]
Update on the Damage Direction Indication subject. Since you're now using Overkill's damage direction indication, it seems you've inherited a bug in their own implementation. The colour for taking near-fatal health damage plays over the armour damage colour if you're at extremely low health. Let me explain...

In my game, armour damage displays a green indicator, health damage displays a red one and near-fatal health damage displays a purple one. Regardless of my health, I should always be getting a green indicator if I have armour. However, once my health is low enough for my health damage indication to switch from red to purple, I will then ALWAYS get purple damage indication, even after my armour has recovered. As far as I'm aware, that's not working as intended.

**Comment by Kamikaze94** [comment]
Nope, actually that was meant to be happening.
The reasoning behind was to remember to heal up, if you get the chance.
But granted, that it isn't useful, if noone brought FAKs to the heist, and wasting a med isn't the best idea... :P
_Edit: Changed that now._

**Comment by Malidictus** [comment]
Oh... I personally find it distracting because I don't know when my armour has broken if I'm getting health damage indicators :) As a user of Muscle, I tend to not heal up and instead rely on natural regeneration if I can help it. That's why maintaining my armour is so crucial. Can that be made into an option?
