### ISSUE TITLE
WolfHUD cannot find SuperBLT

### ISSUE THREAD

**Issue by OmegaRidleyy** [Kamikaze94/WolfHUD#800]
- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

WolfHUD running

# Current Behavior

WolfHUD not running

# Failure Information

WolfHUD cannot find SuperBLT

## Steps to Reproduce

1. removing old WolfHUD
2. removing BLT
3. 'installing' SuperBLT
4. 'installing' WolfHUD

## Context

standard high end computer setup, win 10, etc

newest mod versions

## BLT log

<details> 
  <summary>BLT Log</summary>

  12:07:56 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\debug\blt_debug.cpp:124) Command line: "H:\Steam\steamapps\common\PAYDAY 2\payday2_win32_release.exe"
12:07:56 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\platforms\w32\signatures\signatures.cpp:255) Scanning for signatures in payday2_win32_release.exe
12:07:56 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\platforms\w32\signatures\signatures.cpp:301) Scanned for 59 signatures in 0 milliseconds with 0 cache misses
12:07:57 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
12:08:02 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:51) CURL_INITD
12:08:02 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
12:08:03 AM Lua: [BLT] Setup...
12:08:03 AM Lua: [BLT] Loading module: 	BLTLogs
12:08:03 AM Lua: [BLT] Loading module: 	BLTModManager
12:08:03 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:08:03 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:08:03 AM Lua: [BLT] Loading module: 	BLTLocalization
12:08:03 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:08:03 AM Lua: [BLT] Loading mods for state: table: 0x001c8ac0
12:08:03 AM Lua: [BLT] Loading mod: base
12:08:03 AM Lua: [BLT] Loading mod: BeardLib
12:08:03 AM Lua: [BLT] Loading mod: Stop crime spree crash on join base
12:08:03 AM Lua: [BLT] Loading mod: Stop the crimespree loss on crash
12:08:03 AM Lua: [BLT] Loading mod: WolfHUD
12:08:03 AM Lua: [BLT] Setting up mod: 	base
12:08:03 AM Lua: [BLT] Setting up mod: 	BeardLib
12:08:03 AM Lua: [BLT] Setting up mod: 	Stop crime spree crash on join base
12:08:03 AM Lua: [BLT] Setting up mod: 	Stop the crimespree loss on crash
12:08:03 AM Lua: [BLT] Setting up mod: 	WolfHUD
12:08:03 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
12:08:03 AM Lua: [BLT] Setup...
12:08:03 AM Lua: [BLT] Loading module: 	BLTLogs
12:08:03 AM Lua: [BLT] Loading module: 	BLTModManager
12:08:03 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:08:03 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:08:03 AM Lua: [BLT] Loading module: 	BLTLocalization
12:08:03 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:08:03 AM Lua: [BLT] Loading mods for state: table: 0x001c8aa0
12:08:03 AM Lua: [BLT] Loading mod: base
12:08:03 AM Lua: [BLT] Loading mod: BeardLib
12:08:03 AM Lua: [BLT] Loading mod: Stop crime spree crash on join base
12:08:03 AM Lua: [BLT] Loading mod: Stop the crimespree loss on crash
12:08:03 AM Lua: [BLT] Loading mod: WolfHUD
12:08:03 AM Lua: [BLT] Setting up mod: 	base
12:08:03 AM Lua: [BLT] Setting up mod: 	BeardLib
12:08:03 AM Lua: [BLT] Setting up mod: 	Stop crime spree crash on join base
12:08:03 AM Lua: [BLT] Setting up mod: 	Stop the crimespree loss on crash
12:08:03 AM Lua: [BLT] Setting up mod: 	WolfHUD
12:08:04 AM Lua: [Family Jewels][ERROR] [AddFiles] File does not exist! Maps/Family Jewels/vo/day1/dragovich/tooklong1.movie
12:08:04 AM Lua: [Family Jewels][ERROR] [AddFiles] File does not exist! Maps/Family Jewels/vo/day1/dragovich/tooklong2.movie
12:08:04 AM Lua: [Family Jewels][ERROR] [AddFiles] File does not exist! Maps/Family Jewels/vo/day1/dragovich/tooklong3.movie
12:08:04 AM Lua: [Family Jewels][ERROR] [AddFiles] File does not exist! Maps/Family Jewels/vo/day1/dragovich/tooklong4.movie
12:08:04 AM Lua: [BeardLib] [Map Framework] Initialized Mod: Maps/Family Jewels/
12:08:04 AM Lua: [WolfHUD] ERROR: Error while loading, settings file could not be opened (mods/saves/WolfHUD_v2.json)
12:08:04 AM Lua: Initted Family Jewels interactions!
12:08:05 AM Lua: Loading mod settings : nil
12:08:05 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:943) Initiating Hook
12:08:05 AM Lua: [BLT] Setup...
12:08:05 AM Lua: [BLT] Loading module: 	BLTLogs
12:08:05 AM Lua: [BLT] Loading module: 	BLTModManager
12:08:05 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:08:05 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:08:05 AM Lua: [BLT] Loading module: 	BLTLocalization
12:08:05 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:08:05 AM Lua: [BLT] Loading mods for state: table: 0x31182480
12:08:05 AM Lua: [BLT] Loading mod: base
12:08:05 AM Lua: [BLT] Loading mod: BeardLib
12:08:05 AM Lua: [BLT] Loading mod: Stop crime spree crash on join base
12:08:05 AM Lua: [BLT] Loading mod: Stop the crimespree loss on crash
12:08:05 AM Lua: [BLT] Loading mod: WolfHUD
12:08:05 AM Lua: [BLT] Setting up mod: 	base
12:08:05 AM Lua: [BLT] Setting up mod: 	BeardLib
12:08:05 AM Lua: [BLT] Setting up mod: 	Stop crime spree crash on join base
12:08:05 AM Lua: [BLT] Setting up mod: 	Stop the crimespree loss on crash
12:08:05 AM Lua: [BLT] Setting up mod: 	WolfHUD
12:08:22 AM Lua: Inserted global event into list!
12:08:30 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:447) Incoming HTTP Request/Request
12:08:30 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:461) https://api.modwork.shop/api.php?command=CompareVersion&did=14924&vid=3.47&token=Je3KeUETqqym6V8b5T7nFdudz74yWXgU - 869
12:08:30 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:168) Launching Async HTTP Thread
12:08:30 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:447) Incoming HTTP Request/Request
12:08:30 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:461) http://payday2maps.net/crimenet/checkversion/q010fj.txt - 1384
12:08:30 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:168) Launching Async HTTP Thread
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:447) Incoming HTTP Request/Request
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:461) https://znix.xyz/paydaymods/updates/meta.php?id=payday2blt - 2816
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:168) Launching Async HTTP Thread
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:447) Incoming HTTP Request/Request
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:461) https://znix.xyz/paydaymods/updates/meta.php?id=payday2bltwsockdll - 2804
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:168) Launching Async HTTP Thread
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:447) Incoming HTTP Request/Request
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:461) http://api.paydaymods.com/updates/retrieve/?mod[0]=wolfhud - 2805
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:168) Launching Async HTTP Thread
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:447) Incoming HTTP Request/Request
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:461) http://api.paydaymods.com/updates/retrieve/?mod[0]=fed_inv - 2806
12:09:17 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:168) Launching Async HTTP Thread
12:09:18 AM FATAL ERROR:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:242) mods/base/req/utils/json-1.0.lua:212: Failed to scan constant from string <html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>openresty</center>

</body>

</html>

 at starting position 1
stack traceback:
	[C]: in function 'assert'
	mods/base/req/utils/json-1.0.lua:212: in function 'decode'
	mods/base/req/utils/json.lua:9: in function <mods/base/req/utils/json.lua:8>
	[C]: in function 'pcall'
	mods/base/req/utils/json.lua:8: in function 'decode'
	mods/base/req/BLTUpdate.lua:76: in function 'clbk_got_update_data'
	mods/base/req/BLTUpdate.lua:60: in function <mods/base/req/BLTUpdate.lua:59>
12:09:18 AM Lua: Found a json error, attempting to use old json loader!
12:09:18 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:91) mods/base/req/utils/json-0.9.lua:372: Unexpected character at Line 1 character 1: < (60) when reading object ({ or [ or ' or " or number or boolean or null expected)
Context: 
<html>

<head><title>404 Not Fo
^
12:09:18 AM FATAL ERROR:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:242) mods/base/req/utils/json-1.0.lua:212: Failed to scan constant from string <html>

<head><title>404 Not Found</title></head>

<body>

<center><h1>404 Not Found</h1></center>

<hr><center>openresty</center>

</body>

</html>

 at starting position 1
stack traceback:
	[C]: in function 'assert'
	mods/base/req/utils/json-1.0.lua:212: in function 'decode'
	mods/base/req/utils/json.lua:9: in function <mods/base/req/utils/json.lua:8>
	[C]: in function 'pcall'
	mods/base/req/utils/json.lua:8: in function 'decode'
	mods/base/req/BLTUpdate.lua:76: in function 'clbk_got_update_data'
	mods/base/req/BLTUpdate.lua:60: in function <mods/base/req/BLTUpdate.lua:59>
12:09:18 AM Lua: Found a json error, attempting to use old json loader!
12:09:18 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:91) mods/base/req/utils/json-0.9.lua:372: Unexpected character at Line 1 character 1: < (60) when reading object ({ or [ or ' or " or number or boolean or null expected)
Context: 
<html>

<head><title>404 Not Fo
^
12:09:18 AM Lua: [Updates] Received update data for 'payday2bltwsockdll'
12:09:18 AM Lua: [Updates] Received update data for 'payday2blt'
12:09:18 AM Lua: [Updates] Comparing hash data for payday2bltwsockdll:
Server: dfbbdc34a4308c900ed5c137cf0e29b084272dff47a403407069abe7041d1a55
 Local: dfbbdc34a4308c900ed5c137cf0e29b084272dff47a403407069abe7041d1a55
12:09:19 AM Lua: [Updates] Comparing hash data for payday2blt:
Server: 5157f526ff00afe903cfdbd3fda37ca14c9c0e6525e945ba71c9f0e7ce69c0f6
 Local: 5157f526ff00afe903cfdbd3fda37ca14c9c0e6525e945ba71c9f0e7ce69c0f6
12:10:27 AM Lua: [BLT] Performing save...
12:10:27 AM Lua: [BLT] Save complete? true
12:10:42 AM Lua: [BLT] Performing save...
12:10:42 AM Lua: [BLT] Save complete? true
12:10:45 AM Lua: [BLT] Performing save...
12:10:45 AM Lua: [BLT] Save complete? true
12:11:03 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:57) CURL CLOSED

</details>

**Comment by MEXAHOTABOP** [comment]
hello
this is crash not related to wolfhud 
try to remove `mods/base`

**Comment by OmegaRidleyy** [comment]
Hey man, thanks for responding.
which file do you mean?

**Comment by MEXAHOTABOP** [comment]
c/windows/system32/drivers/etc/hosts on windows

**Comment by OmegaRidleyy** [comment]
didn't help.. my WolfHUD still reports:
**No SuperBLT Detected!**
**WolfHUD is no longer compatable with regular BLT**
etc etc

even tho i removed the regular blt multiple times and added superBLT...

**Comment by MEXAHOTABOP** [comment]
try to remove mods/base

**Comment by OmegaRidleyy** [comment]
like i said, i removed the regular BLT...
i'm a software developer, i know how to read instructions ;) i did as the website of superBLT told me to.. if the basic instructions would have worked, we wouldn't be here ^^

**Comment by MEXAHOTABOP** [comment]
in logs what you posted in first message only error was with broken paydaymods

ok may be something wrong with superblt check since in logs you use superblt(but then dunno why only you write about this)
try remove check in https://github.com/Kamikaze94/WolfHUD/blob/master/Core.lua#L1346
from line 1346 to line 1371

i dont play in payday for long time so cant check if something wrong

**Comment by OmegaRidleyy** [comment]
i somehow managed to fix it.. the WolfHUD works now.

i removed EVERYTHING again, downloaded it again and added it again. Now it works.
Only thing is, for some reason it doesn't update/download the Federal Inventory stuff.. but i guess i can live without this.

my guess is, that i had some old federal inventory files that somehow made the wolfhud look for old blt? ... makes no sense but whatever..
