### ISSUE TITLE
Wolfhud inconpadible with custom joker names

### ISSUE THREAD

**Issue by sirben99** [Kamikaze94/WolfHUD#812]
I am running the latest version
 I made sure this issue doesn't persist without this mod

 **Expected Behavior**

There should be an option to turn off converted police unit names like Security Guard, SWAT Unit etc so it doesent interviene with keepers joker names

**Current Behavior**

The Jokers display theyr unit name wich intervienes with Keepers Joker Names mod (Or whatever other mod adds joker names)

Wolfhud installed
![20200307140814_1](https://user-images.githubusercontent.com/32977052/76143322-3dabbe00-607f-11ea-9605-7ba99d152ff4.jpg)

Wolfhud uninstalled
![20200307141321_1](https://user-images.githubusercontent.com/32977052/76143326-413f4500-607f-11ea-9516-2e619b8449cf.jpg)

This is very annoying and i cant find anything from the options menu to disable this. Im not sure if this a bug or just something that wasnt implomented. I desided to post here since i cant find other information anywhere. Sorry for the broken ass english

**Comment by Kamikaze94** [comment]
There is a setting to disable Joker over-head healthbars.
Its in "WolfHUD Settings > Waypoint Settings > Show Minions"

**Comment by sirben99** [comment]
> There is a setting to disable Joker over-head healthbars.
> Its in "WolfHUD Settings > Waypoint Settings > Show Minions"

Ah okay. I recall doing that but not working but i can try that and report if it fixes the problem. Thank you for the reply!

**Comment by sirben99** [comment]
This worked! Thank you so much. A little bit hidden tho. Dint think it was under waypoint settings. But it worked and thats the point.
