### ISSUE TITLE
Some problem with texts

### ISSUE THREAD

**Issue by easymoney322** [Kamikaze94/WolfHUD#815]
# Expected Behavior

Noral text, working counts, etc

# Current Behavior

Almost every text line in the game contains error message
Here is the list of screenshots: 
[TAB hud](https://steamuserimages-a.akamaihd.net/ugc/772869828585248730/6866AFEC1049244B3E1676C49F9FD2738FA9C0CF/)

[Interaction text](https://steamuserimages-a.akamaihd.net/ugc/772869828585238642/0B695139F0C95ABADB5E7A140F35F4CC6CC1B38B/)

[Assault Progress, converted units name, drill status name](https://steamuserimages-a.akamaihd.net/ugc/772869828585238982/E606C0F3F1ECEB7EA3D8D118176AE886B2408D0C)

[Hoxton unit name, buffs description](https://steamuserimages-a.akamaihd.net/ugc/772869828585238255/B20017E442ACA9E1EF5E8A5AC0169D8033045456/)

Tried to change  mods language on something else - no result

## Steps to Reproduce

1. I legit did nothing, it was like that since installisation. Hosted all the heists by myself.

## Context

#

* Operating System: Windows 10
* BLT version: 1.1.6.0
* Other mods installed: None
* Game, Steam and mods language: English. Game directory root on english too.
* OS language: Russian

## BLT log

<details> 
  <summary>BLT Log</summary>

   [2020_03_11_log.txt](https://github.com/Kamikaze94/WolfHUD/files/4317803/2020_03_11_log.txt)

</details>

**Comment by easymoney322** [comment]
There is also no settings in "mod options" expect language choosing

**Comment by MEXAHOTABOP** [comment]
try remove mod and redownload https://github.com/Kamikaze94/WolfHUD/archive/master.zip

**Comment by easymoney322** [comment]
> try remove mod and redownload https://github.com/Kamikaze94/WolfHUD/archive/master.zip

It worked. 

Now I have a question. The first try was "3.1.3_fix" hud mod and caused the same result.
Then I reinstalled it with "3.1.3" version, and it was the same. 
Whats the difference between these two and this one? Should links lead to it then?

**Comment by MEXAHOTABOP** [comment]
3.1.3_fix this some fix for version 3.1.3 (ваш КО)
master this is main branch of mod and contain bleeding edge version of mod 
absolutely untested and very dangerous version in theory
