### ISSUE TITLE
Segmentation fault when starting a contract

### ISSUE THREAD

**Issue by Killerqu00** [Kamikaze94/WolfHUD#821]
I am getting segmentation error every time I try to enter contract start page. I have no mods except superBLT default mod and WolfHUD.
Here's the crash log https://pastebin.com/mjz9YJZW

Steps:
1. Open the game
2. Select any contract
3. Try to start it and get a crash

OS: Ubuntu 18.04
SuperBLT: latest
WolfHUD: latest

<details> 
  <summary>Crash.txt</summary>

   Segmentation fault!

Obtained 26 C++ stack frames:
 0x7fd0fceee5d0 libsuperblt_loader.so : blt::error::handler(int)+0x3d0
 0x7fd0fba0ef20 libc.so.6 : +0x3ef20
       0xdffbd9 payday2_release : std::__1::unordered_map<int, dsl::wd3d::CachedSampler, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, dsl::wd3d::CachedSampler> > >::operator[](int&&)+0x39
       0xdeaaa8 payday2_release : dsl::wd3d::D3DRenderDevice::SetSamplerState(int, dsl::wd3d::D3DStateBlock const&)+0x98
       0xde96be payday2_release : dsl::wd3d::D3DRenderDevice::prepare_render_atom(dsl::RenderAtom const*, dsl::wd3d::D3DShader const*, int, int)+0x18e
       0xde94a3 payday2_release : dsl::wd3d::D3DRenderDevice::render_with_fallback(dsl::RenderAtom const*, int)+0x133
       0x8daece payday2_release : tg::SquareGeometry::render(dsl::RenderDevice*)+0x9e
       0x8cacab payday2_release : tg::EffectInstance::apply(dsl::RenderDevice*)+0xeb
       0x8cc4fd payday2_release : tg::TextureGenerator::generate(dsl::RenderDevice*, std::__1::vector<tg::TextureEffectInstanceInterface*, std::__1::allocator<tg::TextureEffectInstanceInterface*> >&)+0x9d
       0x8e2269 payday2_release : PostProcessor::Effect::render(dsl::RenderDevice*)+0x89
       0xdee175 payday2_release : dsl::wd3d::D3DRenderDevice::end_scene()+0x345
       0xa90f7e payday2_release : ps3_name_collision::SceneManager::render(dsl::RenderDevice*)+0x1fe
       0xd04718 payday2_release : dsl::ViewPort::render(dsl::RenderDevice*)+0x188
       0xd04938 payday2_release : dsl::SimpleViewPort::render(dsl::RenderDevice*)+0x38
       0x8d3c1b payday2_release : RenderInterface::render_scene(RenderInterfaceBase::SceneData const&)+0x42b
       0x8d370b payday2_release : RenderInterface::render_frame()+0x15b
       0x8d77d1 payday2_release : ThreadedRenderInterface::process_input(ThreadedRenderInterface::InputMessage&)+0x111
       0x8d75f6 payday2_release : ThreadedRenderInterface::process_one_message()+0x1a6
       0x8d7388 payday2_release : ThreadedRenderInterface::callback()+0xd8
                payday2_release() [0x8d4781]
       0xc8efc9 payday2_release : dsl::ThreadManager::ThreadManagerThreadProc(void*)+0x29
                payday2_release() [0xe3f049]
                payday2_release() [0xe5fa96]
 0x7fd0fbdc86db libpthread.so.0 : +0x76db
 0x7fd0fbaf188f libc.so.6 : clone+0x3f

</details>

**Comment by MEXAHOTABOP** [comment]
looks like blt bug 
can you try other revisions of blt?

**Comment by Killerqu00** [comment]
Well, that problem fixed when I recompiled source code from superBLT repository.
