### ISSUE TITLE
crash after entering the robbery

### ISSUE THREAD

**Issue by punqdrop** [Kamikaze94/WolfHUD#824]
Good afternoon. Faced such a problem - the game crashes after in the lobby I press the "start robbery" button. Before that, everything worked well.

**Comment by MEXAHOTABOP** [comment]
Hello.
Please fill issue template or add game and BLT logs at least.

**Comment by punqdrop** [comment]
Sorry, I'm not very good at English. Can you explain in more detail what I should do, please? Should I throw off a crashlog or something like that?

**Comment by MEXAHOTABOP** [comment]
Don`t need to worry about that.
https://github.com/Kamikaze94/WolfHUD#bug-reports

если что я русский

**Comment by punqdrop** [comment]
[2020_04_01_log.txt](https://github.com/Kamikaze94/WolfHUD/files/4413583/2020_04_01_log.txt)
[crashlog.txt](https://github.com/Kamikaze94/WolfHUD/files/4413600/crashlog.txt)
Я тоже русский. В общем, после того как я нажимаю кнопку в лобби, идёт чёрный экран, затем синий экран с подсказками, он немного грузится, а потом вылетает.
Буду рад за помощь.

**Comment by MEXAHOTABOP** [comment]
wolfhud не совместим с pirate perfection и другими модами на разблокировку dlc

**Comment by punqdrop** [comment]
От всей души благодарю)
