### ISSUE TITLE
Game crashes on double-click when trying to equip a secondary equipment

### ISSUE THREAD

**Issue by Hexer10** [Kamikaze94/WolfHUD#829]
Here is the [crashlog](https://gist.github.com/Hexer10/07fce71194116b89b49a51d73d405a91).

Seems like the error is in these lines, specifically in the #L324, when the variable `_mouse_click` is accessed, which seems likes is now `nil`.
https://github.com/Kamikaze94/WolfHUD/blob/9abfea09f9b2c136a2bbeefe3d22c6bdf553e968/lua/MenuTweaks.lua#L317-L325

**Comment by Hexer10** [comment]
This can be fixed by checking if `self._mouse_click` variable is `nil`, but then you lose the functionality that there was before, which iirc it equipped a secondary equipment with a double right click.
Double clicking with the left button still work fine.

**Comment by MEXAHOTABOP** [comment]
Not sure why this is happens, but if this helps then you can create pull request .
I dont remember if wolfhud ever do something with weapon equip.

**Comment by Hexer10** [comment]
I'm looking deeper into this, and it seems like that before setting the `_mouse_click` and the `_mouse_click_index` variables this check was added(199.3):
https://github.com/mwSora/payday-2-luajit/commit/78711f3fedc568b361a5a480a970e7a15b778d97#diff-8c935a4cc2f7bbc7b637be5eadc12559R8536-R8539

So maybe those variables with the RMB don't ever get initialized hence they are `nil`. I'm wondering if we can trigger the update manually (or avoid the `"alive"` check would cause issues)

**Comment by Hexer10** [comment]
We'll I tried playing around with it and seems like the RMB doesn't crash if you copy paste the "self._mouse_click" code, but I guess checking for `nil` atm it's just more reliable

**Comment by MEXAHOTABOP** [comment]
Problem was fixed with new release
