### ISSUE TITLE
GameInfoManager crash

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#83]
I'm posting this on behalf of a friend of mine, so I don't have a lot of information on what he was doing when the bug occurred. I just know that he crashed, gave me a crash log and walked away from the computer. I'll fill in with more details as I have them. In the meantime, crash log is as follows:

Application has crashed: C++ exception
mods/WolfHUD/lua/GameInfoManager.lua:2027: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

**Comment by Malidictus** [comment]
I tracked down my friend, but he didn't have much additional information. He said that there was only one player left alive (everyone else was in custody) throwing bags into the escape vehicle after the escape zone had spawned. He crashed at a seemingly random point during this process. He's using the current auto-update build and has no other mods installed. He was not hosting.

**Comment by Kamikaze94** [comment]
Is your friend using the dev build or release version?
In the first case, it is in the ECMs destroy function.
The original function gets called in that case before the events for GameInfoManager get triggered, meaning, if the game is too fast in destroying that unit, it can potentially cause problems.....
I'll change something there, just to be save...  :)

**Comment by Malidictus** [comment]
He's using the release version, though I called it "current auto-update build." Sorry, didn't know the right term :) So that's fixed in the current Dev Build? Cool, I'll let him know, both that it's fixed and what caused it.

Although we've used ECMs in stealth before and he hasn't crashed. Is this something specific to Loud?
