### ISSUE TITLE
Crash when vehcile takes damage

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#84]
I've been running into a really weird crash with an unhelpful crash log (which I'll link to the end anyway). It happens when I'm driving or riding in a vehicle which happens to take damage. I don't know if I have to be the one taking damage directly or the vehicle itself, but it's crashes me pretty consistently. I've crashed in the Birth of Sky zodiac, the Aftershock truck and in a forklift on both Alesso and Meltdown.

I'm using the version of WolfHUD from the GitHub repo as of [this post](https://github.com/Kamikaze94/WolfHUD/issues/80#issuecomment-251151460). I "compared notes" with a friend of mine running the latest stable build from PaydayMods auto-update and he does not crash with vehicles. Given the timing, I suspect it might have something to do with the vehicle damage direction indicator.

Crash log as follows:

Application has crashed: access violation

---

Callstack:

```
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
```

---

Current thread: Main

---

**Comment by Kamikaze94** [comment]
So you're probably before commit 4b161e05e9a60242de6cf805171766bf5bb2531c.
As that commit message says, I disabled the vehicle Damage Indicators with that version, exactly for the reason you reported. For some reason they are causing access violations.

I'm just wondering if their removal was an gameplay decission by Overkill, or they simply didn't want to bother with fixing them.... :/

**Comment by Malidictus** [comment]
I've not seen that commit, no. So that's another one I've reported that's already fixed? Damn, sorry... I'll grab the latest dev build and will make do without vehicle damage indicators for the time being :)
