### ISSUE TITLE
Mission clock broken after last update (difficulty)

### ISSUE THREAD

**Issue by Malidictus** [Kamikaze94/WolfHUD#85]
The mission clock seems to be busted since the Friday update. It doesn't crash or anything, but it reads 00:00:00 for the entire duration of the heist.

**Comment by Tatsugi** [comment]
I've noticed it too.

**Comment by Kamikaze94** [comment]
Yep, Overkill added the ability to hide the timer and assault banner per level.
Counter gets stuck, because the enabled variable doen't get set.

Btw, the TabStats panel was also getting resized now, making half of the stats invisible.
Both problems should be fixed now.

**Comment by Malidictus** [comment]
Yes, I was going to report the TabStats panel, as well. Noticed that some time after I made the initial report.

At least WolfHud hasn't started crashing so far :) Will you be pushing some of these updates Live, or is the clock not considered important enough for that?

**Comment by Kamikaze94** [comment]
I was actually about to, when you reported the Assault text issue...  :P
Thats what's keeping me so far.
Still not sure, if I should push an update now every day, while crimefest lasts.  
(Or if I'm able to fix everything in directly ^^)
Guess I'll at least wait with the Federal Inventory ones till all mask packs are released....

**Comment by Malidictus** [comment]
I would suggest pushing frequent updates during CrimeFest, at least if anything obvious breaks. You WolfHUD looks incredibly professional. Some minor bugs nobody's likely to notice, such as losing your gadget state if you enter a vehicle (which you did fix) aren't likely bother anybody, but obviously broken stuff like the clock not working will. I have to imagine there will be other stuff as well, but we'll see what happens with the rest of the CromeFest updates. If it's anything obviously buggy, I'd say push an update.

Don't mean to butt in on your development cycle, of course. Just a piece of opinion :)
