### ISSUE TITLE
Assault Ticker Empty While Client

### ISSUE THREAD

**Issue by NerdVenom** [Kamikaze94/WolfHUD#86]
If I'm host, the Assault Ticker works just fine but if I join someone else's game then the Assault Ticker is empty and displays no info.
![empty assault](https://cloud.githubusercontent.com/assets/12417397/19208359/b26f918c-8cbe-11e6-8dc4-9d80088f44a1.jpg)

**Comment by Kamikaze94** [comment]
Seems like I forgot a check, when disabling the network sync (which is currently not working, therefore disabled, blabla, ^^)
Removed that from the main branch for now anyways. Have enough to do, whith focussing on crimefest fixxes, no time for additional experiments :P
The last commit should fix this, :)

**Comment by NerdVenom** [comment]
Thanks, I'll check it out and see if it's fixed.
