### ISSUE TITLE
WolfHUD missing in the Mod Options menu

### ISSUE THREAD

**Issue by TheCatMan2000** [Kamikaze94/WolfHUD#864]
# Expected Behavior

I expect to find WolfHUD in the Mod Options menu in-game

# Current Behavior

WolfHUD is nowhere to be found in Mod Options

## Context

* Operating System: (K)ubuntu 20.04
* BLT version: Not sure.
* Other mods installed: None. Just WolfHUD.

I was following this guide to install SuperBLT: https://steamcommunity.com/sharedfiles/filedetails/?id=801187233
I only installed SuperBLT, then went on to install WolfHUD.
I'm not sure if this is an issue on my end, an issue with the mod, or the guide.

## BLT log

[BLT Log & Crash Log.zip](https://github.com/Kamikaze94/WolfHUD/files/5004419/BLT.Log.Crash.Log.zip)
(In a zip file because the log file was ~130mb)

## Crash log

[BLT Log & Crash Log.zip](https://github.com/Kamikaze94/WolfHUD/files/5004419/BLT.Log.Crash.Log.zip)

**Comment by MEXAHOTABOP** [comment]
Your log are full of blt errors,

make sure what you use last superblt release from 
https://gitlab.com/znixian/payday2-superblt, if this didn't help build 
them yourself.

31.07.2020 03:51, Nikolas Vaught пишет:

**Comment by TheCatMan2000** [comment]
Building SuperBLT myself didn't help. I still get that whole load of errors.

I tried starting the game with only SuperBLT and I still get a horrible two-million line log file of segmentation faults.
So, I went to the wrong place.

Sorry about that.
