### ISSUE TITLE
Mission intro skip and auto-payday select

### ISSUE THREAD

**Issue by Boltpen** [Kamikaze94/WolfHUD#870]
- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

 There is the ENDING of the mission, which is more... of a pain really. Upon completing the mission and getting your payday, it automatically selects one of the three cards to choose your payday. That's not desirable either, considering some of us (however futile) like the choice upon the rng.

## Steps to Reproduce

1. Upon completing the mission and seeing the end-game stats, going to your payday will IMMEDIATELY select yours for you. I have not done this with other people yet, however I usually lone wolf anyways and will get to playing with others when possible to see if this bug persists in online lobbies.
## Context

* Operating System: Windows 10
* BLT version: Latest
* Other mods installed: None.

## BLT log

(( Could not pull up the folder currently, for unrelated reasons.

**Comment by Boltpen** [comment]
Because I am not on github very often, for further questions or such, please message me on steam. 
https://steamcommunity.com/profiles/76561198116382246/

**Comment by nobodySophie** [comment]
I mean it doesn't seem like he will fix any of issues very soon so I wouldn't expect any messages from him

**Comment by Boltpen** [comment]
> I mean it doesn't seem like he will fix any of issues very soon so I wouldn't expect any messages from him

Sure, but it's still good to leave comments and such there. For all we know he might.

**Comment by Boltpen** [comment]
Apparently it's a FEATURE. I didn't see that there were options called SKIP IT. And upon looking at it, I was.... A little amused. Looks like I was just being stupid.
