### ISSUE TITLE
Не видно мод WolfHud Master 2020

### ISSUE THREAD

**Issue by Lolka555** [Kamikaze94/WolfHUD#871]
# WolfHud

- [да] I am running the latest version
- [да] I made sure this issue doesn't persist without this mod
- [да] I checked to make sure that this issue has not already been filed

WolfHud Master 2020 не виден мод в самой игре в настройке, все правильно установлено. Мод находиться в правильной папке, но сам мод не виден в настройках мода.

# Current Behavior

Не работает, и не виден в настройках WolfHud Master

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Переустановка мода
2. Переустановка игры

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 full
* BLT version: Super
* Other mods installed: много, не конфликтующих. ![Снимок](https://user-images.githubusercontent.com/70414732/91633515-79ea2680-e9f1-11ea-8210-b1f0b7251a83.PNG)

## BLT log

[2020_08_29_log.txt](https://github.com/Kamikaze94/WolfHUD/files/5144991/2020_08_29_log.txt)
[2020_08_28_log.txt](https://github.com/Kamikaze94/WolfHUD/files/5144992/2020_08_28_log.txt)

<details> 
  <summary>BLT Log</summary>

   [SuperBLT]

</details>

**Comment by PhantomGamers** [comment]
you need to post a log

**Comment by Lolka555** [comment]
> you need to post a log
I did it

**Comment by PhantomGamers** [comment]
Delete the "WolfHUD" folder, you should only have "WolfHUD-master"

I don't see it in the screenshot but it's showing up in the logs so either the screenshot is incomplete or you're showing the wrong folder.

**Comment by Lolka555** [comment]
> Delete the "WolfHUD" folder, you should only have "WolfHUD-master"
> 
> I don't see it in the screenshot but it's showing up in the logs so either the screenshot is incomplete or you're showing the wrong folder.

I deleted it, but it doesnt work
