### ISSUE TITLE
Endles verifying WolfHUD

### ISSUE THREAD

**Issue by InfamousMunky** [Kamikaze94/WolfHUD#883]
Hi i have a problem becouse after last update of WolfHUD i can't update it all the time is written verifying.
Sorry for my bad english and thanks for help.

**Comment by noahwillrule** [comment]
Hey I was actually having this same problem! I figured out that the mod folder needed to be named WolfHUD-master instead of WolfHUD-3.1.7 or whatever combination of numbers it was. After I did that I relaunched the game and it worked fine. Hope that helps!

**Comment by InfamousMunky** [comment]
> Hey I was actually having this same problem! I figured out that the mod folder needed to be named WolfHUD-master instead of WolfHUD-3.1.7 or whatever combination of numbers it was. After I did that I relaunched the game and it worked fine. Hope that helps! <

Yeah its work for me too, thanks.
