### ISSUE TITLE
Crash when I try to modify a weapon.

### ISSUE THREAD

**Issue by Delalosa** [Kamikaze94/WolfHUD#929]
This is the crash report
populate_weapon_category_new_original() lib/managers/menu/blackmarketgui.lua:10107
original() @mods/WolfHUD-master/lua/MenuTweaks.lua:113
on_create_func() @mods/base/req/core/Hooks.lua:265
init() lib/managers/menu/blackmarketgui.lua:157
new() core/lib/utils/coreclass.lua:35
_setup() lib/managers/menu/blackmarketgui.lua:2179
BlackMarketGui__setup_original() @mods/Goonmod Shop  Standalone/lua/BlackMarketGUI.lua:27
original() @mods/WolfHUD-master/lua/MenuTweaks.lua:286
_setup() @mods/base/req/core/Hooks.lua:265
init() lib/managers/menu/blackmarketgui.lua:1990
new() core/lib/utils/coreclass.lua:35
create_blackmarket_gui() lib/managers/menu/menucomponentmanager.lua:2930
create() lib/managers/menu/menucomponentmanager.lua:2921
set_active_components() lib/managers/menu/menucomponentmanager.lua:490
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
__orig() lib/managers/menumanagerpd2.lua:20
update() @mods/AutoCooker-master/delayedcalls.lua:49
original() lib/setups/setup.lua:877
update() @mods/base/req/core/Hooks.lua:188
update() lib/setups/menusetup.lua:358
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557

**Comment by MEXAHOTABOP** [comment]
Disable `Goonmod Shop Standalone`

If not help then disable `AutoCooker-master` and other mods

If not help then try to fill template that you delete since this is all 
that can be figured from your backtrace

20.09.2021 16:36, Delalosa пишет:

**Comment by Delalosa** [comment]
Here is a little more information if it helps you
SCRIPT STACK

original() lib/managers/menu/blackmarketgui.lua:10107
on_create_func() @mods/base/req/core/Hooks.lua:265
init() lib/managers/menu/blackmarketgui.lua:157
new() core/lib/utils/coreclass.lua:35
original() lib/managers/menu/blackmarketgui.lua:2179
_setup() @mods/base/req/core/Hooks.lua:265
init() lib/managers/menu/blackmarketgui.lua:1990
new() core/lib/utils/coreclass.lua:35
create_blackmarket_gui() lib/managers/menu/menucomponentmanager.lua:2930
create() lib/managers/menu/menucomponentmanager.lua:2921
set_active_components() lib/managers/menu/menucomponentmanager.lua:490
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
original() lib/setups/setup.lua:877
update() @mods/base/req/core/Hooks.lua:188
update() lib/setups/menusetup.lua:358
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main
