### ISSUE TITLE
Locked Assault still displays custom message if advanced assault is turned off.

### ISSUE THREAD

**Issue by Pichu0102** [Kamikaze94/WolfHUD#93]
If I turn off the advanced assault option, it still shows something different than the vanilla behavior of the assault banner during endless assaults. 

I tried to change it myself by moving around:
`if managers.hud and managers.hud:_locked_assault() then`
`			return self:text("wolfhud_locked_assault")`

But I couldn't get it to work. The expected behavior if advanced assault is turned off would be to return hud_assault_assault always like it does later in the code.

**Comment by Kamikaze94** [comment]
Hmm, changed that, because it makes sense that way...
The original intention was to always show it, so people don't waste their time waiting for an assault break to trade teammates or move stuff, when its locked....
Anyways... :)
