### ISSUE TITLE
3.3.2 crashes shortly after starting a heist

### ISSUE THREAD

**Issue by scanlanjr** [Kamikaze94/WolfHUD#944]
# Expected Behavior
No crashing

# Current Behavior

Crashes shortly after a heist starts

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open payday 2
2. Go to play offline and select Ukrainian job and put it on mayhem 
3. Start the heist and after a few seconds game crashes

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows 10
* BLT version: 4.7
* Other mods installed: CustomFOV; Disable corpses + shields; Enemy Health and Info; No ADS Recoil Animations; No VR Fade; hoplib, peer mod display; shuffle play and Weapon laser defaults to full strength.

## BLT log

12:15:32 PM Lua: [INFO] [BLT] Setup... 
12:15:32 PM Lua: [INFO] [BLT] Loading module: BLTLogs 
12:15:32 PM Lua: [INFO] [BLT] Loading module: BLTModManager 
12:15:32 PM Lua: [INFO] [BLT] Loading module: BLTKeybindsManager 
12:15:32 PM Lua: [INFO] [BLT] Loading module: BLTPersistScripts 
12:15:32 PM Lua: [INFO] [BLT] Loading module: BLTLocalization 
12:15:32 PM Lua: [INFO] [BLT] Cleaning logs folder, lifetime 1 day(s) 
12:15:32 PM Lua: [INFO] [BLT] Loading mods for state: table: 0x23cede00 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: base 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: BeardLib 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: CustomFOV 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: Disable corpses + shields - Gab 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: Enemy Health and Info 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: No ADS Recoil Animations 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: No VR Fade 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: pd2-hoplib-master 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: Peer Mod Display 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: Shuffle Play 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: Weapon laser defaults to full strength - Gab 
12:15:32 PM Lua: [INFO] [BLT] Loading mod: WolfHUD-3.3.2 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  base 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  BeardLib 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  pd2-hoplib-master 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  WolfHUD-3.3.2 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  Enemy Health and Info 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  Peer Mod Display 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  Shuffle Play 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  Disable corpses + shields - Gab 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  CustomFOV 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  Weapon laser defaults to full strength - Gab 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  No VR Fade 
12:15:32 PM Lua: [INFO] [BLT] Setting up mod:  No ADS Recoil Animations 
12:15:33 PM Lua: [INFO] Loading mod settings : nil 
12:15:47 PM Lua: [WolfHUD] WARNING: HUDTeammateCustom: Unoverridden function call: set_revives_amount
12:15:47 PM Lua: [WolfHUD] WARNING: HUDTeammateCustom: Unoverridden function call: set_revives_amount
12:15:48 PM Lua: [WolfHUD] WARNING: HUDTeammateCustom: Unoverridden function call: set_revives_amount
12:16:06 PM Log:  (C:\projects\payday2-superblt\src\http\http.cpp:57) CURL CLOSED

## Crash log(s)

Sat Aug 13 12:16:05 2022

Application has crashed: C++ exception
[string "core/lib/utils/corecode.lua"]:100: attempt to call method 'alive' (a nil value)

SCRIPT STACK

get_info() @mods/pd2-hoplib-master/req/UnitInfoManager.lua:212
set_unit_health() @mods/Enemy Health and Info/lib/hudmanager.lua:144
func() @mods/WolfHUD-3.3.2/lua/EnemyHealthbar.lua:257
_update_fwd_ray() @mods/base/req/core/Hooks.lua:294
update_original() lib/units/beings/player/states/playerstandard.lua:438
update() @mods/WolfHUD-3.3.2/lua/BurstFire.lua:228
original() lib/units/beings/player/playermovement.lua:279
@mods/base/req/core/Hooks.lua:288

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.127.120
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 / nvldumd.dll[31.0.15.1694]
	Language : english
	Memory :     24511MB 760KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by MEXAHOTABOP** [comment]
try to disable mod Enemy Health and Info

**Comment by scanlanjr** [comment]
> try to disable mod Enemy Health and Info

yea I removed it and now its working. does the mod have its own enemy health thing or will it be updated to support that mod, but thanks btw

**Comment by MEXAHOTABOP** [comment]
Wolfhud have nothing to do with crash, since we did not modify alive varible, and crash happen not in wolfhud code.

**Comment by scanlanjr** [comment]
i found the option to enable the health so im all good
