### ISSUE TITLE
latest commit buy all assets doesn't show in mp

### ISSUE THREAD

**Issue by Hulkfog** [Kamikaze94/WolfHUD#95]
Kilandor version edited to exclude levels that have no assets
http://pastebin.com/Heivr5rh Example another version buy all assets

**Comment by Kamikaze94** [comment]
Were you by any chance not host?
I know, it didn't show up as client as assets seem to be generated only be the host. (and probably synced to clients...)

Edit: The link you posted helped clearing up some of the questions I had, so thanks for that :)
Especially on the sync_save and sync_load functions.

Btw, couldn't find the original script on Killandors GitHUB. :P 

Thanks for the help on this one :D

**Comment by Hulkfog** [comment]
Kilandor removed it, it was part of his abandoned hud
