### ISSUE TITLE
GAME crashing after the new update 

### ISSUE THREAD

**Issue by veernezus** [Kamikaze94/WolfHUD#956]
[new 1.txt](https://github.com/Kamikaze94/WolfHUD/files/10805011/new.1.txt)

- [x] I am running the latest version
- [x] I made sure this issue doesn't persist without this mod
- [x] I checked to make sure that this issue has not already been filed

Everything is in the file (new 1.txt)

**Comment by angel4245** [comment]
у меня тоже такая проблема

**Comment by veernezus** [comment]
FIXED WHEN UPDATING LAST BLT VERSION (Released after this post)
