### ISSUE TITLE
Game crashes after entering heist and shooting

### ISSUE THREAD

**Issue by salesOsiel** [Kamikaze94/WolfHUD#964]
please help
- [✓ ] I am running the latest version
- [✓ ] I made sure this issue doesn't persist without this mod
- [✓ ] I checked to make sure that this issue has not already been filed

# Expected Behavior

Game working fine, I should be playing the heist

# Current Behavior

What is the current behavior?
game crashes whenever i shoot in a heist.  i tried multiple heists and they all work fine at first until i right click. Example: Nightclub, shot the dude guarding the doors, right when i right clicked, it crashed lmao

# Failure Information (for bugs)
Application has crashed: C++ exception
mods/WolfHUD-master/lua/TabStats.lua:1140: attempt to index global 'Steam' (a nil value)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Career
2. Do Transport heists 
3.  enter heist and shoot 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows 11
* BLT version: 1.3.9
* Other mods installed: nope just wolfhud and blt
* ...

## BLT log

Please include the contents of your BLT log around the time the bug appeared.  
You can find the BLT log inside your games "/mods/logs/" folder.

<details> 
  <summary>BLT Log</summary>

   [Please paste your BLT log here.]

</details>

## Crash log(s)

If the bug is causing a crash, please provide the contents of your crashlog.  
You can find your crashlog in "%localappdata%/Payday 2/crash.txt"

<details> 
  <summary>Crash.txt</summary>
Application has crashed: C++ exception
mods/WolfHUD-master/lua/TabStats.lua:1140: attempt to index global 'Steam' (a nil value)

SCRIPT STACK

_process_damage() @mods/WolfHUD-master/lua/TabStats.lua:1207
_on_damage_received() @mods/WolfHUD-master/lua/TabStats.lua:1172
damage_bullet() lib/units/enemies/cop/copdamage.lua:926
give_impact_damage() lib/units/weapons/raycastweaponbase.lua:2953
on_collision() lib/units/weapons/raycastweaponbase.lua:2830
_fire_raycast() lib/units/weapons/raycastweaponbase.lua:958
fire() lib/units/weapons/raycastweaponbase.lua:574
fire_original() lib/units/weapons/newraycastweaponbase.lua:2079
fire() @mods/WolfHUD-master/lua/BurstFire.lua:89
trigger_pressed() lib/units/weapons/raycastweaponbase.lua:467
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:5142
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:1017
update_original() lib/units/beings/player/states/playerstandard.lua:446
update() @mods/WolfHUD-master/lua/BurstFire.lua:228
original() lib/units/beings/player/playermovement.lua:279
@mods/base/req/core/Hooks.lua:264

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        

-------------------------------

Current thread: Main

</details>

**Comment by Not4Eric** [comment]
I have the same problem do you have the game on Steam or on Epic Games?

**Comment by salesOsiel** [comment]
> 

i have it on epic games

**Comment by Not4Eric** [comment]
Me too maybe it needs steam to work? sorry for late response

Edit: its not a windows 11 issue because i use windows 10

**Comment by danggtr** [comment]
In folder PAYDAY2/mods/WolfHUD-master/lua. Delete files 1.TabStats.lua 2. RichPresence.lua 3. EnhancedCrewLoadout.lua

**Comment by salesOsiel** [comment]
> In folder PAYDAY2/mods/WolfHUD-master/lua. Delete files 1.TabStats.lua 2. RichPresence.lua 3. EnhancedCrewLoadout.lua

thanks a lot it works now
