### ISSUE TITLE
Игра вылетает при стрельбе в кого-либо

### ISSUE THREAD

**Issue by VaraNBY** [Kamikaze94/WolfHUD#966]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.  
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [+] I am running the latest version
- [+] I made sure this issue doesn't persist without this mod
- [+] I checked to make sure that this issue has not already been filed

# Expected Behavior
No crashes
# Current Behavior
Вылет при попытке убить полицейского или гражданского(при обычной стрельбе все нормально)

# Failure Information (for bugs)
Application has crashed: C++ exception
mods/WolfHUD-master/lua/TabStats.lua:1140: attempt to index global 'Steam' (a nil value)

## Steps to Reproduce
1. step запускаю игру
2. step запускаю ограбление и стреляю по кому-либо
3. вылет

## Context
* windows 10
* the latest
* no
* ...

## BLT log
SCRIPT STACK

_process_damage() @mods/WolfHUD-master/lua/TabStats.lua:1207
_on_damage_received() @mods/WolfHUD-master/lua/TabStats.lua:1223
damage_bullet() lib/units/enemies/cop/copdamage.lua:926
give_impact_damage() lib/units/weapons/raycastweaponbase.lua:2953
on_collision() lib/units/weapons/raycastweaponbase.lua:2830
_fire_raycast() lib/units/weapons/raycastweaponbase.lua:958
fire() lib/units/weapons/raycastweaponbase.lua:574
fire_original() lib/units/weapons/newraycastweaponbase.lua:2079
fire() @mods/WolfHUD-master/lua/BurstFire.lua:89
trigger_pressed() lib/units/weapons/raycastweaponbase.lua:467
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:5142
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:1017
update_original() lib/units/beings/player/states/playerstandard.lua:446
update() @mods/WolfHUD-master/lua/BurstFire.lua:228
original() lib/units/beings/player/playermovement.lua:279
@mods/base/req/core/Hooks.lua:264

**Comment by XanBesi** [comment]
такая же тема

**Comment by 0vrDrive** [comment]
Присоединяюсь к проблеме

**Comment by LilRainBee** [comment]
У меня тоже беда, я всё установил, проверил, обновил, перепроверил, способы разные попробовал, но ничего не помогло.... 1 пуля в любого противника и вылет(((

**Comment by LilRainBee** [comment]
Зайди в папку игры , а потом иди по данному пути mods/wolfhud-master/lua и удаляй TabStats!!!!!!!!!!!!!!! 
Парни! Всё исправится! Просто сделайте это! И всё будет работать, но помните, что при входе в игру не нажимайте на обновление в нижнем левом углу, просто играйте

**Comment by danggtr** [comment]
> 

Не сработало

**Comment by XanBesi** [comment]
скорее всего «wolfhud» еще не поддерживает игру с EGS.

**Comment by danggtr** [comment]
Наверно


> скорее всего «wolfhud» еще не поддерживает игру с EGS.

Наверно
