### ISSUE TITLE
Проблема отображения иконок баффов

### ISSUE THREAD

**Issue by Fijdka** [Kamikaze94/WolfHUD#972]
При появлении новых иконок баффов, они, иногда, налезают друг на друга (то есть идут внахлест).

> До появления баффа:

![изображение_2023-06-17_230811954](https://github.com/Kamikaze94/WolfHUD/assets/136924682/a0006b44-b378-40d0-a016-55b3ad50a146)

> После появления баффа:

![изображение_2023-06-17_230859218](https://github.com/Kamikaze94/WolfHUD/assets/136924682/7fe09e13-1c6a-4ead-b1af-409d7c2b3d1c)

> Context

- Platform: Steam

- Operating System: Windows 10

- BLT version: Latest

- Other mods installed: SuperBLT, Berserker Live Matters, BLT Skin Unlock, Bot Bullet Collision Fixer, Customizable legendary skins, Depth of Field Removal, Disable Alesso Heist Music, Disable Safehouse Raid, Disable Weapon Preview Rotation, Drag and Drop Inventory, ECM time left in chat, Full Speed Swarm, Goonmod Shop Standalone. HopLib, Instant Restart, Isolation Helper [No Mercy], Lobby Player Info, Low Violence Mode, Meth Helper Updated, No Confirm Dialogs v2, No Fade to black, no fog, No Screen Shake, Simple Mod Updater, The Fixes.

> BLT log

- [2023_06_17_log.txt](https://github.com/Kamikaze94/WolfHUD/files/11779737/2023_06_17_log.txt)

**Comment by Fijdka** [comment]
> При появлении новых иконок баффов, они, иногда, налезают друг на друга (то есть идут внахлест). До появления баффа: ![изображение_2023-06-17_230811954](https://user-images.githubusercontent.com/136924682/246625277-a0006b44-b378-40d0-a016-55b3ad50a146.png) После появления баффа: ![изображение_2023-06-17_230859218](https://user-images.githubusercontent.com/136924682/246625305-7fe09e13-1c6a-4ead-b1af-409d7c2b3d1c.png)

**Comment by danggtr** [comment]
Попробуй увеличить интерфейс игрока

**Comment by Fijdka** [comment]
> Попробуй увеличить интерфейс игрока

Если речь идёт про интерфейс, изменяемый в самом WolfHud, то все остаётся так же, только иконки становятся больше, но так же налезают друг на друга.

**Comment by chromKa** [comment]
Переходите на VanillaHud - продолжение Wolfhud. К сожалению, kamikaze походу забил на мод, поддержка от энтузиаста перешла туда.

**Comment by Fijdka** [comment]
> Переходите на VanillaHud - продолжение Wolfhud. К сожалению, kamikaze походу забил на мод, поддержка от энтузиаста перешла туда.

У него такой же интерфейс, что и у вулфа?

**Comment by chromKa** [comment]
> > Переходите на VanillaHud - продолжение Wolfhud. К сожалению, kamikaze походу забил на мод, поддержка от энтузиаста перешла туда.
> 
> У него такой же интерфейс, что и у вулфа?

Да, это доработанный Вульф по сути.
