### ISSUE TITLE
WolfHUD crashing with the Jackal SMG (With WolfHUD v20)

### ISSUE THREAD

**Issue by Runey5** [Kamikaze94/WolfHUD#99]
so, i may have found a bug, with the new weapon pack, the modded jackal SMG with the john wick weapon pack mods on it, the game will crash, when i remove WolfHUD from my mods folder in payday 2 i can load in fine.

whenever i load into a heist at the start my game would instantly crash
----------------------------------------------------------------------

Sun Oct 23 18:29:30 2016

Application has crashed: C++ exception
mods/WolfHUD/lua/WeaponGadgets.lua:93: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.56.60
	CPU : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_78c173b1404a4b4e\nvd3dum.dll[21.21.13.7557]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16343MB 396KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Speakers (Logitech G933 Gaming Headset))

**Comment by Runey5** [comment]
i tested my theory again, same thing, the jackal gun without mods on it, no crash, the assault banner set to the right, no crashing, then tested it with mods on it with the assault banner set to the right, this happened
----------------------------------------------------------------------

Mon Oct 24 23:41:34 2016


Application has crashed: C++ exception
mods/WolfHUD/lua/WeaponGadgets.lua:93: attempt to index field '?' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.56.60
	CPU : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_78c173b1404a4b4e\nvd3dum.dll[21.21.13.7557]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16343MB 396KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Speakers (Logitech G933 Gaming Headset))

changed the assault banner location to the center, same gun without mods, no crash. same settings, assault banner in the center with mods.
----------------------------------------------------------------------

Mon Oct 24 23:45:44 2016


Application has crashed: C++ exception
mods/WolfHUD/lua/WeaponGadgets.lua:93: attempt to index field '?' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.56.60
	CPU : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_78c173b1404a4b4e\nvd3dum.dll[21.21.13.7557]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16343MB 396KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Speakers (Logitech G933 Gaming Headset))

this time moved the assault banner to the left with no mods on the jackal, no crash. with mods on the jackal i crashed.
----------------------------------------------------------------------

Mon Oct 24 23:49:54 2016


Application has crashed: C++ exception
mods/WolfHUD/lua/WeaponGadgets.lua:93: attempt to index field '?' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.56.60
	CPU : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_78c173b1404a4b4e\nvd3dum.dll[21.21.13.7557]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16343MB 396KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Speakers (Logitech G933 Gaming Headset))


this happens at the start of every heist with the jackal submachine gun with the john wick weapon pack mods on it (the latest one) but without the mods i load in fun. whether or not i'm playing by myself, or join someones lobby whenever the heist starts i'll crash if i have the mods on that gun, but without the mods it works fine. as soon as i remove wolfhud i load in fine with the modded gun.

**Comment by Kamikaze94** [comment]
Hmm, I doubt that crash having anything to do with the assault banner.
The first crashlog you posted (I think?) said something about HUDRestoration and a missing value. That was the current_assalt_wave, that now gets synced, for dropins to know how many wayves are already completed.

All the crashlogs you posted now point at the Weapon laser update.
If you say its not happening with an unmodified Jackal, I guess its one of the Gadgets or the grip with laser and flashlight mod.

**Comment by Runey5** [comment]
ah, i'll take the mods off one by one too see which is doing it, the first one i posted was old, for some reason i thought the recent crashlogs get put ontop instead of the bottom. i don't have RestorationHUD installed anymore

**Comment by Runey5** [comment]
i just tested it, with only the mods from the john wick pack, i took the grip laser combo off and i loaded in fine.

do you have any idea as to why it would cause this issue?

**Comment by Kamikaze94** [comment]
Nope, not really.
The crash message says something is nil. Thats probably the theme.
But it cannot be nil, unless something at the initialization of the themes went wrong... maybe a mod conflict or something, I donn't know....
But in that case, you should have problems with all laser attachments, not only on the Jackal.

Maybe check your mods for something that hooks into "lib/units/weapons/weaponlaser", ?

**Comment by Runey5** [comment]
i got a rainbow laser mod and rainbow flashlight mod, all my other mods are, BuilDB, Drag and Drop Inventory, Lobby Player Info, Voice Chat Icon for the overrides i got, Bodhi's sound mod, Federal Inventory, Felix ear nom revive/pick up, it came from a land down under currency mod, mira mod and yobadown mod and the WolfHUD_Textures. based on those all i can think of is the rainbow laser/flashlight mod, which actually seems to be ones causing the crash. if i disabled the laser/torch in wolfhud could i still use those two mods? if not would it add raindow lasers/flashlight's as a feature in wolfhud?

**Comment by Kamikaze94** [comment]
For the Lasers, you could disable the ones from WolfHUD and use another mod.
The Flashlight has no option to toggle on or off, so you'd need to use WolfHUD's setting here.
They both support setting their colors to "Rainbow" already. :P

**Comment by Runey5** [comment]
they do? well then time to find it, haha thanks for the help :)
